### ISSUE TITLE
Is it possible to run service fabric core subsystem in different VMs?

### ISSUE THREAD

**Issue by bingosummer** [Microsoft/service-fabric#101]
From https://github.com/Microsoft/service-fabric/issues/75, I know that the only way to run service fabric on multiple VMs is through an Azure deployment. I have two questions:
1. Could you support deploying this open source version on multiple VMs?
2. I assume that each VM has all the core subsystems. Is it possible to run the subsystems in separated VMs?

**Comment by masnider** [comment]
Each VM does _not_ run the whole set of system services. Yes, running the system services separately from other services is common and fully supported by the platform.

**Comment by alexgman** [comment]
what do you mean when you say _subsystems_ ? 

If you are just talking about multiple nodes, you can do this through the [cluster manifest file:](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest)
```

"nodes": [{
    "nodeName": "vm0",
    "iPAddress": "localhost",
    "nodeTypeRef": "NodeType0",
    "faultDomain": "fd:/dc1/r0",
    "upgradeDomain": "UD0"
}, {
    "nodeName": "vm1",
    "iPAddress": "localhost",
    "nodeTypeRef": "NodeType1",
    "faultDomain": "fd:/dc1/r1",
    "upgradeDomain": "UD1"
}, {
    "nodeName": "vm2",
    "iPAddress": "localhost",
    "nodeTypeRef": "NodeType2",
    "faultDomain": "fd:/dc1/r2",
    "upgradeDomain": "UD2"
}],
```

**Comment by bingosummer** [comment]
I mean the core subsystems in https://github.com/Microsoft/service-fabric/tree/master/docs/architecture.

**Comment by masnider** [comment]
There is no single core subsystem. That page references the "core subsystems" - a list of the major logical groups of functionality in SF. Each part is made up of multiple components and different services. The Subsystem view of Service Fabric is mainly for organizing a view of Service Fabric's functionality and doesn't represent physical, separate entities that run in one place or another. Some of these are distributed components run on every machine, some are services that run on particular machines in the cluster, and some are both. Where represented as separate services (like you would see if you expanded the "System" app in Service Fabric Explorer) can be constrained to run on particular VMs, but there's no notion of doing this "by subsystem".  Hopefully this answers your question. I'm going to close down this issue, if you have further questions please open another one or reopen this one if you feel that my answer was not sufficient.
