### ISSUE TITLE
OnPrem Diagnostics Store Location

### ISSUE THREAD

**Issue by rob-smartspace** [microsoft/service-fabric#1012]
When setting up a cluster onprem the cluster config json file asks us to replace the file share location with one that all nodes can access.

Is there a functional reason to use a network path instead of allowing them to all log to a local disk drive?

My understanding is that location is used only to record and each node's data is independent of each others.  I understand that should a node go down the diagnostics data may not be available for that node.

The reason i ask is i have a situation where a network drive all nodes can authenticate against and read/write data is not possible, the cause of this issue is beyond my control.

**Comment by maburlik** [comment]
The reasoning for a shared network drive is to establish a central store for easy exfiltration of SF logs in case you need to provide diagnostics to us for investigation. Shared network drive is only one option, we also offer first class support to upload logs to an Azure storage container owned by you.

**Comment by robert-io** [comment]
Thanks Max, so the reason for the network path is accessablity in a disaster, meaning SF will function correctly with the logs local to each node.

With regards to exfiltration we have other options so this is not a consideration.

**Comment by robert-io** [comment]
I have the response i wanted but i can't see an option for me to close the issue, so please feel free to close it.
