### ISSUE TITLE
remove an actor forcefully

### ISSUE THREAD

**Issue by pouyapalmerbet** [microsoft/service-fabric#1018]
I am facing a scenario in which, the actor must be removed (don't care if it is busy and running), it seems like if an actor is busy it cannot be removed. I could not find any documentation about this behavior, so I think I am missing something. appreciate it if anyone can help here. this is how I am trying to connect and delete the actor.

`
var proxyFactory = new ServiceProxyFactory((c) => new FabricTransportServiceRemotingClientFactory(settings));
var actorService = proxyFactory.CreateServiceProxy<IActorService>(actorServiceUri, new ServicePartitionKey(partitionKey), listenerName: listener);
await actorService.DeleteActorAsync(actorId, new CancellationToken());
`

**Comment by craftyhouse** [comment]
These threads may help. Please let us know if not. 

https://stackoverflow.com/questions/51326280/how-to-call-azure-service-fabric-remoting-proxy-with-cancellationtoken

https://github.com/microsoft/service-fabric/issues/796#issuecomment-379883950

We do have it in our backlog to update the public docs here with more information about CancellationToken  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-secure-communication
