### ISSUE TITLE
User-assigned Managed Identities added during application upgrade do not work

### ISSUE THREAD

**Issue by jberezanski-mdg** [microsoft/service-fabric#1020]
Service Fabric Runtime Version: 7.1.417.9590

Environment: Azure

Description: 

Since Service Fabric 7.1 was released, we have been relying on its support for Managed Identity to authenticate our services to Azure resources. Our SF application currently consists of 5 services (stateless and stateful). The application has 5 custom user-assigned identities, used by each of the services. In addition, the application has a system-assigned identity configured, but it is not currently used by any service.
Everything is configured appropriately in application and service manifests according to the docs. The cluster has ManagedIdentityTokenService enabled. We are deploying the application via an ARM template. Each of the services obtains tokens from the MI endpoint during startup. **Everything works correctly when the application is deployed from scratch** (a new application instance).

The problem, however, arises when **a new user-assigned identity is added**, either to a new service or to an existing one, **during upgrade of an existing application instance** (from an older applicationTypeVersion). Consider these two applicationTypeVersions:

V1: ServiceA + identity-a, ServiceB
V2: ServiceA + identity-a, ServiceB + identity-b, ServiceC + identity-c

In other words, upgrading from V1 to V2 adds a new service with its own identity and adds an identity to an existing service.

When upgrading an application instance from V1 to V2, the upgrade appears to be successful, however, ServiceB and ServiceC crash upon startup because they **receive a "NotFound" response from the Managed Identity endpoint**.
There is also a discrepancy in what is visible in different Service Fabric Explorer tabs for the application:
- on the "Essentials" tab, all expected identities are shown (identity-a, identity-b, identity-c) together with their AAD object ids;
- on the "Details" tab, only the one previously existing identity is shown (identity-a).

We tried waiting for some time (~30 minutes) to account for hypothetical AAD replication latency, but nothing changed. Then we tried deleting and creating a new instance of ServiceB and ServiceC, but to no effect. Restarting SF nodes did not help either. The only thing that worked was to **delete the entire application and deploy it from scratch** - obviously an unacceptable solution, even if we were not using stateful services.

Observed behavior:

The ManagedIdentityTokenService returns NotFound when a service is trying to obtain a token for a user-assigned identity added during upgrade of an existing application.

Expected Behavior:

A token for a user-assigned identity added during upgrade of an existing application can be obtained immediately after application upgrade.

OS(Windows/Linux): Windows

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by jberezanski-mdg** [comment]
We had a couple of additional findings after experimenting with a trivial test application.

The test application consists of code generated by the Visual Studio .NET Core SF Stateless and Stateful Service wizards, modified only to acquire a token from the Managed Identity endpoint in the service constructor and throw an exception if the token cannot be obtained. There are two ApplicationTypeVersions:
- Version V1 consists of 2 services: S1 and S2. S1 uses a SystemAssigned managed identity. S2 does not use any identity (and does not acquire a token).
- Version V2 consists of 3 services: S1, S2 and S3. S1 is unmodified. S2 and S3 have a user-assigned managed identity (each service its own) and try to acquire tokens at startup.

Here is what we observed:
1. On one of our clusters, after upgrading the application from V1 to V2 (adding user-assigned MI to one existing service and adding a new service with a user-assigned MI), the services started failing. However, after about 26 hours (!), the services recovered.
2. On another cluster, we performed this sequence of steps:
a) created a new instance ("app1") of the application with version V1;
b) upgraded app1 to version V2 -> the services started failing, as above;
c) created a new instance ("app2") of the application with version V2 -> services in app2 worked correctly from the start, but additionally, once app2 finished deploying, services in app1 started working, too (!).

This observed behavior suggests that there may exist a cache of identity information for a given ApplicationTypeVersion; that cache is invalidated when deploying a new application, but not when upgrading an existing one; eventually (after a long time) the cache expires and the upgraded application starts behaving correctly. (This is just a hypothesis and I may be, of course, wildly off the target here.)

**Comment by craftyhouse** [comment]
Sorry for the delay here. Were you able to get any further with this or see any difference on 7.2?

**Comment by jberezanski-mdg** [comment]
No difference observed on 7.2. We had opened a support ticket (id 120092124008193) and learned that it was caused by the Service Fabric resource provider caching the identities for 24 hours and that a fix was being worked on, but with no ETA. (That was in early October.)

Right now, we are working around it by performing deployments in two stages: first we add/configure identities, wait at least 24 hours and only then proceed to deploy code changes.

**Comment by craftyhouse** [comment]
Thanks for the details, that helped a lot. Confirmed it was fixed internally so tracking down what release it will be available in.

**Comment by dragav** [comment]
@jberezanski-mdg I am assuming all the app upgrades are going through SFRP, as updates/PUTs on Azure resources. Would be great to have this confirmation - anything else is not supported.

Working from that assumption: we are aware of a couple of bugs whose effect would match the symptoms reported above. Both bugs have been fixed, and their respective releases rolled out. That is, we would not expect to see this in any SF72 cluster/in any region. Again, this operates on the premise that you are upgrading SF apps via ARM, and that the config version of the app/service manifests are incremented with each deployment.

If the above holds and you are still seeing an issue with an SF72 cluster, please open a support case so we can take a look at the cluster activity and traces. Thanks.

@amenarde FYI

**Comment by jberezanski-mdg** [comment]
Our app upgrades are always performed by redeploying the ARM template with a new `Microsoft.ServiceFabric/clusters/applicationTypes/versions` resource and updated `typeVersion` property of the `Microsoft.ServiceFabric/clusters/applications` resource. All version numbers in the manifests (application type, service types, code and config packages) are always incremented (they are actually generated from Azure DevOps build id).

I don't remember when was the last time we saw the issue, because we have been using the two-stage deployment workaround since October. I will check it over the next couple of days and open a new support ticket if needed, as you suggested.

We did encounter a (seemingly) similar problem earlier this week: after adding an existing user-assigned MI (used by a SF service) to a new Azure AD group (which granted additional access rights to some resources) and upgrading the SF app to a new version, the tokens received from the Managed Identity Token Service did not allow access to those new resources for several (at least 6) hours. This too seemed like a token caching issue (unfortunately we could not wait to see when/if it would resolve automatically by itself). But I suspect this should be treated as a separate issue - we will open a support ticket once we finish checking everything on our side.

**Comment by dragav** [comment]
Changing identities should always require a 2-step deployment; adding new services with new identities should be fixed as noted above.

With regards to tokens - the SF runtime does cache tokens (lookup key is the service instance id + token audience), for a bit less than the lifetime of the token (and the service itself should do the same). The RP does not cache tokens, only credentials. Caching is required (throughout the pipeline) to avoid throttling conditions imposed by the Managed Identity service (which are the order of low thousands per 20s window). To force the re-issuance of a token, you can restart the service instance or move it to another node.

**Comment by jberezanski-mdg** [comment]
Just wanted to confirm that everything now works as expected when we add new identities to existing services, so this issue can be closed.

**Comment by dragav** [comment]
Thanks for confirming.
