### ISSUE TITLE
Unable to install service Fabric

### ISSUE THREAD

**Issue by Kris001Sharma** [microsoft/service-fabric#1023]
Service Fabric Runtime Version: 
7.1.456
Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
local
Description: 
Trying to install service fabric using WebPI but not able to do so.

Observed behavior:
![image](https://user-images.githubusercontent.com/23724226/92433897-fcc26c80-f1bb-11ea-88e5-56454da526dc.png)

Here is the log:
08-09-2020 04:35:26,Info,Installing Service Fabric Runtime. Logs written to C:\WINDOWS\TEMP\InstallFabricRuntime_637351563267491060.log
08-09-2020 04:35:26,Info,Running extract in parallel.
08-09-2020 04:35:26,Info,Unpackaging autoextractor...
08-09-2020 04:35:26,Info,08-09-2020 10:05:26 Running Process: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser with timeout 00:01:00
08-09-2020 04:35:27,Info,Current Powershell Execution Policy: Unrestricted
08-09-2020 04:35:27,Info,Searching for legacy installation registry key.
08-09-2020 04:35:27,Info,Service Fabric Product not detected in registry.
08-09-2020 04:35:27,Info,Found legacy fabric files at C:\Program Files\Microsoft Service Fabric. Start removal...
08-09-2020 04:35:27,Info,Executing powershell.exe with parameters: -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\CleanFabric.ps1' -LogPath C:\WINDOWS\TEMP\FabricSetupLog.Uninstall_637351563267491060.log
08-09-2020 04:35:27,Info,08-09-2020 10:05:27 Running Process: powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\CleanFabric.ps1' -LogPath C:\WINDOWS\TEMP\FabricSetupLog.Uninstall_637351563267491060.log with timeout 00:10:00
08-09-2020 04:35:27,Info,Creating temporary runtime directory C:\Program Files\Microsoft Service Fabric.ixnqq4jv.5dj.
08-09-2020 04:35:27,Info,Extracting runtime cab to C:\Program Files\Microsoft Service Fabric.ixnqq4jv.5dj...
08-09-2020 04:35:27,Info,08-09-2020 10:05:27 Running Process: C:\WINDOWS\TEMP\MicrosoftServiceFabricAutoextractor.exe /L "C:\Program Files\Microsoft Service Fabric.ixnqq4jv.5dj" /E /Y with timeout 01:00:00
08-09-2020 04:35:28,Info,Legacy Fabric Uninstalled using CleanFabric.ps1!
08-09-2020 04:35:37,Info,Successfully extracted cab file to C:\Program Files\Microsoft Service Fabric.ixnqq4jv.5dj
08-09-2020 04:35:37,Info,Moving FabricRoot files from 'C:\Program Files\Microsoft Service Fabric.ixnqq4jv.5dj' to 'C:\Program Files\Microsoft Service Fabric'.
08-09-2020 04:35:37,Info,Installing Service Fabric Runtime... Logs written to: C:\WINDOWS\TEMP\FabricSetupLog_637351563267491060.log
08-09-2020 04:35:37,Info,Executing powershell.exe with parameters: -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -AcceptEULA -LogPath C:\WINDOWS\TEMP\FabricSetupLog_637351563267491060.log
08-09-2020 04:35:37,Info,08-09-2020 10:05:37 Running Process: powershell.exe -NoProfile -Command & 'C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\InstallFabric.ps1' -FabricRootIsPreInstalled -AcceptEULA -LogPath C:\WINDOWS\TEMP\FabricSetupLog_637351563267491060.log with timeout 00:10:00
08-09-2020 04:35:38,Info,Successfully installed Service Fabric Runtime

Expected Behavior:

OS(Windows/Linux): 
Win 10
If this is a regression, which version did it regress from?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by Kris001Sharma** [comment]
tried to install older version directly using runtime.exe and runtime.
still no luck
![image](https://user-images.githubusercontent.com/23724226/92434110-9ee25480-f1bc-11ea-8180-ff9e89845774.png)

**Comment by githubkelv** [comment]
I got the same error few days ago and resolve it by adding:

%SystemRoot%\system32  to the PATH env variable

**Comment by athinanthny** [comment]
@anantshankar17  Please can you investigate this issue

**Comment by craftyhouse** [comment]
As described above please make sure your PATH is not misconfigured

Validate %SystemRoot%\system32 is set to the PATH env variable. Can validate by typing "path" in a cmd prompt.
