### ISSUE TITLE
7.1 CU5 or CU4?

### ISSUE THREAD

**Issue by jberezanski-mdg** [microsoft/service-fabric#1033]
The latest SF release is named "Fourth Refresh" both in the [announcement article](https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-1-fourth-refresh-release/ba-p/1653859) and in the [release notes](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-71CU5-releasenotes.md). However, the release notes file is named "Service-Fabric-71CU5-releasenotes.md" instead of "...71CU4..." - a typo?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by maburlik** [comment]
CU4 was an intermediate release candidate and was skipped.

**Comment by jberezanski-mdg** [comment]
I see. Thank you for clarification.
