### ISSUE TITLE
I've been trying to create a new SF Cluster but the VMSS once create going into a continuous updating moded. 

### ISSUE THREAD

**Issue by Jim-Guthrie** [microsoft/service-fabric#1037]
**Describe the bug**
After a clean deployment I can't use my cluster because the VMSS instances are continuously updating. 

**To Reproduce**
deploy new service fabric cluster. Add the Geneva extension. bring a bit to eat. This is the 3rd time I'm at more that 4 hours of updating and can't use the cluster. 

**Expected behavior**
Cluster to be deployed and in use in under an hoiur. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71749662/93971373-e2909e80-fd24-11ea-8f25-061352b3d1ca.png)

![image](https://user-images.githubusercontent.com/71749662/93971407-f5a36e80-fd24-11ea-900a-f9379a98763b.png)

![image](https://user-images.githubusercontent.com/71749662/93971459-1075e300-fd25-11ea-9357-59121165c8d6.png)

 -  Service Fabric version : 7.1.458.9590 
 - OS(for browser not SF) : 2004 19041.208
 - Browser/ Browser version [e.g. chrome, safari]: Edge

**Additional context**

**Comment by craftyhouse** [comment]
@Jim-Guthrie are you still facing this issue?

**Comment by peterpogorski** [comment]
Closing this issue, @Jim-Guthrie feel free to reopen if you are still experiencing it.
