### ISSUE TITLE
Possible to disable ip6tables in FabricDeployer.dll?

### ISSUE THREAD

**Issue by drnic** [Microsoft/service-fabric#104]
On my Xenial image, FabricDeployer.dll is failing with this `ip6tables` command:

```
# ip6tables  -w 30  -I  OUTPUT  1  -p  tcp  --dport 19080  -m comment --comment  'WindowsFabric:azure-service-fabric0 WindowsFabric Http Gateway (TCP-Public-Out)' -j ACCEPT
ip6tables v1.6.0: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
```

I've raised a ticket with purveyors of fine base images https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/40

Is it possible to disable this `ip6tables` command (that is, disable IPv6 support in general) until I resolve this issue with my Xenial distro?

In this repo, it only looks like IPv4 *OR* IPv6 is used, not both https://github.com/Microsoft/service-fabric/blob/master/src/prod/src/Hosting2/FirewallSecurityProvider.cpp#L388-L399 (it tries IPv4, then tries IPv6 I think)

Although https://github.com/Microsoft/service-fabric/blob/master/src/prod/src/Hosting2/FirewallSecurityProvider.cpp#L549-L560 looks like it assumes both are setup.

**Comment by bpm-ms** [comment]
@raunakpandya and @maburlik do you guys know how he might be able to get this work? Can you follow up and figure out whether this is currently possible?

**Comment by drnic** [comment]
Issue resolved by configuration in `bosh deploy` manifest https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/40#issuecomment-384117628 (apparently IPv6 is disabled by default; sorry I didn't know)
