### ISSUE TITLE
Managed cluster load balancing rules missing support for defining port for probe

### ISSUE THREAD

**Issue by juho-hanhimaki** [microsoft/service-fabric#1048]
I was skimming through the managed cluster ARM template and it seems that it's not possible to define a port for the probe in the load balancer (i guess backend port is assumed?). 

In some existing stuff we are using cluster configuration where a listener on the probe port will start listening only after some initialization has been finished. The actual backend port has possibly been listened for a while before that. We may also want to take the probe down independently from the backend service.

Additionally I think it should be possible to share a single health probe with multiple load balancing rules.

Imo it would be useful to have more control over probes to enable all kinds of application scenarios.

https://docs.microsoft.com/en-us/azure/templates/microsoft.servicefabric/2020-01-01-preview/managedclusters

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by peterpogorski** [comment]
Thanks for the suggestion @juho-hanhimaki! This is something that we should be able to add to the encapsulated model and will add to the backlog for future API releases.

**Comment by craftyhouse** [comment]
Please review and let us know if you still have gaps
https://docs.microsoft.com/en-us/azure/templates/microsoft.servicefabric/2021-07-01-preview/managedclusters?tabs=bicep#loadbalancingrule
