### ISSUE TITLE
Managed Cluster - Deploy to existing Vnet?

### ISSUE THREAD

**Issue by CodedBeard** [microsoft/service-fabric#1049]
Just having a look through the new templates and roadmap, I don't see any mention of the ability to deploy a new managed cluster into an existing vnet?  Our existing clusters are all deployed to an existing vnet attached to our express route circuit, as most of the traffic is internal only, and the parts that are not are exposed via app gateway to the internet not directly.

Is existing vnet support on the roadmap, or already available and im just being blind?

**Comment by peterpogorski** [comment]
You currently are not able to deploy a managed cluster into existing Vnet. This is something that I will add to the roadmap as we will want to provide this support for our customers.

**Comment by gh-sachip** [comment]
We need this feature to use existing VNETs will this be supported? When?

**Comment by jonielsen** [comment]
Any update on when VNET support will be available  with managed SF clusters?

**Comment by craftyhouse** [comment]
We are targeting the week of 8/23 for the new preview api that includes this feature. Docs and a blog announcement should coincide with the availability.

**Comment by jkonecki-techfabric** [comment]
@craftyhouse I would appreciate if you could add a comment to this issue once the preview API has been published.
I'm eager to use it straight away.
