### ISSUE TITLE
Service Bus 1.1 (Windows Fabric) and Service Fabric Runtime & SDK

### ISSUE THREAD

**Issue by jaliyaudagedara** [microsoft/service-fabric#105]
I am having trouble getting Service Bus 1.1 to work when the same machine has Service Fabric runtime (6.2.262) and SDK (3.1.262) installed. Service Bus 1.1 uses Windows Fabric.

Is there any way that I can have both of them running and working on the same machine. Because one project requires Service Bus 1.1 and other needs Service Fabric.

**Comment by jaliyaudagedara** [comment]
Just noted, after installing Service Fabrik Runtime and SDK, Windows Fabric service is no longer under Services. So it's no surprise, it doesn't work.

**Comment by rishirsinha** [comment]
These two technologies do not work with each other. We have taken a work item to make it more explicit.
