### ISSUE TITLE
Release notes missing of version 7.1.429.9590description of Issue

### ISSUE THREAD

**Issue by BaMi83** [microsoft/service-fabric#1053]
Service Fabric Runtime Version: 7.1.429.9590

Environment: Azure

Description:  Release notes missing of version 7.1.429.9590

Observed behavior: i can choose version 7.1.429.9590,  but can't find the releasenotes of this version. and what happend with CU4?

Expected Behavior:

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
This has all the release notes for versions we have publicly released:
https://github.com/microsoft/service-fabric/tree/master/release_notes

Hope that helps. Please let us know if you have more questions.
