### ISSUE TITLE
Update Service Fabric source

### ISSUE THREAD

**Issue by tsarpaul** [microsoft/service-fabric#1059]
Hi,

Current open-source service fabric version is 6.4 (look at commits here: https://github.com/microsoft/service-fabric/tree/master/src)
When will there be an update? Is the release plan schedule relevant?

**Comment by tsarpaul** [comment]
Hi!

Any ETA? :)

**Comment by tsarpaul** [comment]
bump

**Comment by LeroyK** [comment]
Duplicate of #437

**Comment by craftyhouse** [comment]
thanks @LeroyK 
Please follow https://github.com/microsoft/service-fabric/issues/437 for updates on this so we can answer in one place.
