### ISSUE TITLE
The configuration system feels outdated

### ISSUE THREAD

**Issue by stijnherreman** [microsoft/service-fabric#106]
After getting used to the joy that is Microsoft.Extensions.Configuration, configuring Service Fabric feels outdated.

Instead of setting an environment variable containing the environment name (on my own device or e.g. via App Service application settings in the Azure portal) and loading environment-specific configuration from whatever source I like, I have to use a [complex](https://stackoverflow.com/questions/33928204/where-do-you-set-and-access-run-time-configuration-parameters-per-environment-fo) XML-based system and publish profiles for managing per-environment configuration. I'm having flashbacks to all my unpleasant experiences with configuring WCF.

A highly upvoted comment from the above link shows that a lot of people dislike the current configuration system:

> Can I just say "yuck!". This is hopelessly convoluted for a simple environment based setting. This is ripe for some dev effort from the SF team.

I don't have suggestions right now for how to improve this, because I'm pretty new to Service Fabric. Nevertheless I think it's useful to voice my concerns on this, if only to get a discussion started.

**Comment by vturecek** [comment]
@stijnherreman - totally agree. There's actually been a lot of work happening to get a fresh start on all the configuration and manifest files you see today with the goal of drastically simplifying things, decoupling a lot of the overloaded configuration settings, and of course, moving away from XML. 

That work started a while back before we went open source but it will make its way out here too as we continue to transition the project to GitHub. We'll likely start posting some specs and designs in the next couple of weeks.

**Comment by stijnherreman** [comment]
That's great to hear, I'm looking forward to the new designs 👍
