### ISSUE TITLE
Windows Update 20H2 causing local DEV Service Fabric clusters from Starting

### ISSUE THREAD

**Issue by kms254** [microsoft/service-fabric#1066]
Service Fabric Runtime Version: 7.1.456.9590

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
Dev cluster
Description: After Installing Windows updates 20H8 the user cannot start up the dev cluster on their local machine. Starting up the cluster eventually crashes causing the machine to enter a forced reboot. 

Observed behavior:  Starting up a local cluster One/Five Node it starts up successfully and then shortly there after there is a failure that causes the entire machine to reboot and cluster never actually starts up.

Expected Behavior: Dev Cluster starts up like normal. 

OS(Windows/Linux): Windows 10 20H2

If this is a regression, which version did it regress from? After the Windows 10 20H2 update.

Notes:
I have uninstalled, rebooted, cleared out orphaned  files on the OS, rebooted, reinstalled via the WPI fabric. We have attempted to apply additional updates after 20H8. I have tried resetting the local cluster. I have looked through the generated trace logs. Additionally this update seems like it cleared out all of our local computers certificates.  I thought this was the problem but after resetting the cluster and reinstalling the Fabric runtime/sdk the auto generated cert was remade. This is happening on multiple machines. 

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
@kms254  Is this still occurring with 7.2? I'm on the same build of windows and not heard of this happening elsewhere.

Any further info/traces/windows event logs you can share?

**Comment by kms254** [comment]
Right now I am running 7.1.456.9590 since that is what matches our dev cluster.  I think this issue is related because the systems will crash and force reboot when going into users and groups:
https://www.bleepingcomputer.com/news/microsoft/windows-10-20h2-lsass-crash-issue-causes-forced-reboots/

I haven't formatted my machine yet so ill work on getting some logs.

**Comment by craftyhouse** [comment]
The issue you linked above got resolved yesterday if that was affecting you, may be worth updating your boxes now.
As of January 7, 2020, this issue is now resolved and the safeguard hold has been removed when devices are using the latest feature update bundles and refreshed media. Please note, if there are no other safeguards that affect your device, it can take up to 48 hours before you will be able to the update to Windows 10, version 2004 or Windows 10, version 20H2.

Please re-open if we can help further.
