### ISSUE TITLE
Service Fabric is stuck deploying, VMs have no D drive

### ISSUE THREAD

**Issue by nottu** [microsoft/service-fabric#1071]
Environment: Azure

Description: D drive is not attached

OS(Windows/Linux): Windows

I can see the following Events when I remote into one of my VMSS instances.

ERROR: Microsoft.Azure.ServiceFabric.Extension.Core.AgentException: Service Fabric data drive for "dataPath":D:\\SvcFab may not be available.

Heartbeat: Not Ready: Service Fabric data drive for "dataPath":D:\\SvcFab may not be available. Check whether the drive is mounted correctly.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by maburlik** [comment]
Your deployment template SF vm extension properties describe D:\SvcFab as the data root location. You can change this to a well known drive you expect to exist.

**Comment by maburlik** [comment]
Here is the reference doc with more explicit instructions:
https://techcommunity.microsoft.com/t5/azure-paas-blog/changing-datapath-in-service-fabric-cluster/ba-p/1502439

It says this line:
"This is strictly only for test clusters as DataPath set to anything other than the temporary D drive is unsupported and if something goes wrong with cluster with this configuration, you should be ready to re-build your cluster."
but this is more an assertion that by changing this path you are responsible for the robust existence and persistence of this path across machine reboots, reimages, etc. Service Fabric will run the same way as long as this path remains reliably present.

**Comment by peterpogorski** [comment]
@nottu are you still experiencing any issues with this?

**Comment by peterpogorski** [comment]
Closing this issue, @nottu feel free to reopen if you are still experiencing any issues.
