### ISSUE TITLE
Reliable dictionary throws System.Timeout exception - Timed out waiting for Exclusive lock

### ISSUE THREAD

**Issue by CloudStu** [microsoft/service-fabric#1074]
Service Fabric Runtime Version: 7.1.458.9590

Environment: Azure

Description: ReliableDictionary throws System.TimeoutException

When calling AddOrUpdateAsync, we often see exceptions of the form

> Timed out waiting for Exclusive lock on key; id=06456e56-5be9-4014-9b25-131a93cc2b8d@132479419220050358@urn:parents/dataStore@132479419345046409, timeout=4000ms, txn=132493742374894375, lockResourceNameHash=18104434

    at async Task<TValue> System.Fabric.Store.TStore<TKey, TValue, TKeyComparer, TKeyEqualityComparer, TKeyRangePartitioner>.AddOrUpdateAsync(IStoreWriteTransaction transaction, TKey key, Func<TKey, TValue> addValueFactory, Func<TKey, TValue, TValue> updateValueFactory, TimeSpan timeout, CancellationToken cancellationToken)   
    at async Task<TValue> Microsoft.ServiceFabric.Data.Collections.DistributedDictionary<TKey, TValue>.AddOrUpdateAsync(Transaction tx, TKey key, TValue addValue, Func<TKey, TValue, TValue> updateValueFactory, TimeSpan timeout, CancellationToken cancellationToken)

Observed behavior: In one production environment for example, I can see the above exception has been thrown over 100 times in the last 7 days.

Expected Behavior: No exception.

OS(Windows/Linux): Windows

In particular, I'd like to understand what this exception means. I thought it indicated a system under stress, but I also see it is sometimes thrown during relatively quiet periods.

I assume the exception is transient, but as well as avoiding the exception in the first place, can you advise how we should handle it - is retrying recommended, or will it simply exacerbate the problem?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by zuhairp** [comment]
Is that the full message?  In newer versions of SF, the message should have more details that can help us answer your question.

**Comment by CloudStu** [comment]
Yes, that is the full message. Do we know which version introduces the additional details? I will coordinate with my team to upgrade.

**Comment by zuhairp** [comment]
I just noticed that you said you are running on 7.1, which definitely includes the longer message that I expect. The expanded exception message includes which other transaction the transaction is blocked on. You could approximate it by tracing the transaction ID at both the beginning and after CommitAsync() to see which transaction is stuck longer than the timeout (default is 4 seconds).

One common issue that I've seen is code where a single transaction first does a read (like TryGetValueAsync) followed by a write (like AddOrUpdateAsync). In that case, you can pass LockMode.Update to the TryGetValueAsync to break the deadlock.

**Comment by CloudStu** [comment]
My apologies, I've checked another error and found there is more info. Either it was lost the first time it was sent to me, or we had a mix of old and new clusters (we have dozens).

> Timed out waiting for Exclusive lock on key; id=e41d0b00-2a45-491b-a373-d9f2fdabc34c@132470161183211823@urn:parents/dataStore@132470153578627758, timeout=4000ms, txn=132471291341522950, lockResourceNameHash=1778992875958245207; **oldest txn with lock=132471291341522948 (mode Shared)**

I'm not sure what to do with this info though. We aren't actively logging all of our transactions, so this information doesn't mean much to me. Is there somewhere I can look this up, or do I need to add more logging (or add a listener for some built in logging?)

> One common issue that I've seen is code where a single transaction first does a read (like TryGetValueAsync) followed by a write (like AddOrUpdateAsync). In that case, you can pass LockMode.Update to the TryGetValueAsync to break the deadlock.

This service has 3 different transactions on a single reliable dictionary. The one I just copied here is from a transaction that only calls AddOrUpdateAsync. Another transaction, which is only called during service initialisation, calls CreateEnumerableAsync and MoveNextAsync (so only reads), but should never run concurrently with the other transactions.

The final transaction, which might run concurrently with the first calls TryGetValueAsync followed by a SetAsync or RemoveAsync.

It sounds like this transaction should be using LockMode.Update on the TryGetValueAsync.

Could this transaction and its lack of correct LockMode be causing deadlock in the first transaction with the AddOrUpdateAsync? Or is it only expected it might cause a deadlock within itself? Just trying to understand if this LockMode.Update on this other transaction could be the silver bullet that fixes the deadlock in the first transaction.

Many thanks!

**Comment by zuhairp** [comment]
The "TryGetValueAsync-Set/RemoveAsync" transaction will deadlock with another "TryGetValueAsync-Set/RemoveAsync" transaction working on the same key. If those two transactions deadlock with each other, then all other transactions that operate on the same key will start timing out as well. 

Without a full picture of the system, it's hard for me to say that it's the silver bullet, but it's worth trying out.

**Comment by zuhairp** [comment]
Hi @CloudStu, did switching to LockMode.Update help?

**Comment by zuhairp** [comment]
Closing issue since there hasn't been a response. Please reactivate if necessary
