### ISSUE TITLE
Unable to add node 7.2.413.9590

### ISSUE THREAD

**Issue by vdvarlamov** [microsoft/service-fabric#1077]
Service Fabric Runtime Version: 7.2.413.9590

Environment: Standalone  cluster

Description: 
**Unable to add node !**

> Add nodes to clusters configured with Windows Security using gMSA
> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes
```
System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
AggregateException: One or more errors occurred.
 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65
   at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient11.EndUpgradeConfiguration(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

> Add-ServiceFabricNode
> https://docs.microsoft.com/en-us/powershell/module/servicefabric/add-servicefabricnode?view=azureservicefabricps
```
 Add-ServiceFabricNode -NodeName "node6" -NodeType "NodeSecondary" -IpAddressOrFQDN "*.*.*.*" -UpgradeDomain "UD1" -FaultDomain "fd:/dc1/r1" -FabricRuntimePackagePath .\DeploymentRuntimePackages\MicrosoftAzureServiceFabric.7.2.413.9590.cab
Trace folder already exists. Traces will be written to existing trace folder: C:\SF_source\DeploymentTraces
Opening TraceWriter SFDeployer, path C:\SF_source\DeploymentTraces\SFDeployer-637408704984415821.trace
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.
Adding Service Fabric Node...
Add node creating new node in manifest: NodeName: node6, UpgradeDomain: UD1, FaultDomain: fd:/dc1/r1, IPAddressOrFQDN: *.*.*.*, NodeTypeRef: NodeSecondary, IsSeedNode: False
Configuring nodes.
Default installation directory chosen based on system drive of machine '*.*.*.*'.
Copying installer to all machines.
Configuring machine '*.*.*.*'.
System.IO.FileNotFoundException: ServiceFabricServiceModel.xsd
   at System.Fabric.Common.SchemaLocation.GetWindowsFabricSchemaLocation()
   at System.Fabric.FabricDeployer.DeploymentParameters.Initialize()
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.NewNodeConfigurationInner(String clusterManifestPath, String infrastructureManifestPath, String jsonClusterConfigPath, String fabricDataRoot, String fabricLogRoot, String fabricHostCredentialUser, SecureString fabricHostCredentialPassword, Boolean runFabricHostServiceAsManual, Boolean removeExistingConfiguration, FabricPackageType fabricPackageType, String fabricPackageRoot, String machineName, String bootstrapPackagePath)
....................................................
Deployment failed. Cleaning node node6.
Trace folder already exists. Traces will be written to existing trace folder: C:\SF_source\DeploymentTraces
Closing TraceWriter SFDeployer, path C:\SF_source\DeploymentTraces\SFDeployer-637408704984415821.trace
Cleaning up faulted installation.
Opening TraceWriter SFDeployer, path C:\SF_source\DeploymentTraces\SFDeployer-637408705026157070.trace
Collecting event logs failed due to error System.IO.FileNotFoundException: Could not find file '\\*.*.*.*\C$\Windows\temp\ServiceFabricEventLog.txt'.
File name: '\\*.*.*.*\C$\Windows\temp\ServiceFabricEventLog.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass16_0.<RemoveNodeConfigurationAsync>b__1(String machineName) on machine *.*.*.*. Please go to each node to view event logs.
Closing TraceWriter SFDeployer, path C:\SF_source\DeploymentTraces\SFDeployer-637408705026157070.trace
Add-ServiceFabricNode : One or more errors occurred.
At line:1 char:1
+ Add-ServiceFabricNode -NodeName "node6" -NodeType "NodeSecondary" -Ip ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Servi...usterConnection:ClusterConnection) [Add-ServiceFabricNo
   de], AggregateException
    + FullyQualifiedErrorId : StartNodeErrorId,Microsoft.ServiceFabric.Powershell.AddNode
```
`'*.*.*.*'` - IP address

OS(Windows/Linux): Windows Server 2019

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by maburlik** [comment]
This is hit because the ServiceFabricServiceModel.xsd is not found, and likely has to do with how you are loading the modules.

Either:
1. Run AddNode.ps1, which will extract the standalone package DeploymentComponents which contains the file.
2. Install SF (to enable FabricEnvironment.GetCodePath() to work) and add the node remotely via cmdlets.
3. Copy over the ServiceFabricServiceModel.xsd to the common directory of the entry assembly for your execution path.

Keep in mind only #1, #2 are supported and #3 is a workaround.

class SchemaLocation
    {
        private const string ServiceFabricSchemaFileName = "ServiceFabricServiceModel.xsd";

        public static string GetWindowsFabricSchemaLocation()
        {
            string fabricCodePath = null;
            try
            {
                fabricCodePath = System.Fabric.Common.FabricEnvironment.GetCodePath();
            }
            catch (FabricException) { }
            if (fabricCodePath != null)
            {
                string schemaLocation = System.IO.Path.Combine(fabricCodePath, ServiceFabricSchemaFileName);
                if (System.IO.File.Exists(schemaLocation))
                {
                    return schemaLocation;
                }
            }

#if !DotNetCoreClr
            var entryAssembly = System.Reflection.Assembly.GetEntryAssembly();
            if (entryAssembly != null)
            {
                string entryPointLocation = System.IO.Path.GetDirectoryName(entryAssembly.Location);
                if (entryPointLocation != null)
                {
                    string schemaLocation = System.IO.Path.Combine(entryPointLocation, ServiceFabricSchemaFileName);
                    if (System.IO.File.Exists(schemaLocation))
                    {
                        return schemaLocation;
                    }
                }
            }
#endif

            var currentAssembly = typeof(SchemaLocation).GetTypeInfo().Assembly;
            if (currentAssembly != null)
            {
                string currentAssemblyLocation = System.IO.Path.GetDirectoryName(currentAssembly.Location);
                if (currentAssemblyLocation != null)
                {
                    string schemaLocation = System.IO.Path.Combine(currentAssemblyLocation, ServiceFabricSchemaFileName);
                    if (System.IO.File.Exists(schemaLocation))
                    {
                        return schemaLocation;
                    }
                }
            }

            throw new System.IO.FileNotFoundException(ServiceFabricSchemaFileName);
        }
    }

**Comment by craftyhouse** [comment]
Thanks @maburlik 

@vdvarlamov Please let us know if the above does not resolve the issue.

thanks
