### ISSUE TITLE
Fix typo in generated ServiceManifest.xml from VS template

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric#1080]
Service Fabric Runtime Version: 7.1.458

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
One-box, one-machine cluster

Description: 
The current VS Service Fabric templates all generate a ServiceManifest.xml on which line 22 contains a typo. It produces a typo which reads:

```
  <!-- Config package is the contents of the Config directoy under PackageRoot that contains an 
```

Note that "directoy" is missing an "r".  This has been bugging me since I've started using Service Fabric, so it's only just now occurred to me that I could file a ticket about it.

It's low priority, but it's got to be a pretty easy fix.

Observed behavior:
There's a typo in the generated ServiceManifest.xml file, at or around line 22.

Expected Behavior:
"directoy" is spelled correctly as "directory" in the generated ServiceManifest.xml file, at or around line 22.

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from?
This has been an issue as long as I can recall.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by BigMorty** [comment]
This typo has been fixed in the next release (16.9 Preview 3) of the VS Service Fabric tools, thanks for reporting it!
