### ISSUE TITLE
One node X509 cluster creation fails

### ISSUE THREAD

**Issue by mcurko** [microsoft/service-fabric#1086]
Service Fabric Runtime Version: 7.2.434.9590

Environment: Standalone

Description: Certificate wad installed on the server according to the procedure describede here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-x509-security and ASF cluster creation attempted using the attached script. The creation failed.

Observed behavior: failure

Expected Behavior: success
[files.zip](https://github.com/microsoft/service-fabric/files/5573924/files.zip)

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from? n/a

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Same root cause as https://github.com/microsoft/service-fabric/issues/1082
