### ISSUE TITLE
sfctl sa-cluster config outputs FABRIC_E_TIMEOUT on Ubuntu

### ISSUE THREAD

**Issue by aynurin** [microsoft/service-fabric#1095]
Service Fabric Runtime Version:

7.2.431.1804

Environment:

Dev cluster / Standalone 

Description: 

I'm trying to implement one of the configurations that are not currently officially supported. Could you help to point out if the issue I'm facing related to the fact that this is not supported or not? And is the support coming anytime in the future? Is there any way for a workaround?

Two configurations I want to try:

1. Standalone cluster on Ubuntu.
2. Or AWS AutoScaling group of Service Fabric nodes managed by an Azure Service Fabric resource.

For both of these scenarios I want to try and install a DevCluster and then upgrade it via `sfctl sa-cluster config` to a configuration that seemingly should allow the above modes (X509, shared storage, proper certificates, etc.)

I set up the Dev Cluster following these walkthroughs:

* [Prepare your development environment on Linux](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux?tabs=sdksetupubuntu%2Clocalcluster)
* [Azure Service Fabric CLI](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cli)

Observed behavior:

`sfctl cluster health` responds `OK`, but `sfctl sa-cluster config` outputs:

```
Command arguments: ['sa-cluster', 'config', '--configuration-api-version', '1.0.0', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5894750378>, <function OutputProducer.on_global_arguments at 0x7f589401c268>, <function CLIQuery.on_global_arguments at 0x7f58940462f0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f589401c2f0>, <function CLIQuery.handle_query_parameter at 0x7f5894046378>]
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTP connection (1): 127.0.0.1
urllib3.connectionpool : http://127.0.0.1:19080 "GET /$/GetClusterConfiguration?api-version=6.0&ConfigurationApiVersion=1.0.0&timeout=60 HTTP/1.1" 504 70
msrest.exceptions : (FABRIC_E_TIMEOUT) Operation timed out.
(FABRIC_E_TIMEOUT) Operation timed out.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.6/dist-packages/sfctl/entry.py", line 81, in execute
    return super(SFInvoker, self).execute(args)
  File "/usr/local/lib/python3.6/dist-packages/knack/invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/lib/python3.6/dist-packages/knack/commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/knack/commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/lib/python3.6/dist-packages/azure/servicefabric/operations/_service_fabric_client_ap_is_operations.py", line 931, in get_cluster_configuration
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models._models_py3.FabricErrorException: (FABRIC_E_TIMEOUT) Operation timed out.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Performing cluster version check
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTP connection (1): 127.0.0.1
urllib3.connectionpool : http://127.0.0.1:19080 "GET /$/GetClusterVersion?api-version=6.4&timeout=60 HTTP/1.1" 200 26
```

`sfctl sa-cluster config-upgrade` posts a very similar output.

Expected Behavior:

More like "desired behavior" is to be able to update the sa-cluster config and configure a standalone cluster on Ubuntu.

OS(Windows/Linux):

Ubuntu 18.04

If this is a regression, which version did it regress from?

It is a fresh install.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by maburlik** [comment]
There is currently no plan to add a standalone cluster offering for Linux but feel free to create a topic on the SF user voice as we use this as one of our feedback sources to judge whether a feature request should be incorporated into the roadmap.
https://feedback.azure.com/forums/293901-service-fabric

Regarding the timeout behavior this is the same behavior that is seen when issuing the command against a non-standalone Windows cluster as well, since the FabricUOS (Upgrade Orchestration Service) system service does not exist for non-standalone clusters so is not present to receive & process the request.
