### ISSUE TITLE
Installer of Service Fabric Runtime 7.X fails 

### ISSUE THREAD

**Issue by SinueeHernandez** [microsoft/service-fabric#1099]
Not able to install service fabric runtime 7.2.445. Tried already by 

- Web Platform installer   [webpi3.txt](https://github.com/microsoft/service-fabric-issues/files/5667058/webpi3.txt)

- Manual installer.  
![image](https://user-images.githubusercontent.com/13387095/101653326-d30c2200-3a04-11eb-9ab9-c197c9805bb7.png)

- WebPICMD.exe
![image](https://user-images.githubusercontent.com/13387095/101653431-f040f080-3a04-11eb-83d4-e43ca07f1571.png)
Log wasn't generated. 

## Expected Behavior
Be able to install without any problem 

## Current Behavior
Can't install it.

## Steps to Reproduce
1. download a solution of service fabric example. 
2. Open the solution on VS  2019
3. VS asks to install service fabric. 
4. Installer fails. 

#### Service Fabric Runtime and SDK Version :
runtime 7.2.445
SDK  4.2.445

#### Operating System :
Win 10 LTSC  Version 1809 (OS Build 17763.1577)

**Comment by craftyhouse** [comment]
Are you able to use the Web Platform Installer https://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK ? 

Do you by chance have service fabric cluster actually running on your local box?

**Comment by craftyhouse** [comment]
Please reopen if you need more assistance.
