### ISSUE TITLE
Unable to remote debug from Visual Studio 2019 Cloud Explorer

### ISSUE THREAD

**Issue by johnden12** [microsoft/service-fabric#1101]
I am trying to connect to a Azure Linux Service Fabric from visual studio in order to debug an issue I am experiencing.

I have followed the document https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-debugging-your-application#debug-a-remote-service-fabric-application, however there is no option to Enable / Attach Debugger within the VS2019 cloud explorer

Visual Studio 16.7.5
SF Cluster; 5 node Linux Ubuntu 18.01 LTS cluster

**Comment by craftyhouse** [comment]
Were you able to get further with this? If not I'll try to repro.

**Comment by johnden12** [comment]
> Were you able to get further with this? If not I'll try to repro.

I opened a technical support incident with Microsoft, who informed me that remote debugging of linux clusters via cloud explorer is currently not supported. They suggested other means to get the required information, for example Application Insights, or using the LLDB debugger.

**Comment by craftyhouse** [comment]
Glad support was able to assist. Thanks for the update!
