### ISSUE TITLE
Copy-ServiceFabricApplicationPackage additional visibility

### ISSUE THREAD

**Issue by jaydavid** [microsoft/service-fabric#1109]
Hello,

I'm attempting to get a test / development single node cluster up and running.  I have the cluster itself created, but when I attempt to load an application into it using Copy-ServiceFabricApplicationPackage things always seem to stall or hang.

Visual Studio publish does the same, I had hoped to get around that issue by writing some powershell scripts to perform deployments but no luck.

The script is reporting progress, which does move (slowly) up until a point, then it hangs and does not progress.

Hopefully I am not just being impatient.  I've tried to do this in both East US and East US 2 and I'm not certain if the problem is local to my PC or if there is something else in the chain that I'm just missing.

If there are any additional diagnostic details that I can get visibility into using this powershell command I'd be interested to know, or if there are any thoughts to diagnose or work around the issue they would be greatly appreciated.

Thanks!

**Comment by craftyhouse** [comment]
Glad you were able to resolve. Noted on timeout response. Please let us know if you see this again in the future.
