### ISSUE TITLE
Passing application parameters to SetupEntryPoint without affecting EntryPoint

### ISSUE THREAD

**Issue by scharnyw** [microsoft/service-fabric#1117]
Service Fabric Runtime Version: 7.0.457.9590

Environment: Must be one of these values Standalone

Description: 

I have a StatelessService which has a SetupEntryPoint and I would like to pass some parameters from Application Manifest into it. There are 2 solutions I tried:

1. Use EnvironmentVariables, but that would make them visible to my EntryPoint application as well. Preferably I would like to avoid this. There doesn't seem to be a way to set environment variables only for SetupEntryPoint without them being visible to the EntryPoint application.

2. I tried the following but it didn't work because the arguments are passed as a verbatim string:

		<SetupEntryPoint>
		  <ExeHost>
		    <Program>MySetupEntryPoint.exe</Program>
		    <Arguments>[MyApplicationParameter]</Arguments>
		    <WorkingFolder>CodePackage</WorkingFolder>
		  </ExeHost>
		</SetupEntryPoint>

I have seen #375 and several SO questions on this issue but none of it provides a solution or conclusively says that it is not possible. Any clarifications on this would be appreciated.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue so we can assist, but closing at this time.
