### ISSUE TITLE
SFC installation error

### ISSUE THREAD

**Issue by mcurko** [microsoft/service-fabric#1119]
Service Fabric Runtime Version: 7.2.445.9590

Environment: Standalone 

Description: I'm using a new Windows 2016 installation on an Azure VM. Firewall down, NSG completly open. When I try the TestConfiguration.ps1 script with a config having iPAddress set to FQDN or external IP address of the server, the script fails:

```
PS C:\asf> .\TestConfiguration.ps1 -ClusterConfigFilePath letva.json
Trace folder doesn't exist. Creating trace folder: C:\asf\DeploymentTraces
Running Best Practices Analyzer...
Opening TraceWriter SFDeployer, path C:\asf\DeploymentTraces\SFDeployer-637433564841934494.trace
Config validation: Certificate *.mydomain.hr is not installed on node test1971.westeurope.cloudapp.azure.com under My. Check the node availability, certificate installation, and the remote certificate store read permission on the nodes.
Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.
Closing TraceWriter SFDeployer, path C:\asf\DeploymentTraces\SFDeployer-637433564841934494.trace


LocalAdminPrivilege        : True
IsJsonValid                : False
IsCabValid                 :
RequiredPortsOpen          :
RemoteRegistryAvailable    :
FirewallAvailable          :
RpcCheckPassed             :
NoDomainController         :
NoConflictingInstallations :
FabricInstallable          :
DataDrivesAvailable        :
DrivesEnoughAvailableSpace :
Passed                     : False

Test Config failed with exception: System.InvalidOperationException: Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

However, the certificate is installed, and if I use internal IP address of the server, everything is fine:

```
PS C:\asf> .\TestConfiguration.ps1 -ClusterConfigFilePath letva2.json
Trace folder already exists. Traces will be written to existing trace folder: C:\asf\DeploymentTraces
Running Best Practices Analyzer...
Opening TraceWriter SFDeployer, path C:\asf\DeploymentTraces\SFDeployer-637433572542664589.trace
Best Practices Analyzer completed successfully.
Closing TraceWriter SFDeployer, path C:\asf\DeploymentTraces\SFDeployer-637433572542664589.trace


LocalAdminPrivilege        : True
IsJsonValid                : True
IsCabValid                 :
RequiredPortsOpen          : True
RemoteRegistryAvailable    : True
FirewallAvailable          : True
RpcCheckPassed             : True
NoDomainController         : True
NoConflictingInstallations : True
FabricInstallable          : True
DataDrivesAvailable        : True
DrivesEnoughAvailableSpace : True
Passed                     : True
```

The server in question is created from a shapshot that was already used to successfully install the cluster, so I know that with the internal IP address the installation will proceed successfully. I have noticed the problem with FQDN on a customer on-prem server, so the error is consistent across environments.

I observe the same problem on Windows 2019, and also if I add FQDN to local hosts file.

**Config and traces:** [files.zip](https://github.com/microsoft/service-fabric/files/5682722/files.zip)

Observed behavior: Not good, a confusing error message appears.

Expected Behavior: To be able to install the cluster.

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from? n/a

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
This VM was cloned from a snapshot if I understand correctly? I wonder if the ACL's need to be updated if the certs are still properly installed.

I'd recommend following these procedures and see if it helps get you further, specifically step 3
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-x509-security#install-the-certificates

**Comment by mcurko** [comment]
No, this is a clean Windows Server installation on a VM. I did follow the above-metioned procedure. Were the ACLs not set correctly, both checks (with internal IP and with FQDN) would fail.

**Comment by craftyhouse** [comment]
Sorry for the delay, if you are still facing this issue I'd recommend filing a support case so we can assist further. 
https://github.com/microsoft/service-fabric/blob/master/CONTRIBUTING.md#open-an-issue
