### ISSUE TITLE
Is there any specific plan for the release of Standalone Linux clusters?

### ISSUE THREAD

**Issue by MaChao9914** [microsoft/service-fabric#1122]
Is there any specific plan for the release of Standalone Linux clusters?
I am a developer based on Sf.net sdk for application development. I am very interested in Standalone Linux clusters and how to migrate windows clusters to Linux clusters. Is this feasible?

**Comment by craftyhouse** [comment]
There have been no changes to the plans at this time, but would be welcome to hear about your use case as demand helps push priority. 

This comment is still accurate as what options there are currently. 
https://github.com/microsoft/service-fabric/issues/149#issuecomment-669587037

If the current feature gaps do not matter to your applications it should be completely doable. See this link for more info
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-linux-windows-differences

There is a community post about migrating a couple years back, but I'm not aware of any guidance we have posted at this time. 
https://stackoverflow.com/questions/41569030/how-to-migrate-windows-service-in-azure-service-fabric 

Hope that helps

**Comment by MaChao9914** [comment]
> There have been no changes to the plans at this time, but would be welcome to hear about your use case as demand helps push priority.
> 
> This comment is still accurate as what options there are currently.
> [#149 (comment)](https://github.com/microsoft/service-fabric/issues/149#issuecomment-669587037)
> 
> If the current feature gaps do not matter to your applications it should be completely doable. See this link for more info
> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-linux-windows-differences
> 
> There is a community post about migrating a couple years back, but I'm not aware of any guidance we have posted at this time.
> https://stackoverflow.com/questions/41569030/how-to-migrate-windows-service-in-azure-service-fabric
> 
> Hope that helps

Thank you very much for your reply, but I still don’t know about the release plan of Standalone Linux clustersThank you very much for your reply, but I still don’t know about the release plan of Standalone Linux clusters

**Comment by craftyhouse** [comment]
There are no additional options planned at this time, but will definitely update the community if that changes. The bosh method referenced above should help though. Glad to chat more about your use case offline if you want. mike dot craft at microsoft
