### ISSUE TITLE
Missing Release Notes for Service Fabric 7.2 CU3

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric#1123]
Service Fabric Runtime Version: 7.2
Environment: Azure

Description: 

There are no Release Notes for 7.2 CU3 in the https://github.com/microsoft/service-fabric/tree/master/release_notes folder. There are Release Notes for 7.2 RTO, 7.2 CU2 and 7.2 CU4 but 7.2 CU3 appears to be missing. Can they please be added.

Observed behavior:
N/A

Expected Behavior:
N/A

OS(Windows/Linux): 
N/A

If this is a regression, which version did it regress from?
N/A

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by peterpogorski** [comment]
@markwragg you can now find the 7.2 CU3 release notes here: https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-72CU3-releasenotes.md 

The main difference between 7.2 CU2 and 7.2 CU3 is an additional fix for a memory leak in very specific scenarios when using remoting V2 and creating and destroying services dynamically.  This release is a manual upgrade only and was targeted for customers with this specific scenario.
