### ISSUE TITLE
Services from a deleted application are recreated

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#1127]
**Service Fabric Runtime Version:** 7.2.445.9590

**Environment:** Azure

**Description:**

I deleted a SF application to essentially reset my dev environment. I've done this literally hundreds of times. I screwed up some code today, and normally when I do this, I simply publish an update, and the cluster will recover. Today when the update was deployed I noticed a lot of services, which should have been deleted, were still hanging around, and were causing a lot of exceptions (we create / delete services every few minutes.) So, I figured, I'll just reset. So I deleted the app, and kicked off a fresh deploy from devops. After a bit, I came back, and I see that the app has deployed, and there are lots of services, some of which had existed prior to the delete. I thought I was losing my mind, so I deleted everything again, redeployed the app, and once again they're back. There is zero possibility that my code recreated the services, so I suspect there's a major problem with the 7.2.445.9590 release.

**Observed behavior:** Delete app, deploy app, old services be back.

**Expected Behavior:** Delete app, deploy app, old services be gone.

**OS(Windows/Linux):** Windows

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
If you haven't already resolved this or opened a case I'd highly suggest you do at this time so we can get some eyes on what you are seeing so we aren't missing a possible bug.

See guidance here https://github.com/microsoft/service-fabric/blob/master/CONTRIBUTING.md#support-channels

thanks!
