### ISSUE TITLE
Regression: Can't install/reset 1- or 5-node dev cluster in 7.2.445

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric#1131]
Service Fabric Runtime Version: 
7.2.445

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
Dev cluster

Description: 
In SF 4.2.434, I'm able to install and run the local cluster without issue. After upgrading to 7.2.445, any attempt to install either the 1- or 5-node cluster fails. It says to look at the logs, but they're deleted from C:\SfDevCluster\Log before I can look at them. I uninstalled 7.2.445, installed 7.2.434 and the dev cluster works fine. Reinstalling 7.2.445 renders it in the same state - unable to use the dev cluster, so it's definitely a regression in the 7.2.445 release.

The following six events are observed in the Event Viewer at each attempt to install the cluster:

Warning
> The description for Event ID 257 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> SecurityUtility
> UpdateFolderAcl: Folder C:\SfDevCluster\Data does not exist.
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Error
> The description for Event ID 53760 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> FabricSetup.FolderACLManager
> Adding ACLs to data root C:\SfDevCluster\Data failed with error E_INVALIDARG
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Error
> The description for Event ID 53760 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> FabricSetup.FabricSetupOperationBase
> FolderACLManager::Install failed with error E_INVALIDARG
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Error
> The description for Event ID 53760 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> FabricSetup.FabricSetupOperationExecutor
> FolderACLManager::Install failed with error E_INVALIDARG, Rolling back
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Warning
> The description for Event ID 23041 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> FabricActivationManager
> FabricSetup operation returned errorcode E_INVALIDARG
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Warning
> The description for Event ID 23041 from source Microsoft-ServiceFabric cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> FabricActivationManager
> Scheduling FabricSetup retry via timer.
> 
> The publisher has been disabled and its resource is not available. This usually occurs when the publisher is in the process of being uninstalled or upgraded

Observed behavior:
Cluster fails to install and is thus unusable.

Expected Behavior:
Cluster should install and be usable.

OS(Windows/Linux): 
Windows

If this is a regression, which version did it regress from?
Works in 7.2.434, breaks in 7.2.445

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by mevora-msft** [comment]
Just to isolate machine specific issue, could you try installing 445 on a different system? I tried upgrading from 434->445 and didn't run into any issues. Also, could you try uninstalling 434 first before installing 445 and see if that helps?

**Comment by craftyhouse** [comment]
I also did the upgrade and was able to setup a 1 and 5 node cluster without issue. Clean up everything, reboot, try again maybe? Let us know!

**Comment by WhitWaldo** [comment]
Well, this is inexplicably working today, a mere reboot later. I'd already tried uninstalling all the SF versions and then installing only 445, but it didn't work (repeatedly) the other day. I can't explain why a reboot changed anything, but here we are.

Please consider this no longer an outstanding issue and thank you for the quick response!
