### ISSUE TITLE
Fail to start local service fabric cluster

### ISSUE THREAD

**Issue by manish1604** [microsoft/service-fabric#1132]
Service Fabric Runtime Version: 4.2.445.9590

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster] Standalone

Description: Fail to start a new cluster.

Observed behavior:
Local Cluster ready status: 100% completed.
PS>TerminatingError(Connect-ServiceFabricCluster): "No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue."
WARNING: Service Fabric Cluster is taking longer than expected to connect.

Waiting for fabric:/System/NamingService to be ready. This may take a few minutes...
PS>TerminatingError(Connect-ServiceFabricCluster): "No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue."
>> TerminatingError(Connect-ServiceFabricCluster): "No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue."
>> TerminatingError(Connect-ServiceFabricCluster): "No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue."
No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.

Expected Behavior: Local cluster should start

OS(Windows/Linux): Windows

If this is a regression, which version did it regress from?

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by manish1604** [comment]
Also followed the steps:
1. Install vcredist_x64.exe you will also need to:
2.run C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\CleanCluster.ps1
3. run C:\Program Files\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1

It did not help

**Comment by craftyhouse** [comment]
Hello,
Just to verify...
Are you following this guide to deploy the standalone product?
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server

Or this one for onebox/local?
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started

Looks like local/onebox? 1 node or 5 node? There is a UI element in the notification area if using local/onebox you can leverage to setup 1 or 5 node setups.

**Comment by manish1604** [comment]
I was able to resolve the issue after installing few more components in visual studio (VS2019)

Attached installed components of visual studio 19.
![image](https://user-images.githubusercontent.com/31246550/103688963-7a6a6f00-4f47-11eb-8bce-f9df500b2412.png)
