### ISSUE TITLE
Can't find fabricClusterAutoupgradeEnabled in ClusterConfig.json

### ISSUE THREAD

**Issue by hugginssd** [microsoft/service-fabric#1133]
**Service Fabric Runtime Version:** 

 7.0.466.9590

**Environment:** 

Standalone

**Description:** 
1. Navigated to `C:\ProgramData\SF`
2. Opened `ClusterConfig.json`
3. Couldn't find the `fabricClusterAutoupgradeEnabled` as expected

**Observed behavior:**

This is my ClusterConfig.json file currently
[ClusterConfig.txt](https://github.com/microsoft/service-fabric/files/5804146/ClusterConfig.txt)

**Expected Behavior:**

I'm in the process of trying to upgrade my Service Fabric Cluster from 7.0.x to 7.2.x. But now the problem is I can't find the `fabricClusterAutoupgradeEnabled  ` in ClusterConfig.json file in `C:\ProgramData\SF`. 

**OS(Windows/Linux):** 

Windows Server 2016 Datacenter

**NB:** _This is a D365FO on-premise environment_
---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
If this is a production cluster please follow the guidance here https://github.com/microsoft/service-fabric/blob/375d9bb735c0d6e05c445da5a4e4e9721540494f/CONTRIBUTING.md#production-issues to get the proper assistance.

This should help answer your question https://social.msdn.microsoft.com/Forums/en-US/18cde88c-d05d-4229-988c-5dfd36260a65/enable-fabricclusterautoupgradeenabled-flag-on-existing-cluster
