### ISSUE TITLE
EndpointCertificate behavior - order and valid only?

### ISSUE THREAD

**Issue by denis-dbm** [microsoft/service-fabric#1134]
Service Fabric Runtime Version: 7.0.470.9590

Environment: Standalone

Description: 
Hi community! I have a doubt about EndpointCertificate tag (in ApplicationManifest). When using the following instruction:

`<EndpointCertificate X509StoreName="MY" X509FindType="FindBySubjectName" X509FindValue="*.somedomain.com" Name="HttpsCert" />`

One or more certificates can be returned. What's order will it be returned? Does it return invalid certificates too?

**UPDATE (just to confirm)**: EndpointCertificate supports only find by thumbprint? I found this information on [this link](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-model-schema-complex-types).

Thanks.

Observed behavior:

Expected Behavior:

Order: from oldest to newest, by installation date
Valid Only: true

OS(Windows/Linux): Windows

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Please review these two places and see if that helps. There are key differences before and after SF72CU4 (7.2.445) as noted in docs
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-cluster-using-cert-cn
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-change-cert-thumbprint-to-cn
