### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#1137]
As there is a MASSIVE bug with the latest version of Service Fabric which renders a cluster completely unusable in less than 48 hours (issue reproduced 3 times with support), I've been forced to rollback my Nuget packages and update our deploy scripts. According to this page, https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-versions the windows version prior to 7.2.445.9590 is 7.2.433.9590. All well and good, but it's difficult to know which NuGet packages to rollback to. If I look in Visual Studio, the version prior to 4.2.445 is 4.2.434. Are the 4.2.434 NuGet packages compatible with the 7.2.433.9590 runtime?

**Comment by craftyhouse** [comment]
What is the support case #? CU5 is rolling out so want to check if something there helps.

For your question around 7.2.433.9590. This information is posted in the release notes available here. https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-72CU2-releasenotes.md

**Comment by jackbond** [comment]
The tracking id is 2012220050008435. I've literally left a cluster in a completely unusable state for weeks to facilitate you guys resolving the issue. Describing the response as lackluster would be charitable.

**Comment by craftyhouse** [comment]
Thanks, poked at it, but not clear to me if it's still open. I would follow-up there with support as needed. 

Hope your version question is answered.

**Comment by JohnNilsson** [comment]
If there "is a MASSIVE bug with the latest version of Service Fabric which renders a cluster completely unusable in less than 48 hours" would anyone care to explain what it is, and how to avoid triggering it?

**Comment by jackbond** [comment]
If your application continuously creates and deletes lots of services, there is an issue where a delete call will return without error, but the service won't actually be deleted. Deleting the application won't actually resolve the issue, as the "deleted" services re-appear when the app is re-installed. Only way to resolve was to delete the cluster itself. During a support call yesterday, we discovered that calling Remove-ServiceFabricService (Powershell) with the ForceRemove flag would fully remove a partially deleted service.

**Comment by JohnNilsson** [comment]
Perhaps not an entirely new issue. I had this snippet stored away in some old notes to help with stuck application deletes at some point. Seems to address a similar situation.

```powershell
var $replicas = $replicas = Get-ServiceFabricDeployedReplica -ApplicationName $appName -NodeName $nodeName
foreach($replica in $replicas){
  Remove-ServiceFabricReplica -ForceRemove -NodeName $nodeName -PartitionId $replica.Partitionid -ReplicaOrInstanceId $replica.ReplicaOrInstanceId
}
```

**Comment by jackbond** [comment]
@JohnNilsson This issue goes way beyond stuck deletes, which is definitely an issue. With the 445 release (I believe) services can get in a half deleted state, where they'll show up in the cluster with a phantom ServiceManifestVersion 1.0:1.0. If you call Remove-ServiceFabricService without the -ForceRemove, it will error out saying the service doesn't even exist, although Get-ServiceFabricService will return it as a service, it displays in the SF explorer, and it's definitely running.

**Comment by jackbond** [comment]
@JohnNilsson Latest rollout halted. I had rebuilt our dev cluster to update a certificate. Took about a week, but the issue has resurfaced.

https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-2-fifth-refresh-release/ba-p/2096575

"potential issue that causes replica deletion state to not be correctly persisted on the node"
