### ISSUE TITLE
Connect-ServiceFabricCluster fails when server certificate is not specified

### ISSUE THREAD

**Issue by FredrikDahlberg** [microsoft/service-fabric#1142]
Service Fabric Runtime Version:
7.2.432.9590

Environment:
Azure

Description: 
Connect-ServiceFabricCluster without specifying the server certificate fails with

Connect-ServiceFabricCluster : FABRIC_E_SERVER_AUTHENTICATION_FAILED: 0x800b0109 or
Connect-ServiceFabricCluster : FABRIC_E_SERVER_AUTHENTICATION_FAILED: CertificateNotMatched

Observed behavior:
Service Fabric picks the wrong server certificate.

Expected Behavior:
I expect Service Fabric to use the active server certificate and nothing else. This usually works.

Workaround:
The only workaround I found is to add the parameters -ServerCommonName and -ServerCertThumbprint to specify the server certificate. Also making sure that it is the server certificate with the latest expiration date that is used.

EDIT (Solved): This happened because I installed the client certificate on the scaleset. Did not save me any time to use the same certificate for different things.

**Comment by craftyhouse** [comment]
Can you expand on this comment? "I expect Service Fabric to use the active server certificate and nothing else. This usually works".  The parameters you call out are expected to make sure you are selecting the right cert.

**Comment by FredrikDahlberg** [comment]
> 
>  The parameters you call out are expected to make sure you are selecting the right cert.

The server parameters are a list of expected values making sure you connect to the correct cluster. I don't believe that it should affect which certificate that is selected.

The cluster is configured to use specific certificates and then there are conventions for which one that is selected. The problem here seems to be that the server validates against some other certificate than the server certificate or skips some validation when the server parameters are added.

I have several clusters with various client certificates and usually you can connect without specifying the expected server certificate.
