### ISSUE TITLE
ASP.NET Core differences within and outside Service Fabric

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric#1148]
Service Fabric Runtime Version: 
4.2.445

Environment: Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
OneBox/Dev Cluster

Description 
I'm finding that aspects of ASP.NET Core 5.0 execute differently when running within Service Fabric than not and it's not clear why. I've got a months-long support ticket (120112024000687) open showing Blazor authentication working outside of SF and when importing the same project into a stateless ASP.NET Core project, it fails to authenticate.

In an attempt to see if I could get this to work with another identity provider (I'm using Auth0 in this case), I cloned a sample repository offered by Auth0 that runs as a standalone ASP.NET Core project. I've made a few tweaks to it as it didn't work out of the box, but it can be cloned from [https://github.com/WhitWaldo/nonsf-auth0](https://github.com/WhitWaldo/nonsf-auth0). Load the project in /QuizManager, set the apporopriate identity provider values in appsettings.json and start it up. It will show a simple Blazor server-side page that indicates you're not logged in. Open your network developer tools, preserve the log and click Log In at the top. You'll find yourself redirected to the identity provider's login page. Let's take a look at the network requests so we know what we're expecting to see (my ports will vary from yours because of the fake HTTPS endpoint used).

1. First, a request is made to https://localhost:44363/login?redirectUri=/. The response points back via a 302 to my identity provider's instance domain along with parameters identifying the client and whatnot. 
2. The next request is a GET made to the identity provider's page as noted in the location header in the last response. It points to another redirect to a different path, still on the IdP's domain.
3. Finally, we're there and we can log in. We don't actually need to authenticate for what I'm seeking to demonstrate through.

Let's now turn to what happens in the SF application. You can clone the repo I've got for this at [https://github.com/WhitWaldo/sf-auth0](https://github.com/WhitWaldo/sf-auth0) This project is identical to the other one except that I've dropped the "quiz" functionality. Clone this, set the IdP parameters in Web1/PackageRoot/Config/Settings.xml where indicated. Start debugging and you'll see we're at the same sort of Blazor server-side page if you navigate to https://localhost:9013 (your port should match in this case). You're not logged in, so open your network developer tools, preserve the log and click Log In at the top once again. This time you'll see the page flicker and appear to refresh and see exactly what you were looking at a moment ago (still not logged in).

If we look at the network requests, we'll see that they vary somewhat:

1. First, a request is made to https://localhost:9013/login?redirectUrl=/ as before. Instead of pointing to the login page at the IdP, this oddly instead points 
2. The redirect points instead to the logout path for some reason. This is followed and the user is logged out.

Why the difference? I've run kdiff against either directory and apart from spacing/tab usage, there appears to be no distinction between either project except that it works as it should outside of SF and fails to work inside SF. Any ideas?

OS(Windows/Linux): 
Windows

If this is a regression, which version did it regress from?
Never gotten Blazor to work with authentication inside SF

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by jesbach** [comment]
Hi @WhitWaldo 
Looks like there as typo in the file [Login.cshtml](https://github.com/WhitWaldo/sf-auth0/blob/master/Web1/Pages/Login.cshtml)
`@page
@model Web1.Pages.LogoutModel
@{
}`
This should be LoginModel - hope this fixes your issue.

**Comment by WhitWaldo** [comment]
@jesbach That does indeed resolve the issue, thank you. This will let me at least move forward with Auth0 as the IdP, but if there's anything you can do to help with support ticket 120112024000687 as well, I'd really appreciate it.

**Comment by WhitWaldo** [comment]
@jesbach I hate to say it, but I've got to re-open this. While your spotting the typo allowed the login page to show, I actually attempted to log in just now and it's not working. I simply added logging to either repo and have removed all the assembly load lines leaving just the details of what happened.

I'll describe the steps taken - first the non-SF version.
* I launched the application
* I was already logged in, so I logged out of the application
* I clicked the Log In link and it took me to the Auth0 login page
* This time, I logged into it and it took me to an authenticated page as expected upon getting redirected back to my page.

And the SF version:
* I launched the application
* I wasn't logged in yet, so I clicked the Log In link and it look me to the Auth0 login page.
* I logged into it and it threw me an exception page with the following message:

> OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'Unauthorized', error_uri: 'error_uri is null'.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
> 
> Exception: An error was encountered while handling the remote login.
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

> Exception: An error was encountered while handling the remote login.
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
> Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

So, like the support ticket, I'm experiencing that the same application works fine when not in Service Fabric and doesn't work when loaded in (and I've double-checked for typos this time). Again, works great up until the callback and then there's a difference in how it operates for no clear reason.

[NonSfLog.txt](https://github.com/microsoft/service-fabric/files/6014493/NonSfLog.txt)
[SfLog.txt](https://github.com/microsoft/service-fabric/files/6014494/SfLog.txt)

**Comment by WhitWaldo** [comment]
So I've been pouring over the trace logs today in an attempt to figure out what's happening and while I see what's happening, I haven't yet figured out how to step through the ASP.NET Core framework to see the actual values being passed to determine what's happening, but here's an update of where I'm at.

For the sake of brevity, I'm excluding all the traces prior to and starting from the callback. It's configured to callback to /callback after successful authentication. In either case (SF and non-SF), a request is made to the callback. Here's what I see from the point of the /callback request start in Blazor outside of Service Fabric (lines 631 through 662 of the attached nonsf-trace.txt):

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 POST https://localhost:44363/callback application/x-www-form-urlencoded 418
> Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware: Trace: All hosts are allowed.
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: POST requests are not supported
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/callback'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/callback'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint '/_Host'
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: Entering Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler's HandleRemoteAuthenticateAsync.
> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Trace: Performing unprotect operation to key {df922caa-2829-4bb1-9455-b49c4514b9f1} with purposes ('G:\code\blazor-quiz-manager\QuizManager', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'Auth0', 'v1').
> **Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: MessageReceived: '?code=9Fso7LAerQlQfB1N'.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Debug: Updating configuration
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: Authorization code received.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Debug: Redeeming code for tokens.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: Token response received.**
> 'iisexpress.exe' (CoreCLR: clrhost): Loaded 'G:\code\blazor-quiz-manager\QuizManager\bin\Debug\netcoreapp3.1\Microsoft.IdentityModel.JsonWebTokens.dll'. 
> The thread 0x5e08 has exited with code 0 (0x0).
> The thread 0x38f4 has exited with code 0 (0x0).
> The thread 0x9884 has exited with code 0 (0x0).
> 'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.12\System.Security.Cryptography.Cng.dll'. Symbols loaded.
> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Trace: Performing unprotect operation to key {df922caa-2829-4bb1-9455-b49c4514b9f1} with purposes ('G:\code\blazor-quiz-manager\QuizManager', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'System.String', 'Auth0', 'v1').
> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Trace: Performing protect operation to key {df922caa-2829-4bb1-9455-b49c4514b9f1} with purposes ('G:\code\blazor-quiz-manager\QuizManager', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Cookies', 'v2').
> Microsoft.AspNetCore.CookiePolicy.CookiePolicyMiddleware: Trace: Needs consent: True.
> Microsoft.AspNetCore.CookiePolicy.CookiePolicyMiddleware: Trace: Has consent: False.
> Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Information: AuthenticationScheme: Cookies signed in.
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 1215.3904ms 302 
> Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Debug: Connection ID "18230571370515792001" disconnecting.
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 GET https://localhost:44363/  
> Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware: Trace: All hosts are allowed.
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: The request path / does not match a supported file type
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 2 candidate(s) found for the request path '/'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Page: /_Host' with route pattern '' is valid for the request path '/'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/'
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint '/_Host'

This line `Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Debug: Redeeming code for tokens.` is the last one of either trace log that is shared between the two.  Here, we see that a message is received from the IdP representing some proprietary authorization code. Per the emphasized lines, it aims to redeem the code for a token, receives the token response, sets a pile of cookies and redirects back to _Host  From here, a token response is received, it sets a pile of cookies and we're in.

Looking at the equivalent lines in the SF trace log, we have the following (lines 598-642):

> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 POST https://localhost:8512/callback application/x-www-form-urlencoded 396
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Debug: POST requests are not supported
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Debug: Circuit id 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' disconnected from connection 'WQjfZCjqLtBOaaJ7KOH-Dw'.
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/callback'
> Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'Fallback {*path:nonfile}' with route pattern '{*path:nonfile}' is valid for the request path '/callback'
> Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync ending.
> Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint '/_Host'
> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Trace: Performing unprotect operation to key {33bb7499-58bd-464d-9c94-5b912213a6cb} with purposes ('C:\SfDevCluster\Data\_App\_Node_3\Auth0TestType_App128\Web2Pkg.Code.1.0.0', 'Microsoft.AspNetCore.Components.Server.CircuitIdFactory,V1').
> Microsoft.AspNetCore.Components.Server.CircuitDisconnectMiddleware: Debug: Circuit with id 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' terminating gracefully.
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry: Debug: Circuit with id CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE has been removed from the registry for permanent disconnection.
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Debug: Disposing circuit 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' started.
> Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext: Trace: Application complete.
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Debug: Circuit id 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' disconnected from connection 'WQjfZCjqLtBOaaJ7KOH-Dw'.
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Debug: Closing circuit with id 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE'.
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 0 of type Web2.App
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 1 of type Microsoft.AspNetCore.Components.Routing.Router
> Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: Removing connection SIIXxGeaWhIKiKK6WBv-FA from the list of connections.
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 2 of type Microsoft.AspNetCore.Components.Authorization.AuthorizeRouteView
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 3 of type Microsoft.AspNetCore.Components.Authorization.CascadingAuthenticationState
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 4 of type Microsoft.AspNetCore.Components.CascadingValue`1[System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Components.Authorization.AuthenticationState]]
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 5 of type Microsoft.AspNetCore.Components.Authorization.AuthorizeRouteView+AuthorizeRouteViewCore
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/_blazor'
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 6 of type Microsoft.AspNetCore.Components.LayoutView
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 7 of type Web2.Components.MainLayout
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/1.1 GET https://localhost:8512/_blazor?id=SIIXxGeaWhIKiKK6WBv-FA - - - 101 - - 8861.4788ms
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 8 of type Web2.Components.NavMenu
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 9 of type Web2.Components.AccessControl
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 10 of type Microsoft.AspNetCore.Components.Routing.NavLink
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: Entering Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler's HandleRemoteAuthenticateAsync.
> Microsoft.AspNetCore.Components.RenderTree.Renderer: Debug: Disposing component 11 of type Microsoft.AspNetCore.Components.Authorization.AuthorizeView
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Debug: Disposing circuit 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' succeeded.
> Microsoft.AspNetCore.Components.Server.CircuitDisconnectMiddleware: Debug: Circuit with id 'CbEWMg-yIpmpVoAI68ZZpuHBs8SqDbiUyrSDxZJBfQE' terminated gracefully.
> Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Blazor disconnect'
> Microsoft.AspNetCore.Server.Kestrel: Trace: Connection id "0HM6M157TQ0T8" sending HEADERS frame for stream ID 21 with length 37 and flags END_STREAM, END_HEADERS
> Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/2 POST https://localhost:8512/_blazor/disconnect multipart/form-data;+boundary=----WebKitFormBoundaryNYoPOWRQI8dlEQHT 359 - 200 0 - 5343.5457ms
> Microsoft.AspNetCore.Server.Kestrel: Debug: Connection id "0HM6M157TQ0T8", Request id "0HM6M157TQ0T8:00000017": started reading request body.
> Microsoft.AspNetCore.Server.Kestrel: Debug: Connection id "0HM6M157TQ0T8", Request id "0HM6M157TQ0T8:00000017": done reading request body.
> Microsoft.AspNetCore.Server.Kestrel: Debug: Connection id "0HM6M157TQ0T9" stopped.
> Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Trace: Performing unprotect operation to key {33bb7499-58bd-464d-9c94-5b912213a6cb} with purposes ('C:\SfDevCluster\Data\_App\_Node_3\Auth0TestType_App128\Web2Pkg.Code.1.0.0', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'Auth0', 'v1').
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: MessageReceived: '?code=mwBo826sRjovxa0N'.
> **Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Debug: Updating configuration
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Trace: Authorization code received.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Debug: Redeeming code for tokens.
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Error: Message contains error: 'access_denied', error_description: 'Unauthorized', error_uri: 'error_uri is null', status code '401'.
> Exception thrown: 'Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException' in Microsoft.AspNetCore.Authentication.OpenIdConnect.dll**

Note that here, we see a similar authorization code being received upon the return to the /callback path. It attempts to redeem the code for tokens and.. that's the end of the similarities. Here there's failure for no particularly obvious reason. The SF service got a code and for reasons unknown has rejected the same code that the non-SF version accepted without issue.

I attempted to debug my way through the Microsoft.AspNetCore.Authentication.OpenId library and see what exactly is happening, but for whatever reason I keep getting the "Source Not Available" page in Visual Studio and haven't found any means to access the OpenId library debug symbols in order to step through it.

[nonsf-trace.txt](https://github.com/microsoft/service-fabric/files/6017385/nonsf-trace.txt)
[sf-trace.txt](https://github.com/microsoft/service-fabric/files/6017386/sf-trace.txt)

**Comment by siby-george** [comment]
Look at error, call to Auth0 for get accesstoken from code is failing with 401. Check the context by add empty handler for event.OnAuthorizationCodeReceived in OpenIdConnectOptions and inspect context to check what is different between both.

**Comment by WhitWaldo** [comment]
@siby-george It'd be nice to fix this altogether, but my larger question is why this works outside of Service Fabric and fails when running within Service Fabric. There being no other differences between the two than the latter running in Service Fabric, why is there a difference at runtime between each?

I'll add the empty handler and get back to you later today on what that looks like.

**Comment by WhitWaldo** [comment]
Solved it. The difference is that SF is distributed and a single instance obvious isn't. With help from someone that watched the last community call, I've identified that proper installation and utilization of the data protection services across all instances unifies the keys used to protect the cookie and allows the client to successfully validate all the intermediate checks.
