### ISSUE TITLE
[BUG] MSBuild doesn't package referenced services' code anymore from service fabric project using Package as build target

### ISSUE THREAD

**Issue by wesleyegbertsen** [microsoft/service-fabric#1168]
**Describe the bug**
On March 15th our service fabric project stopped correctly packaging its referenced services' code (StatelessServices) in the output of the packaged service fabric project, on our DevOps environment using a windows-2019 hosted agent. It seems around that time there was an image update for the Microsoft hosted agents, I verified this by checking the image version in our build pipeline jobs. The job that started to not package the referenced services' code, was indeed running a newer image version. Here are the changes for the new image version: [Updating readme file for win19 version 20210309.0](https://github.com/actions/virtual-environments/commit/a2e7cb6a06f1f1ddc63cfaebf1c89281c535b6b4#diff-816219d3c9f30fcc1c40f88ca826c1662bf99eded781c1b419dd2dfb577ae227) (Visual Studio 2019 enterprise was updated from 16.8.5 to 16.9.0 with this image update). 

I already tried to update to the latest version of the Microsoft.VisualStudio.Azure.Fabric.MSBuild-NuGet, but that doesn't solve the issue. The weird thing is when I package the service fabric project locally via the context menu in the solution explorer of visual studio professional 2019 16.19.2 the code is correctly packaged. But when using the same MSBuild command locally, as we use on our DevOps environment, the referenced services' code also doesn't get packaged like on DevOps.

**Area/Component**:
Packaging service fabric project via MSBuild with as build target Package supplied by the Microsoft.VisualStudio.Azure.Fabric.MSBuild-NuGet. On our DevOps environment it started going wrong on the windows-2019 hosted microsoft agent when it started to use image version 20210309.0.

**To Reproduce**
Have a service fabric project with multiple referenced services (stateless fabric services), also have the Microsoft.VisualStudio.Azure.Fabric.MSBuild-NuGet in the service fabric project. Then build the service fabric project using the following command via PowerShell: 

`.\MSBuild.exe "C:\path\to\ServiceFabricProject.sfproj" -nologo -nr:false -t:Package -p:PackageLocation=C:\path\to\applicationpackage -p:RunCodeAnalysis=false -p:platform="AnyCPU" -p:configuration="Release"  `

**Expected/Observed behavior**
It's expected that the referenced services' from the service fabric project in the packaged application package folder e.g. 'Service1Pkg', would also have the built code folder in it, but they don't.  Instead they just have the Config folder (with Settings.xml) and the ServiceManifest.xml.

**Service Fabric Project Version:** 
2.4

**Microsoft.VisualStudio.Azure.Fabric.MSBuild Version:**
1.6.7

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by BigMorty** [comment]
@dbreshears , can we get someone to look at this?

**Comment by dbreshears** [comment]
@BigMorty .  Yeah, we are taking a look.

**Comment by BigMorty** [comment]
Thanks, you guys are awesome! ♥♥

**Comment by NCarlsonMSFT** [comment]
@wesleyegbertsen I tried to make a basic repro on my machine and using your command line it still built as expected. Would it be possible for you to create a minified repro repo for us to test against?

**Comment by wesleyegbertsen** [comment]
@NCarlsonMSFT I need to discuss with my team that we would need to setup a minified repo to get further assistance here, and plan it in our upcoming sprint. Since it's currently easter break, the earliest I can discuss this with my team is on tuesday. Our new sprint also start tuesday, so that's nice. I will give an update here on tuesday, but I think I or someone else in our team would be able to pick this up fairly soon at the beginning of our next sprint.

Thank you so far for looking into this!

**Comment by wesleyegbertsen** [comment]
@NCarlsonMSFT Our team has managed to create a minified repro repo, a teammember has created a repo for it here: https://github.com/WASoftlines/MinifiedFabric

The solution file is in the SF folder and the service fabric project is also in the SF folder. I hope you can also reproduce the issue we are experiencing with this repo. 

Thanks in advance!

**Comment by NCarlsonMSFT** [comment]
@wesleyegbertsen The issue I see when looking at the minified repro is that you specify x64 as the default platform for NoState.csproj instead of the AnyCPU platform you intended to use. Is there a reason your default platform is x64?

The reason this works in VS and not in MSBuild is that when building in the context of a solution we can use the configuration map in the .sln file to know which platform/configuration to use for each file. When building the SF proj by itself we respect whatever the default platform is defined in the project (this is to support the surprisingly common scenario where different services use different platforms).

**Comment by wesleyegbertsen** [comment]
@NCarlsonMSFT I changed the default platform of the NoState project to AnyCPU and it indeed would then package the code corectly. It's still weird though that this just started to happen recently with an update to visual studio on the hosted agent, and thus indirectly an update to MSBuild. The scope of this issue is resolved, so I think we can close this issue.
