### ISSUE TITLE
[BUG] - test bug to see if project filter works

### ISSUE THREAD

**Issue by craftyhouse** [microsoft/service-fabric#1169]
**Describe the bug**
This is a test, this is only a test

**Area/Component**:
Please mention area or component in Service Fabric where issue was found. Ex: security, monitoring, placement or resource governance, Reliable services, Actors, programming models,SDK,.etc.

**To Reproduce**
1. Go to '...' 1
2. Click on '....' 2 
3. Scroll down to '....'3 

**Expected behavior**
For this to show up in bug bucket

**Observed  behavior**:

**Screenshots**

**Service Fabric Runtime Version:** 
ex: 7.1.*, 7.2.*

**Environment:**
 - Must be one of these values [Standalone OR Azure OR OneBox/Dev cluster]
 - OS: [e.g. Windows 2019, Ubuntu 18.04] 
 - Version [e.g. 7.1, 7.2 ]

If this is a regression, which version did it regress from?

**Additional context**

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by athinanthny** [comment]
@craftyhouse  Closing test issue
