### ISSUE TITLE
servicefabric depends on docker-ce - can we downgrade this to an optional requirement?

### ISSUE THREAD

**Issue by drnic** [microsoft/service-fabric#118]
```
$ dpkg -i servicefabric_6.2.141.1.deb
...
dpkg: dependency problems prevent configuration of servicefabric:
 servicefabric depends on docker-ce (>= 17.03.0~ce-0~ubuntu-xenial); however:
  Package docker-ce is not installed.
```

Where `docker` is installed a different way (my situation) or perhaps where using `docker-ee` instead, can we make `docker-ce` an optional package to install?

**Comment by suhuruli** [comment]
@mani-ramaswamy

**Comment by maburlik** [comment]
Back in 6.x we had removed docker-ce as a direct dependency with the switch to moby-engine, which is installed during the node configuration phase of setup.
