### ISSUE TITLE
[Question] -How to handle IService upgrade

### ISSUE THREAD

**Issue by zsybupt** [microsoft/service-fabric#1184]
Hi Team:
The problem can be simplified as below :
we have two services of our service fabric cluster:
```csharp
public class ServiceA: IService
{
     public async Task CallA()
    {
        var proxy = CreateProxy(urlofBService);
        await proxy.CallB();
    }
}

public class ServiceB: IService
{
     public async Task CallB()
     {
     }
}
```
ServiceA will call ServiceB with remoting call. 
If next time we update code to:
```csharp
public class ServiceA: IService
{
     public async Task CallA()
    {
        var proxy = CreateProxy(urlofBService);
        await proxy.CallBNew();
    }
}

public class ServiceB: IService
{
     public async Task CallBNew()
     {
     }
}
```
we have 3 nodes in our cluster, when we do upgrade deployment, each node is placed in different upgrade domains, for example, node0 has upgraded, and node1 is upgrading, node2 is not triggered yet. At this moment, when a request hits ServiceA at node0, it will call CallBNew method, if this remoting call is routed to node2, there will be an exception, because node2 is still old code deployed. Any solution or suggestion about this problem ?
Thanks

**Comment by tuhland** [comment]
You need to do a "staggered release".

Step 1: Deploy a version of Service B which has both CallB() and CallBNew() but Service A still calls CallB().
Step 2: Deploy a version of Service A that now calls CallBNew().
Step 3: Deploy a version of Service B which no longer has CallB().

This get's a bit easier / faster if both services live in different applications, but the same steps still apply.

**Comment by zsybupt** [comment]
@tuhland Thanks, but for now, services are located in all nodes, so if we want to do "staggered release", first we need to keep both the old method and new method in ServiceB and deploy,  and checkin new ServiceA code to deploy, then remove the old code of ServceB do final deploy

**Comment by tuhland** [comment]
Yep, that's what I mean with it "getting easier". Less code base hassles.

**Comment by athinanthny** [comment]
@zsybupt Can you clarify if you received answers to handle issues reported here from the community? If yes, please close the issue.  We will mark it closed if we don't hear back in 2 business days. 
For common questions related to Service Fabric , please file them here https://docs.microsoft.com/en-us/answers/topics/azure-service-fabric.html 

For bugs in our run releases or request for new product feature , please continue to use one of  the respective templates in this repo
https://github.com/microsoft/service-fabric/issues/new/choose

**Comment by JustinKaffenberger** [comment]
This is a common problem in any system where you want high uptime and rolling upgrades. In my company's software we try our best to always make changes in a forward/backward compatible way to avoid this scenario.

**Comment by zsybupt** [comment]
Thanks for all your comments, seems we have to conside compatible for every uprade
