### ISSUE TITLE
Unable to upgrade to Microsoft.ServiceFabric.AspNetCore.Kestrel 5.0.514

### ISSUE THREAD

**Issue by clausndk** [microsoft/service-fabric#1186]
**Describe the bug**
I have a project, where we have upgraded to .NET 5, but we are unable to upgrade the package Microsoft.ServiceFabric.AspNetCore.Kestrel to 5.0.514.

**Area/Component**:
Hosting

**To Reproduce**
1. Create empty web api asp.net core project v 5.

**Expected behavior**
No errors, and able to respond to web requests.

**Observed  behavior**:
No web server is ever started, and the context factory is called multiple times, without any exceptions.

**Service Fabric Runtime Version:** 
7.2.452.9590

**Environment:**
 - Dev cluster and Azure cluster

Windows Server 2019 Version 1809, Build: 17763.1852

**Additional context**
I have created a simple project here for testing:
https://github.com/clausndk/MsSfKestrelPackage

If I upgrade the package in https://github.com/clausndk/MsSfKestrelPackage/blob/main/WebApi/WebApi.csproj, to version 5.0.514, I cannot start the web server.
If I run with version 4.2.477, I can start the webserver and I can get responses to /api/ping.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by athinanthny** [comment]
@clausndk  Support for .NET 5 is GA in 8.0 release. 8.0 roll out started on 04/8 and it should complete in 7-10 days. https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-8-0-release/ba-p/2260016

Can you try to upgrade to 8.0 runtime version and validate this scenario. If you don't experience it  post upgrade, close the issue. If it persist, please file new bug for 8.0 release version.

**Comment by athinanthny** [comment]
@clausndk please create new issue if this behavior persists post upgrading to 8.0 as well
