### ISSUE TITLE
SF8 adoption blocker. Please provide a SF mock by SF team.

### ISSUE THREAD

**Issue by kgflying** [microsoft/service-fabric#1188]
**Is your feature request related to a problem? Please describe your workload details.**
My team wants to adopt SF8 because we want to move .net 5. We use SF mock, which is provided by 3rd party, https://github.com/loekd/ServiceFabric.Mocks/issues -> https://github.com/loekd/ServiceFabric.Mocks/issues/115 Because that one is driven by open source community, it's totally out of control when the SF8 support will be added.

**Describe the solution you'd like**
SF team should provide a SF mock. So whenever, SF team release a new version, SF should upgrade its mock accordingly.

**Describe alternatives you've considered**
NO alternatives!!!
Because the mock does not support SF8, we cannot move SF8, meaning that we cannot move to .net 5, which is very bad for us.

**Area/Component**:
Unit test.

**Expected behavior**
SF team release a SF mock, which is mainly for UT.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by JustinKaffenberger** [comment]
I can second this. It would be nice if the SF team could contribute to ServiceFabric.Mocks for each update. I know on a few occasions I've had to make a PR in ServiceFabric.Mocks to support a certain version of the SF SDK. 

We've also toyed with the idea of just forking the repo in-house and maintaining our own copy, since the only thing that changes frequently are the SF SDK versions.

**Comment by athinanthny** [comment]
@kgflying  Thanks for sharing this open source project https://github.com/loekd/ServiceFabric.Mocks .

This is not maintained by ServiceFabric team and you much reach out to repository owner for further updates/support for new SF versions.

**Comment by kgflying** [comment]
Hi @athinanthny ,  I don't think you understand this request. The request is:

We need do UT. Because SF team not provide a SF mock, we end up using 3rd party mock. Because 3rd party mock does not support SF8, we cannot move to SF8.

The request is:
**SF team provide a mock for UT. So we don't need use 3rd party mock.**

Is it clear to you?

**Comment by adwearing** [comment]
I agree with @kgflying here, seems a strange setup to rely on a 3rd party solution for mocks to your own product/service. Especially when that 3rd party solution doesn't keep upto date as frequent as the service.
