### ISSUE TITLE
Possible Memory Leak In CreateServiceProxy

### ISSUE THREAD

**Issue by nkorai** [Microsoft/service-fabric#119]
Using the RemotingV2 stack and currently using runtime 6.2.262.9494. 
When using Service Fabric Remoting for service-to-service calls, I'm using the following code in a loop:
```
var proxyFactory = new ServiceProxyFactory((c) =>
{
	return new FabricTransportServiceRemotingClientFactory();
});

var uri = new Uri($"fabric:/AppName/ServiceName");
var partition = new Microsoft.ServiceFabric.Services.Client.ServicePartitionKey(1);
var listenerName = "RemotingListener";

var myServiceProxy = proxyFactory.CreateServiceProxy<ICustomService>(uri, partition, listenerName: listenerName);
var result = await myServiceProxy.CustomCall();
```
Overtime this loop consumes an increasing amount of memory. I've seen similar issues with `ActorProxy` having memory leak/GC issues as well and the solution there was to cache the `ActorProxy`. I went ahead and did that, caching `myServiceProxy`, and my memory usage issues went away. 

Similar issue to [this issue](https://github.com/Azure/service-fabric-issues/issues/62) in the old repository?

**Comment by nkorai** [comment]
Yes I previously was and I believe that's what was causing the memory consumption to grow. That's the bit that I cached and what caused the memory consumption to stop growing.

**Comment by suchiagicha** [comment]
We dont recommend creating factory for every request.  You SHOULD cache factory .
Proxy can be created for every request.
Article explains more about the same.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#service-proxy-lifetime

**Comment by suchiagicha** [comment]
@nkorai 
There are 2 cases :
1 Increasing of the memory if you are creating ServiceProxyFactory for every request is expected. 
This is wrong design on your side.  You should be using singelton factory.

2 Increasing of the memory if you are creating proxy for every request but  creating singleton proxyfactory is not expected. This would be the bug if thats the case.

Have you tried scenario 2 and see if you are still seeing the memory issue. ?

**Comment by nkorai** [comment]
I'll try out scenario 2 and post back tomorrow.
