### ISSUE TITLE
SF classic vs Managed vs Mesh

### ISSUE THREAD

**Issue by 1TheMuffinMan** [microsoft/service-fabric#1190]
Things are getting confusing here. It feels like the same path .NET went down with Core, Framework and now ".NET".

Are these 3 separate forks of SF that are going to be maintained or is Mesh actually the old name for the Azure Managed instance?

**Comment by juho-hanhimaki** [comment]
Service Fabric mesh is has been retired. So it didn't become a finished product.
https://azure.microsoft.com/en-us/updates/azure-service-fabric-mesh-preview-retirement/

Now there exists just traditional SF clusters and the new managed clusters which is still in preview.

Info about managed clusters:
https://docs.microsoft.com/en-us/azure/service-fabric/overview-managed-cluster

**Comment by 1TheMuffinMan** [comment]
@juho-hanhimaki thank you!
