### ISSUE TITLE
[Feature]: Managed Clusters: Allow node types to be configured for either internal or public load balancers

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric#1208]
**Is your feature request related to a problem? Please describe your workload details.**
Today's managed clusters create a public load balancer for all node types. I have many services that don't need, and shouldn't be exposed to the public internet. If absolutely necessary, I'd prefer to expose them via a firewall-enabled service like Azure App Gateway or the like.

Please consider allowing node types to be considered so they're available online via an internal load balancer.

**Describe the solution you'd like**
When provisioning a node type, display a radio button letting the user indicate whether it should have an internal or public load balancer.

**Describe alternatives you've considered**
Unmanaged clusters are easily enough to provision with mixed internal and public load balancers for multiple node types.

**Area/Component**:
Cluster provisioning

**Expected behavior**
Improved cluster and application security

**Additional context**
N/A

**Service Fabric Runtime Version:** 
All

**Environment:**
Azure

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
This ask should be covered by the 2021-11-01-preview API. If not, please let us know what gaps still exist from your perspective.

thanks!

**Comment by WhitWaldo** [comment]
@craftyhouse It's not quite clear to me what the useDefaultPublicLoadBalancer property does. Ideally, given the goal is that everything is just managed for me, I think there's room to both simplify and broaden the applicability of the BYOVN and BYOLB scenarios in light of this parameter addition.

From the perspective of how I traditionally set up a non-managed cluster), I would create separate subnets for each node type, assign a different load balancer to each subnet/node type and go from there, so I'm finding myself confused about how the managed approach is intended to instead work in light of this. I spoke to this on our call the other day, but I wanted to write it out for clarity and future reference.

Put simply then, if SF is managing the network, there are at most two subnets - one for public and one for private connections and each has a complimentary load balancer assigned. Node types are disbursed according to their specifications of how they set usePublicLoadBalancer or not, but the whole of it is otherwise entirely managed.

If I'm picking and choosing the subnets each node type is assigned to, use the usePublicLoadBalancer flag to create a managed load balancer that's either public or private based on the value.

And if I'm setting my own load balancers, I'm effectively setting my own subnets and bringing my own load balancers, so there's nothing for SF to do apart from ensure connectivity + NSG rules.

I would then expect to see something like a 'usePublicLoadBalancer' on each node type and it would be handled according to the following scenarios:

# Scenario: Didn't bring my own vnet/load balancers
As part of initialization, managed SF spins up the managed virtual network. A single subnet (let's call it the "publicSubnet") is created with a managed public load balancer for all primary node types + any node type for which usePublicLoadBalancer is not set or is explicitly set to true.

If any node type exists for which usePublicLoadBalancer is explictly false, a single second subnet (the "privateSubnet") is created and assigned an internal load balancer and each of these node types are assigned to this "internal" subnet.

# Scenario: Brought my own vnet
Before I start on this one, I really think it'd be made simpler if you moved subnetId from the managedCluster and instead put a subnetId on each node type. You already have a flag to discern which is the primary node type. From there:
- If primary node type + subnetId is set, use that subnet for as the primary managed subnet + create managed public load balancer
- If the primary node type + subnet is set + usePublicLoadBalancer is false, fail validation and indicate that the primary node type must be on a public load balancer
- If not primary + subnetId is set, use this subnet for the node type. If usePublicLoadBalancer is true, create a managed public load balancer on the subnet. If usePublicLoadBalancer is false, create a managed internal load balancer on the subnet.
- If not primary + subnetId is not set, look at usePublicLoadBalancer. If true, assign the node type to use the same subnet as the primary node type (since it's public and already has a public load balancer). If false, assign the node type to the "privateSubnet" as illustrated above and use the internal load balancer assigned there.


# Scenario: Brought my own load balancer
In a similar vein as my proposal on bring your own vnet (which is really, bring your own subnet on a per node-type basis), you'd essentially just complement the above with whether they're specifying their own load balancer. If so, they've already picked a subnet that the LB is using - manage the nodes in there and you can discern from there if it's a public or internal load balancer accordingly. If they bring their own load balancer and also set the usePublicLoadBalancer flag (true or false), fail validation and indicate the two can't both be true.
