### ISSUE TITLE
[Certificate Issue] - Service Fabric stuck on “Waiting for Nodes”

### ISSUE THREAD

**Issue by svaneeden** [microsoft/service-fabric#1211]
This is not a bug report, but more a cry for help...

I am deploying a Service Fabric Cluster using an ARM template.

When using a self-signed certificate everything is good and well. The cluster is created and all nodes are healthy.

But when I do the same with our chained certificate, the cluster gets stuck in "Waiting for nodes".

Concerning the virtual machine scale set... all instances are up and running and healthy.

When I check the validity of the certificate on any of the nodes, I can confirm that the complete chain is trusted.

![image](https://user-images.githubusercontent.com/10448901/120455014-ae31af80-c394-11eb-88ee-fc0b35169132.png)

The root certificate is installed in the "Trusted Root Certification Authorities" store and the issuing certificate is stored in the "Intermediate Certification Authorities" store.

When looking in the windows event log I see the following entries.

**Warning** - "Request failed: PUT https://westeurope.servicefabric.azure.com/runtime/clusters//nodes/ (CorrelationId=, UtcTime=06/02/2021 07:18:01, Certificate=) {"nodeTypeRef":"xxxx","ipAddress":"","faultDomain":"4","upgradeDomain":"4","zone":"","location":"","infrastructurePlacementID":"","faultDomainOverride":"","upgradeDomainOverride":"","coordinationGroupID":""}"

**Warning** - "System.Exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized. at System.Net.HttpWebRequest.GetResponse() at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, X509Certificate2 clientCertificate) at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, List`1 clientCertificates)

at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, List`1 clientCertificates) at Microsoft.Azure.ServiceFabric.Extension.Core.WrpTopologyService.UpdateNodeInfo(String machineName, NodeDescription nodeDescription) at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.UpdateNodeTopology(String nodeName)"

**Warning** - "ERROR: Microsoft.Azure.ServiceFabric.Extension.Core.AgentException: System.Net.WebException: The remote server returned an error: (401) Unauthorized. at System.Net.HttpWebRequest.GetResponse() at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, X509Certificate2 clientCertificate) at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, List`1 clientCertificates)

at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.UpdateNodeTopology(String nodeName) at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.d__100.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.ServiceFabric.Extension.Core.NodeBootstrapAgent.d__95.MoveNext()"

**Warning** - "Request failed: POST https://westeurope.servicefabric.azure.com/runtime/clusters/GUID/nodes/NodeInstance/vmextensionRepair (CorrelationId=, UtcTime=06/02/2021 07:18:01, Certificate=) {"sequenceNumber":"0","output":""}"

**Error** - "Failed to process adhoc repair response: System.Exception: System.Net.WebException: The remote server returned an error: (401) Unauthorized. at System.Net.HttpWebRequest.GetResponse() at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, X509Certificate2 clientCertificate) at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, List`1 clientCertificates)

at Microsoft.Azure.ServiceFabric.Extension.Core.RestClient.Invoke(Uri requestUri, String method, String requestBody, List`1 clientCertificates) at Microsoft.Azure.ServiceFabric.Extension.Core.WrpTopologyService.GetAdHocRepairPollResponse(String machineName, VmExtensionAdHocRepairPollRequest request) at Microsoft.Azure.ServiceFabric.Extension.Core.RepairStrategy.AdHocRepairHandler.PollSFRPForRepair()"

**Comment by wouterroos** [comment]
In addition (I'm working on the issue with @svaneeden). When creating a cluster from the Azure portal using the same certificate the nodes **do** show up successfully (@svaneeden please comment with any information you have on that). Is there any way to get more information on what is causing the 401 error?

Thanks!

**Comment by svaneeden** [comment]
After my original post, I tried to create a cluster via the Azure Portal, using the intended production certificate. I manually created a key vault first and uploaded the certificate as a .pfx. I followed the wizard and low and behold, it worked. Only difference is that it now references the certificate via thumbprint instead of common name (as there was no option in the Azure Portal to tell it otherwise). 

![image](https://user-images.githubusercontent.com/10448901/120769969-f16b5a00-c51d-11eb-9976-410ed99c2c06.png)

Thus, when we deploy via the ARM template using the intended production certificate, it **does not** work, but same ARM template with self-signed certificate **does work**. Doing it manually via the Azure Portal using the intended production certificate, **works** as well. This is really confusing!

**Comment by JohnNilsson** [comment]
Since I was recently having troubles like this, perhaps you are running into an issue with the `certificateIssuerThumbprint` ?
See: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-change-cert-thumbprint-to-cn

I guess not applicable when setting up a new cluster, but also checkout https://github.com/Azure/Service-Fabric-Troubleshooting-Guides , after certain rescue operations there might be situations where the cluster and the resource provider aren't in sync with the configured thumbprints.

**Comment by svaneeden** [comment]
@JohnNilsson, thank you so much! That was indeed the mistake I made. Instead of using the issuing certificate's thumbprint, I was using the end certificate's thumbprint.

Just a recap for anyone else running into this problem.
The common name should be the CN of the cluster certificate, but the thumbprint should be the thumbprint of the issuing certificate. Please see screenshots below.

![image](https://user-images.githubusercontent.com/10448901/120827274-922c3a80-c55b-11eb-8375-c8305f7f7358.png)

![image](https://user-images.githubusercontent.com/10448901/120827783-15e62700-c55c-11eb-8ca3-f2e77051b0ac.png)
