### ISSUE TITLE
Just a kind reminder: please make a plan for .Net 6.0 support at a earlier time.

### ISSUE THREAD

**Issue by kgfly** [microsoft/service-fabric#1224]
What makes many developers really unhappy is: .Net 5.0 was released Nov 2020. But SF did not add the support till April 2021, which is about **half year** delay.

Since .Net 6 is a LTS while .Net 5 is not, I think many people will move from .net 4 to .net 6 directly.

Per schedule, .Net 6.0 will be released on Nov 2021, https://dotnet.microsoft.com/platform/support/policy/dotnet-core. Please make a plan .Net 6.0 support at a earlier time. BTW, .Net 6.0 is in preview 4 now. https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/

It would be great if SF .Net 6.0 support could be released **together** with .Net 6.0 this time.

Thanks.

**Comment by tommarkosi** [comment]
If it takes until March to get the next LTS version of .NET it'll be sad times at Ridgemont High.

I also see there is interest in Hot Reload (The BIG .NET 6 feature) in #1189

**Comment by kgflying** [comment]
Any idea when (which version) will support .net 6?

**Comment by craftyhouse** [comment]
.NET 6.0 support is available
