### ISSUE TITLE
503 Service Not Available error : When deployed stateless service using palcement properties

### ISSUE THREAD

**Issue by dharmeshtailor** [microsoft/service-fabric#1240]
We have Service Fabric cluster with 4 nodes. We decided to split the microservices among nodes ( backend / frontend ).

2 nodes for web exposed stateless services. 2 nodes for backend services that does batch processing and other long runnings operations. We use placement constraints to place the services in respective nodes.

When services are deployed using palcement properties, we intermittently get 503 service not available response when trying to access the service via external url. All works fine when we remove the placement constraints and set instance count to -1.

Not sure what's happening here, i thought load balancer should be able orchestrate requests appropriately , but looks it is not.

**Comment by craftyhouse** [comment]
If you are still facing this issue please try these other forums https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#post-a-question-to-microsoft-qa
