### ISSUE TITLE
Scaleset naming convention

### ISSUE THREAD

**Issue by AdmiralBond** [microsoft/service-fabric#1247]
It blows my mind that this wasn't resolved in the very first preview, but the naming convention for nodes in a scaleset should be

nodename_000 (or more)

and not

nodename_0

I realize this isn't a Service Fabric issue, but I don't know how to communicate with the scaleset developers.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
I would suggest submitting this request on their site, documented here https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/vmss-support-help#submit-feature-requests-on-azure-feedback
