### ISSUE TITLE
6.2.274.9494 is available via the portal...

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#125]
And you guys have communicated NOTHING. Is this the broken 6.2, mentioned here...

https://blogs.msdn.microsoft.com/azureservicefabric/2018/04/26/second-update-on-the-service-fabric-6-2-release/

Or is this a new 6.2? And if it's a new 6.2, you've entirely lost the point of version numbers.

> As you all know, publishing a release that contains bugs is always disappointing and causes frustration. There is no excuse for not doing the due diligence of validating the binaries we ship. We do however have processes in place which helped us find these issues quickly before the majority of customer clusters received the bits.

There's also no excuse for your appalling lack of communication.

**Comment by rishirsinha** [comment]
We apologize for the lack of communication. This is a new updated version which has all the requisite fixes.

**Comment by MikkelHegn** [comment]
Release notes and information about the release is available here: https://blogs.msdn.microsoft.com/azureservicefabric/2018/05/14/6-2-release-update/

**Comment by JEJ0** [comment]
I think that one point in JackBond's comment has been missed.  If you are going to refer to versions by their short names (e.g. "6.2") then you need to retire that name if you pull the release.   If you intend to use the build number, then please do so exclusively.

The current mixture means that it is very hard to tell in cases like this if you have the intended version.

**Comment by MikkelHegn** [comment]
Thanks for the feedback and point taken. We are working on improving the communication and accessibility of release notes and version info.

Today the release notes have the most detailed information. They are attached to the announcements blog we put here.: https://blogs.msdn.microsoft.com/azureservicefabric/.

**Comment by jackbond** [comment]
@JEJ0 Thanks. Glad to know that I'm not the only one to think the current approach is confusing.

@MikkelHegn I don't know if it's possible, but perhaps you can pin a link on the blog to this repository?

**Comment by craftyhouse** [comment]
Just to close this, we post in one place
https://techcommunity.microsoft.com/t5/azure-service-fabric/bg-p/Service-Fabric

and have relnotes on github for each release that is generally made available
6.5+ history here https://github.com/microsoft/service-fabric/tree/master/release_notes

Hope that helps
