### ISSUE TITLE
Application terminates unexpectedly with error code 3221225786

### ISSUE THREAD

**Issue by emilroman** [microsoft/service-fabric#1254]
> If you know the area of code this belongs to, please select an appropriate tag.
> Otherwise, select `triage-needed`

**Bug or Enhancement:**
Bug
 
> Questionnaire for bug reports.  Feel free to delete if filing an enhancement

**Describe the issue:**

I am running an on-premise SF cluster (SF version 7.2.413.9590) with 3 nodes (virtual machines hosted in Amazon AWS).
I have a couple of stateless apps configured to each run with 2 active instances.
One app, always fails on 1 node, soon after it's instantiated, with the following error message:
"ServiceHostProcess: my_app.exe started at ‎2021‎-‎08‎-‎12T12:20:20.171786400Z 
with Process Id 9776 for ApplicationId 07e9f371-1dbd-452f-9def-e8461df1a65c 
terminated unexpectedly with exit code 3221225786 on node id 85772935593a0315f92e3293832c5fe9"

I can't figure out what the root cause might be, would really appreciate your help.

**Describe as best as possible how to reproduce the issue:**

> If found from a deployment, please include the following

**Service Fabric Version:*7.2.413.9590*

**Guest OS version:*Windows Server 2019*

**Hosted on Azure or On-Prem:*On-Prem*

**Comment by ywlei** [comment]
@emilroman did you figure out the issue?
