### ISSUE TITLE
[BUG] - Azure/Service Fabric/Issues related to the Service Fabric Cluster/My cluster is stuck in updating state when configured with custom ports

### ISSUE THREAD

**Issue by theamitverma** [microsoft/service-fabric#1260]
**Describe the bug**
Azure/Service Fabric/Issues related to the Service Fabric Cluster/My cluster is stuck in updating state when configured with custom ports

**Area/Component**:
Azure/Service Fabric/Issues related to the Service Fabric Cluster/My cluster is stuck in updating state on Portal

**To Reproduce**
1. Go to 'Azure Portal'
2. Click on Create 'Service Fabric Cluster'
3. Create Cluster with Custom Port within the approved range - we have configured a Service Fabric Cluster with a slight change in deployment configs through the Azure Portal - changed Service Fabric Explorer port from default 19080 to 19081, and changed Client Connection Endpoint port from default 19000 to 19001.
4. See error - Now we observe that Cluster is stuck in Updating state (on Portal), althgouh all the nodes are created and visibile from the related VMSS (VM Scale Set) and Cluster is also accessible through Explorer endpoint (i.e. https://pg-sfcluster-02.northeurope.cloudapp.azure.com:19081/Explorer), although the Explorer is also unable to show details related to Cluster Nodes.

**Expected behavior**
Azure Portal should show the newly provisioned Service Fabric Cluster with custom ports and all other details of cluster should be visible.

**Observed  behavior**:
Cluster Creation is stuck in "Updating" state.

**Screenshots**

![image](https://user-images.githubusercontent.com/35689028/131130500-e775ea59-4f77-4afe-b8f4-b8ac74f79110.png)
![image](https://user-images.githubusercontent.com/35689028/131130530-12d7df37-fcd3-472c-9b4e-f16066666e22.png)
![image](https://user-images.githubusercontent.com/35689028/131130555-1a94e030-2297-45e4-acbd-071841a2cf54.png)

**Service Fabric Runtime Version:** 
8.1.321.9590

**Environment:**
 - Must be one of these values [Service Fabric Cluster]
 - OS: [Ubuntu 18.04] 
 - Version [8.1.321.9590]

If this is a regression, which version did it regress from?

**Additional context**
Not applicable.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
How did you do step 3 above? During initial creation or post deployment?

Do you have an NSG configured and are the ports allowed?

**Comment by craftyhouse** [comment]
Please re-open if you are still facing issues here. I only ran in to problems like the above when NSG was not allowing traffic to the non-standard ports.
