### ISSUE TITLE
Error when deploying ARM template for ServiceFabric application

### ISSUE THREAD

**Issue by levimatheri** [microsoft/service-fabric#1262]
**Describe the bug**
I'm deploying an application to ServiceFabric using ARM template. On the template under resource type `Microsoft.ServiceFabric/clusters/applicationTypes/versions`, I'm providing an `appPackageUrl` to the sfpkg file that contains the code for the application, which is in blob storage and appending SAS token . However, every time I deploy, I get the error:
```
Status: Failed
Error:
Code: ClusterChildResourceOperationFailed
Message: Resource operation failed. Operation: CreateOrUpdate. Error details: {
"Details": "FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR: DOWNLOAD PATH SANITIZED"
}
```
**Area/Component**:
ServiceFabric ARM template

**Expected behavior**
Should deploy ARM template

**Observed  behavior**:
Deployment fails.

**Environment:**
 - Azure
 - Windows2019
 - Version 8.1.321.9590

**Comment by levimatheri** [comment]
I used Powershell to try deploying to my local cluster (see [example](https://docs.microsoft.com/en-us/powershell/module/servicefabric/register-servicefabricapplicationtype?view=azureservicefabricps#example-5--register-an-application-type-from-an-external-store-async) and the error shows more detail now -> FABRIC_E_IMAGEBUILDER_VALIDATION_ERROR: The package downloaded from '<blobUrl>' has application type name '<type in manifest>', which doesn't match expected value '<type declared during creation>'.

**Comment by craftyhouse** [comment]
Please try this forum for more assistance if you are still facing this issue. 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#post-a-question-to-microsoft-qa

You may be missing a required parameter?
-ApplicationTypeName
Specifies the application type name, as it is defined in the application manifest. The application type name and the application type version uniquely identify the application type. This is needed when provisioning an sfpkg from an external store.
