### ISSUE TITLE
Troubleshooting High CPU usage for Actors

### ISSUE THREAD

**Issue by davidelettieri** [microsoft/service-fabric#1263]
We are experiencing frequent 100% cpu usage for our actors. We have a 5 machine service fabric cluster on Azure and we are observing a recurring pattern were on one or more machines gradually the cpu usage increase in a few hours timespan up to 100%. 

So far we have been restarting the actors from the service fabric explorer but it's becoming more and more frequent. Is there any guidance on how to troubleshoot such issues?

**Environment:**
 - Azure
 - Windows Server 2016 Datacenter
 - Service Fabric Version 8.1.321.9590

**Comment by davidelettieri** [comment]
It looks like the process is spawning a lot of threads with very similar stack traces such as

```0, ntoskrnl.exe!ObDereferenceObjectDeferDelete+0x194
1, ntoskrnl.exe!KeWaitForMultipleObjects+0x1284
2, ntoskrnl.exe!KeWaitForMultipleObjects+0xb3f
3, ntoskrnl.exe!KeWaitForMultipleObjects+0x4fe
4, ntoskrnl.exe!ObWaitForMultipleObjects+0x2c7
5, ntoskrnl.exe!IoFreeMiniCompletionPacket+0xe25
6, ntoskrnl.exe!setjmpex+0x6933
7, ntdll.dll!NtWaitForMultipleObjects+0x14
8, KernelBase.dll!WaitForMultipleObjectsEx+0xef
9, coreclr.dll!coreclr_initialize+0x7f6f6
10, coreclr.dll!coreclr_initialize+0x7f475
11, coreclr.dll!coreclr_initialize+0x7ef2b
12, coreclr.dll!coreclr_initialize+0x7ecdb
13, 0x7ffee2347e2a
```

**Comment by craftyhouse** [comment]
Please post questions/discussions to Q&A or Stackoverflow as suggested here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#post-a-question-to-microsoft-qa
