### ISSUE TITLE
[BUG] - Upgrades In Progress UI does not update when the upgrade is concluded

### ISSUE THREAD

**Issue by davidelettieri** [microsoft/service-fabric#1267]
**Describe the bug**
During every upgrade of our applications the "update in progress" page in Service Fabric Explorer remains stuck at the last upgrade domain.

**Area/Component**:
Service Fabric Explorer

**To Reproduce**
Upgrade an application

**Expected behavior**
I expect the interface to update accordingly with the state of the upgrade.

**Observed  behavior**:
This is the final update of the UI, apparently the last node is not updated but the release has been concluded as shown in the second screenshot

![service fabric explorer](https://user-images.githubusercontent.com/5262655/134027046-d62fe760-4485-4dba-ae12-7eb2fe814508.PNG)
![devops](https://user-images.githubusercontent.com/5262655/134027063-92d0a9a1-076c-4bed-ab80-ab33f856270a.PNG)

**Service Fabric Runtime Version:** 
8.1.329.9590

**Environment:**
 - Azure Cluster
 - OS: Windows Server 2016 Datacenter
 - Version 8.1.329.9590

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Please file SFX issues here https://github.com/microsoft/service-fabric-explorer/issues . I unfortunately can not transfer it.
