### ISSUE TITLE
Failed to containerized .netCore3.1 application on Windows Server 2019 Managed Service Fabric Cluster

### ISSUE THREAD

**Issue by vbshell** [microsoft/service-fabric#1272]
I have used "FROM mcr.microsoft.com/dotnet/core/sdk:3.1" base image for creating my dotnet core 3.1 application image
My machine OS is Windows 10 (Version 10.0.19042.1237). However Host OS is Windows Server 2019.
Once I deployed application on Managed Service Fabric cluster (Node OS is Windows Server 2019), application is failing however same application If I published/deploy on my local Service Fabric Cluster, its working fine.
Below is error after publishing code on Managed SF Cluster:

**"'_System.Hosting' reported Error for property 'Download:1.0:1.0:8b1f1d53-de3a-4420-8690-6bd06b303ff4'.
There was an error during download. Container deployment is not supported on the node_."**

Application Details are below: (FYI)

1. I have created .Net Core 3.1 Sample API in Visual Studio 2019
2. Installed Docker Host on my Windows 10 machine.
3. Switched docker host to Windows container
4. Created docker image of my .net Core application.
5. Pushed that image to private docker registry
6. Created Service Fabric Container application where I pulled this image
7. Deployed Service Fabric Container application on local Service Fabric Cluster and Its working fine.
8. On Azure Cloud, created managed Service Fabric Cluster (Node OS is Windows Server 2019)

Problem Started From Next step
9. From Visual Studio, I have published my Service Fabric Container application to managed Service Fabric Cluster (Node OS is Windows Server 2019)
10. After publishing, application shows above error in Service Fabric Cluster Explorer

![image](https://user-images.githubusercontent.com/90249026/136812297-7b2879b3-6651-42c8-aae7-a4e21cacae4e.png)

###  REFERENCE NOTE : I have posted same query on below link
https://github.com/dotnet/dotnet-docker/issues/2101

**Comment by craftyhouse** [comment]
As the error describes, it looks like you are not using an image that supports containers. Please deploy an OS image that supports containers such as "WindowsServer 2019-Datacenter-with-Containers"
