### ISSUE TITLE
[BUG] Onebox on windows?

### ISSUE THREAD

**Issue by Mortana89** [microsoft/service-fabric#1291]
I know we can run Linux Onebox containers on windows now, is there also the option to run a windows cluster in a single container on windows machines?
What I'm looking for is deploying to a local SF docker container and run some API tests. Also, since we have windows asp.net core services running in a local SF emulator, it would be easy to get the complete cluster in one container and distribute to the non-windows guys.

**Comment by craftyhouse** [comment]
Not at this time, but we are looking at how to officially support such a pattern.
