### ISSUE TITLE
[Feature]: .NET 6 support timeline?

### ISSUE THREAD

**Issue by theunis-allegiance** [microsoft/service-fabric#1292]
Is there a timeline for .NET 6 support?

**Comment by IvanAlekseev** [comment]
.Net 5 is going out of support soon in [May 2022](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). We need to find what should we do with apps targeting .Net 5. Do we have to wait till March and SF 9.0 release?

**Comment by ThiemeNL** [comment]
The release notes of SF 8.1 had a key announcement:
`Preview Added support for .NET 6.0 Service Fabric applications`

I found out that the default .NET core actor template of SDK version 5.2.1363 uses net6.0 as target framework.
But I didn't see any announcement that net6 is officially supported.

**Comment by craftyhouse** [comment]
.NET GA support is targeted for 9.0 release, but as previously mentioned you can test your .NET 6.0 apps now as we have preview support.

**Comment by jackbond** [comment]
/unresolve

WTF?

You guys have got to get your acts together.

"Starting Service Fabric 8.2, we will be building Service Fabric ASP.NET Core packages against .NET Core 3.1, .NET Core 5.0, .NET Core 6.0"

https://techcommunity.microsoft.com/t5/azure-service-fabric-blog/azure-service-fabric-8-2-first-refresh-release/ba-p/3040415

Is the SF team actually going to target net6.0, release templates that target net6.0, and NOT officially support net6.0?
