### ISSUE TITLE
[Question]: Setting memory limit using ARM template

### ISSUE THREAD

**Issue by levimatheri** [microsoft/service-fabric#1294]
Is there a way to set ResourceGoverancePolicy e.g. for memory limit for an application, using ARM template?

**Comment by craftyhouse** [comment]
You can configure in the app manifest https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-resource-governance#specify-resource-governance 

and then rollout using ARM

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-arm-resource#add-a-new-application-to-your-resource-manager-template

Does that help?

**Comment by levimatheri** [comment]
Gotcha. I was hoping it would just be a property in the arm template. But this is okay.
