### ISSUE TITLE
[Question]: Is there a way to disable reverse proxy retries completely?

### ISSUE THREAD

**Issue by biltongza** [microsoft/service-fabric#1295]
**Is your feature request related to a problem? Please describe your workload details.**
We are using stateless services in an Azure SF cluster and we are having an issue where downstream timeouts cause the reverse proxy to continuously retry among different nodes, eventually causing resource exhaustion. There doesn't seem to be a way to disable this behaviour. 

**Describe the solution you'd like**
A way to disable reverse proxy retries completely. We generally don't have transient errors, and in this case we are seeing timeouts from a downstream source, no matter which node the reverse proxy tries, all of them will communicate with the same downstream source and timeout.

**Describe alternatives you've considered**
None, we don't see any alternatives.

**Area/Component**:
Cluster/reverse proxy configuration

**Expected behavior**
We've just had a cascade of the reverse proxy continuously retrying requests for 10 minutes at a time, and each one of those requests causes more requests within SF because we have inter service communication happening, and each of those requests is being retried as well (we are aware we can change the inter service communication behaviour via a custom retry policy in the constructor of ServicePartitionClient and we intend to do so). This caused unavailability within our production cluster for an hour. Our expected behaviour is for this not to happen.

**Service Fabric Runtime Version:** 
8.2, .net SDK 4.1.510

**Environment:**
 - Azure
 - OS: Windows Server 2016 Datacenter
 - Version 8.2

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by damianwojdan** [comment]
I don't think there is a built-in switch to do that from a configuration level. 
On a service level to disable retries the service that returns the HTTP 404 response also needs to return the following header:

`X-ServiceFabric : ResourceNotFound`

Some details here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services

**Comment by biltongza** [comment]
Yeah, a timeout isn't a 404 though. We already use the ResourceNotFound trick for actual 404s.

**Comment by craftyhouse** [comment]
I would suggest exploring one of the new reverse proxy solutions we are developing below. These should be able to help with your scenario as they both have health check capabilities and won't blindly retry. We are working to get these to production quality over the coming months and would appreciate any feedback on the repos.

https://github.com/microsoft/service-fabric-yarp/

https://github.com/microsoft/service-fabric-traefik/
