### ISSUE TITLE
Incorrect error: Partition count can be updated only for services using NamedPartitioningScheme

### ISSUE THREAD

**Issue by negberts** [microsoft/service-fabric#1297]
**Bug**
 
**Describe the issue:**

We have an application on our production cluster with the following parameters in the manifest:
```

<Parameter Name="AchtergrondProces_MinReplicaSetSize" DefaultValue="2" />
    <Parameter Name="AchtergrondProces_PartitionCount" DefaultValue="1" />
    <Parameter Name="AchtergrondProces_TargetReplicaSetSize" DefaultValue="3" />
    <Parameter Name="AutorisatieService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="BouwstofService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="CachingService_MinReplicaSetSize" DefaultValue="2" />
    <Parameter Name="CachingService_PartitionCount" DefaultValue="1" />
    <Parameter Name="CachingService_TargetReplicaSetSize" DefaultValue="3" />
    <Parameter Name="DocumentService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="EventHandlerService_InstanceCount" DefaultValue="1" />
    <Parameter Name="ExternalApi_InstanceCount" DefaultValue="-1" />
    <Parameter Name="MaintenanceService_InstanceCount" DefaultValue="1" />
    <Parameter Name="ManagementService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="MengselService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="PlanningService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="ProjectService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="ReportingService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="ServiceFabricApi_InstanceCount" DefaultValue="-1" />
    <Parameter Name="StamgegevensService_InstanceCount" DefaultValue="-1" />
    <Parameter Name="TenantActorService_MinReplicaSetSize" DefaultValue="2" />
    <Parameter Name="TenantActorService_PartitionCount" DefaultValue="10" />
    <Parameter Name="TenantActorService_TargetReplicaSetSize" DefaultValue="3" />
    <Parameter Name="UserProfileActorService_MinReplicaSetSize" DefaultValue="2" />
    <Parameter Name="UserProfileActorService_PartitionCount" DefaultValue="10" />
    <Parameter Name="UserProfileActorService_TargetReplicaSetSize" DefaultValue="3" />
```

When we try to update our application with a new version we get the following error:

2021-12-01T10:30:10.1872517Z Failed to start application upgrade. Error Default service update validation failed: Partition count can be updated only for services using NamedPartitioningScheme, for details about different partitioning schemes please refer to the https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-partitioning. Updated service: fabric:/Pim.ServiceFabric/TenantActorService..
2021-12-01T10:30:10.1880752Z Could not start upgrade successfully. Unregistering application type 'Pim.ServiceFabricType' and version '4.0.1.48'.

The complete log is included:
[tasklog_18.log](https://github.com/microsoft/service-fabric/files/7633098/tasklog_18.log)

As far as I can see the partitioncount for the TenantActorService is 10 on the current cluster and is 10 in the update package... So what is going on here?

**Describe as best as possible how to reproduce the issue:**

> If found from a deployment, please include the following

**Service Fabric Version:**
5.2.1235.9590
**Guest OS version:**
Windows 2019
**Hosted on Azure or On-Prem:**
Azure

**Comment by negberts** [comment]
One suggestion I have is returning the mismatch (target and actual) in the error so debugging gets easier.

**Comment by craftyhouse** [comment]
Please open a support case if you are still facing this problem:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
