### ISSUE TITLE
[BUG] FABRIC_E_HEALTH_ENTITY_NOT_FOUND on entities that do exist after recovery.

### ISSUE THREAD

**Issue by PepijnGramberg** [microsoft/service-fabric#1298]
**Describe the bug**
After a series of events including some recovery, the healthstate queries are returning errors even after a long time period.

**Area/Component**:
Monitoring/Explorer

**Order of events**

1. ARM update to VMSS
2. 1 VM fails to get online properly (not noticed)
3.  Recreated application types with same name but new version (so not just a new version in the same applicationtype!)
4. Deployed new applications
5. Notice and Reboot broken vm
6. First the old versions are still on this VM
7. This did autorepair the new applications are running on this VM
8. Health state queries are still not working 12hr+ later

**Expected behavior**
Full recovery.

**Observed  behavior**:
There are no warnings/errors to be seen in the explorer except when navigating to Node>Application. Healthstate gives Unknown on this node, and there are exceptions like:
```
Http failure response for https://[clusterurl].onmicrosoft.com:19080/Nodes/[_cluster-SS_3]/$/GetApplications/[aplicationname]/$/GetHealth?EventsHealthStateFilter=0&DeployedServicePackagesHealthStateFilter=1&api-version=3.0&_cacheToken=1638440053603: 404 FABRIC_E_HEALTH_ENTITY_NOT_FOUND
```
These exceptions / no info is on the application level and the package level. But at Code Packages and Replicas level it is working fine.

**Service Fabric Runtime Version:** 
8.0.521

**Environment:**
 - Azure
 - OS: Windows 2019
 - Version 8.2.1235.9590

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Please log a support request if you are still facing this problem

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
