### ISSUE TITLE
[Question]: Using .NetCore 6 Minimal APIs

### ISSUE THREAD

**Issue by francescocristallo** [microsoft/service-fabric#1300]
I'm trying to use .Net Core 6 **Minimal APIs** model for Service Fabric Microservices.

So far using .Net 5 templates in Visual Studio 2022, I couldn't figure out how to refactor using Minimal APIs.

Is this supported yet?

**Comment by esbenbach** [comment]
Not an MS person, but there isnt even .net core generic host support yet - so i doubt it.

**Comment by juho-hanhimaki** [comment]
Generic host support is included in latest SDK. It seems they forgot to announce it in the release notes. I have tested minimal API's and it seems to work.

**Comment by esbenbach** [comment]
@juho-hanhimaki do you have an example/refence anywhere? I can't seem to find anything changed in the github repo that says it should support generic host (other than the existing workarounds that is).

And sorry for highjacking the issue fancesco - though generic host thing should help point you in the right direction for use of minimal API i  think.

**Comment by juho-hanhimaki** [comment]
You can find the generic host PR here: https://github.com/microsoft/service-fabric-aspnetcore/pull/96

It is included in the 5.2.1363 libraries. There was nothing special about using the minimal API. Don't have the code handy now.

**Comment by esbenbach** [comment]
Ahh awsome - i was looking at the main and dotnet repos, forgot about the aspnetcore one. Thanks a bunch!

**Comment by francescocristallo** [comment]
Visual Studio 2022 now have updated templates using .Net 6 and Minimal Apis.

**Comment by kosalanuwan** [comment]
Where can I find the service fabric scaffoldings/project templates that are used when you create a new service fabric app from Visual Studio?
