### ISSUE TITLE
Events - Invalid API version

### ISSUE THREAD

**Issue by strabu** [microsoft/service-fabric#1301]
**Describe the bug**
Service Fabric Explorer on local dev cluster (http://localhost:19080/)
shows red Error-Message after clicking on Application-"Events"-Tab

**To Reproduce**
1) Install Service Fabric SDK 5.2.1235
2) Start local Dev Cluster
3) Open http://localhost:19080/ in a Webbrowser (eg. Google Chrome)
4) navigate to: Cluster/System/fabric:/System/ClusterManagerService
5) click tab: "Events"
6) see Error-message: "null failed. Code: E_INVALIDARG Message: Invalid API version"

**Expected behavior**
Should show Events not an Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/8020862/144613754-756ec694-9046-4639-8c28-c1b2a03c330d.png)

![image](https://user-images.githubusercontent.com/8020862/144613073-2fcfb924-4567-4641-8cde-3303f1c29f4e.png)

 -  Service Fabric version
Service Fabric SDK and Tools 5.2.1235
Service Fabric runtime 8.2.1235

 - OS(for browser not SF)
 Windows 10
 - Browser/ Browser version
Chrome 96

**Additional context**
Service Fabric Explorer sends a request with "api-version=7.2" but the Cluster is running 8.2"

**Comment by jeffj6123** [comment]
Transferred to the main service fabric repo because this is an issue with the Event store service.

**Comment by craftyhouse** [comment]
Please update to 8.2 and let us know if you still face this problem. Thanks

**Comment by stoepa** [comment]
Hi all,

I am experiencing the same. Running on the latest version

![image](https://user-images.githubusercontent.com/6512585/157835251-a4d3060e-120d-4881-be10-4b102a789a93.png)

Any idea how to fix?

**Comment by strabu** [comment]
I'm also running the latest version:
![image](https://user-images.githubusercontent.com/8020862/157880714-d6661f98-27c3-4f05-8351-9482502d2837.png)
![image](https://user-images.githubusercontent.com/8020862/157880766-7230b681-063c-4dfc-8b44-18d5e9a0d094.png)

**Comment by bjorn-einar-bjartnes-4ss** [comment]
I have this issue too.
Checking the network tab in the browser, Service Fabric explorer tries to fetch
```
http://localhost:19080/EventsStore/Applications/ xXXX /$/Events?starttimeutc=2023-08-08T10:15:13Z&endtimeutc=2023-08-15T10:15:13Z&eventTypesFilter=ApplicationProcessExited,ApplicationContainerInstanceExited&api-version=7.2
```
when I click to open the application, which returns
```
{
  "Error": {
    "Code": "E_INVALIDARG",
    "Message": "Invalid API version"
  }
}
```

If I manually tries to call the API with 
```
&api-version=9
```
it works fine. 

Application runs
```

  <package id="Microsoft.ServiceFabric" version="8.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Data" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Data.Extensions" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Data.Interfaces" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Services" version="5.2.1235" targetFramework="net462" />
  <package id="Microsoft.ServiceFabric.Services.Remoting" version="5.2.1235" targetFramework="net462" />
```

Service Fabric 9.1.1799.9590
