### ISSUE TITLE
SDK 5.2.1571

### ISSUE THREAD

**Issue by festivus** [microsoft/service-fabric#1331]
I noticed this was released on 3/10 but I can't find any information on what's in the release.

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by jackbond** [comment]
The NuGet packages showed up yesterday, and in an unusual twist, 1571 is already available in the portal as an upgrade.

When you announce,

"Service Fabric runtime has identified a bug during additional testing and is temporarily suspending support for Windows Server 2022"

You look foolish. You can't simply go, "we lied, we're UNSUPPORTING that." And if you do something like that, when you have a fix, YOU ANNOUNCE IT AT THE TOP OF YOUR LUNGS.

As it stands, there still is no official announcement of whether SF supports .NET 6, and 2022 support is a complete mystery.

The SF product managers don't respond to anyone anywhere.

******* FIRE SOMEONE.

**Comment by jackbond** [comment]
Here's how you know that the Service Fabric Product Managers don't give a **** about doing their jobs. We're all obviously in the business of writing software. When you release a new product, even just a minor new version, aren't you excited to share the news. What's new? What's fixed?

They can't even be bothered to do a timely release note, even when there's a pending "We really screwed up badly bug".

A grotesque combination of laziness and incompetence.

It's part of MY job to know what's going on with technologies my company uses. As part of that, I check this repo at least once every couple days or so. Sadly, it doesn't appear that ANYONE involved with Service Fabric could give a **** about their users.

**Comment by festivus** [comment]
I don't know what's going on within the team. I've personally met @masnider and he's a great guy. I don't know if he's still involved with service fabric. There does seem to be a lack of information coming from the team lately but I'm going to choose to remain professional here.

**Comment by jackbond** [comment]
I've meant plenty of great guys who suck at their job, and I don't think it's unprofessional to call out those who suck at their job.

And I think it can be stated with 100% certainty that the SF's teams failure to clarify the current state of support for both .NET 6 and Windows 2022 after MONTHS of uncertainty is completely unacceptable.

Heck, the initial post is objective evidence that someone isn't doing their job. There's simply no other way to slice it.

**Comment by jackbond** [comment]
Is this acceptable?

https://github.com/microsoft/service-fabric/issues/1324

"abandonment aura" describes the current status of Service Fabric perfectly.
