### ISSUE TITLE
[Question] - How to upgrade Certificate/Cluster Configuration in SF 8.2

### ISSUE THREAD

**Issue by andrewcrowley21** [microsoft/service-fabric#1338]
**Describe the bug**
I don't know where else to ask this, so please lead me in the right direction if needed. I am on SF version 8.2.1486.9590 and I don't know how to update my cluster configuration (with primary and secondary certificates) to use a newly declared certificate. The goal is to remove the secondary certificate thumbprint, move the primary certificate to the secondary certificate, and make a newly declared certificate thumbprint primary. 

There is documentation on how to upgrade certificate thumbprints using Azure Powershell and Azure Resource Manager, but unfortunately those are not options for me as I am using a Standalone Cluster with 3 nodes.

**Service Fabric Runtime Version:** 
8.2.1486.9590

**Environment:**
 - Standalone Cluster (3 nodes)
 - OS: Windows Server 2019
 - Version 8.2.1486.9590

**Comment by craftyhouse** [comment]
Please direct questions to one of the appropriate forums as documented 
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

Microsoft Q&A preferred or stackoverflow
