### ISSUE TITLE
how to install cluster on windows core

### ISSUE THREAD

**Issue by alexgman** [microsoft/service-fabric#134]
I'm running virtualbox on windows 10, and the host has this version:

![image](https://user-images.githubusercontent.com/4227695/40201892-0cd97be2-59e6-11e8-9888-ddf1bec2fd11.png)

The VM has windows 2016 core installed:

![image](https://user-images.githubusercontent.com/4227695/40202145-b495b652-59e6-11e8-8a15-1b7f48620a36.png)

To install all dependencies, I've followed this advice and have run [this](https://github.com/Azure/service-fabric-issues/issues/710): **Please note that I've gotten all latest versions of the dependencies below**
```
# # Install visual c++ 2012 SP1 redistributable package
Invoke-WebRequest "http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU1/vcredist_x64.exe" -OutFile "C:\vcredist.exe" -UseBasicParsing; \
    Start-Process "C:\vcredist.exe" -ArgumentList '/install', '/passive' -NoNewWindow -Wait; \
    rm "C:\vcredist.exe"

# Install Service Fabric Runtime
Invoke-WebRequest "http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabric.6.0.232.9494.exe" -OutFile "C:\ServiceFabricRuntime.exe" -UseBasicParsing; \
    Start-Process "C:\ServiceFabricRuntime.exe" -ArgumentList '/AcceptEULA', '/QUIET' -NoNewWindow -Wait; \
    rm "C:\ServiceFabricRuntime.exe"

# Install Service Fabric SDK
Invoke-WebRequest "http://download.microsoft.com/download/3/2/1/3217654F-6882-4CEA-BD51-49287EDECE9B/MicrosoftServiceFabricSDK.2.8.232.msi" -OutFile "C:\ServiceFabricSDK.msi" -UseBasicParsing; \
    Start-Process "msiexec" -ArgumentList '/i', 'C:\ServiceFabricSDK.msi', '/passive', '/quiet', '/norestart', '/qn' -NoNewWindow -Wait; \
    rm "C:\ServiceFabricSDK.msi"
```

However, I'm running into the following issue:

![image](https://user-images.githubusercontent.com/4227695/40202095-967011c2-59e6-11e8-9e6d-64ab58b567c3.png)

**What am I doing wrong?**

**Comment by rishirsinha** [comment]
@alexgman, have you tried restarting after the install? I feel like I am sounding like "Maurice Moss" from "The IT Crowd", but it looks like there is a reason this is a meme.

**Comment by alexgman** [comment]
Yes indeed I have tried to restart.

**Comment by Flern** [comment]
First, use Dependency Walker to see what's causing the DLL issue.

I had the same issue at one point, and it turned out there was an undocumented dependency on VC++ 2008 (or 2005? or 2015? sorry I don't have better recollection) redistributable package (don't quote me on that).  SF team just assumed it would be present and never documented or included the dependency in the SDK/runtime install.

See this for more troubleshooting options:
[](https://github.com/Azure/service-fabric-issues/issues/539)

Good luck!

**Comment by maburlik** [comment]
We have numerous customers regularly running on Windows Server Core and cover this as a supported path. It's likely there was a bug in the BPA code in 2018 as many improvements have been made to the code base since then. Feel free to open another thread if you are still hitting issues.
