### ISSUE TITLE
Docker image name does not respect parameters

### ISSUE THREAD

**Issue by mjrousos** [microsoft/service-fabric#136]
To enable easily deploying a Service Fabric app with different versions of a container, it would be useful to allow the `Image\name` attribute of `ImageOverrides` to use parameters.

**Desired Behavior**

In ApplicationManifest.xml, specify container host policies like:

```xml
<ContainerHostPolicies CodePackageRef="portabilityservice.configurationservice.Code">
    <RepositoryCredentials AccountName="[RepositoryUserName]" Password="[RepositoryPassword]"/>
    <ImageOverrides>
        <Image Name="portabilityservice.azurecr.io/portabilityservice-configurationservice:[ImageTag]" />
    </ImageOverrides>                
    <PortBinding ContainerPort="80" EndpointRef="portabilityservice.configurationserviceEndpoint"/>
</ContainerHostPolicies>
```

I would like to have the service deployed correctly using parameterized values for the container repository user name and password, and for the container image tag.

**Actual Behavior**
Parameterizing repository credentials works, as desired, but the image name with `[ImageTag]` embedded in it does not work. In order for container images to pull correctly, there can be no parameters in the image name.

**Comment by craftyhouse** [comment]
I would suggest trying to set the image in the service manifest as described here
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-manifest-example-container-app#frontendservice-service-manifest

Please re-open if you are still facing this issue, but closing at this time.
