### ISSUE TITLE
[BUG] - Web Api Template scaffolding error in VS 2022 Community on Latest .NET SDK

### ISSUE THREAD

**Issue by ralav** [microsoft/service-fabric#1361]
Create web api project from scaffolding vanilla template error in VS 2022

**Area/Component**:
Web Api Stateless Project

**To Reproduce**
Attempt to create new project from vanilla template of VS 2022 Community with Latest .NET SDK in Windows 11 

**Expected behavior**
Able to successfully create stateless web api project

**Observed  behavior**:

**Screenshots**
<img width="310" alt="image" src="https://user-images.githubusercontent.com/26783264/169721292-0b90d762-1bd9-42ea-8a1a-ef7b92b8cc5e.png">

**Service Fabric Runtime Version:** 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/26783264/169721337-8f4690da-0827-43ca-8797-037b2b24071a.png">

**Environment:**
 - Dev cluster
 - OS: Windows 11 Professional Latest

**Additional context**
NA

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by ravindraaditya** [comment]
I found a workaround. create the project in VS 2019 and then dev through VS 2022

**Comment by tyler-kearney-pu** [comment]
My workaround was to create as a .net 5 project, then upgrading to 6/7.

**Comment by NCarlsonMSFT** [comment]
@ralav sorry for the delay in this being looked into. Unfortunatly this was not brough to my attention till over the weekend (I work on the relevant VS tools). For a quicker response in the future i recommend using the "Report a Propblem" feature in VS as that usually gets to the correct team faster:
![image](https://user-images.githubusercontent.com/14239288/201792654-e66071c6-1d4d-44d3-afb7-5208f06b9801.png)

I'm testing a fix for you issue, and it should be available in the 17.5 timeframe. In the meantime, an additional workaround to retargeting from .NET 5 is to uncheck "Do not use top-level statements" when making a .NET 6/7 web project:
![image](https://user-images.githubusercontent.com/14239288/201792377-e7d37a80-3c07-42f1-9b8d-d3984e4531d3.png)
Out template's code does not handle this new option (yet)

**Comment by ralav** [comment]
> My workaround was to create as a .net 5 project, then upgrading to 6/7.

Never ever do manual efforts around this, as sometimes we will end up in loosing enhanced or ignored.

**Comment by ralav** [comment]
> @ralav sorry for the delay in this being looked into. Unfortunatly this was not brough to my attention till over the weekend (I work on the relevant VS tools). For a quicker response in the future i recommend using the "Report a Propblem" feature in VS as that usually gets to the correct team faster:
> 
> ![image](https://user-images.githubusercontent.com/14239288/201792654-e66071c6-1d4d-44d3-afb7-5208f06b9801.png)
> 
> 
> 
> I'm testing a fix for you issue, and it should be available in the 17.5 timeframe. In the meantime, an additional workaround to retargeting from .NET 5 is to uncheck "Do not use top-level statements" when making a .NET 6/7 web project:
> 
> ![image](https://user-images.githubusercontent.com/14239288/201792377-e7d37a80-3c07-42f1-9b8d-d3984e4531d3.png)
> 
> Out template's code does not handle this new option (yet)

Thanks for the suggestion and regarding workaround I feel not okay. It's fine being package issue but expecting redundant.

**Comment by NCarlsonMSFT** [comment]
A fix for this is available in [Visual Studio 2022 17.5 Preview 2](https://visualstudio.microsoft.com/vs/preview/)
