### ISSUE TITLE
[QUESTION] - Correct way to update SF

### ISSUE THREAD

**Issue by FredrikDahlberg** [microsoft/service-fabric#1364]
Most changes to a Service Fabric cluster requires that you deploy a new cluster. What is the correct process for this? It is easy to spin up a new cluster but what are you supposed to do with the old cluster?

With any other tech you bring the old thing offline. You make a switch. If the new stuff fails, you just go to the old thing.

What is the correct way for doing this in SF cause it seems utterly broken by design…

**Comment by Mortana89** [comment]
Have you got a cluster with some reliability?
We're running 8 nodes with a total of roughly 120 microservice instances, for over 4 years. I've never encountered what you describe, except for single-node clusters?

**Comment by FredrikDahlberg** [comment]
> Have you got a cluster with some reliability? We're running 8 nodes with a total of roughly 120 microservice instances, for over 4 years. I've never encountered what you describe, except for single-node clusters?

Silver at least. About the same node count. The case we have right know is changing the OS upgrade policy since the SF defaults crashes the cluster all the time.

It is not practical possible to run 120 micro-services on SF btw.  How would you do that?

**Comment by Mortana89** [comment]
> > Have you got a cluster with some reliability? We're running 8 nodes with a total of roughly 120 microservice instances, for over 4 years. I've never encountered what you describe, except for single-node clusters?
> 
> Silver at least. About the same node count. The case we have right know is changing the OS upgrade policy since the SF defaults crashes the cluster all the time.
> 
> It is not practical possible to run 120 micro-services on SF btw. How would you do that?

I didn't say it's practical 😀 
It's one solution with 25ish different micro services, some APIs (in a front end node type, 3 VMs) and some workers (in a back end node type, 5 VMs). Rollouts take half an hour but hey, we're not complaining 😉

Are you using ARM to update the settings? Does the cluster go in an upgrade mode though or does it just give up as a whole?

**Comment by FredrikDahlberg** [comment]
...we have ARM templates that works for everything. The problem is that changing any core setting of SF requires a new cluster.

**Comment by craftyhouse** [comment]
Please direct questions to one of the appropriate forums as documented
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

Microsoft Q&A preferred or stackoverflow

**Comment by FredrikDahlberg** [comment]
> Please direct questions to one of the appropriate forums as documented https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
> 
> Microsoft Q&A preferred or stackoverflow

Should I have to ask SO about basic things like how to update a SF cluster correctly even when you provided the recommendations to do so?
