### ISSUE TITLE
Future Support for 2019-Datacenter-with-Containers OS image

### ISSUE THREAD

**Issue by BaMi83** [microsoft/service-fabric#1366]
**SF Runtime**
Future SF releases

**Environment:**
Azure

**Description:**
The windows server 2019 with datacenter OS image support will be deprecated in august, because of the mirantis docker Engine which will be a paid product.

**MS health Advisory:**
Previously we announced that the support story for the Mirantis Container Runtime (formerly Docker EE) on Windows will be transitioning to Mirantis Inc. in September 2022. We would like to supplement this announcement with a reminder that in accordance with the transition, both the DockerMsftProvider API and the "Windows Server with containers" images published by Microsoft on the Azure Gallery will be deprecated. This is largely because Microsoft won't have the distribution rights for the Mirantis Container Runtime come September.

Note: If you're using Windows containers on AKS or AKS on prem (Azure Stack HCI or Windows Server), this announcement doesn't apply to you; Microsoft provides a fully supported container runtime at no additional cost for these environments.

We're reaching out to you because we have records of you using one of the following Azure gallery images:

2016-Datacenter-with-Containers
2016-datacenter-with-containers-g2
2016-Datacenter-with-Containers-GS
2019-Datacenter-Core-with-Containers
2019-datacenter-core-with-containers-g2
2019-Datacenter-Core-with-Containers-smalldisk
2019-datacenter-core-with-containers-smalldisk-g2
2019-Datacenter-with-Containers
2019-datacenter-with-containers-g2
2019-Datacenter-with-Containers-GS
2019-Datacenter-with-Containers-smalldisk
2019-datacenter-with-containers-smalldisk-g2
Required action
At the end of September 2022, Microsoft will stop publishing new versions of these images to the gallery. At the end of March 2023 these images will be removed from the Azure gallery; Microsoft won't offer a replacement image in the gallery that bundles a container toolchain. Going forward, you'll have the following options:

1. Make the transition to AKS/AKS-HCI where full support and automatic management of the container runtime is provided at no additional cost.
2. Use a Windows Server Azure Marketplace Image produced by Mirantis. This will start as a pilot program based on customer interest, for which Mirantis will make available a version of the Windows Server VM image with the Mirantis Container Runtime preinstalled alongside any tooling they deem relevant. For information on this program please contact us.
3. Use the Azure Image Builder service to build your own image based on the desired version of Windows Server and bundle a container runtime of your choice.
4. Use VM Scale Set Custom Script Extensions to do a post-deployment configuration of your VM to install your desired container toolchain.

For customers using Windows containers in Service Fabric, Service Fabric only supports Mirantis Container Runtime as a configuration, which can incur a support cost if desired._

* What is the next in line OS image which supports SF without container support?
* And is there already any news on when there will be a marketplace image available with support for containers?
* Also, when we want to use a different OS Image, what is the best way to achieve this (we use an ARM deployment for the entire SF cluster) simply use a different ImageSKU and enroll the cluster ? Does SF/VMSS support an in-place upgrade?

**OS (Windows/Linux)**
Windows

**Comment by levimatheri** [comment]
@craftyhouse any comment on this?
