### ISSUE TITLE
Unable to reset a cluster

### ISSUE THREAD

**Issue by chirdeeptomar** [microsoft/service-fabric#137]
I have had service fabric working but all of the sudden it has stopped working. I suspect its after the latest visual studio update.

I have reinstalled Service Fabric SDK, Visual Studio 2017 and VC++ redistributable. Deleted actual folders from the disk including C:\SfDevCluster but still no luck.

Running the DevClusterSetup.ps1 produces the following:

Do you want to continue [Y/N]?: Y
Removing cluster configuration...
Unable to start fabric host service because System.InvalidOperationException: Cannot start service FabricHostSvc on computer '.'. ---> System.ComponentModel.Win32Exception: An instan
ce of the service is already running
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.Fabric.FabricDeployer.FabricDeployerServiceController.StartHostSvc(String machineName)
Cleaning existing certificates...
Certificates removed.
Stopping all logman sessions...
Cleaning log and data folder...

Using Cluster Data Root: C:\SfDevCluster\Data
Using Cluster Log Root: C:\SfDevCluster\Log

The generated json path is C:\Users\ChirdeepTomar\AppData\Local\Temp\tmp5F6C.tmp.json
Processing and validating cluster config.
Create node configuration succeeded
Starting service FabricHostSvc. This may take a few minutes...

**Comment by arturenault** [comment]
Hi Chirdeep,

Can you check if the FabricHostSvc service is running by running `sc query FabricHostSvc`?

If it is, run `sc stop FabricHostSvc` to stop it from running. Check no Fabric*.exe tasks are running using task manager (like Fabric.exe, FabricSetup.exe, FabricHost.exe, etc.) and then try running the powershell script again.

**Comment by maburlik** [comment]
This may have been an indicator of FabricHostSvc crashing & being stuck in a crash uploading loop in an older release. Feel free to open another thread if you are still hitting issues.
