### ISSUE TITLE
Error getting user account information for [domain\username]: status=5, error=E_ACCESSDENIED

### ISSUE THREAD

**Issue by Antonissimus** [microsoft/service-fabric#1374]
Hi, Guys!

We had a working standalone cluster (ServiceFabric_7_2_457_9590).
After migrating to the new domain forest, we ran into a problem.
Factory starts up with no problems, but when we try to install an application, an error occurs:

_Error getting user account information for [domain\username]: status=5, error=E_ACCESSDENIED_

There seem to be some blocks, possibly related to some global policies. But I have no idea where to look.
One other thing, a new account was created in the new domain to run the applications.

It's very similar to [Microservice's, Kerberos security and AD forest permissions #748](https://github.com/microsoft/service-fabric/issues/748?ysclid=l4wj0p9q49444235013)  or this [Service Fabric requirements to RunAs a domain user](https://stackoverflow.com/questions/44389648/service-fabric-requirements-to-runas-a-domain-user). But unfortunately we cannot rebuild the domain from scratch (

We tried to install the factory from scratch, but it did not bring a positive result

Thanks in advance!!

**Comment by craftyhouse** [comment]
Please file a support case or use Microsoft Q&A forum. 

https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-support#create-an-azure-support-request
