### ISSUE TITLE
Unable to mount directory that does not exist to container

### ISSUE THREAD

**Issue by cod7alex** [Microsoft/service-fabric#139]
Hi,

I am using volume with my container SF application: 
`<Volume Source="D:\my\folder" Destination="C:\containerfolder" IsReadOnly="false"></Volume>`

My service fails with `There was an error during CodePackage activation.The source location specified for container mount is invalid. Source: D:\my\folder`. I assume this happens because `folder` does not exist.

Are there any possibility to easily overcome this? Thanks.

**Comment by likevi-MSFT** [comment]
It is possible that the directory isn't being created before trying to launch the container, which would result in an error since Docker requires the source directory to exist before deploying the container. I'll look into this issue.

**Comment by harahma** [comment]
@cod7alex Use binds instead of volume since you do not have a specific volume driver.

**Comment by likevi-MSFT** [comment]
It appears for Windows, we require the directory to exist. Currently investigating if Docker for Windows requires the directory to exist. It Docker does not require the directory to exist then we can probably remove the check for directory existence and just let Docker deploy the container.

**Comment by likevi-MSFT** [comment]
For bind mounts, it is a limitation from Docker. We choose not to create the directory for you in Service Fabric prior to creating the container with a bind mount because we don't have any way of knowing who to setup permission for and whether. 

Instead the volume driver should be responsible for creating and providing a directory on the host.

**Comment by likevi-MSFT** [comment]
@cod7alex Are there any open concerns you still have or can we consider the issue resolved?

**Comment by cod7alex** [comment]
@likevi-MSFT i got your point. I am good with closing it. Thank you!
