### ISSUE TITLE
"Error parsing Program.cs" when creating new project

### ISSUE THREAD

**Issue by michaelnero** [microsoft/service-fabric#1390]
**Describe the issue:**
I'm trying to create a new Service Fabric project, but I keep getting the following error when setting up a new project or adding a service to an existing project: "Error parsing Program.cs, aborting converting the web project to a Service Fabric service." I've tried this on multiple machines, even one with a fresh Windows installation, VS 2022, and Service Fabric SDK, so I don't _think_ this is related to my development environment, but I might be wrong.

**Describe as best as possible how to reproduce the issue:**
1. Open VS 2022 as an Administrator
2. Create a new Service Fabric project, selecting framework 4.8
3. Create a new empty ASP.NET Core (hosted on .NET Core) project through the Service Fabric new project creation wizard. Select the option: Do not use top-level statements
4. Wait for the new project to be created, and then I get the error message. I don't see anything in the Output window, and I don't know where I can find some logs to attach.

**If found from a deployment, please include the following**
Not applicable; the issue is on my local machine.

**Comment by tyler-kearney-pu** [comment]
If it helps. my workaround was to target .net 5, then manually upgrade to 6.

**Comment by yashagarwal23** [comment]
Same as #1361.
This has been fixed in [Visual Studio 2022 17.5 Preview 2](https://visualstudio.microsoft.com/vs/preview/)
