### ISSUE TITLE
[BUG] - The current cluster version 8.2.1686.9590 support ends 01.11.2022 00:00:00

### ISSUE THREAD

**Issue by ckrueger1979** [microsoft/service-fabric#1393]
**Describe the bug**
Service fabric states:
The current cluster version 8.2.1686.9590 support ends 01.11.2022 00:00:00

Documentation 
https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-versions
states
8.2CU6 - 8.2.1686.9590
End of support: Current version

Is the version EOL on 01.11.2022 and we have to migrate to 9.x until than or is the documentation page correct?

**Environment:**
 - Standalone
 - OS: Windows 2019
 - Version: 8.2.1686.9590

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
Not sure where you got that message, but the support for 8.2 ended November 30th 2022. Please update to 9.0/9.1 asap.
