### ISSUE TITLE
[Feature]: Package SF SDK for winget / Windows Package Manager

### ISSUE THREAD

**Issue by cthlo** [microsoft/service-fabric#1394]
**Is your feature request related to a problem? Please describe your workload details.**
SF runtime is already packaged for winget (though a little behind on version: #1391)
Can we have the SDK on winget, please?

**Area/Component**:
SDK

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by craftyhouse** [comment]
duplicate of https://github.com/microsoft/service-fabric/issues/1391 - Please track there
