### ISSUE TITLE
[BUG] upgrade from 9.0.1103.1 wrong line terminators in /var/lib/dpkg/info/servicefabric.prerm file

### ISSUE THREAD

**Issue by dechnik** [microsoft/service-fabric#1404]
**Describe the bug**
Service-fabric won't upgrade to newest version because of prerm script file containing wrong line terminators

`Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: Preparing to unpack .../servicefabric_9.0.1114.1.deb 
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: dpkg (subprocess): unable to execute old servicefabric package pre-removal script (/var/lib/dpkg/info/servicefabric.prerm): No such file or directory
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: dpkg: warning: old servicefabric package pre-removal script subprocess returned error exit status 2
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: dpkg: trying script from the new package instead
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: dpkg (subprocess): unable to execute new servicefabric package pre-removal script (/var/lib/dpkg/tmp.ci/prerm): No such file or directory
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]: dpkg: error processing archive /mnt/sfroot/_sfc-vmss_0/Fabric/work/FabricUpgrade/servicefabric_9.0.1114.1.deb (--unpack):
Nov 16 10:32:59 sfc-vmss000000 doupgrade._sfc-vmss_0.sh[28026]:  new servicefabric package pre-removal script subprocess returned error exit status 2`

manually running this script:
`bash: ./servicefabric.prerm: /bin/bash^M: bad interpreter: No such file or directory`

after file reformat upgrade process continues without any issues

**Service Fabric Runtime Version:** 
9.0.1103.1
9.0.1114.1

**Environment:**
 - Azure
 - OS: [Ubuntu 18.04] 

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by ChrisBurgessMS** [comment]
Thank you for the report.  Fixes have been made and will be included in the next 9.0 and 9.1 updates.
