### ISSUE TITLE
Installing service fabric on windows 11

### ISSUE THREAD

**Issue by GomolemoBojosi** [microsoft/service-fabric#1440]
I downloaded both service fabric runtime and sdk, however when trying to run the runtime.exe i get the following "Installation must be called with /accepteula. Running without arguments from explorer is not supported. Press enter to exit. Process will automatically close after 30 seconds."

The i proceed to "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser" and in the powershell navigate to the folder that contains the two executable and run "MicrosoftServiceFabric.9.1.1653.9590.exe /force /accepteula", but the command is not recognized even though i added the path variables according to https://learn.microsoft.com/en-us/answers/questions/1181752/service-fabric-runtime-installation-for-windows-fa , can someone please assist, I'm running windows 11 OS.

when i try to run the runtime it shows this:
![image](https://github.com/microsoft/service-fabric/assets/28733676/9f8207bb-6a37-4350-bab4-2faf9110213a)

already did the set execution policy to unrestricted

Ran this command to try installing with powershell

![image](https://github.com/microsoft/service-fabric/assets/28733676/de8b4225-3c24-4154-a8bc-2222a9744ae5)

When i was using windows 10, everything installed smoothly

**Comment by inputoutputcode** [comment]
@GeeBojosi please can you run the SDK (eg. MicrosoftServiceFabricSDK.6.1.1799.msi) installation first. After you can install the runtime (eg. MicrosoftServiceFabric.9.1.1799.9590.exe /accepteula) without any error.

**Comment by tygore587** [comment]
> Ran this command to try installing with powershell
> 
> ![image](https://user-images.githubusercontent.com/28733676/245415753-de8b4225-3c24-4154-a8bc-2222a9744ae5.png)
> 
> When i was using windows 10, everything installed smoothly

You are in `C:\Windows\system32` folder and I think you don't have downloaded the file there. You need to navigate to your downloads folder first or `shift+rightclick` in the folder where the exe is located and click `Open powershell window here`.

If you run the command after that, it should work. Also if you want to troubleshoot this yourself, please pay attention to the error you got from the terminal. It Is `CommandNotFoundException` and `ObjectNotFound` which mostly means it can't locate the thing you want to run in the terminal.

**Comment by adsrivastava2** [comment]
You can run the command like
 ./MicrosoftServiceFabric.10.0.1949.9590.exe /accepteula

**Comment by Rajeshwari22** [comment]
I had a similar error; all I did was copy the file from the Downloads folder back to C:\Windows\ and then run the command .\MicrosoftServiceFabric.10.1.2175.9590.exe /accepteula. Could install Service Fabric Runtime successfully.
