### ISSUE TITLE
Problems to deploy my first containerized app to a Standalone Service Fabric using Azure Container Registry

### ISSUE THREAD

**Issue by licjapodaca** [Microsoft/service-fabric#146]
I already have a Service Fabric project in Visual Studio 2017 with the following projects:

- **Service Fabric Application**
- **Gateway** (ASP.NET Core with .Net Core and the API Gateway Ocelot)
- **ServiceA** (That is a reliable service using ASP.NET Core WebAPI)
- **ServiceB** (Containerized App using ASP.NET 4 with WebAPI 2)

>Sample code in GitHub https://github.com/licjapodaca/service-fabric-sample-gateway

When I deploy without the ServiceB the Service Application, everything is OK, but when the project ServiceB was including with the option **Add Container Orchestrator Support** in Visual Studio 2017 when try to deploy the Service Fabric application again, appears me a message like the following:

![image](https://user-images.githubusercontent.com/828781/41130917-cf5155a4-6a6d-11e8-8fc6-58f320d0dc2d.png)

>The question here is, **What are the steps to follow to create a Server Certificate and the installation process in the machine or machines that needs to deploy the Service Fabric application?**

Thanks in advance for your help.

**Comment by BigMorty** [comment]
From the Azure portal, assuming you have the proper permissions, you can download the server cert from the KeyVault associated with your SF cluster. Go to the KeyVault in the resource group your cluster is in, click on Certificates on the left and then click on the Certificate. There is an option to download the cert as .pfx. Once you have the .pfx on your dev machine you can double click it to install it and the VS can use it.

BTW, the reason the server cert is needed in this scenario is because the service you containerized needs to have its Docker image pushed to your Azure Container Registry (ACR). To do this in a way that Service Fabric will have access to the image, we encrypt the ACR password using the server cert and them place that in the manifest.

**Comment by licjapodaca** [comment]
Sorry @BigMorty , I forgot to tell you, my **Service Fabric cluster is a Standalone** installation (On-Premises), the steps to follow in this scenario is different?

**Comment by BigMorty** [comment]
There still must be a server cert, that is what you need to install on your dev machine for VS to connect. Adding @amanbha and @NCarlsonMSFT who might know how to extract the server cert from on-prem cluster.

**Comment by NCarlsonMSFT** [comment]
@licjapodaca How did you create your standalone cluster? Is it insecure, secured by certificate, or secured by windows?
Assuming a cluster certificate has been installed you can get it's thumbprint by opening Service Fabric Explorer for the cluster (typically https://<cluster dns>:19080/Explorer/index.html) and going to the manifest tab of the cluster node (add #/tab/manifest to the url). In the manifest look for the certifcates element underneath the nodetype element and that will have the thumbprint for the cluster certificate, if one has been configured.
Assuming it has been configured you should be able to get the certificate by remoting into the machine and exporting the certificate using the certificate manger or powershell (https://docs.microsoft.com/en-us/powershell/module/pkiclient/export-pfxcertificate?view=win10-ps); you can use the thumbprint form above to find the correct certificate in either tool.
Then transfer that pfx file to your client and import it.

**Comment by licjapodaca** [comment]
Hi @NCarlsonMSFT , I create the standalone cluster of SF by Windows security, but I already found another way to deploy ASP.NET 4 MVC WebAPI apps in a container by using the Service Fabric Hosted Containers template with the help of an  Azure Container Registry like in the following image:

![image](https://user-images.githubusercontent.com/828781/41378868-46cc17d0-6f15-11e8-8375-8e4fa086b63d.png)

As you can see:

**1 and 2.** I create the instruction of a new Service Fabric Service using the Hosted Container template giving the complete name of the image plus the Azure Container Registry that I will use.

**3.** Then, it adds the ServiceManifest that represent my ServiceB project that is in ASP.NET MVC 4 WebAPI.

**4.** And Finally, I just add the `Dockerfile` that my service need to create the Image. This process will be done by TFS (On-Premises) with Continuous Integration, first it builds the .Net Project and then will create the Image and upload to Azure Container Registry, so when our Testers trigger the Continuous Delivery it downloads from ACR the image and store it in the Service Fabric Image Store to create the n instances of the service.

It would be ok with this scenario?

**Comment by NCarlsonMSFT** [comment]
@licjapodaca you'll quickly run into the same issue here that you need to provide the credentials for connecting to ACR in your application manifest ([example](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-container-registry-authentication)) and it is highly recommended that you encrypt the password (and if possible don't check it in). Our publish dialog and [release task](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/service-fabric-deploy) both will handle that step for you. But only if your cluster is configured with a cluster certificate.

Would it be possible for you to configure your cluster with windows authentication and a cluster certificate as in this example: https://github.com/Azure-Samples/service-fabric-dotnet-standalone-cluster-configuration/blob/master/Samples/ClusterConfig.Windows.X509.MultiMachine.json ?

@MikkelHegn is it possible to add a cluster certificate to a windows secured cluster after the fact?

**Comment by licjapodaca** [comment]
Excellent @NCarlsonMSFT ... thanks for your help, I will made the changes with the information that you gave me in your last post.

Greetings
