### ISSUE TITLE
Managed service Identity support in SF and containers

### ISSUE THREAD

**Issue by jeeshnair** [Microsoft/service-fabric#147]
Hi,

Is MSI supported from windows containers?. I tried getting access token from within container for VM enabled for MSI and I get a time out exception.  Getting the token from VM it self works fine.

"["An error occurred while sending the request. The operation timed out \n\nAn error occurred while sending the request."]"

**Comment by vturecek** [comment]
Yup, this is in the works, FYI @aljo-microsoft

**Comment by aljo-microsoft** [comment]
If I understand you would like an identity for your SF application to enable it to authenticate to other services; if so, this is being worked on, and will be announced on our team blog when released.
