### ISSUE TITLE
[Feature] .Net 8 support timeline?

### ISSUE THREAD

**Issue by ahhyunahn** [microsoft/service-fabric#1472]
Hi! I am developing a new project and was wondering what the timeline would be for .net 8 support for service fabric. I am delaying majority of the code migration until November (so I can use .net 8 and also use R9 which I believe should also support .net 8 shortly after it's out), but wasn't sure what .net 8 support timeline would look like for service fabric. Do you have any rough ideas on what the timeline would look like? This will help me plan out milestones immensely, would really appreciate any insight!

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by johntyrrell** [comment]
Most likely this will be somewhere june 2024. Just like support for .NET 6 and .NET 7 came several months later. 
But don't expect an official response here on github.

**Comment by kgfly** [comment]
.Net 8 preview was announced on February 21st, 2023, 8 months ago

Why SF always have a half year delay? Make no sense, isn't it?

**Comment by jackbond** [comment]
Actually, they'll announce they support it, then they'll announce that they found a bug and don't support it (after you've upgraded), fail to update their documentation to indicate they don't support it, and then randomly six months later, buried in a doc casually mention that they support it again.

The service fabric project managers are a joke.

**Comment by francescocristallo** [comment]
I manually installed the .Net 8 runtime on the virtual machines and it works with a new Blazor .Net 8 RC2 project.
Would be great indeed to have the official support right after .Net 8 is released.

**Comment by jackbond** [comment]
Service fabric isn't officially dead, but this sure looks like a replacement...

https://devblogs.microsoft.com/dotnet/introducing-dotnet-aspire-simplifying-cloud-native-development-with-dotnet-8

**Comment by mfmadsen** [comment]
My thoughts as well. But on the other hand several other projects coming out of Redmond in the last couple of years seem to all try to be the new cloud native development framework. So wonder whether Aspire will be replaced a new pet project in a year or two…

**Comment by francescocristallo** [comment]
Aspire looks great, but they left the deployment part of it to the developer, it's a local orchestrator for microservices (so far).
It will surely be enhanced with Kubernetes and Azure Container Apps deployment, plus App Service + Azure Functions for who does not use containers.

Service Fabric on the other hand has its own project service in Azure, has progressive deployment directly from Visual studio with no downtime and act as a layer on top of Virtual Machines scale sets exposing a fixed IP, essential for SaaS using custom domains for customers, that can't validate each single one of them as requested by Azure App Service and Container Apps. 
Being on top of VMs it's also way more scalable compared to a managed service. 
I scaled it to ~100 VM with billions of requests per hour, and it was very stable.

They overlap in many ways, but in my opinion we are not yet there for Aspire to be a 100% replacement.

**Comment by flyingosprey** [comment]
@francescocristallo , just courious: what issue will you face if you use K8S? which is very scable too.

**Comment by FredrikDahlberg** [comment]
> Aspire looks great, but they left the deployment part of it to the developer, it's a local orchestrator for microservices (so far). It will surely be enhanced with Kubernetes and Azure Container Apps deployment, plus App Service + Azure Functions for who does not use containers.
> 
> Service Fabric on the other hand has its own project service in Azure, has progressive deployment directly from Visual studio with no downtime and act as a layer on top of Virtual Machines scale sets exposing a fixed IP, essential for SaaS using custom domains for customers, that can't validate each single one of them as requested by Azure App Service and Container Apps. Being on top of VMs it's also way more scalable compared to a managed service. I scaled it to ~100 VM with billions of requests per hour, and it was very stable.
> 
> They overlap in many ways, but in my opinion we are not yet there for Aspire to be a 100% replacement.

I did not get this first but Aspire does not seem to be a product at all. Just a tool to help you to develop code within solutions with poor architecture.

**Comment by francescocristallo** [comment]
> @francescocristallo , just courious: what issue will you face if you use K8S? which is very scable too.

No issues apart complexity, I developed another project using Kubernetes, but I found it too complex to manage with too many parts to stitch together to make it work as I wanted to. 
For a small team or a single developer, I found Service Fabric with its native Visual Studio an Azure integration easier to use. 
I look forward for Aspire to evolve quickly into a full alternative.

**Comment by santo2** [comment]
also like the actual sfproj support, I feel left behind as a service fabric user... they are not paying enough attention anymore to their users of a system that runs very important software.

**Comment by tscamell** [comment]
.NET 7 is EOL on 14th May 2024. Will Service Fabric support .NET 8 before this date? Or is the expectation that organisations will be required to **downgrade** their applications to .NET 6?

Even still, .NET 6 is EOL in Novemember 2024. It would be really helpful for the community if the Service Fabric team can publicize their roadmap for when .NET 8 will be supported on Service Fabric.

As a side note, I have updated one of our applications already to .NET 8, and it is already working successfully on a SF build of 10.0.1949.9590. However, deploying this to production would then invalidate our support until it is offically supported!

**Comment by olegsych** [comment]
We're working on shipping .NET 8 support in April. Here is the feature on our internal backlog for reference by Microsoft employees.

https://dev.azure.com/msazure/One/_workitems/edit/17509673

**Comment by tscamell** [comment]
Thank you for the update @olegsych. It's greatly appreciated

**Comment by mezzo81** [comment]
@olegsych Hi, are you sure it will be out in April?  We are already very excited :-)

**Comment by jackbond** [comment]
Regardless of whether it ships in April, the complete and total lack of professionalism on the part of the Service Fabric management team is simply astounding. Giving Service Fabric customers less than six weeks to test / deploy updates to both dotnet and service fabric is a joke. It's not like the dotnet support schedule was a secret. This was blatant undeniable incompetence on the part of multiple managers, all of whom should be fired. And for anyone who thinks that's harsh, don't worry it's purely hypothetical. They've clearly already gutted the entire team and re-assigned all but one or two part time engineers. They're following the Silverlight roadmap of abandoning a project without officially announcing it.

**Comment by olegsych** [comment]
@mezzo81 I can't guarantee it will be _out_ in April. The SDK changes are well under way and I expect them to be ready for the release we already have scheduled for April. If everything goes as planned, it will be rolled out by the end of that month, including new versions of both the runtime and the SDK packages. However, stuff happens, and releases can slip despite our best efforts when something urgent comes up.

@jackbond I understand your frustration. For what it's worth, let me assure you that Service Fabric is a critical platform and an Azure backbone running on millions of cores. We have dozens of software engineers working from multiple continents and time zones. These engineers are also on-call to provide assistance to the many Microsoft teams and external customers during their live-site incidents. As most systems of its size and critical nature, Service Fabric changes are slow to make and require careful testing to reduce the risk of wide-spread Azure outages affecting dozens of resource types. We are improving our velocity, but this will take a while. Please be patient.

**Comment by mfmadsen** [comment]
@olegsych thank you for your reply on this an your honest feedback. Great to hear this. I completely understand the precautions you need to consider with such a critical product. While the project obviously is not following normal open source product development, it is still super appreciated that you do the work on this. Thanks!

**Comment by JohnNilsson** [comment]
@olegsych indeed, thanks a bunch for that input it helps a lot!

Careful and slow changes to me is a feature, so to me "improving velocity" should not be the main priority, what we need is the ability to plan, which depends on transparency into your end of things (which your post above do provide, so again, a bit thanks for that). If there is any priority conflict between increasing velocity, and increasing transparency, please opt for the latter.

**Comment by SamHard** [comment]
> Giving Service Fabric customers less than six weeks to test / deploy updates...

@jackbond, for enterprise applications, you can avoid some of the "crunch" in the future if you can stick to releases of .NET that are advertised as having long-term support (LTS).  You will save time (and worry) by not adopting the Standard Term Support (STS) releases of .NET.  
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by desdesdes** [comment]
Even though the release notes do not specify it directly it look like .net 8 support is added to [SF 10.1 CU2](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_101CU2.md).

Am i correct and is it officially supported on SF 10.1 CU2?

**Comment by olegsych** [comment]
No. The 10.1 CU2 release doesn't support .NET 8. What makes you think so? I don't see it in the release notes and the following page lists only .NET 7 and .NET6 https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-versions

**Comment by LoloActemium** [comment]
I am also waiting for .Net 8 official support.
I was able to migrate to .Net 8 and deploy our application on our test Service Fabric cluster.
Applications seems to work properly, but I will wait for official support before pushing these on production.

**Comment by LoloActemium** [comment]
@olegsych Yes, I have some dependencies on AspNetCore packages.

**Comment by jackbond** [comment]
We're running Service Fabric, net80, and AspNetCore, along with actor and stateless services, and have not experienced so much as a hiccup. Is there something specific that the SF team knows doesn't work?

**Comment by olegsych** [comment]
Thanks @jackbond! No, we think that AspNetCore should work on .NET 8 with net7 binaries as well but haven't tested it specifically. We already have internal builds with net8 binaries passing the full test suite, so that's what we'll officially support in the next SDK update, in particular because .NET 7 end of support is in May.

**Comment by onerstam** [comment]
@olegsych Are there any news related to the release date of dotnet8 supporting Service Fabric SDK? I am glad to hear that is is passing the full test suite. In my ears it sounds like it could be near a public release.

**Comment by olegsych** [comment]
@onerstam We're close, but still a couple of weeks out. We're addressing unrelated problems we've discovered in the SF runtime and as soon as they are resolved the new SDKs will be out too. You can start now by building your service with the latest SDK 7.1 version. It contains net7 binaries that should work. Other have already done this and we don't know of any specific problems with the older SF SDK versions, we just didn't run our full test suite. Then upgrade to the latest SDK build with the net8 binaries once it's out.

**Comment by filipb-cariad** [comment]
Hi @olegsych Any Update on this?

**Comment by tomverhoeff** [comment]
.NET 7 is now officially out of support and Microsoft folks are (rightfully) telling everyone to upgrade. If only we could actually do this 🤷

**Comment by Dainius14** [comment]
Great! Now we're forced to use outdated .NET version. More than half a year to update one of the _main_ dependencies of this project and it has not been done. Just want to reiterate that this whole Service Fabric thing is a joke and MS better just kill it with this kind of """development""".

**Comment by olegsych** [comment]
Hey @filipb-cariad, I'm sorry for the delay. The new ETA for the next Service Fabric public release is May 28.

**Comment by filipb-cariad** [comment]
> Hey @filipb-cariad, I'm sorry for the delay. The new ETA for the next Service Fabric public release is May 28.

Thanks @olegsych!

**Comment by rvriens** [comment]
Today it is May 28.... Any news yet?
What will be the new version, 10.2?

**Comment by SierraNL** [comment]
@olegsych any update, since we're passed the ETA date?

**Comment by ckrueger1979** [comment]
any news?

**Comment by olegsych** [comment]
I'm sorry about the delay, everyone. We have discovered another, unrelated problem in the Service Fabric Runtime 10.1 CU3 release candidate and had to create another build with the fix. It has now been verified and we have resumed our pre-prod rollout and validation process. The ETA for the public release was pushed out to next Monday, June 10.

**Comment by LoloActemium** [comment]
Is there any news ? ETA is today.

**Comment by rmsryu** [comment]
Can you provide instruction of how to maintain support for our applications? Is the .net team planning to extend .net 7 and .net 6 support? or what is suppose to happen with those users that have applications in .net 7 and those in .net 6?

**Comment by mezzo81** [comment]
This whole thing is getting really silly and no longer looks professional.
Is ServiceFabric now a hobby project?

**Comment by olegsych** [comment]
The new ETA for public release of 10.1CU3 was pushed out to next Monday, June 17.

Here is the .NET support policy: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core. .NET 6 is supported through November 2024.

**Comment by jackbond** [comment]
Do you guys realize how bad this makes the entire service fabric team look? If you weren't going to be ready with net80 the day net70 went out of support, then you never should have officially supported net70. And how the hell were you guys not prepared for this? The dotnet release schedule is not a secret, and it's like this took the team entirely by surprise. What's really sad was this was all predicted over six months ago. And why? I'm sorry to say, it's because the SF team is a joke. Will anyone be fired over this?

**Comment by jackbond** [comment]
It's time to escalate this.

https://x.com/jackbond/status/1800586805051564066

**Comment by SamHard** [comment]
.Net 7 was never promised as LTS.  .Net 5 similarly went out of support before 6 was supported by SF. If you want to stay in support, only select the LTS versions for your software.

**Comment by mezzo81** [comment]
Hi,

That's right what you write, but .net 6 also expires in November and if this continues and NET 8 support will take months (we already have mid-June), time is a bit short. All of our applications also run on NET 6, but we can't switch them all over to NET 8 in 1-2 months and then also test them...

**Comment by silentsouls** [comment]
.net 7 was supported by service fabric.
And now you tell me i was not suppose to upgrade to .net 7 because it was not LTS...

Either you do or you do not support non LTS versions. 
But when you do, you have a responsibility too.

Basically what you are telling us is to downgrade our code, this is stupid.

**Comment by jackbond** [comment]
It's mindboggling that some people are willing to defend the Service Fabric team / Azure when they've so obviously fucked their customers in regards to Service Fabric. If you state you officially support a non LTS version there's an implicit guarantee that you will support the next LTS version prior to the non LTS going out of support.

net80 was released SEVEN FUCKING MONTHS AGO

SEVEN FUCKING MONTHS

The Service Fabric product managers can GO FUCK THEMSELVES.

And fuck your code of conduct. That assumes you've acted professionally. All you've done the last few years is fuck your customers, you don't deserve a shred of respect.

**Comment by messnerdev** [comment]
![JackSF](https://github.com/microsoft/service-fabric/assets/46359640/bfba2c8e-1da9-47c7-a14e-c3a9e7342183)

**Comment by KacperGwiazdowski** [comment]
@olegsych is there any news? ETA is today

**Comment by mezzo81** [comment]
any update ?

**Comment by ckrueger1979** [comment]
@olegsych 
new ETA?

**Comment by Devion** [comment]
It would be nice to have a date, even if weeks away - as long as it actually gets released on that day :)
Even just a RC would be nice to have just to start testing with .net 8 support at this point...

**Comment by flyingosprey** [comment]
> .Net 7 was never promised as LTS. .Net 5 similarly went out of support before 6 was supported by SF. If you want to stay in support, only select the LTS versions for your software.

@SamHard , .Net 7 has expired on "May 28, 2024" and SF .Net 8 support is still not ready yet. What's your suggestion for the customer who's running on .Net7, (which SF did support since Version10) ???

Please don't tell us the solution is "Downgrade to .Net 6".

**Comment by olegsych** [comment]
The new versions of the Service Fabric Runtime and SDK are now available at 
- https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.10.1.2175.9590.exe
- https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabricSDK.7.1.2175.msi

The documentation changes and nuget packages will be published tomorrow.

Rollout of the new runtime version to Azure has started today and should be completed in ~3 weeks.

**Comment by ckrueger1979** [comment]
CAB file for offline update?

**Comment by rmsryu** [comment]
> CAB file for offline update?

I guess is this https://download.microsoft.com/download/B/0/B/B0BCCAC5-65AA-4BE3-AB13-D5FF5890F4B5/10.1.2175.9590/MicrosoftAzureServiceFabric.10.1.2175.9590.cab

Just updated version 10.1.2175.9590 on the URL as per previous CAB file URLs

**Comment by rmsryu** [comment]
Trying to plan ahead for this upgrade. Can it be shared what is the directly upgrade from version "**Can upgrade directly from**"?

https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-versions

**Comment by rmsryu** [comment]
> The new versions of the Service Fabric Runtime and SDK are now available at
> 
> * https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.10.1.2175.9590.exe
> * https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabricSDK.7.1.2175.msi
> 
> The documentation changes and nuget packages will be published tomorrow.
> 
> Rollout of the new runtime version to the public Azure cloud has started today and should be completed in ~3 weeks.

Documentation has been updated, but no mention of .NET 8 support. Any reason for that?

https://github.com/MicrosoftDocs/azure-docs/commit/12729eeee3761faf078b5f676b71e9fb07b7dc40

**Comment by olegsych** [comment]
Thanks for the heads-up. It's an oversight. I have already created a PR to fix that.

**Comment by Morne-Jooste-Gendac** [comment]
@olegsych 

With the latest Service Fabric (10.1.2175.9590) installed on our cluster and the services updated to .Net 8.0 and SDK version (7.1.2175.9590) we are unable to deploy as the nodes do not have .net 8.0 installed. Is this not suppose to be part of the runtime that service fabric installs on the nodes? The nodes do not contain any other .net runtime version but can run .net 7.0 and .net 6.0 services without any issue.

![image](https://github.com/microsoft/service-fabric/assets/77429155/c0fdeff7-5280-4f45-a00a-1636d2711ad6)

![image](https://github.com/microsoft/service-fabric/assets/77429155/4b9b6e87-a83a-49dc-b072-5c4e54257035)

![image](https://github.com/microsoft/service-fabric/assets/77429155/df6277a1-0206-4921-b235-eca2bc370f7e)

**Comment by negberts** [comment]
@Morne-Jooste-Gendac we have been using a CustomScriptExtension to install the .net runtimes for a long time. Even for 5, 6 and 7. Just download the https://dot.net/v1/dotnet-install.ps1 file in the custom script and execute it with -Runtime dotnet -Channel 8.0 as parameters and the runtime will be installed on the VM's on creation of the VM.

**Comment by LoloActemium** [comment]
@negberts @Morne-Jooste-Gendac Why not give a try on self contained binaries ?
Runtime will be packed with your service, so you don't have to take care about which version is installed.

**Comment by Gabriel-Lacatus** [comment]
@LoloActemium This will severely increase the size of your deployment artifacts (multiplied with the number of services/applications) which will lead to:
- increased build times
- increased artifact copy times
- increased package deployment times
- increased service upgrade times
- increased disk space usage on the nodes

If you're not bothered with all of the above, then yes, building with contained framework is the easiest to do.

**Comment by LoloActemium** [comment]
@Gabriel-Lacatus Yes, it's the prize you have to pay. It's up to you for choosing the right scenario that fits your needs.

**Comment by olegsych** [comment]
@Morne-Jooste-Gendac Service Fabric doesn't install any .NET runtimes on Windows today. If you had services previously running on .NET 7, the runtime must have been installed similar to how @negberts described.

**Comment by simonwahub** [comment]
.NET Core 8.0 has a breaking change that SelfContained is $false. The default value was $true in previous .NET Core SDKs.

**Comment by Morne-Jooste-Gendac** [comment]
> .NET Core 8.0 has a breaking change that SelfContained is $false. The default value was $true in previous .NET Core SDKs.

@simonwahub Adding <SelfContained>true</SelfContained> in the csproj of all the services fixed the issue without needed to install additional runtimes. The issue was the breaking change in the framework, previously we used to package them self-contained but now you have to manually specify that it should be self-contained.

Thank you for pointing out the change

**Comment by rasmus-s** [comment]
Hi @olegsych Great with the .NET 8 support in SF. Looking ahead what are the plan for support .NET 9 in SF? Do the SF team plan to support it a few months after the .NET 9 GA release or will SF transition into only support .NET releases with LTS?

As you can see from this thread we are some that care about SF and want to use the latest stuff.

**Comment by olegsych** [comment]
Thanks @rasmus-s! We already started working on .NET 9 support and should have it available with the .NET 9 GA. We are re-evaluating our support policies, so don't take this as a promise or a recommendation yet.

**Comment by olegsych** [comment]
Service Fabric 10.1 CU3 is now available in all public regions of Azure. Thanks everyone for your feedback! It was reflected in the [release notes](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_101CU3.md). I hope we don't find any new surprises, but if we do, feel free to reactivate this.

**Comment by TheAngryByrd** [comment]
Is .net 8 supposed to come installed on a service fabric cluster? I'm on Linux cluster with version `10.1.2306.1` and only dotnet 6 seems to be installed by default.

**Comment by filipb-cariad** [comment]
It doesn't. You have to install it as part of your init scripts. Here is an example with windows server:

https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Scripts/install-dotnet-80.ps1
