### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by tuhland** [microsoft/service-fabric#1476]
I can't find release notes or announcements of any kind for the two latest SF releases. 
They are available as cluster upgrades and NuGet packages, but no documentation to be found. 
What's in these releases?

- 10.0.1949
- 10.1.1541

---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by Kallebollare** [comment]
Any update on this??

**Comment by tuhland** [comment]
Nope. I just checked if I could find any updates / news. The only thin I found is the same issue in a different channel, also with no reply for 2 weeks. I commented there as well.

**Comment by Kallebollare** [comment]
thx for info @tuhland! what is the other channel that you are referring to?

**Comment by tuhland** [comment]
Notes are now visible in the repository:
https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_100CU1.md
https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_101RTO.md

The releases also start to appear in some places:
https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-versions

But not in others:
https://learn.microsoft.com/en-us/azure/service-fabric/release-notes
https://azure.microsoft.com/en-us/updates/?status=nowavailable&query=Service%20Fabric

**Comment by tuhland** [comment]
Closing it, since my "issue" is solved.
