### ISSUE TITLE
How to query the name of the current cluster? Or, could you add this functionality to FabricClient?

### ISSUE THREAD

**Issue by danrozenberg** [Microsoft/service-fabric#150]
Hello, 
Could you please add functionality to query SF for the name of the cluster to which the Host is currently part of? This would come in handy in many diagnostic situations. So far I have not been able to figure out how to do this with a query...Is there any way to do this, or is a new feature needed? Ideally, we would like to do something like this ``fabricClient.QueryManager.GetClusterName()``.

Thanks!

**Comment by samedder** [comment]
We've had this request come up before but it isn't something that's logical from the perspective of Service Fabric. A cluster doesn't have a "name" associated with it.

Some alternatives that may help you achieve what you're looking for:

- If you're looking to differentiate machines, consider using either Azure or [SF environment variables](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-environment-variables-reference)
- If you want to identify applications uniquely by cluster, modify your deployments to use unique application names

In general you don't want to have to retrieve the cluster name

**Comment by danrozenberg** [comment]
Thank you for your answer. Do you also have a link for Azure environment variables? I couldn't readily find anything about them.

**Comment by samedder** [comment]
Sorry, probably poor phrasing on my part.

There isn't an environment variable like in classic cloud services or web apps that you can use to determine you're running in an Azure VMSS but you can use something like the [Azure Instance Metadata service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service).

**Comment by danrozenberg** [comment]
Thank you. I will take a look and see if I can come up with a good solution for our situation. I might be back to bug you all again.

**Comment by danrozenberg** [comment]
@Samedder, I think accessing Azure Instance Metadata service will solve the issue as I can fetch the cluster name from there. Thanks for letting me know it exists!

**Comment by vany0114** [comment]
Guys, I need a way to get the clusterid as well, but out of service fabric application, I mean, I have a SF stateless service which installs a windows service on every node, so I need to get the cluster id, from that service, I was thinking to get the `clusterManifest.xml` or `FabricHostSettings.xml` from `D:\SvcFab` but I'm not sure if SF ALWAYS uses that path. Any suggestions?

Thanks in advance!

**Comment by samedder** [comment]
@vany0114 please create a new issue.
