### ISSUE TITLE
Prevent Service Fabric from generating firewall rules automatically for external access

### ISSUE THREAD

**Issue by licjapodaca** [Microsoft/service-fabric#152]
Currently, I already create an On-Premises Standalone Service Fabric Cluster with 5 nodes (Windows Server 2016 with Containers) with Windows Security, the only way that I want that external users access to the cluster it is across from the API Gateway, so I remove the firewall rules in every node of the cluster accessing the port to the Reverse Proxy (19081) and the range of ports that represents the Microservices in Service Fabric... so everything is OK at this point... but after I remove that rules and pass certain time, that firewall rules appears again in the inbound firewall rules Reverse Proxy 19081 and the range of ports that represent the Microservices specified in the cluster configuration file when I created the SF cluster.

How can I prevent Service Fabric to generate this rules that automatically it creates?, Can I suspend this action? If so, how?

Thanks in advance...

**Comment by licjapodaca** [comment]
Help please ...

**Comment by samedder** [comment]
It's not clear what you mean by this:

> the only way that I want that external users access to the cluster it is across from the API Gateway, 

Stand Alone clusters will have a reverse proxy endpoint, as configured by the following setting in your json configuration file:

    "nodeTypes": [
        "reverseProxyEndpointPort": "19081", //Default
    [...]

A cluster has to have multiple system endpoints available always, not only for admin access and management but also for replication. Manually modifying firewall rules created by Service Fabric will likely result in your cluster just being unresponsive.

It's up to your clients to connect to the correct ports.

**Comment by licjapodaca** [comment]
Ok let me more clarify my problem starting from the following image:

![image](https://user-images.githubusercontent.com/828781/41803276-f626932c-763b-11e8-8ec5-c7d1b032af09.png)

As you can see, all frontends just access accross a NLB installed in the 5 nodes and define the domain "api.domain.net" pointing to a specific IPAddress and port (50605), and the NLB decides to which Node of the 5 will select with the same port (50605). The only ports that I want to expose from the Service Fabric Cluster externally are 19000 (Connect to SF), 19080 (SFX) and 50605 (API Gateway) but **NOT THE MICROSERVICES PORTS**, so for that I use the Windows Firewall Rules in every Cluster Node, but every certain time the Rules that I already remove created by the initial Service Fabric creation add them again as you can see in the following image:

![image](https://user-images.githubusercontent.com/828781/41803402-4a9c19c6-763d-11e8-880b-972db680b1bb.png)

I want to remove those ports and tell to Service Fabric that not generate again those firewall rules, but how?

>**Note**: My Service Fabric is implemented in an On-Premises infrastructure.

**Comment by samedder** [comment]
I think understand what you're trying to do but I think you're trying to secure your cluster incorrectly.

For example. there are even more ports that Service Fabric uses beyond 19000 and 19080 for say replication and leasing. If you're trying to secure your cluster by blocking all ingress ports except for say RDP, 19000 and 19080 you're going to cause all your nodes to fail from lease failures.

Consider also the case where you're running more than 1 service that has and endpoint, how are you supposed to handle binding then?

Is configuring NLB drop rules at the gateway an option?

**Comment by licjapodaca** [comment]
Hi @samedder , my problem was solved, I reuse the same Firewall rules that Service Fabric creates and just I specify the IP Addresses of the 5 SF nodes at "RemoteAddress" field in the rules as you can see in the following image:

![image](https://user-images.githubusercontent.com/828781/41823322-161f5e20-77b3-11e8-94e5-f5d15a634615.png)

With that I suspend the external access to the Reverse Proxy and the Microservices port range, I just want to give external access to the posts 19000 (SF Connect), 19080 (SFX) and 50605 (API Gateway [Secure Token Access with IdentityServer4]) added to the Firewall rules by demand like in the following image:

![image](https://user-images.githubusercontent.com/828781/41823394-1f0580ea-77b4-11e8-8e04-cd6cc70a01c7.png)

With this movement I solve my problem.

Thanks for your help...

Greetings

**Comment by samedder** [comment]
In general we do not recommend modifying the firewall rules added by service fabric like this. Any modifications should be done through the cluster manifest or cluster configuration so they are durable between host operations.

**Comment by licjapodaca** [comment]
Ok, but how can I do the same approach in the cluster configuration file?

**Comment by licjapodaca** [comment]
@samedder Hi, how can I do that in the cluster configuration file? The same approach...

Greetings

**Comment by Mahons** [comment]
Hi @samedder @licjapodaca, just wondering if any update on how to do this using the cluster configuration as we're following the same approach (Standalone) with locking down the default ports to remote addresses?
