### ISSUE TITLE
Looking for published studies on deployed systems

### ISSUE THREAD

**Issue by JEJ0** [Microsoft/service-fabric#156]
(I'm probably asking this in the wrong forum, so bear with me)

I can find hints in slides that Service Fabric is used in as an underlying technology within Azure itself.  I haven't found any detailed descriptions of them, however.

I think it would be useful to publish some papers on how Azure itself has used Service Fabric, and especially how it manages it in a production setting.  What environmental monitoring is needed? How is security handled? What about capacity planning?  Or multi-site availability?  Or upgrades? ... and so on.

Jim.

**Comment by MikkelHegn** [comment]
Hi Jim, Here's one I can think of on top of my head from Intune: https://cloudblogs.microsoft.com/enterprisemobility/2015/06/16/architecture-matters-the-service-fabric-of-our-lives/

**Comment by JEJ0** [comment]
Hi Mikkel,

Thanks, that's not bad, but not quite what I was hoping for.  This is pretty high level - it shows that SF is being used by InTune, that Brad is happy, but doesn't really talk about operationalizing it.  If I had a suggestion, it would be great if there could be a deep dive on some global deployment and how it works.    But in the absence, I can at least reference that one.

Jim.

**Comment by ChackDan** [comment]
Here are a few more resources.. 

https://cloudblogs.microsoft.com/enterprisemobility/2018/06/12/how-we-built-rebuilt-intune-into-a-leading-globally-scaled-cloud-service/
https://blogs.msdn.microsoft.com/azureservicefabric/tag/customer-profile/
https://blogs.msdn.microsoft.com/azureservicefabric/tag/case-study/
https://customers.microsoft.com/en-us/search?sq=%22Azure%20Service%20Fabric%22&ff=&p=0&so=story_publish_date%20desc

**Comment by MikkelHegn** [comment]
I passed on your request to these guys :-) https://www.youtube.com/watch?v=vM5x9kk6ZVY&list=PLlrxD0HtieHh73JryJJ-GWcUtrqpcg2Pb
