### ISSUE TITLE
Error when using custom FabricTransportServiceRemotingProviderAttribute

### ISSUE THREAD

**Issue by antonGritsenko** [Microsoft/service-fabric#161]
Hi all

Service Fabric version: 6.0.219

We using custom FabricTransportServiceRemotingProviderAttribute with the following code:

```
public class ExtendedFabricTransportServiceRemotingProviderAttribute : FabricTransportServiceRemotingProviderAttribute
    {
        /// <summary>
        /// Create custom listener (service side) for Remoting V2 and add <see cref="ExtendedServiceRemotingDispatcher"/> to pipeline
        /// </summary>
        /// <param name="serviceContext"></param>
        /// <param name="serviceImplementation"></param>
        /// <returns></returns>
        public override IServiceRemotingListener CreateServiceRemotingListenerV2(ServiceContext serviceContext, IService serviceImplementation)
        {
            // create our own dispatcher, this will handle adding info to headers
            var messageHandler = new ExtendedServiceRemotingDispatcher(serviceContext, serviceImplementation);

            // note: attributes names remoting for V1 and V2 are NOT the same
            var listner = new FabricTransportServiceRemotingListener(serviceContext: serviceContext, serviceRemotingMessageHandler: messageHandler);

            return (IServiceRemotingListener)listner;
        }

        /// <summary>
        /// Create custom client using <see cref="ExtendedFabricTransportServiceRemotingClientFactory" />
        /// </summary>
        /// <param name="callbackMessageHandler"></param>
        /// <returns></returns>
        public override IServiceRemotingClientFactory CreateServiceRemotingClientFactoryV2(IServiceRemotingCallbackMessageHandler callbackMessageHandler)
        {
            // send default implementation as attribute
            return new ExtendedFabricTransportServiceRemotingClientFactory(base.CreateServiceRemotingClientFactoryV2(callbackMessageHandler));
        }

    }
```

This class defined in shared assembly, when used in same assembly like this:

`[assembly:ExtendedFabricTransportServiceRemotingProviderAttribute(RemotingListener = RemotingListener.V2Listener, RemotingClient = RemotingClient.V2Client)]`

This shared assembly used by 5 different services inside Service Fabric cluster.
Attribute works as expected, no problem here. 

I have issue on my dev machine (and I don't know if it same or not in production, can not check this). On each debug of the cluster (1-node config, 1 service instance per node) lines r`eturn new ExtendedFabricTransportServiceRemotingClientFactory(base.CreateServiceRemotingClientFactoryV2(callbackMessageHandler))` and `var listner = new FabricTransportServiceRemotingListener(serviceContext: serviceContext, serviceRemotingMessageHandler: messageHandler);` throws"silent"
 exception:

> System.ArgumentException
>   HResult=0x80070057
>   Message=An instance of EventSource with Guid cbd93bc2-71e5-4566-b3a7-595d8eeca6e8 already exists.
>   Source=mscorlib
>   StackTrace:
>    at System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized()

The service is always the same, but there is nothing special inside (I think this is just because of services order)

That's all what I have. I did check, the event source with cbd93bc2-71e5-4566-b3a7-595d8eeca6e8
 is Microsoft-ServiceFabric-Events event source (System.Fabric.Common.Tracing.FabricEvents class).

Any thoughts why it can be and how to fix this?

PS Is any official way to raise such bugs? This issue tracker looks a bit abandoned (vacations season?).

**Comment by VipulM-MSFT** [comment]
Please file the issue in this repo: https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues

**Comment by antonGritsenko** [comment]
moved to https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/126
