### ISSUE TITLE
ClusterId in Cluster Manifest on Premise

### ISSUE THREAD

**Issue by vany0114** [microsoft/service-fabric#167]
Hey guys,

I noticed that the `ClusterId` is located in `Paas` section into the cluster manifest when I have the cluster on Azure, like this:
```
<Section Name="Paas">
    <Parameter Name="ClusterId" Value="43ad3924-de4a-4d14-a148-9cb8a7fc97e9" />
</Section>
```

But I have a doubt which is the section name when the cluster is on-premise.

**Comment by VipulM-MSFT** [comment]
@maburlik to comment.

**Comment by craftyhouse** [comment]
Should be the same
