### ISSUE TITLE
Backup restore fails occasionally with `FABRIC_E_RESTORE_IN_PROGRESS` when no restore was started

### ISSUE THREAD

**Issue by darran1971** [microsoft/service-fabric#168]
I have been testing the new Periodic Backup/Restore service with our On-Premise test cluster.
https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-standalonecluster

 I have enabled the Backup Service, and also created Backup profiles, and enabled the backup for an application. This has worked as expected, and I have restored some backups after deleting the service data.

However, I had an issue where I could not restore a particular service, as the error code "FABRIC_E_RESTORE_IN_PROGRESS"  was returned with a message that a "restore is already in progress". I ran the "getRestoreProgress" Api call and it did return the following:

{
     "RestoreState": "Accepted",
     "TimeStampUtc": "0001-01-01T00:00:00Z",
     "RestoredEpoch": {
         "DataLossNumber": "131738809905628409",
         "ConfigurationNumber": "8589934592"
     },
     "RestoredLsn": 54719
 }

I had no idea why this restore was started, and I could not find any way to Cancel this "accepted" restore. So it appeared to be stuck on this status. 

 I tried to remove and re-deploy the service I was trying to restore. However, I found that trying to restore the backup resulted with the same "Restore in progress" error. So yesterday, I removed the backup/restore system service from the cluster, and then re-activated it, which resulted in all the backup API calls returning a (504) gateway error.

I noticed that after I de-activated and then re-activated the Backup/Restore service, it had an ordinary looking partition ID (a6c0a4d8-49f8-4102-8e83-be24c17fb437) . When initially activating the backup service, it had the usual system style partition id such as :00000000-0000-0000-0000-000000007000. After re-activating, all of the Rest API calls to the backup service resulted in a gateway (504) error.

I tried to find a solution to the Gateway (504) error that resulted from re-activating the service but I ended up removing the cluster, and creating it again. I then restored the backups I had made using the backup/restore service.

**Comment by samedder** [comment]
Hey @darran1971, thanks for reporting this can I ask what version of ServiceFabric you have installed?

**Comment by darran1971** [comment]
No problem. The version of ServiceFabric  installed at the time was 6.2.283.9494. I have since upgraded to 6.2.301.9494.

**Comment by aagup** [comment]
@darran1971 Thanks for reporting this. Any restore requested is expected to timeout after a default timeout of 10 mins / timeout stated in request otherwise.  The issue stated above appears to be a restore stuck in progress and for deeper understanding of the issues encountered above it will be great if you can share the logs for the cluster in which issue was encountered.

For sharing the logs you can zip the folder for "FabricLogRoot" which by default is at  C:\SfDevCluster\Log\Traces. If there is some custom logs folder you can query the same by the following command ' reg query "HKLM\SOFTWARE\Microsoft\ServiceFabric" '

We will also like to know the steps followed by you to de activate and re activate the BackupRestore Service so it resulted it to be a ordinary partition Id and not a system service style partition id. 
Backup Restore service is expected to carry a system style partition id and failure in so will result in gateway error as stated .

**Comment by darran1971** [comment]
I have since deleted that cluster and re-created it, so the original logs are lost.
However, I've had the restore in progress error again today (on a new cluster), and it may have coincided with a scheduled backup running when I run the restore.

P.s. The steps I took to deactivate  the backup service were to remove  the following from ClusterConfig properties. 
        "addonFeatures": ["BackupRestoreService"],

Then upgrade the cluster.

Following this, I re-added the above and upgraded the cluster again. At this point the backup/restore service had the non system guid type and returned a 504 error.

I have attached two logs relating to the time I had restore in progress error today (complete folder size was too large to attach here)

[fabric_traces_6.2.301.9494_131751676489217885_29.zip](https://github.com/Microsoft/service-fabric/files/2164023/fabric_traces_6.2.301.9494_131751676489217885_29.zip)
[fabric_traces_6.2.301.9494_131751676489217885_30.zip](https://github.com/Microsoft/service-fabric/files/2164027/fabric_traces_6.2.301.9494_131751676489217885_30.zip)

**Comment by raunakpandya** [comment]
@darran1971 - Given that we don't have logs/ steps here, we aren't able to make progress here. Let me know if you are still hitting this with the latest version.

**Comment by darran1971** [comment]
[SetGlobalMastersBackupPolicy.zip](https://github.com/Microsoft/service-fabric/files/2690006/SetGlobalMastersBackupPolicy.zip)


Hi @raunakpandya,

It would appear I am hitting this issue again.

Following the last issue you investigated, I created the backup policy, and enabled backups using that policy (see attached zip above). However, I noticed that the backups were not being taken. So I tried to run a **manual** backup using the following script:-

```
$StorageInfo = @{
    Path = '\\ukhqbks001\HOBUS$\UATPeriodicBackupStore'
    StorageKind = 'FileShare'
}

$OnDemandBackupRequest = @{
    BackupStorage = $StorageInfo
}

$body = (ConvertTo-Json $OnDemandBackupRequest)

$url = "http://localhost:19080/Partitions/950a0699-19d7-46c0-9e12-8729b372276f/$/Backup?api-version=6.4"
Invoke-WebRequest -Uri $url -UseDefaultCredentials -Method Post -Body $body -ContentType 'application/json'
```

The result was accepted, but still NO backup was generated. So I executed the above script again and I now see the backup in progress error shown below

:
![image](https://user-images.githubusercontent.com/40686134/50147210-752d1f80-02ad-11e9-928c-6b4e0195f492.png)

Here are some logs taken at the time I run the first manual backup using above script (that was accepted)

[e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1358_00636807204718347338_2147483647.dtr.zip](https://github.com/Microsoft/service-fabric/files/2690027/e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1358_00636807204718347338_2147483647.dtr.zip)

[e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1359_00636807205068690422_0000000000.dtr.zip](https://github.com/Microsoft/service-fabric/files/2690030/e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1359_00636807205068690422_0000000000.dtr.zip)

**Comment by raunakpandya** [comment]
Hey, I am assuming the GetBackupProgress API is returning you the state as ACCEPTED even when you query after few minutes right? The logs you shared for were exactly around the time when you invoked the API. Possible for you to share the logs for few minutes post you invoke the API as well? 

Can you also check if the service has access to file share?

**Comment by darran1971** [comment]
Hi @raunakpandya,

Yes, that is correct. it still says accepted after several hours. The service uses the same share for diagnostics logging and that is working fine (File share access granted for the gMSA account credentials and machine accounts).

Here are the logs after a few minutes.
[e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1360_00636807208174476897_0000000000.dtr.zip](https://github.com/Microsoft/service-fabric/files/2690668/e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1360_00636807208174476897_0000000000.dtr.zip)

[e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1359_00636807208009947972_2147483647.dtr.zip](https://github.com/Microsoft/service-fabric/files/2690661/e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1359_00636807208009947972_2147483647.dtr.zip)
[e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1360_00636807211878083506_2147483647.dtr.zip](https://github.com/Microsoft/service-fabric/files/2690663/e8fb74f2cf373516634a3b7ff8f76b65_fabric_traces_6.4.617.9590_131890990982540202_1360_00636807211878083506_2147483647.dtr.zip)

**Comment by aagup** [comment]
@darran1971  Are you still facing this issue ? 
Thanks

**Comment by darran1971** [comment]
Hi @aagup, I haven't seen this error for a while, so I guess it can be closed.

**Comment by aagup** [comment]
@darran1971 Thanks for the update.
