### ISSUE TITLE
How to get the cluster id

### ISSUE THREAD

**Issue by vany0114** [microsoft/service-fabric#170]
Guys, I need a way to get the clusterid, but out of service fabric application, I mean, I have a SF stateless service which installs a windows service on every node, so I need to get the cluster id, from that service, I was thinking to get the `clusterManifest.xml` or `FabricHostSettings.xml` from `D:\SvcFab` but I'm not sure if SF ALWAYS uses that path. Any suggestions?

Thanks in advance!

**Comment by samedder** [comment]
Is this an Azure deployment of Service Fabric? Generally speaking we will try to use `D:\SvcFab` but it is configurable in the Extension settings and may change in the future.

We can consider adding an API to get this programatically from Service Fabric in the future.

**Comment by vany0114** [comment]
Yes it is.

**Comment by samedder** [comment]
So there should always be a file called `ClusterManfiest` in the folder defined by the FabricDataRoot variable. This is configurable by the user when you deploy the cluster, but you can determine it by looking at the registry key under `HKLM\SOFTWARE\Microsoft\Service Fabric`. This defaults to `D:\SvcFab`.

**Comment by samedder** [comment]
Accidental reopen? @craftyhouse is there a reason this was assigned to me?

**Comment by samedder** [comment]
Closing issue as workaround was provided. There is no plan to add support for getting the cluster ID programmatically.
