### ISSUE TITLE
Connecting to my SF via Visual Studio with a port other than 19000

### ISSUE THREAD

**Issue by pk-picturepark** [Microsoft/service-fabric#172]
Hi

In the cluster configuration for a three node, single machine, unsecured on premise cluster (v6.2.283.9494), I changed the default port from 19xxx to 18xxx (see config below).

The publish process in Visual Studio 2017 somehow cannot handle these port changes properly, eventhough the connection endpoint has been adjusted in the publish profiles.

Publishing to the old 19000 endpoint worked flawlessly, but the endpoint on port 18000 won't be recognized at all. However, a connection started directly from powershell seems to work even for the 18000 port.

Is publishing from within Visual Studio somewhat restricted to port 19000? If yes, is there a workaround?

Thx,

Used ClusterConfig

{
	"name": "DEV_Cluster",
	"clusterConfigurationVersion": "1.0.0",
	"apiVersion": "10-2017",
	"nodes": [{
		"nodeName": "node0",
		"iPAddress": "[DEV MACHINE IPADDRESS]",
		"nodeTypeRef": "NodeType0",
		"faultDomain": "fd:/dc1/r0",
		"upgradeDomain": "UD0"
	},
	{
		"nodeName": "node1",
		"iPAddress": "[DEV MACHINE IPADDRESS]",
		"nodeTypeRef": "NodeType1",
		"faultDomain": "fd:/dc2/r0",
		"upgradeDomain": "UD1"
	},
	{
		"nodeName": "node2",
		"iPAddress": "[DEV MACHINE IPADDRESS]",
		"nodeTypeRef": "NodeType2",
		"faultDomain": "fd:/dc3/r0",
		"upgradeDomain": "UD2"
	}],
	"properties": {
		"enableTelemetry": false,
		"fabricClusterAutoupgradeEnabled": false,
		"diagnosticsStore": {
			"metadata": "Please replace the diagnostics file share with an actual file share accessible from all cluster machines. For example, \\\\localhost\\DiagnosticsStore.",
			"dataDeletionAgeInDays": "21",
			"storeType": "FileShare",
			"connectionstring": "D:\\ServiceFabric\\DiagnosticsStore"
		},
		"nodeTypes": [{
			"name": "NodeType0",
			"clientConnectionEndpointPort": "18000",
			"clusterConnectionEndpointPort": "18001",
			"leaseDriverEndpointPort": "18002",
			"serviceConnectionEndpointPort": "18003",
			"httpGatewayEndpointPort": "18080",
			"reverseProxyEndpointPort": "18081",
			"applicationPorts": {
				"startPort": "20001",
				"endPort": "20031"
			},
			"isPrimary": true
		},
		{
			"name": "NodeType1",
			"clientConnectionEndpointPort": "18004",
			"clusterConnectionEndpointPort": "18005",
			"leaseDriverEndpointPort": "18006",
			"serviceConnectionEndpointPort": "18007",
			"httpGatewayEndpointPort": "18082",
			"reverseProxyEndpointPort": "18083",
			"applicationPorts": {
				"startPort": "20288",
				"endPort": "20318"
			},
			"isPrimary": true
		},
		{
			"name": "NodeType2",
			"clientConnectionEndpointPort": "18008",
			"clusterConnectionEndpointPort": "18009",
			"leaseDriverEndpointPort": "18010",
			"serviceConnectionEndpointPort": "18011",
			"httpGatewayEndpointPort": "18084",
			"reverseProxyEndpointPort": "18085",
			"applicationPorts": {
				"startPort": "20575",
				"endPort": "20605"
			},
			"isPrimary": false
		}],
		"fabricSettings": [{
			"name": "Setup",
			"parameters": [{
				"name": "FabricDataRoot",
				"value": "D:\\ServiceFabric\\Cluster"
			},
			{
				"name": "FabricLogRoot",
				"value": "D:\\ServiceFabric\\Log"
			}]
		},
		{
			"name": "Hosting",
			"parameters": [{
				"name": "FabricContainerAppsEnabled",
				"value": "false"
			}]
		}]
	}
}

**Comment by likevi-MSFT** [comment]
@masnider @dkkapur

**Comment by pk-picturepark** [comment]
Just following up. Do you have any input on this issue?

**Comment by pk-picturepark** [comment]
Not sure why, but It works now. Probably fixed with a new VS2017 update.
