### ISSUE TITLE
Get node name when cluster is on-premise

### ISSUE THREAD

**Issue by vany0114** [Microsoft/service-fabric#175]
Hey guys,

I would like to know if there is an easy way to get the node name when I have the cluster on-premise, since my machine could have a different name than the node, let's say the machine name is `machine1` but the node name is `vm1` 

This is related with #170 I need to get the node name outside of SF application. So I noticed that the manifest contains this section when the cluster is on-premise, but I would like to know if is there another way to get it:

```
<Infrastructure>
    <WindowsServer>
      <NodeList>
        <Node NodeName="vm0" IPAddressOrFQDN="10.0.1.4" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc1/r0" UpgradeDomain="UD0" />
        <Node NodeName="vm1" IPAddressOrFQDN="10.0.1.5" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc2/r0" UpgradeDomain="UD1" />
        <Node NodeName="vm2" IPAddressOrFQDN="10.0.1.6" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/dc3/r0" UpgradeDomain="UD2" />
      </NodeList>
    </WindowsServer>
  </Infrastructure>
```

**Comment by samedder** [comment]
Have you tried using the [`NodeContext`](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.nodecontext?view=azure-dotnet) class? You should be able to get the `NodeName` from there.

**Comment by vany0114** [comment]
The point is that I need to get the name out of the SF app, let's say from a console app, is it possible tho?

**Comment by vturecek** [comment]
@vany0114 Yes, the Service Fabric API has a method for that:
[C#](https://docs.microsoft.com/dotnet/api/system.fabric.fabricclient.queryclient.getnodelistasync?view=azure-dotnet)
[CLI](https://docs.microsoft.com/azure/service-fabric/service-fabric-sfctl-node)
[PowerShell](https://docs.microsoft.com/powershell/module/servicefabric/Get-ServiceFabricNode?view=azureservicefabricps)
[HTTP](https://docs.microsoft.com/rest/api/servicefabric/sfclient-api-getnodeinfolist)

**Comment by VipulM-MSFT** [comment]
Closing the issue based on the answers above.
