### ISSUE TITLE
[Question] Is Service Fabric support .NET 4.7.2?

### ISSUE THREAD

**Issue by ifle** [microsoft/service-fabric#186]
Is Service Fabric support .NET 4.7.2?

**Comment by thuru** [comment]
an gray mode answer would be NO.

https://github.com/Azure/service-fabric-issues/issues/412

I ran into this issue, and as discussed downgrading services to .net462 worked.

**Comment by masnider** [comment]
Service Fabric supports this. As far as we understand things the issue people are experiencing is related to the tooling/build process, not to running services. If you are experiencing actual issues with a service built against higher .NET versions not working, please let us know and we'd be happy to take a look.
