### ISSUE TITLE
Start-ServiceFabricClusterConfigurationUpgrade System.Runtime.InteropServices.COMException (-2147017627) AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by EVMartinez** [microsoft/service-fabric#190]
The above error is shown while trying to update the cluster configuration.

Scenario:
Domain Controller 2016 Forest functional Level 2016
1 Service Fabric on premises cluster 5 nodes (security with managed group service account)
Service fabric version 6.3.162.9494
Only 1 .net stateless application with three replicas in this cluster
 
Background
I shutdown the entire cluster then when I started the cluster the FailoverManagerService threw a warning because two of its 5 replicas were inactive. The error pointed out that was unable to open its database after multiple attempts. I found a similar issue in this service fabric github repo but the cause that you pointed out was insufficient disk space. Unfortunately not my case since the servers have 100GB of free disk space.

Since I found no solution (and logs didn't provide any meaningful information) I removed the 2 nodes following the instructions of put the following in the config file
 
{
            "Name": "NodesToBeRemoved",
            "Value": "SF02, SF04"
          }
And removing the nodes also in the config file
The first attempt didn’t work because it says that the certificate can’t be changed (I didn’t know what that means since I’m using MSA as security), the section that caused the conflict is the following:

  "Properties": {
    "Security": {
      "$id": "1",
      "CertificateInformation": {
        "$id": "2"
      },
      "WindowsIdentities": {
        "$id": "3",
        "ClustergMSAIdentity": "SomeDomain\\SomeMSAAAccount",
        "ClusterSPN": "http/FQDNOfMyCluster",
        "ClientIdentities": [
          {
            "IsAdmin": true,
            "Identity": "SomeDomain\\SomeAdmin"
          },
          {
            "IsAdmin": false,
            "Identity": "SomeDomain\\SomeClient"
          }
 
I had to change it to this:
 
 
  "Properties": {
    "Security": {
      "WindowsIdentities": {
        "ClustergMSAIdentity": "SomeDomain\\SomeMSAAAccount",
        "ClusterSPN": "http/FQDNOfMyCluster",
        "ClientIdentities": [
          {
            "IsAdmin": true,
            "Identity": "SomeDomain\\SomeAdmin"
          },
          {
            "IsAdmin": false,
            "Identity": "SomeDomain\\SomeClient"
          }
 
After that, the nodes were successfully removed, leaving the cluster with 3 nodes. Then I deleted the old service fabric C:\Program Data\SF folder and ran the AddNode.ps1 command (with the -windowscredential parameter) in the removed nodes to add them again.

They were successfully added.

Now I try to update the cluster config, removing this part from the current config
 
{
            "Name": "NodesToBeRemoved",
            "Value": "SF02, SF04"
          }
 
And adding the add-on "BackupRestoreService"  If I don’t remove the security properties that I mentioned above, the following error is thrown "The new certificate cannot be added since the authentication type of the cluster cannot be modified" which is odd since this cluster does not use certificates but MSA. If I remove them, I get the error that is the subject of this email. No trace is generated for this error (current level is 4) I took memory dumps of powershell.exe and the 10 different processes of Service Fabric to see the inner exception with no luck. I took a perfview trace to see the inner exceptions, no luck either. I tried in the different forums and github repos, nobody had this error before. I’m out of ideas.
 
Attached is the current config and the new config that I’m trying to apply. If you read until here, I appreciate your time! Do you have any ideas? 

[currentconfig.txt](https://github.com/Microsoft/service-fabric/files/2275237/currentconfig.txt)
[newconfig.txt](https://github.com/Microsoft/service-fabric/files/2275238/newconfig.txt)

**Comment by EVMartinez** [comment]
I'm not, but I was able to reproduce the issue following the same steps above in another cluster, clean install and same results, I can share the logs if you want.

**Comment by EVMartinez** [comment]
This is what I found in the trace file at the moment of trying this operation:

Event Name                    	    Time MSec	Process Name        	Rest  
Microsoft-ServiceFabric/Client	3,262,089.280	Process(3868) (3868)	ThreadID="3,408" id="PowerShell-b0fe4caa-d721-4302-9369-f9b47b46aa58" type="ClientConnectionManager" text="6571f6e1-74fa-4139-a443-97f2b2bd2f92:0: gateway replied with error=FABRIC_E_CONFIG_UPGRADE_FAILED" FormattedMessage="6571f6e1-74fa-4139-a443-97f2b2bd2f92:0: gateway replied with error=FABRIC_E_CONFIG_UPGRADE_FAILED " 
Microsoft-ServiceFabric/Client	3,286,926.413	Process(3868) (3868)	ThreadID="4,708" id="PowerShell-b0fe4caa-d721-4302-9369-f9b47b46aa58" type="ClientConnectionManager" text="8ea6edce-a41d-445a-9dac-6d7db91e4d05:0: gateway replied with error=FABRIC_E_CONFIG_UPGRADE_FAILED" FormattedMessage="8ea6edce-a41d-445a-9dac-6d7db91e4d05:0: gateway replied with error=FABRIC_E_CONFIG_UPGRADE_FAILED " 


Event Name                                	    Time MSec	Process Name        	Rest  
Microsoft-ServiceFabric/EntreeServiceProxy	3,262,088.996	Process(3460) (3460)	ThreadID="3,584" id="[e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192]" type="EntreeServiceProxy.RequestProcessingFailed" text="ProcessClientOperation for action 'ForwardMessage' encountered error FABRIC_E_CONFIG_UPGRADE_FAILED. activity id = 6571f6e1-74fa-4139-a443-97f2b2bd2f92:0" FormattedMessage="ProcessClientOperation for action 'ForwardMessage' encountered error FABRIC_E_CONFIG_UPGRADE_FAILED. activity id = 6571f6e1-74fa-4139-a443-97f2b2bd2f92:0 " 
Microsoft-ServiceFabric/EntreeServiceProxy	3,286,925.556	Process(3460) (3460)	ThreadID="3,576" id="[e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192]" type="EntreeServiceProxy.RequestProcessingFailed" text="ProcessClientOperation for action 'ForwardMessage' encountered error FABRIC_E_CONFIG_UPGRADE_FAILED. activity id = 8ea6edce-a41d-445a-9dac-6d7db91e4d05:0" FormattedMessage="ProcessClientOperation for action 'ForwardMessage' encountered error FABRIC_E_CONFIG_UPGRADE_FAILED. activity id = 8ea6edce-a41d-445a-9dac-6d7db91e4d05:0 " 



Event Name                     	    Time MSec	Process Name        	Rest  
Microsoft-ServiceFabric/Routing	3,262,080.517	Process(2928) (2928)	ThreadID="3,888" id="" type="Complete" text="Routing of message f1673f75-e278-443a-89ed-e6e6ecd29c97:91719(1) header [From: e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192, To: 468bef7e6e2b337868f890a6ad7c9b7a:131788263725511478, MessageId: f1673f75-e278-443a-89ed-e6e6ecd29c97:91719, Expiration: 1:59.999, RetryTimeout: 05.000, UseExactRouting: true, ExpectsReply: true] failed with FABRIC_E_CONFIG_UPGRADE_FAILED" FormattedMessage="Routing of message f1673f75-e278-443a-89ed-e6e6ecd29c97:91719(1) header [From: e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192, To: 468bef7e6e2b337868f890a6ad7c9b7a:131788263725511478, MessageId: f1673f75-e278-443a-89ed-e6e6ecd29c97:91719, Expiration: 1:59.999, RetryTimeout: 05.000, UseExactRouting: true, ExpectsReply: true] failed with FABRIC_E_CONFIG_UPGRADE_FAILED " 
Microsoft-ServiceFabric/Routing	3,286,924.923	Process(2928) (2928)	ThreadID="2,996" id="" type="Complete" text="Routing of message f1673f75-e278-443a-89ed-e6e6ecd29c97:91839(1) header [From: e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192, To: 468bef7e6e2b337868f890a6ad7c9b7a:131788263725511478, MessageId: f1673f75-e278-443a-89ed-e6e6ecd29c97:91839, Expiration: 1:59.999, RetryTimeout: 05.000, UseExactRouting: true, ExpectsReply: true] failed with FABRIC_E_CONFIG_UPGRADE_FAILED" FormattedMessage="Routing of message f1673f75-e278-443a-89ed-e6e6ecd29c97:91839(1) header [From: e70c57902b6e509cd7c27e0d0f0098ff:131788263218828192, To: 468bef7e6e2b337868f890a6ad7c9b7a:131788263725511478, MessageId: f1673f75-e278-443a-89ed-e6e6ecd29c97:91839, Expiration: 1:59.999, RetryTimeout: 05.000, UseExactRouting: true, ExpectsReply: true] failed with FABRIC_E_CONFIG_UPGRADE_FAILED " 


Event Name                          	    Time MSec	Process Name        	Rest  
Microsoft-ServiceFabric/SystemFabric	3,262,123.365	Process(3868) (3868)	ThreadID="3,408" id="" type="UpgradeOrchestrationService.StartClusterConfigurationUpgradeAsync" message="AsyncCalloutAdapter-36610825: end delegate threw an exception System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627) AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65 at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context) at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context) at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously) --- End of inner exception stack trace ---" FormattedMessage="AsyncCalloutAdapter-36610825: end delegate threw an exception System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627) AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65 at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context) at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context) at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously) --- End of inner exception stack trace --- " 
Microsoft-ServiceFabric/SystemFabric	3,286,927.506	Process(3868) (3868)	ThreadID="4,708" id="" type="UpgradeOrchestrationService.StartClusterConfigurationUpgradeAsync" message="AsyncCalloutAdapter-23324256: end delegate threw an exception System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627) AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65 at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context) at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context) at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously) --- End of inner exception stack trace ---" FormattedMessage="AsyncCalloutAdapter-23324256: end delegate threw an exception System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627) AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65 at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeConfiguration(IFabricAsyncOperationContext context) at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context) at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously) --- End of inner exception stack trace --- " 

Attached is the relevant trace file.
[fabric_traces_6.3.162.9494_131788263062175252_3.zip](https://github.com/Microsoft/service-fabric/files/2291513/fabric_traces_6.3.162.9494_131788263062175252_3.zip)

**Comment by jkochhar** [comment]
Sorry for the delay. Please ping me AT jkochhar AT microsoft DOT com.

**Comment by cdonovan63** [comment]
Has there been any progress on this issue.  I fought with it over the weekend through yesterday.  I finally wiped out the cluster and re-created it from scratch.

- I've got a cluster config file checked into source control that I used to create my initial cluster and make any changes to it.  
- I followed the instructions at this link to remove a node from the cluster for some hardware maintenance: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes#remove-nodes-from-your-cluster
- When I tried to add the node back in, I used the AddNode.ps1 script to add it back in successfully
- When I ran Start-ServiceFabricClusterConfigurationUpgrade I received the same COMException and AggregateException.

So I really would like to hear if there is any resolution to this before we deliver this solution to a customer.  I don't want to tell them they have to re-create the cluster every time they need to do maintenance on a node.

**Comment by maburlik** [comment]
Regarding the error "The new certificate cannot be added since the authentication type of the cluster cannot be modified" this issue has been fixed as of 7.0 CU4.

With the target release of 7.2 changes have been made to rework the way upgrades are managed in FabricUOS to ensure better state consistency, improve internal retries, and to provide considerably better transparency into errors encountered during the initial and ongoing processing of upgrades. The internal aggregate exception you are hitting should produce a more explicit error in the next release.

Unfortunately the only way to investigate the inner errors with the current latest release of 7.1 is to send us the fabric etl logs from the node running FabricUOS primary.

I'm closing this issue for now since the original issue is likely not consistent with the latest issue encountered by @cdonovan63 but feel free to start another thread if you are still hitting issues. You can use the standalone log uploader tool bundled in the standalone cluster package to package up the relevant logs.
