### ISSUE TITLE
 ActorProxy.Create() doesn't consider [ActorServiceAttribute], infers service name from actor name

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/service-fabric#198]
I have a statefull service which I try to convert to an agent service to leverage the built-in scheduling mechanism.

The service is called AgentService and the actor is called HeartbeatActor.

When I'm making this call:

```c#
ActorRuntime.RegisterActorAsync<HeartbeatActor>(
    (serviceContext, agentType) => new AgentService(serviceContext, agentType))
            .GetAwaiter()
            .GetResult();
```

I'm getting this exception:

>System.Fabric.FabricException: 'Invalid Service Type'
>Inner Exception: COMException: Exception from HRESULT: 0x80071C21

`ActorRuntime.RegisterActorAsync` uses `ActorNameFormat.GetActorServiceName()` which looks for `{0}Service` by default but luckily can be overridden by  `[ActorServiceAttribute]`. So far so good.

Then I try to activate my actor to schedule it:

```c#
protected override async Task RunAsync(CancellationToken cancellationToken)
{
    var proxy = ActorProxy.Create<IHeartbeatActor>(new ActorId(typeof(AgentActor).FullName));
    await proxy.Activate();
}
```

but I'm getting this exception:

>Service does not exist.
>Inner Exception: COMException: Exception from HRESULT: 0x80071BCD

If I specify service url explicitly:

```c#
var proxy = ActorProxy.Create<IHeartbeatActor>(new ActorId(typeof(AgentActor).FullName), this.Context.ServiceName);
await proxy.Activate();
```
Then the exception is this:

>Invalid partition key/ID '{0}'  for selector {1}
>Inner Exception: COMException: Exception from HRESULT: 0x80071BBF

These exceptions happen in turn because `ActorProxy.Create()` uses `ActorNameFormat.GetFabricServiceName()` which doesn't support `[ActorServiceAttribute]` or any other way to customize its behavior and always looks for ` {0}Service`.

Do I understand the issue correctly? Is this something you could improve?

**Comment by abatishchev** [comment]
Ping?

**Comment by VipulM-MSFT** [comment]
@abatishchev - please let us know if this solves the issue. If so, feel free to close the issue.

**Comment by abatishchev** [comment]
Let me try to specify both application and service name.

**Comment by VipulM-MSFT** [comment]
@abatishchev - did this resolve the issue? If so, please feel free to close it.

**Comment by abatishchev** [comment]
Oh, sorry, thanks!
