### ISSUE TITLE
Permanent Error loop while adding BackupRestoreService: Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on Node. API call: IStatefulServiceReplica.ChangeRole(P)

### ISSUE THREAD

**Issue by EVMartinez** [Microsoft/service-fabric#199]
Configuration
On-Premises SF Cluster 5 Nodes
Ver.  6.3.162.9494

While trying to add the feature BackupRestoreService Service Fabric is trying to build the replica in one node. After a while, I got the following exception:

  | Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on SF05. API call: IStatefulServiceReplica.ChangeRole(P); Error = System.Reflection.TargetInvocationException (-2146232828) Exception has been thrown by the target of an invocation.    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)    at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)    at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)    at System.Fabric.BackupRestore.BackupRestoreEndPoints.OwinHttpServer.StartOwinHttpServer(String listenAddress)    at System.Fabric.BackupRestore.Service.OwinCommunicationListener.OpenAsync(CancellationToken cancellationToken)    at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__27.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__18.MoveNext() For more information see: http://aka.ms/sfhealth

Then Service Fabric goes to another node trying to build de replica, with the same result. Inside the traces I got exceptions like the following:

ThreadID="832" contextSequenceId="-6,911" fuDescid="00000000-0000-0000-0000-000000007000" fuDescpcEpochdataLossVersion="131,790,874,096,992,537" fuDescpcEpochconfigVersion="4,294,967,297" fuDescccEpochdataLossVersion="131,790,874,096,992,537" fuDescccEpochconfigVersion="8,589,934,594" contextSequenceId_localReplicaDesc="-6,655" contextSequenceId_remoteReplicas="-6,400" flags="-" proxyErrorCodeerrorCodeval="-2,146,232,828" proxyErrorCodeapiinterface="IStatefulServiceReplica" proxyErrorCodeapiapi="ChangeRole" proxyErrorCodeapimetadata="P" proxyErrorCodemessage="System.Reflection.TargetInvocationException (-2146232828) Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder) at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context) at System.Fabric.BackupRestore.BackupRestoreEndPoints.OwinHttpServer.StartOwinHttpServer(String listenAddress) at System.Fabric.BackupRestore.Service.OwinCommunicationListener.OpenAsync(CancellationToken cancellationToken) at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<OpenCommunicationListenersAsync>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<System-Fabric-IStatefulServiceReplica-ChangeRoleAsync>d__18.MoveNext()" FormattedMessage="00000000-0000-0000-0000-000000007000 131,790,874,096,992,537:4,294,967,297/131,790,874,096,992,537:8,589,934,594 -6,655-6,400State: -. EC: -2,146,232,828:IStatefulServiceReplica.ChangeRole(P) 'System.Reflection.TargetInvocationException (-2146232828) Exception has been thrown by the target of an invocation. at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder) at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context) at System.Fabric.BackupRestore.BackupRestoreEndPoints.OwinHttpServer.StartOwinHttpServer(String listenAddress) at System.Fabric.BackupRestore.Service.OwinCommunicationListener.OpenAsync(CancellationToken cancellationToken) at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<OpenCommunicationListenersAsync>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<System-Fabric-IStatefulServiceReplica-ChangeRoleAsync>d__18.MoveNext()' " 

The servers do have communication between them and all other services are fine, do you have any ideas where to look?

Thanks in advance.
[fabric_traces_6.3.162.9494_131790842813386742_2.zip](https://github.com/Microsoft/service-fabric/files/2299787/fabric_traces_6.3.162.9494_131790842813386742_2.zip)

**Comment by VipulM-MSFT** [comment]
@raunakpandya and @hrushib - can you please check?

**Comment by hrushib** [comment]
@EVMartinez sorry for delayed response. Had a look at the logs and it looks like BackupRestore service is failing to start listening on `http://+:20575/` with Access denied error.

```
Failed to start Owin Http Server with exception
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Access is denied
	at System.Net.HttpListener.AddAllPrefixes()
	at System.Net.HttpListener.Start()
	at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
	at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
	   --- End of inner exception stack trace ---
	at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
	at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
	at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
	at System.Fabric.BackupRestore.BackupRestoreEndPoints.OwinHttpServer.StartOwinHttpServer(String listenAddress)
```

In case you are still facing this issue, then 
1. Attach cluster manifest file you are using to create/upgrade this cluster.
2. Run `netstat -a -b` command from admin command prompt to see if there is any other service already listening on the above port.

**Comment by EVMartinez** [comment]
Hello @hrushib thank you for taking the time to review this issue. Yes, we've reviewed if another process was using the port, but no, no other process was using that port. After some troubleshooting we decided to re-create the cluster, I'm going to close this issue.
