### ISSUE TITLE
Linux service fabric

### ISSUE THREAD

**Issue by anlem12** [Microsoft/service-fabric#203]
When will you provide Linux individual installation files? Can the current version of Linux be used in a formal environment?

**Comment by suhuruli** [comment]
@dkkapur

**Comment by tastyeggs** [comment]
Any updates on this? I feel like we're so close to getting this working *truly everywhere*, yet has been deprioritized for well over a year after the initial "going SF is supported on Linux" announcement.

Is the Service Fabric team serious about having SF truly run everywhere? Or is the plan simply to focus on Azure and Windows Server? Either way, we would greatly appreciate if you can make your stance on this clear.

**Comment by suhuruli** [comment]
Hi @tastyeggs and @anlem12 , 

Service Fabric Ubuntu clusters on-premise can be deployed on-premise (VMWare) through the work we recently did with Bosh: https://github.com/starkandwayne/azure-service-fabric-boshrelease. This is a complete open source method to easily deploy and manage Service Fabric Linux clusters on-premise. Look for the blog posts around this early December :)

**Comment by suhuruli** [comment]
@Pothulapati , thought you would also be interested in the above

**Comment by dkkapur** [comment]
@tastyeggs @anlem12 were you able to give the BOSH provider a shot? If not - please reopen the issue and give me a little more context on the scenario and scope of your respective deployments. Would love to learn more about the use case for this and see if there's anything I can suggest as options that exist today.
