### ISSUE TITLE
Service Fabric code package gets duplicated while we deploy them and causing node failure

### ISSUE THREAD

**Issue by sandy060583** [Microsoft/service-fabric#208]
Recently since last two days we are facing issue when we deploy service fabric code package - it gets duplicated while we deploy them and causing node failures.

See the error screen for reference. I am not sure how to resolve this issue. we are facing this issue on our DEV/QA Cluster since last 2 days. Not able to understand why it causing service failure. 

![node-failure-code-package-duplicate](https://user-images.githubusercontent.com/24560081/44785894-159cee00-abb0-11e8-8250-c451d56b3f2a.PNG)

**Comment by VipulM-MSFT** [comment]
Did you enable "Exclusive Process Model" by mistake? 

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-hosting-model

**Comment by sandy060583** [comment]
But this issue we are facing recently when we added new application type  - ecommerce into the service fabric cluster. before this application type XYZ.Api was wroking fine with ServicePackageActivationMode="ExclusiveProcess". why since we added new application into cluster it gives this issue? any specific reason behind it?

**Comment by VipulM-MSFT** [comment]
The exclusive process always results in additional processes for hosting different replicas. It is possible that total number of partitions you have for the services in this package is higher than the number of nodes. Note that if you use exclusive process, during the upgrade it is possible that more than one partitions are placed on the node and you would end up with more than one package and process activation on a node.
