### ISSUE TITLE
Secure cluster with Active Directory running on Windows Server 2003

### ISSUE THREAD

**Issue by framgeld** [Microsoft/service-fabric#21]
Hi,

The following page states that Service Fabric secure clusters are secured using either group-managed service accounts or machine groups.

> https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security

Our AD controllers are running Windows Server 2003, and upgrading these is not an option.

What is the correct way to create a secured Service Fabric cluster using a Windows Server 2003 AD?

**Comment by anmolah** [comment]
@rishirsinha, do we support windows server 2003 for standalone? I think not

**Comment by framgeld** [comment]
@anmolah @rishirsinha I understand that Service Fabric won't install on Windows Server 2003. My query was whether it can be secured using Windows accounts on a Windows Server 2003 Active Directory.

**Comment by anmolah** [comment]
@framgeld, sorry I misunderstood the question. @rishirsinha will be able to point to the right resource who can confirm/deny.

**Comment by rishirsinha** [comment]
AD support for windows security was added so as to reduce the complexity of managing a secure cluster compared to a cluster secured with certificates. We found that without GMSA that was not necessarily the case. Specially with the new Common Name + Issuer store in for certificate management anything through AD is atleast as painful with cert management. Hence we completely moved away for AD support for anything but GMSA.

Our recommendation is to either use GMSA or use certificate security. I am assuming only your AD nodes have 2003 issue and hence you do not have GMSA. Hence the recommendation is to use certificate based security.

**Comment by guhuajun** [comment]
Greetings, 

You should contact your domain administrators to upgrade domain controllers to supported version.

**Comment by rishirsinha** [comment]
@framgeld If the information above is not sufficient let me know. If things look good, please close the issue.

**Comment by framgeld** [comment]
@rishirsinha Thank you for the information.

From what I have read, the different ways to secure the cluster (gMSA vs Windows Security vs X.509 Certificates) appears to be implemented to allow easier management of the cluster. Is this the case?

Are there any security risks associated with securing the cluster using X.509 Certificates instead of gMSA, or is the difference purely "gMSA is easier to maintain"?

**Comment by rishirsinha** [comment]
Both provide security using different mechanisms, but the level of secuirty is the same.

**Comment by framgeld** [comment]
@rishirsinha Thank you for the confirmation and the information provided. It is extremely helpful.

The recommendation in your documentation for securing a Service Fabric cluster is different to your recommendation. Is there any chance the documentation can be updated to reflect your recommendations?

https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-cluster-security#security-recommendations

> For standalone Windows Server clusters, if you have Windows Server 2012 R2 and Windows Active Directory, we recommend that you use Windows security with group Managed Service Accounts. Otherwise, **use Windows security with Windows accounts**.

Also, the same paragraph (to me, at least), indicated Windows Server 2012 R2 for Service Fabric, and ANY Windows Active Directory. This would be clearer if it indicated that the Active Directory needs to be running on Windows Server 2012 R2 in order to use group-managed service accounts. While this may be clear to Active Directory administrators, it was not apparent to myself (a developer).

Thank you for considering my recommendation.

**Comment by framgeld** [comment]
One final question (I hope) regarding the X.509 security: do we need to generate a unique server X.509 certificate for **each node**, or do we need to generate a single server X.509 certificate that we can apply to all of the nodes?

**Comment by framgeld** [comment]
@rishirsinha Does that mean we will need to generate a new certificate each time we add a new node... and then put that new certificate onto all the other nodes?

**Comment by rishirsinha** [comment]
You do not need to. The issue that will happen will the client will complain about the fact that domain name of the server and certificate do not match. In browsers you can override that for SFX. If you are using our client tools, you can explicitly specify the server cert and we will validate.

**Comment by framgeld** [comment]
So we should be able to generate once and apply to new nodes when they come online... this is good. When we configure the node-to-node security, and the nodes are talking to each other (e.g. Service Remoting v2), that won't be affected by the domain names not matching?

Also, if the cluster is secured via X.509 certificates for node-to-node security... will that affect my WCF client that resides outside the cluster (but on the same domain)?

My WCF client is invoked from an ASP.NET website (server-side), and I have used **NetTcpBinding** with transport-level Windows authentication (it doesn't ask me for credentials, so I assume it is picking the credentials up from the host process). My WCF listener is only accessed by WCF clients on the local intranet.
