### ISSUE TITLE
Publish issue in Local Cluster

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [microsoft/service-fabric#211]
Hi Team, 

We created a Service Fabric application which contains following specification:
1. Gateway service
2. Stateful Service to store Reliable collection data

We are able to publish the application in Debug mode, but when we try to publish the services are getting failed.  

Thanks Prabhuji

**Comment by suhuruli** [comment]
Can you share the error message that it is failing with?

**Comment by maburlik** [comment]
This thread has not seen a reply so am closing this for now. Feel free to open another thread if you are still hitting issues.
