### ISSUE TITLE
Fabric.exe crash

### ISSUE THREAD

**Issue by jvenema** [Microsoft/service-fabric#212]
Hey all,

I'm getting a crash starting up Fabric.exe after a completely clean install of all the services. This causes various other errors (Connect-ServiceFabricCluster : The object is closed, Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS
issue, etc), but I believe the root problem is that Fabric is just not running. Any insights on why that might happen? The crash log is pretty indicative, but says nothing about *what* ip address they're talking about or where to find it.

In the app fabric event log I see:

Throwing coding error - Supplied ip address is invalid: <IPorFullyQualifiedDomainName>:<Port> Symbol paths: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;;
Symbol loading time: 00.100
Stack trace:
    00007ff6:abde33c8( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd9ccc6( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd9cc1b( windows_error(487): Attempt to access invalid address.  )
    00007ff6:ac7edc4e( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd59256( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd70c30( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd64b0d( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd64b6c( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abdcb820( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd52f82( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd633d6( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd4d012( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd504ea( windows_error(487): Attempt to access invalid address.  )
    00007ff6:abd9d7b7( windows_error(487): Attempt to access invalid address.  )
    RtlAcquireSRWLockExclusive + 0x40c
    RtlReleaseSRWLockExclusive + 0x739
    BaseThreadInitThunk + 0x14

In the application event log, I see:

Faulting application name: Fabric.exe, version: 6.3.176.9494, time stamp: 0x5b6e5929
Faulting module name: Fabric.exe, version: 6.3.176.9494, time stamp: 0x5b6e5929
Exception code: 0xc0000602
Fault offset: 0x000000000012cded
Faulting process id: 0x54a4
Faulting application start time: 0x01d4414f7a7dee04
Faulting application path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Fabric.exe
Faulting module path: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\Fabric.exe
Report Id: 680f8016-2037-4085-b724-ec0893636f12
Faulting package full name: 
Faulting package-relative application ID:

**Comment by VipulM-MSFT** [comment]
@jvenema - do you still have this issue? Have you tried resetting your local cluster?

**Comment by VipulM-MSFT** [comment]
@jvenema - if this is resolved for you, please feel free to close the issue.

**Comment by VipulM-MSFT** [comment]
Closing the issue - if you still have the issue, please feel free to reopen with repro / additional information for us to investigate.
