### ISSUE TITLE
Environment variable Fabric_ServiceName returns "incorrect" value

### ISSUE THREAD

**Issue by toresenneseth** [Microsoft/service-fabric#213]
Hi,

I'm hosting a service as a Guest Executable, and the environment variable Fabric_ServiceName returns fabric:/[ApplicationName]/[ServiceName] instead of just the service name. According to the docs, Fabric_ServiceName should return just the service name. I guess this is an error in the docs, but can you confirm this?
I'm seeing this on a local cluster running version 6.3.176.9494, SDK version 3.2.179.9494.

-Thanks

**Comment by EVMartinez** [comment]
Hello @toresenneseth did you create your guest executable with ServicePackageActivationMode ExclusiveProcess?

**Comment by VipulM-MSFT** [comment]
@harahma, @gkhanna79 to take a look.

**Comment by toresenneseth** [comment]
Yes, I'm using ExclusiveProcess. Here's my config:
```
<Service Name="Worker" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="WorkerType" InstanceCount="[Worker_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
</Service>
```

**Comment by VipulM-MSFT** [comment]
Can you include the link to the doc?

**Comment by toresenneseth** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-environment-variables-reference

**Comment by grzuber** [comment]
@toresenneseth yes I can confirm that it does return the full service name uri (fabric:/[ApplicationName]/[ServiceName], like you said). Thanks for making this issue! I'm working on changing the documentation to reflect the correct behavior.

**Comment by harahma** [comment]
We should fix the documentation. Full service name is fine as this is what they will see in the SFX.

Sent from my phone

________________________________

**Comment by grzuber** [comment]
The documentation should now be fixed -- @samedder can you close this issue as resolved?
