### ISSUE TITLE
Service Fabric Stateless server and client complete sample

### ISSUE THREAD

**Issue by MyoMinLin** [Microsoft/service-fabric#215]
Hi guys,
Azure Service Fabric is totally new for me.
I am still struggling to test the code from following link.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication

I can run default stateless code.
I am trying to implement TCP client and server communication.
But I don't know it's is same project or another project for client.

With Regards,
Lin

**Comment by VipulM-MSFT** [comment]
Please take a look at the getting started sample https://azure.microsoft.com/en-us/resources/samples/service-fabric-dotnet-getting-started/
