### ISSUE TITLE
missing windows component on sf cluster

### ISSUE THREAD

**Issue by gofrogi** [microsoft/service-fabric#220]
i developed a .net service with c++ native components, those are using gulp32.dll, opengl32.dll and msvfw32.dll. After deployment on SF with virtual machine image "WindowsServerSemiAnnual Datacenter-Cor-1709" the service doesn't run because of missing opengll dlls and msftw32.dll. My question is how to proceed in this case and howto add the missing components?

**Comment by maburlik** [comment]
This is an old thread and I imagine the context is no longer relevant, but for others hitting similar issues the thing to make sure is that the dlls are bundled in the application package and remain co-located at the service activation path in the data root. If you depend on the dlls being present at the global machine scope just make sure this doesn't conflict against other versions of the dlls also made available through PATH. You can run as the service executing user from the service directory to determine whether you are hitting a versioning conflict which often manifests as a dll not found error:
> where msftw32.dll

Feel free to create another thread if you are still hitting issues.
