### ISSUE TITLE
Incorrect PATH passed to SF apps

### ISSUE THREAD

**Issue by daviddob** [microsoft/service-fabric#222]
I raised this issue in Azure/service-fabric-issues#1246 after finding a thread there while debugging java SF applications with openjdk installed in a custom path. As described in the other thread, the path given to entrypoint.sh `/data/service-fabric/sfcluster/data/_Node_4/Fabric/Fabric.Code;/var/vcap/packages/openjdk/bin:/more/stuff/here` - has a `;` in the path that concatenates that which is passed to the Fabric process and that added by SF. This should instead be a `:` instead, as the `;` breaks the path and causes the first entry to parse incorrectly thus causing the app itself to fail.

I believe the offending line can be found here: https://github.com/Microsoft/service-fabric/blob/9a8ddc7a638577dbcc8f5b95132e54c3434f958e/src/prod/src/Hosting2/ApplicationHostProxy.cpp#L429-L434

**Comment by maburlik** [comment]
@deepakjangid-MSFT @BharatNarasimman Can you take a look?

**Comment by VipulM-MSFT** [comment]
Thank you for reporting, yes this is a bug. It is unfortunate that we missed this. We will try to get this fix as soon as possible.

**Comment by gkhanna79** [comment]
@daviddob the issue has been fixed for our next release (6.4). We will also look into the feasibility of getting the fix in for the next CU of 6.3.

**Comment by daviddob** [comment]
Wonderful, thanks.

**Comment by gkhanna79** [comment]
@daviddob We have fixed this for next CU of 6.3 as well. Let me know if this issue can be closed.

**Comment by maburlik** [comment]
In addition to the issue discussed here, further improvements have been made since 2018 including trimming duplicate paths and resolving a issue where some paths were being omitted when activating services with RunAs constraints.
