### ISSUE TITLE
Temp directory paths are not correctly set

### ISSUE THREAD

**Issue by daviddob** [Microsoft/service-fabric#223]
When the temp directories are being set `TMPDIR` and `TMP_DIR` are not being set. https://github.com/Microsoft/service-fabric/blob/9a8ddc7a638577dbcc8f5b95132e54c3434f958e/src/prod/src/Hosting2/ApplicationHostProxy.cpp#L422-L424

According to the dotnet issue here: dotnet/corefx#13710, the Path.GetTempPath() reads from `TMPDIR` - so calls made in several of the QuickStart examples will not properly write to the temp space allocated to them. I believe this should match `Fabric_Folder_App_Temp` variable that is set (but often goes unused in the example apps).

**Comment by suhuruli** [comment]
@BharatNarasimman @gkhanna79  any update on this?

**Comment by gkhanna79** [comment]
@daviddob The envvars being setup above are already being set to the application specific temp folders. That said, I think your point is to include TMPDIR to be set as well (on Linux) which we will look into making.

However, I don't see TMP_DIR being referred to the .NET Core issue you referenced.

**Comment by gkhanna79** [comment]
@grzuber Please look into making this fix.

**Comment by daviddob** [comment]
@gkhanna79 That is correct, on linux TMPDIR needs to be set. TMP_DIR is also used in some cases depending on the flavor (but less widely when compared to TMPDIR)

**Comment by gkhanna79** [comment]
Thanks @daviddob - we will look into this.

**Comment by shsha-msft** [comment]
@daviddob thanks for reporting this issue. We have fixed this issue (we now set TMPDIR on Linux).
The fix should be part of the next release of Service Fabric Runtime.
