### ISSUE TITLE
Local cluster not starting

### ISSUE THREAD

**Issue by fleed** [microsoft/service-fabric#255]
My development local cluster doesn't start properly after the startup of the machine.

I must reset it and add again all applications, which is very annoying.

How could I fix it / reinstall the local cluster?

I'm using version `6.3.187.9494`

**Comment by raunakpandya** [comment]
@fleed - Is this still an issue?

**Comment by fleed** [comment]
In general the local cluster is often giving me problems, but here I cannot provide more information.
I will reopen the bug if I can provide useful information.
