### ISSUE TITLE
IFabricSecretStoreClient Invalid cast exception thrown

### ISSUE THREAD

**Issue by davebally** [Microsoft/service-fabric#262]
Hi , ive updated the service fabric libraries from 6.3187 to 6.4.617 (as shown below) and am now getting the below exception thrown.  This is when i try to instantiate a new FabricClient() object.

The code itself is in a .net standard library used within a .net core 2.2 application.
I have seen similar oddities where mixed versions are used but everything seems to be in line here.

Any clues ?!!?

Thanks

Prior : 
`
 <PackageReference Include="Microsoft.ServiceFabric" Version="6.3.187" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.2.187" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="3.2.187" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="3.2.187" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.2.187" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="3.2.187" />
`

Post : 

`    <PackageReference Include="Microsoft.ServiceFabric" Version="6.4.617" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.3.617" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" Version="3.3.617" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="3.3.617" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.3.617" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="3.3.617" />
`

Exception Text
`Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricSecretStoreClient'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{38C4C723-3815-49D8-BDF2-68BFB536B8C9}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
`

Stack trace
`
   at System.Fabric.FabricClient.CreateNativeClient(IEnumerable``1 connectionStringsLocal)
   at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func``1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke(Action action, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA(Action action)
   at System.Fabric.FabricClient.InitializeFabricClient(SecurityCredentials credentialArg, FabricClientSettings newSettings, String[] hostEndpointsArg)
`

**Comment by guibirow** [comment]
Have you updated the Cluster and SDK as well? 

Not sure what the problem is in here, but the new libraries targeting an old cluster might cause these kind of issues.

**Comment by davebally** [comment]
@guibirow Seems to have been the issue, downloaded local SDK ( its a single node dev cluster ) and all now seems well.
