### ISSUE TITLE
Service Fabric setup dogfood

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#265]
Every time I upgrade the Service Fabric SDK, I get prompted to shutdown the local cluster manager. Seriously guys, how lazy is that? So I need to navigate to the task bar, right click the SF icon, select shutdown, and then it pops up a confirmation prompt BEHIND the installation dialog. So now I have to find the hidden dialog, select yes, and then click the OK on the installation dialog.

How is it that NOBODY on the Service Fabric team has said, "guys this is embarrassing, fix that YESTERDAY"?

Here's how it should work. "Service Fabric needs to shutdown the cluster manager to complete the install. Click yes to continue." BOOM. That's it. What'll that take, about 25 lines of code?

**Comment by johnduhart** [comment]
@jackbond Please take a minute to review the [Microsoft Open Source CoC](https://opensource.microsoft.com/codeofconduct/) if you haven't already.

**Comment by raunakpandya** [comment]
@jackbond - We acknowledge the cleanup (and hence upgrade) experience of the SDKs has some usability issues and we are working on addressing a lot of them in the next release. The current experience can definitely be improved.

**Comment by shacal** [comment]
@jackbond manually upgrading several machines, is already something that you should not do and is just waste use of popups?

**Comment by anantshankar17** [comment]
With the latest CU release (sdk ver 3.3.658), the prompts will not collide.
