### ISSUE TITLE
Backup Restore service fails to come up on standalone cluster secure with gMSA authentication

### ISSUE THREAD

**Issue by raunakpandya** [Microsoft/service-fabric#267]
On SF v6.4, Backup Restore service crashes when enabled on standalone cluster which is secured with gMSA account. 

Reference - MicrosoftDocs/azure-docs#19950

**Comment by raunakpandya** [comment]
This has been fixed in the latest refresh - https://blogs.msdn.microsoft.com/azureservicefabric/2019/02/04/azure-service-fabric-6-4-refresh-release/

**Comment by darran1971** [comment]
Hi raunakpandya,

I have Upgraded my cluster to the latest refresh release, However, this resulted in all instances of the existing BackupRestore service failing on every node. The service tries to start on random nodes, but never gets passed "InBuild". I've checked the logs and it points to a null reference in main on the BRS service. 
I have tried to remove the BackupService via the Configuration Upgrade, but it remained on the cluster (still in error) after the upgrade completed.

**Comment by raunakpandya** [comment]
Hey Darran, can you please log in a new issue for this one? From what version to what version did you upgrade?

**Comment by aagup** [comment]
Hello Darran ,

Can you please share the logs and cluster manifest file for the cluster ?

**Comment by darran1971** [comment]
Hi raunakpandya, aagup,
I upgraded from version 6.4.617.9590 to 6.4.637.9590.
I had the BRS running on gMSA authentication on version 6.4.617.9590. So when I updated to 6.4.637.9590, the FabricBRSSetup.exe crashed on each node, with a nullexception error. The only way I could get the FabricBRSSetup.exe to run on my cluster after upgrading to 6.4.637.9590 was to swap the BRS code package from the previous version "MicrosoftAzureServiceFabric.6.4.617.9590.cab\bin\Fabric\Fabric.Code\__FabricSystem_App4294967295\BRS.Code.Current"

When I did this,  the service was successfully launched on the Nodes again and the BackupRestoreService came out of error state.

So, this appears to be an issue with the new FabricBRSSetup.exe crashing when executed. I can't see any other details in the service fabric logs.

**Comment by aagup** [comment]
Thanks for patience and contribution in work around.

Can you please share the output from the primary node of the FabricBRS Service for the list or urlacl's
netsh http  show urlacl

I will request you to kindly share the traces for the cluster as it will help in root causing the issue.

**Comment by darran1971** [comment]
Hi aagup,
