### ISSUE TITLE
NUGET DLLs missing since latest update

### ISSUE THREAD

**Issue by Mortana89** [Microsoft/service-fabric#271]
Since the .622 update I'm facing issues in nuget packages that don't seem to be deployed to ASF. I set up console redirection and saw it is falling to resolve dependencies for various dlls that come from nuget packages. Diving into thé local cluster seems to tell me these dlls are missing. Could this be related?

**Comment by v-mnagar** [comment]
@Mortana89  which dlls are missing?

**Comment by Mortana89** [comment]
Hi,

All the nuget DLLs. I have dependencies like autofac, fluentvalidation, etc.

Upon deploying I can see in the logs that it states that dll xxx can not be loaded from program.deps.json.
This happened after the upgrade from the previous version.
The only reason I upgraded was because I was facing a COM error when trying to configure HTTPS bindings in Kestrel using ASP.net core...
________________________________

**Comment by Mortana89** [comment]
Hi,

Sorry if I made this not clear.
It's not the service fabric DLLs that are missing, but my actual dependencies are missing...

**Comment by suchiagicha** [comment]
@Mortana89 
Could you provide more detailed on what changes you made ?  How you update to .622 release?
We don't own those dll's . My guess is you might have changed the package version for the non-service fabric dll also?

**Comment by Mortana89** [comment]
I only updated thé asf DLLs using the nuget package manager. And then Is downloaded the latest sdk and Ran the web PI installer
________________________________

**Comment by Mortana89** [comment]
Small update from my side; I removed the ASF SDK, and removed the VS Redist 2017 package. After a reboot, and reinstall, the services are now again able to find their dependencies!
