### ISSUE TITLE
could not enable periodic backup with policy

### ISSUE THREAD

**Issue by santo2** [Microsoft/service-fabric#283]
I want to enable periodic backup for a couple of my services, but after following documentation we are not getting any backups.

- the version of our SF:  6.4.622.9590
- I followed https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster
- Policy has been created successfully, I can confirm that it's existing when I execute GET /BackupRestore/BackupPolicies?api-version=6.4

`
$body = '{
       "Name": "ServiceFabricBackupPolicy",
       "AutoRestoreOnDataLoss": false,
       "MaxIncrementalBackups": "3",
       "Schedule": {
         "ScheduleKind": "TimeBased",
         "ScheduleFrequencyType": "Daily",
         "RunTimes": [
           "0001-01-01T09:00:00Z",
           "0001-01-01T17:00:00Z"
         ]
       },
       "Storage": {
         "StorageKind": "AzureBlobStore",
         "FriendlyName": "Azure_storagesample",
         "ConnectionString": "xxx",
         "ContainerName": "BackupContainer"
       },
       "RetentionPolicy": {
         "RetentionPolicyType": "Basic",
         "MinimumNumberOfBackups": "20",
         "RetentionDuration": "P20D"
       }
     }'
`

- Backup is enabled on 2 applications without receiving exceptions
- when I execute endpoint  "GetBackupEnabledEntities", I get the following exception

`
<ExceptionMessage>
Type 'System.Fabric.BackupRestore.BackupRestoreTypes.ApplicationBackupEntity' with data contract name 'ApplicationBackupEntity:http://schemas.datacontract.org/2004/07/System.Fabric.BackupRestore.BackupRestoreTypes' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.
</ExceptionMessage>
<ExceptionType>
System.Runtime.Serialization.SerializationException
</ExceptionType>
<StackTrace>
`
- I don't see any information on the services themselves, as described in documentation
- I don't see the blob container being created
- "GetBackups" endpoint gives the following error:

`
"Error": {
"Code": "E_INVALIDARG",
"Message": "Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index"
}
`

**Comment by tijntje** [comment]
Any Updates on this? I'm facing the same problem.

**Comment by aagup** [comment]
Hello @tijntje  / @santo2 Can you please share the resource ID for the cluster where the above error is being reported. I will also request you to try other backup policy flavors.

Can you please also try with container name in lower letters

**Comment by hrushib** [comment]
@tijntje, @santo2 
The above mentioned error occurs when the container named used for storing backups doesn't comply with container naming rules. So please update the container name in the above backup policy to comply with [container naming rules](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata).

**Comment by tijntje** [comment]
I tried with following policy:    
```
$body = '{
        "Name": "ServiceFabricBackupPolicy",
        "AutoRestoreOnDataLoss": false,
        "MaxIncrementalBackups": "3",
        "Schedule": {
          "ScheduleKind": "TimeBased",
          "ScheduleFrequencyType": "Daily",
          "RunTimes": [
            "0001-01-01T09:00:00Z",
            "0001-01-01T17:00:00Z"
          ]
        },
        "Storage": {
          "StorageKind": "AzureBlobStore",
          "FriendlyName": "azurestoragesample",
          "ConnectionString": "DefaultEndpointsProtocol=***",
          "ContainerName": "backupcontainer"
        },
        "RetentionPolicy": {
          "RetentionPolicyType": "Basic",
          "MinimumNumberOfBackups": "20",
          "RetentionDuration": "P20D"
        }
      }'
```

Creating the policy succeeds:


```
StatusCode        : 201
StatusDescription : Created
Content           : {}
RawContent        : HTTP/1.1 201 Created
                    Server: Microsoft-HTTPAPI/2.0
                    X-Content-Type-Options: nosniff
                    Date: Thu, 17 Jan 2019 08:19:04 GMT
                    Content-Length: 0


Headers           : {[Server, System.String[]], [X-Content-Type-Options, System.String[]], [Date, System.String[]], [Content-Length, System.String[]]}
RawContentLength  : 0
RelationLink      : {}
Service Fabric Backup enabled successfully
```

Also enabling succeeds:

```
{
  "BackupPolicyName": "ServiceFabricBackupPolicy"
}


StatusCode        : 202
StatusDescription : Accepted
Content           : {}
RawContent        : HTTP/1.1 202 Accepted
                    Server: Microsoft-HTTPAPI/2.0
                    X-Content-Type-Options: nosniff
                    Date: Thu, 17 Jan 2019 08:32:05 GMT
                    Content-Length: 0


Headers           : {[Server, System.String[]], [X-Content-Type-Options, System.String[]], [Date, System.String[]], [Content-Length, System.String[]]}
RawContentLength  : 0
RelationLink      : {}

Service Fabric Backup enabled successfully
```

I get following exception while getting the applied policy for an application:
```
"https://****:19080/Applications/App1/$/GetBackups?api-version=6.4"

Invoke-WebRequest : {"Error":{"Code":"E_UNEXPECTED","Message":"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index ,\r\n"}}
At line:1 char:1
+ Invoke-WebRequest -Uri $urlGet -Method Get -ContentType 'application/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Re...rShell/6.1.1
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by hrushib** [comment]
@tijntje,
You need to use [GetBackupConfigurationInfo](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-api-getapplicationbackupconfigurationinfo) API for getting the applied policy for application.

See [BackupRestore APIs](https://docs.microsoft.com/en-us/rest/api/servicefabric/sfclient-index-backuprestore) for list of supported APIs along with brief description. Also [Understanding periodic backup configuration in Azure Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-configure-periodic-backup) is good read to begin with.
