### ISSUE TITLE
EventStoreService Failed on Updated Cluster

### ISSUE THREAD

**Issue by brianstringfellow** [Microsoft/service-fabric#286]
Attempted to update an existing cluster (v6.4.622.9590) in Azure using the page [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-eventstore) to add the relevant section to the ARM template. The deployment took 1 hour 21 minutes and indicated success when complete. In the service fabric explorer, the cluster is not entirely healthy and the service for `fabric:/System/EventStoreService` indicates an error.

The logs contain the following exception.
```
RunAsync has failed for a stateful service replica.  Application Type Name: __fabricSystem, Application Name: fabric:/System, Service Type Name: EventStoreServiceType, Service Name: fabric:/System/EventStoreService, Partition Id: f62c7741-56f9-46bf-bed7-b1d6a128df12, Replica Id: 131917187832708555, WasCancelled: false, Exception: EventStore.Service.Exceptions.ConnectionParsingException: Config is Missing Operational Store Connection information
   at EventStore.Service.DataReader.EventStoreReader.<InitIfRequiredAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.DataReader.EventStoreReader.<SwitchModeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.Service.EventStoreService.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__23.MoveNext()

**Comment by VDuleb** [comment]
Thanks you @brianstringfellow  for reporting this. We are looking at the issue now and one of the engineer will reach out to you to get some details and share findings.

**Comment by ibabou** [comment]
Hi @brianstringfellow, Can you please share the current fabricSettings of this cluster? you can share the whole cluster resource template as well, I mean here retrieving the current one. Please upload it to a shareable location, and link to it here. Thanks!

**Comment by ibabou** [comment]
Yeah, sure. I sent you an email, please forward to me the template over there. Thanks!

**Comment by ibabou** [comment]
As per @brianstringfellow update (synced offline), the template used didn't include the azure table storage's configuration, that is required by EventStore service. We can close the issue.

**Comment by brianstringfellow** [comment]
Agreed. Once I added the following section to the ARM template, the EventStore service started working. Looking back at the error message in the exception, that makes sense. Perhaps the documentation could contain a note to indicate the link between the EventStore service and the diagnostics storage account.
```
"diagnosticsStorageAccountConfig": {
    "storageAccountName": "sflogstorage",
    "protectedAccountKeyName": "StorageAccountKey1",
    "blobEndpoint": "[concat('https', '://', parameters('storageAccounts_sflogstorage_name'), '.blob.core.windows.net', '/')]",
    "queueEndpoint": "[concat('https', '://', parameters('storageAccounts_sflogstorage_name'), '.queue.core.windows.net', '/')]",
    "tableEndpoint": "[concat('https', '://', parameters('storageAccounts_sflogstorage_name'), '.table.core.windows.net', '/')]"
},
```
