### ISSUE TITLE
Why is local cluster reset so slow?

### ISSUE THREAD

**Issue by kentcb** [Microsoft/service-fabric#299]
Hi,

When I have to reset my 1-node local cluster (which happens more often than I'd like, but that's another issue) it's incredibly _sllllllooow_, taking up to 4 or 5 minutes. Is this expected? If not, any clues as to what might be wrong?

Guess I'm looking for some metrics on how long a local cluster reset is taking for other folks so I can figure out whether this is a problem on my end, or with SF in general.

Thanks

**Comment by anantshankar17** [comment]
Hi @kentcb 
Are you talking about the native 1 node cluster or the mesh 1 node cluster ? For a native SF 1-node cluster, the reset normally completes within 2 minutes. Do you see any errors while the reset is being performed, errors like failure to cleanup/setup cluster ? So, if there is indeed a failure then a retry is done. Could this be taking that long for you ?

**Comment by kentcb** [comment]
Yeah, native.

I think my 5 minute resets are related to a Surface Book 2 + Windows perf + GPU issue I've been struggling with ([this article](https://www.digitaltrends.com/computing/surface-book-2-as-only-pc/) talks about it in the last section).

When my laptop _is_ performing OK, 2 minutes sounds about how long it's taking. That's expected? That still seems an awful long time for a "reset". My assumption is that a reset just stops the service, reverts files, then starts the service. I guess there's a lot more going on...

**Comment by anantshankar17** [comment]
Yeah, the reset actually removes the existing cluster and recreates a new one from scratch.

**Comment by maburlik** [comment]
I've ported the fix for this to our develop branch so you should see this in the next major/minor release post-6.4.

The reason this is taking long is due to extra file copies being done for each node in the cluster.

**Comment by JustinKaffenberger** [comment]
I've also found that making sure any corporate anti-virus is excluding the relevant Service Fabric folders improves speed quite a bit.
