### ISSUE TITLE
Backup Policy Retention duration not respected

### ISSUE THREAD

**Issue by santo2** [microsoft/service-fabric#312]
Hi, 

we have set a backup policy for our service state, but it seems to go over the retention duration.
we have set the retention duration to 15 Days
should this not delete the older backups from storage?
```

<BackupPolicy>
<AutoRestoreOnDataLoss>true</AutoRestoreOnDataLoss>
<MaxIncrementalBackups>255</MaxIncrementalBackups>
<Name>sfbackuppolicy</Name>
<RetentionPolicy i:type="BasicRetentionPolicy">
<RetentionPolicyType>Basic</RetentionPolicyType>
<MinimumNumberOfBackups>0</MinimumNumberOfBackups>
<RetentionDuration>P15D</RetentionDuration>
</RetentionPolicy>
<Schedule i:type="FrequencyBasedBackupSchedule">
<ScheduleKind>FrequencyBased</ScheduleKind>
<Interval>PT15M</Interval>
</Schedule>
<Storage i:type="AzureBlobBackupStorageInfo">
<FriendlyName/>
<StorageKind>AzureBlobStore</StorageKind>
<ConnectionString>****</ConnectionString>
<ContainerName>servicefabricbackups</ContainerName>
</Storage>
</BackupPolicy>
```

This is according to the documentation, there is no mention except for it not to pass 24 days.

**Comment by raunakpandya** [comment]
@santo2 Are you saying that you do see backups in the azure blob storage which are older than 15 days? 
@khandelwalbrijesh can you please follow up?

**Comment by khandelwalbrijesh** [comment]
@santo2, Are you still facing the issue?? I could happen that one day older backups are not deleted because they are part of Incremental backup chain which lies in the window of 15 days.

**Comment by santo2** [comment]
@raunakpandya storage kept building up, the policy was not deleting any old backups in the storage.
One of my colleagues picked this up further, I will check this next monday, will keep you guys up to date.

**Comment by raunakpandya** [comment]
Hey @santo2  - Please share updates once you have any.. We would like to see what's the issue here.

**Comment by santo2** [comment]
Hi Raunak,

we didn't build in the flush yet, but we also didn't have the issue anymore. I will be building in the flush. You can close this ticket for now, I will open it again if I would get this issue again.

________________________________

met vriendelijke groeten,

Peter Derwa
+32 479 66 12 80

________________________________
Van: Raunak Pandya <notifications@github.com>
Verzonden: woensdag 29 mei 2019 08:59
Aan: microsoft/service-fabric
CC: Peter Derwa; Mention
Onderwerp: Re: [microsoft/service-fabric] Backup Policy Retention duration not respected (#312)


Hey @santo2<https://github.com/santo2> - Please share updates once you have any.. We would like to see what's the issue here.

**Comment by raunakpandya** [comment]
Thanks @santo2 . BTW, what do you mean by building flush here?
