### ISSUE TITLE
Backup/Restore service not coming up with Standalone cluster with GMSA security.

### ISSUE THREAD

**Issue by darran1971** [microsoft/service-fabric#313]
Hi #raunakpandya , #aagup

I still have a problem with the FabricBRSSetup.exe file in the latest release (6.4.644.9590) when activating the backup/restore service.

When activating on a node, this file crashes on the servers, with a null exception error in main. However, if I swap the faulting file on the node with an older version (e.g from 6.3.187.9494) it will start up the service and activate on the node. 
This was a short term fix though, as when a node is restarted at a later point in time, the cluster replaces the FAbricBRSSetup.exe with the latest version and the error starts again. 

So there is an issue with this file, primarily around the GMSA code. I decompiled the EXE and found some differences, and potentially missing try/catch sections where new code was added between versions.

This was the old thread on this issue:
https://github.com/Microsoft/service-fabric/issues/267#issue-391605818

The file FabricBRSSetup.exe errors with this event log entry:
```
Application: FabricBRSSetup.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Fabric.BackupRestore.Setup.Program.Main(System.String[])
```

I am currently having to re-create the cluster to remove backup/restore, until this can be resolved.

Thank you,
Darran

**Comment by mccw** [comment]
We are trying to secure our on prem clusters with gMSA and have run into this very same issue.

**Comment by mccw** [comment]
This issue still exists in the latest build 6.4.658.9590

**Comment by raunakpandya** [comment]
Apologies for missing this.. @aagup  can you please take a look here.

**Comment by aagup** [comment]
@darran1971 It will be great if you can share a cluster details where it is failing ? It will help me in faster RCA the issue

**Comment by darran1971** [comment]
Hi @Aagup, I had to rebuild the cluster without the backup service, so I don't have any more details from the original cluster. There was very little reported in the ServiceFabric logs when I was doing some analysis. 

However, from my testing, I found the problem is specifically with the file FabricBRSSetup.exe. This fails with a NULL exception in Main when I'm using GMSA secured cluster. I tested this by using an older version of FabricBRSSetup.exe and that successfully started the BackupRestore service. As I explained in the first post, this fix is temporary, as the FabricBRSSetup.exe  gets overwritten with the latest version from the CAB file when a NODE gets restarted etc.

Thanks,
Darran

**Comment by aagup** [comment]
@darran1971  Can you please share your clustermanifest for the cluster. Please mask secure values and mail to aagup@microsoft.com

**Comment by darran1971** [comment]
[ClusterConfig.gMSA.Windows.MultiMachineUAT.zip](https://github.com/microsoft/service-fabric/files/3225946/ClusterConfig.gMSA.Windows.MultiMachineUAT.zip)

@aagup, Here is the cluster manifest, used to generate the cluster.

**Comment by aagup** [comment]
@darran1971  Can you share the clustermanifest which is displayed in Service Fabric Explorer. 
Is it possible that we can have joint debug session where we can 
![a](https://user-images.githubusercontent.com/31064311/58462408-77928000-814f-11e9-99a5-3033a4343b2a.png)

**Comment by darran1971** [comment]
@aagup, I see what you mean. However, I had rebuilt the cluster without the backuprestore service activated, so I don't have the manifest available. I could create another GMSA cluster with the backup service activated for backup/restore if that would help.

**Comment by mccw** [comment]
Here is a copy of a failing manifest:

https://bitbucket.org/snippets/ScottMcCollough/Ee4pzj

And a copy of the backup/restore error:
![cluster-error](https://user-images.githubusercontent.com/3137337/58557369-d99cc500-81e3-11e9-93bc-23aa9321b676.jpg)

**Comment by darran1971** [comment]
Hi @mccw, I think the error your getting there, looks an issue I had previously, which was the GMSA, needing the same admin setting as the local system account.

This thread had a workaround, though it
https://github.com/MicrosoftDocs/azure-docs/issues/19950#issuecomment-446651242

**Comment by darran1971** [comment]
@aagup, I have re-created the cluster where this issue occured.

This is the cluster state after initially activating the Backup service
![image](https://user-images.githubusercontent.com/40686134/58560993-1be2f800-821e-11e9-8f84-c7209727abcf.png)


Here is the Manifest as requested.

```
<ClusterManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="DRSECUREDRCLUSTER" Version="0" Description="This is a generated file. Do not modify." xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <NodeTypes>
    <NodeType Name="NodeType0">
      <Endpoints>
        <ClientConnectionEndpoint Port="19000" />
        <LeaseDriverEndpoint Port="19002" />
        <ClusterConnectionEndpoint Port="19001" />
        <HttpGatewayEndpoint Port="19080" Protocol="http" />
        <HttpApplicationGatewayEndpoint Port="19081" Protocol="http" />
        <ServiceConnectionEndpoint Port="19003" />
        <ApplicationEndpoints StartPort="20001" EndPort="22000" />
        <EphemeralEndpoints StartPort="49152" EndPort="65535" />
      </Endpoints>
      <PlacementProperties>
        <Property Name="NodeTypeName" Value="NodeType0" />
      </PlacementProperties>
    </NodeType>
  </NodeTypes>
  <Infrastructure>
    <WindowsServer>
      <NodeList>
        <Node NodeName="UKHQSFUAT008" IPAddressOrFQDN="192.168.53.62" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/SEWSEdc/r0" UpgradeDomain="UD0" />
        <Node NodeName="UKHQSFUAT009" IPAddressOrFQDN="192.168.53.72" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/SEWSEdc/r1" UpgradeDomain="UD1" />
        <Node NodeName="UKHQSFUAT010" IPAddressOrFQDN="192.168.53.73" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/SEWSEdc/r2" UpgradeDomain="UD2" />
        <Node NodeName="UKHQSFUAT011" IPAddressOrFQDN="192.168.53.74" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/SEWSEdc/r3" UpgradeDomain="UD3" />
        <Node NodeName="UKHQSFUAT012" IPAddressOrFQDN="192.168.53.79" IsSeedNode="true" NodeTypeRef="NodeType0" FaultDomain="fd:/SEWSEdc/r4" UpgradeDomain="UD4" />
      </NodeList>
    </WindowsServer>
  </Infrastructure>
  <FabricSettings>
    <Section Name="ApplicationGateway/Http">
      <Parameter Name="BodyChunkSize" Value="65536" />
      <Parameter Name="DefaultHttpRequestTimeout" Value="600" />
      <Parameter Name="IsEnabled" Value="true" />
    </Section>
    <Section Name="BackupRestoreService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="ClusterManager">
      <Parameter Name="EnableAutomaticBaseline" Value="True" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Common">
      <Parameter Name="EnableEndpointV2" Value="True" />
    </Section>
    <Section Name="Diagnostics">
      <Parameter Name="ClusterId" Value="691f040a-6ded-4286-a3e5-e7bf7709d996" />
      <Parameter Name="ConsumerInstances" Value="FileShareWinFabEtw, FileShareWinFabCrashDump, FileShareWinFabPerfCtr" />
      <Parameter Name="EnableTelemetry" Value="False" />
      <Parameter Name="MaxDiskQuotaInMB" Value="5120" />
      <Parameter Name="ProducerInstances" Value="WinFabEtlFile, WinFabCrashDump, WinFabPerfCtrFolder" />
    </Section>
    <Section Name="FailoverManager">
      <Parameter Name="ExpectedClusterSize" Value="5" />
      <Parameter Name="IsSingletonReplicaMoveAllowedDuringUpgrade" Value="True" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="FaultAnalysisService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Federation">
      <Parameter Name="NodeIdGeneratorVersion" Value="V4" />
    </Section>
    <Section Name="FileShareWinFabCrashDump">
      <Parameter Name="ConsumerType" Value="FileShareFolderUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabCrashDump" />
      <Parameter Name="StoreConnectionString" Value="\\ukhqbks001\HOBUS$\UATDiagnosticsStore\fabricdumps-691f040a-6ded-4286-a3e5-e7bf7709d996" />
    </Section>
    <Section Name="FileShareWinFabEtw">
      <Parameter Name="ConsumerType" Value="FileShareEtwCsvUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabEtlFile" />
      <Parameter Name="StoreConnectionString" Value="\\ukhqbks001\HOBUS$\UATDiagnosticsStore\fabriclogs-691f040a-6ded-4286-a3e5-e7bf7709d996" />
    </Section>
    <Section Name="FileShareWinFabPerfCtr">
      <Parameter Name="ConsumerType" Value="FileShareFolderUploader" />
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerInstance" Value="WinFabPerfCtrFolder" />
      <Parameter Name="StoreConnectionString" Value="\\ukhqbks001\HOBUS$\UATDiagnosticsStore\fabricperf-691f040a-6ded-4286-a3e5-e7bf7709d996" />
    </Section>
    <Section Name="Hosting">
      <Parameter Name="EndpointProviderEnabled" Value="true" />
      <Parameter Name="FirewallPolicyEnabled" Value="true" />
      <Parameter Name="RunAsPolicyEnabled" Value="true" />
    </Section>
    <Section Name="HttpGateway">
      <Parameter Name="IsEnabled" Value="true" />
    </Section>
    <Section Name="ImageStoreService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="Management">
      <Parameter Name="ImageStoreConnectionString" Value="fabric:ImageStore" />
    </Section>
    <Section Name="NamingService">
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="PlacementAndLoadBalancing">
      <Parameter Name="QuorumBasedReplicaDistributionPerFaultDomains" Value="true" />
      <Parameter Name="QuorumBasedReplicaDistributionPerUpgradeDomains" Value="true" />
    </Section>
    <Section Name="ReconfigurationAgent">
      <Parameter Name="IsDeactivationInfoEnabled" Value="true" />
    </Section>
    <Section Name="RepairManager">
      <Parameter Name="EnableHealthChecks" Value="True" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="RunAs">
      <Parameter Name="RunAsAccountName" Value="sews-e\srvh1uatgmsa" />
      <Parameter Name="RunAsAccountType" Value="ManagedServiceAccount" />
    </Section>
    <Section Name="Security">
      <Parameter Name="AdminClientIdentities" Value="sews-e\UAT Cluster Admin,sews-e\leahd,sews-e\williad,NT AUTHORITY\SYSTEM" />
      <Parameter Name="AllowDefaultClient" Value="False" />
      <Parameter Name="ClientIdentities" Value="sews-e\UAT Cluster Users" />
      <Parameter Name="ClientRoleEnabled" Value="true" />
      <Parameter Name="ClusterCredentialType" Value="Windows" />
      <Parameter Name="ClusterSpn" Value="HTTP/srvh1uatgmsa.sews-e.com" />
      <Parameter Name="DisableFirewallRuleForDomainProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPrivateProfile" Value="false" />
      <Parameter Name="DisableFirewallRuleForPublicProfile" Value="false" />
      <Parameter Name="ServerAuthCredentialType" Value="Windows" />
    </Section>
    <Section Name="Setup">
      <Parameter Name="FabricDataRoot" Value="E:\SF" />
      <Parameter Name="FabricLogRoot" Value="E:\SF\Log" />
    </Section>
    <Section Name="Trace/Etw">
      <Parameter Name="Level" Value="4" />
    </Section>
    <Section Name="UpgradeOrchestrationService">
      <Parameter Name="AutoupgradeEnabled" Value="False" />
      <Parameter Name="AutoupgradeInstallEnabled" Value="False" />
      <Parameter Name="ClusterId" Value="691f040a-6ded-4286-a3e5-e7bf7709d996" />
      <Parameter Name="GoalStateExpirationReminderInDays" Value="30" />
      <Parameter Name="MinReplicaSetSize" Value="3" />
      <Parameter Name="PlacementConstraints" Value="NodeTypeName==NodeType0" />
      <Parameter Name="TargetReplicaSetSize" Value="5" />
    </Section>
    <Section Name="WinFabCrashDump">
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="FolderType" Value="WindowsFabricCrashDumps" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
    <Section Name="WinFabEtlFile">
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="EtlFileProducer" />
    </Section>
    <Section Name="WinFabPerfCtrFolder">
      <Parameter Name="DataDeletionAgeInDays" Value="3" />
      <Parameter Name="FolderType" Value="WindowsFabricPerformanceCounters" />
      <Parameter Name="IsEnabled" Value="true" />
      <Parameter Name="ProducerType" Value="FolderProducer" />
    </Section>
  </FabricSettings>
</ClusterManifest>
        
```

**Comment by mccw** [comment]
That value is set to disabled on all 7 nodes. I restarted all 7 VM's and
deleted and re-created the cluster and am still getting the same Access
Denied error with the backup/restore service.

**Comment by darran1971** [comment]
#mccw, thanks for trying that out. might be one for #raunakpandya, #aagup to take up for you. It does look very similar to the issue I had before though. #Raunakpandya had another workaround on that thread, to set the listener up manually with powershell if I recall.

**Comment by mccw** [comment]
I read through the entire thread and saw that you added the GMSA account to the local administrators group for each node. I hadn't done that. I have added the account, rebuilt the cluster and so far, no error!!
![cluster-no-error](https://user-images.githubusercontent.com/3137337/58562919-d1e31d80-81ef-11e9-8d70-2c12d5aa6615.jpg)

**Comment by darran1971** [comment]
Yes that's right, I had just added that to the above reply after checking my notes.

**Comment by aagup** [comment]
@darran1971  thanks for setting up. I will request you to kindly share the tracing from any of the BRS primary nodes where it is failing

**Comment by darran1971** [comment]
Hi @aagup, Here's a trace log from one of the nodes, where the FabricBRSetup.exe is failing.

[cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036083788455828_1_00636947321131891223_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3236169/cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036083788455828_1_00636947321131891223_0000000000.dtr.txt)

**Comment by aagup** [comment]
@darran1971  I have attached FabricBRSSetup.exe copy with better tracing and point to point diagnostics.
I will request you to kindly replace the BRSSetup in any of the primary node and share traces with us.

[FabricBRSSetup.zip](https://github.com/microsoft/service-fabric/files/3237672/FabricBRSSetup.zip)

Thanks.

**Comment by darran1971** [comment]
Hi @aagup, thanks for sending the file. I have placed it on one of the nodes.
I noticed the minidump created was a smaller file (60,737KB from 143,175KB)

Here is a trace from that node:

[cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_20_00636948846374194571_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3240296/cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_20_00636948846374194571_0000000000.dtr.txt)

[cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_20_00636948852406857448_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3240320/cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_20_00636948852406857448_0000000000.dtr.txt)

**Comment by aagup** [comment]
@darran1971 not sure why I am unable to see any of the new traces. Can you again share some latest traces of the nodes where we placed the updated FabricBRSSetup.exe as mentioned above
Thanks

**Comment by darran1971** [comment]
Hi @Aagup, I have now placed this on all 5 nodes. Heres a trace form another node:


[a8c5c37953a6aeaded243c5e9bc06061_fabric_traces_6.4.658.9590_132036083836491034_44_00636948983671032794_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3241071/a8c5c37953a6aeaded243c5e9bc06061_fabric_traces_6.4.658.9590_132036083836491034_44_00636948983671032794_0000000000.dtr.txt)

The minidump doesn't show the actual exception with this file
![image](https://user-images.githubusercontent.com/40686134/58703424-87ed6980-83a0-11e9-8722-1f14bd433290.png)

**Comment by darran1971** [comment]
Hi @Aaugup,
I noticed the following error, if I run the FabricBRSSetup.exe file (manually) under an admin account:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FabricBRSSetup, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> 
System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by aagup** [comment]
[FabricBRSSetup.zip](https://github.com/microsoft/service-fabric/files/3252637/FabricBRSSetup.zip)
@darran1971  Can you please try with this exe. if it fails, since we have a development env i will request you to disable strong name and share the traces with us

**Comment by darran1971** [comment]
Hi @Aagup, here's a trace from a node running this version.

[cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_142_00636952573299339517_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3253170/cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.658.9590_132036865922628385_142_00636952573299339517_0000000000.dtr.txt)

**Comment by aagup** [comment]
@darran1971 I added some more tracing. Apologies to request you to run again.
[FabricBRSSetup.zip](https://github.com/microsoft/service-fabric/files/3261703/FabricBRSSetup.zip)
PLease share the traces and error reported in FabricBRSSetup.exe

**Comment by darran1971** [comment]
Hi @aagup, Here are some more traces from the above fabricBRSSetup.exe.



[a8c5c37953a6aeaded243c5e9bc06061_fabric_traces_6.4.664.9590_132043041479745041_1_00636954284874494941_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3262127/a8c5c37953a6aeaded243c5e9bc06061_fabric_traces_6.4.664.9590_132043041479745041_1_00636954284874494941_0000000000.dtr.txt)
[cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.664.9590_132043043679730619_1_00636954281167777310_0000000000.dtr.txt](https://github.com/microsoft/service-fabric/files/3262128/cb2cc1e19b22057ceaeb69a5532dfe2a_fabric_traces_6.4.664.9590_132043043679730619_1_00636954281167777310_0000000000.dtr.txt)

**Comment by aagup** [comment]
Hey @darran1971  Can you please this piece of code in any of the gsma machine and share the output over the mail. Please feel free to mask the outputs. If needed please mail at aagup@microsoft.com



using System;
using System.Security.Principal;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string dacl = GetAllowDaclFromUserName("sews-e\\srvh1uatgmsa");
                Console.WriteLine("DACL String {0}", dacl);
            }
            catch(Exception e)
            {
                Console.WriteLine(e);
            }
            
            Console.ReadKey();
        }
        private static string GetAllowDaclFromUserName(string userName)
        {
            Console.WriteLine( "GetAllowDaclFromUserName userName: {0} ", userName);
            NTAccount entryPointRunAsUser = new NTAccount(userName);
            Console.WriteLine( "entryPointRunAsUser is null: {0} ", entryPointRunAsUser == null);
            Console.WriteLine( "entryPointRunAsUser : {0} ", entryPointRunAsUser);
            IdentityReference identityReference =  entryPointRunAsUser.Translate(typeof(SecurityIdentifier));
            Console.WriteLine("identityReference get type : {0}", identityReference.GetType());
            SecurityIdentifier entryPointRunAsUserSid = identityReference as SecurityIdentifier;
            Console.WriteLine( "entryPointRunAsUserSid is null : {0} ", entryPointRunAsUserSid == null);
            if (entryPointRunAsUserSid != null)
            {
                Console.WriteLine( "entryPointRunAsUserSid Value : {0} ", entryPointRunAsUserSid.Value);
            }

            string dacl = GetAllowDacl(entryPointRunAsUserSid);
            Console.WriteLine( "dacl Value : {0} ", dacl);
            return dacl;
        }

        private static string GetAllowDacl(SecurityIdentifier sid)
        {
            return $"D:(A;;GX;;;{sid.Value})";
        }
    }
}

**Comment by darran1971** [comment]
@Hi aagup,

If I run that code for the GMSA account sews-e\srvh1uatgmsa, it throws the following error:
`E:\Debug>GMSATest.exe
GetAllowDaclFromUserName userName: sews-e\srvh1uatgmsa
entryPointRunAsUser is null: False
entryPointRunAsUser : sews-e\srvh1uatgmsa
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at GMSATest.Program.GetAllowDaclFromUserName(String userName) in C:\Users\williad\source\repos\GMSATest\GMSATest\Program.cs:line 32
   at GMSATest.Program.Main(String[] args) in C:\Users\williad\source\repos\GMSATest\GMSATest\Program.cs:line 17`

If i run it for my user account  sews-e\williad, then I get:
`GetAllowDaclFromUserName userName: sews-e\williad
entryPointRunAsUser is null: False
entryPointRunAsUser : sews-e\williad
identityReference get type : System.Security.Principal.SecurityIdentifier
entryPointRunAsUserSid is null : False
entryPointRunAsUserSid Value : S-1-5-21-854245398-507921405-839522115-4105
dacl Value : D:(A;;GX;;;S-1-5-21-854245398-507921405-839522115-4105)
DACL String D:(A;;GX;;;S-1-5-21-854245398-507921405-839522115-4105)`

So does this point at some policy restriction on the GMSA somewhere?

**Comment by aagup** [comment]
Can you try changing the gmsa account name in your cluster manifest from "sews-e\srvh1uatgmsa" to "sews-e\srvh1uatgmsa$" .. (append $ in the end). I would hope it would start working there after. Given this is a GMSA account, it should have a $ in the end. Let me know if it works thereafter. You can first try using the same code I shared above before making changes directly to the cluster manifest.

**Comment by darran1971** [comment]
Hi @aagup, 
Thanks for the support, that has worked. I was unaware we needed a $ appended in the manifest, as it has worked for everything else. 
![image](https://user-images.githubusercontent.com/40686134/59097962-dbb70000-8916-11e9-84ec-ef86b9d4eff3.png)

**Comment by raunakpandya** [comment]
Glad to hear it worked. We will fix the code to handle even if its not specified like in other cases. Thanks for all the patience you have showed in helping trouble shoot this one. Please try out the service and keep the feedbacks coming :)
