### ISSUE TITLE
How does SF communicate with a standalone services process written by a developer?

### ISSUE THREAD

**Issue by buzzers** [Microsoft/service-fabric#314]
When I read SF's documentation, I found that it was mentioned that every app written by a developer was independent of the SF's own process. That is, SF processes and application processes need to rely on IPC to communicate.
I want to know the IPC way SF uses on Windows and Linux. Or is SF not managing the app in a way that I understand?

**Comment by GitTorre** [comment]
I'm afraid I don't understand the question. 

We communicate via configuration, events (health reports, etc...). You tell us what you need us to know to run your service(s) as you intend them to run. We'll take care of the distributed system deails, as you expe
