### ISSUE TITLE
Inject configuration into ASP Core correctly

### ISSUE THREAD

**Issue by AndersMalmgren** [Microsoft/service-fabric#319]
We host a ASP Core web api inside a service fabric instance. I want to forward all configs to the Core app. I use this method

https://dzimchuk.net/configuring-asp-net-core-applications-in-service-fabric/

And then I invoke it using `ConfigureAppConfiguration`

```csharp
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
{
    return new[]
    {
        new ServiceInstanceListener(serviceContext =>
            new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
            {
                ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                return new WebHostBuilder()
                            .UseKestrel()
                            .ConfigureServices(
                                services => services.AddSingleton(serviceContext))
                            .ConfigureAppConfiguration(builder => builder.AddServiceFabricConfiguration(serviceContext))
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseStartup<Startup>()
                            .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseReverseProxyIntegration)
                            .UseUrls(url)
                            .Build();
            }))
    };
}
```

The inected configration in startup class do have the configs applied, like connection string and logging

![image](https://user-images.githubusercontent.com/817577/55858161-40e8b200-5b6f-11e9-8c9f-5a2e8362ef86.png)

But it seems its not fully jacked into the framework.

For example I need to explicit supply ApplicationInsights with the config `services.AddApplicationInsightsTelemetry(Configuration);` otherwise it does not pickup the instrument key. And the logging does not work (the log level is not applied).

**Update:**
I tried doing a custom config provider in a standard core project without service fabric and it works.
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration(builder => builder.AddServiceFabricConfiguration())
            .UseStartup<Startup>();
}

internal class ServiceFabricConfigurationProvider : ConfigurationProvider
{

    public override void Load()
    {
        Data["Logging:Debug:LogLevel:Default"] = "Information";
    }
}

internal class ServiceFabricConfigurationSource : IConfigurationSource
{


    public IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return new ServiceFabricConfigurationProvider();
    }
}

public static class ServiceFabricConfigurationExtensions
{
    public static IConfigurationBuilder AddServiceFabricConfiguration(this IConfigurationBuilder builder)
    {
        builder.Add(new ServiceFabricConfigurationSource());
        return builder;
    }
}
```

So it seems something i service fabric land is not working as it should.

**Comment by AndersMalmgren** [comment]
I also tried

```csharp
 return new WebHostBuilder()
   .UseConfiguration(new ConfigurationBuilder().AddServiceFabricConfiguration(serviceContext).Build())
   .UseKestrel()
```

And got a slightly different IConfiguration object. Though no difference, also notice that Warnign is enabled and info is not (this is default settings).

![image](https://user-images.githubusercontent.com/817577/55861658-1ac71000-5b77-11e9-960f-c03a8b45e256.png)

**Comment by AndersMalmgren** [comment]
I created a repro here

https://github.com/AndersMalmgren/ServiceFabricLoggingRepro

Please advice

**Comment by amanbha** [comment]
The article which you referred to allows adding settings from ServiceFabric service config package to aspnet core, from the repro which you share it doesn't seem to be doing that, If you want the configs from service config package, please see https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore#service-fabric-configuration-provider

**Comment by AndersMalmgren** [comment]
My repro just concentrate on the problem, the config is ignored by asp core

**Comment by amanbha** [comment]
Could you try the nuget in the doc link which I shared.

**Comment by AndersMalmgren** [comment]
Sure, will do.

**Comment by AndersMalmgren** [comment]
@amanbha I updated the repro with the nuget package, no difference

```csharp
.ConfigureAppConfiguration(builder => builder.AddServiceFabricConfiguration(FabricRuntime.GetActivationContext(), options => options.IncludePackageName = false))
```

**Comment by amanbha** [comment]
@AndersMalmgren For my understanding, In your repro, could you please clarify what is not getting injected and where? Whats expected and whats actually happening? I am not able to co-relate that repro with the sanapshots you pasted?

**Comment by AndersMalmgren** [comment]
In the controller I inject both the IConfiguration and a ILogger, you can verify that the injected config has the proper config for logging information to the debug logger, but logging is disabled for all loglevels. Run the repro and test the controller

**Comment by AndersMalmgren** [comment]
Please advice. We need to push this to our test environment soon

**Comment by amanbha** [comment]
@AndersMalmgren I am sorry, I still don't understand the issue here. The Microsoft.ServiceFabric.AspNetCore.Configuration package and the original article link you share, allows the config values from Service Fabric Service code package to be read using IConfiguration interface so that you can read these values in your service code, it also ties update notifications with Config pkg.
I think there is some confusion in the intended usage of this (I might be wrong in my assumption) you were expecting it to set logging for you, Its not going to do that, you will have to configure them eparately.

**Comment by AndersMalmgren** [comment]
In ASP Core you set logging from config. Its not working. The logging framework does not pickup the setings.

**Comment by AndersMalmgren** [comment]
I'll update the repro with a asp core project too so you can see how its supposed to work

**Comment by amanbha** [comment]
@AndersMalmgren Iw ant to clarify that the nuget package and the links which you mentioned earlier allows you to read config values using IConfiguration, they don't configure anything else.

**Comment by AndersMalmgren** [comment]
Logging in ASP Core is purely a config matter. give me 5, fixing a asp core vanilla project

**Comment by AndersMalmgren** [comment]
@amanbha Ok, please check the repro vanilla asp core project commited

https://github.com/AndersMalmgren/ServiceFabricLoggingRepro/tree/master/VanillaApi

**Comment by amanbha** [comment]
@chuanboz Could you please take a look at this?

**Comment by chuanboz** [comment]
@AndersMalmgren , is the issue you meet only for the logging level not applied, does it work for other custom settings?

**Comment by AndersMalmgren** [comment]
Hi @chuanboz As you can see in the repro I inject the IConfiguration and can read the config correctly. Thanks

**Comment by chuanboz** [comment]
And with your custom config provider, and with service fabric does it work as you expect?
Basically I am trying to distinguish whether that's the SF config provider issue, or usage issue of asp.net core configuration.

I'm trying your repro but meet some issue compile the project, trying to upgrade my VS to latest and see if that could load it.

**Comment by AndersMalmgren** [comment]
Yes, I can inject config correctly into my own code and read the config correctly. Using both methods (They are doing the same thing under the hood).

**Comment by chuanboz** [comment]
so the configuration provider is doing its job as expected then.

for the logging level to be applied, based on https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x&view=aspnetcore-2.2#log-level

you'll need to add below ConfigureLogging code to your Startup, which I do not see in your repro.
```C#
public static void Main(string[] args)
{
    var webHost = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            var env = hostingContext.HostingEnvironment;
            config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                  .AddJsonFile($"appsettings.{env.EnvironmentName}.json", 
                      optional: true, reloadOnChange: true);
            config.AddEnvironmentVariables();
        })
        .ConfigureLogging((hostingContext, logging) =>
        {
            logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
        })

}
```

**Comment by AndersMalmgren** [comment]
Its redundant, check my vanilla project, All needed for logging in Core with custom config provider is

```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(builder => builder.AddTestConfiguration()) //Normally this is done through .json config. But douing it this way to prove it works when done through vanilla pipeline not service fabric
                .UseStartup<Startup>();
    }
```

**Comment by AndersMalmgren** [comment]
Also we have a similar issue with application insight not being able to pickup the instrument key from config.

**Comment by chuanboz** [comment]
if you add ConfigureLogging with service fabric project, can you confirm if that will solve your issue or not?

for application insight, can you clarify your expect behavior and also current behavior?
from https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs it seems AddApplicationInsightsTelemetry with configuration is a toally supported scenario.

**Comment by AndersMalmgren** [comment]
I dont have service fabric on this computer. Will try tomorrow at office. But keep in mind even if it works it means you have a discrepancy between ASP Core hosted stand alone or in service fabric. Since it works in vanilla just out of the box. 

Same with app insight. It works out of the box using `services.AddApplicationInsightsTelemetry()` or `WebHost.CreateDefaultBuilder(args).UseApplicationInsights()`. Both methods will pickup the key from config using key `"ApplicationInsights:InstrumentationKey"`

**Comment by chuanboz** [comment]
You're not compare apple to apple, in vanilla asp.net core you're using WebHost.CreateDefaultBuilder(args), while for Service Fabric you're using new WebHostBuilder().

If you look into the source code of CreateDefaultBuilder you'll see it actually adds lots of default behavior including the logging one.

**Comment by AndersMalmgren** [comment]
Alright, that fixes logging. I advice you to update the service fabric project template to use `WebHost.CreateDefaultBuilder()` its easy to miss. 

Though application insights is still not working. In vanilla ASP Core both above methods work. And insights can pickup the instrument key from config. In service fabric even when using `WebHost.CreateDefaultBuilder()` I need to supply it with the config `services.AddApplicationInsightsTelemetry(Configration)`. This indicates to me that something is still not correctly configured as there still is discrepancy between the two

**Comment by chuanboz** [comment]
Glad that fixed the logging issue, for project template to use WebHost.CreateDefaultBuilder() can you create a separate issue for tracking?

**Comment by chuanboz** [comment]
for the app insight behavior, that's the design behavior of app insight which hard code to use appsettings.json.

see https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/2e5aa6c9cf787123990cf56a2505d7137f1704e5/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs

```C#
public void Configure(ApplicationInsightsServiceOptions options)
        {
            var configBuilder = new ConfigurationBuilder()
                .SetBasePath(this.hostingEnvironment.ContentRootPath??Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", true)
                .AddJsonFile(string.Format(CultureInfo.InvariantCulture,"appsettings.{0}.json", hostingEnvironment.EnvironmentName), true)
                .AddEnvironmentVariables();
            ApplicationInsightsExtensions.AddTelemetryConfiguration(configBuilder.Build(), options);

            if (Debugger.IsAttached)
            {
                options.DeveloperMode = true;
            }
        }
```

**Comment by chuanboz** [comment]
@AndersMalmgren , if you still want the same default behavior work for asp.net core and service fabric the same way, you need to open an issue for App Insight, asking them to change DefaultApplicationInsightsServiceConfigureOptions to use the Configuration from DI container rather than build their own ConfigurationBuilder

**Comment by AndersMalmgren** [comment]
Hi, its really dangerous that hosting in service fabric does not work exactly the same as in vanilla. Since service fabric has such a large footprint when developing most teams I know how including my own. Only use service fabric when deploying to test environments and to production. Locally we use vanilla. If we cant be sure the pipeline works the same it creates a QA problem.

Thanks

**Comment by chuanboz** [comment]
@AndersMalmgren , I understand the concern you raised for a parity between vanilla and with Service Fabric, I would agree that would be ideal. 

but as I point out the specific difference is not caused by Service Fabric. In case of App Insight, they chose to hard code to use appSettings.json as the default configuration source, so if you want to get the same default behavior then you could continue to use appSettings.json as the configuration source and that shall give you the same behaivor with or without Service Fabric.

If you have a better suggestion on how Service Fabric could change to make the parity, please raise it and I'd be interest to discuss.

**Comment by AndersMalmgren** [comment]
@chuanboz Thanks for input. I have opened a issue with them. Its not much you can do on service fabric side. thanks

**Comment by kosalanuwan** [comment]
@AndersMalmgren This would not be a problem when using .NET Minimal Hosting for Web API.

```csharp
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
{
    return new ServiceInstanceListener[]
    {
        new ServiceInstanceListener(serviceContext =>
            new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
            {
                ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                var builder = WebApplication.CreateBuilder();

                builder.Services.AddSingleton<StatelessServiceContext>(serviceContext);
                builder.WebHost.UseKestrel(opt =>
                               {
                                   int port = serviceContext.CodePackageActivationContext.GetEndpoint("ServiceEndpoint").Port;
                                   opt.Listen(IPAddress.IPv6Any, port, listenOptions => listenOptions.UseHttps(https =>
                                   {
                                       https.ServerCertificate = GetCertificateFromStore();
                                       // HINT: Allow the machine to decide.
                                       //https.SslProtocols = SslProtocols.Tls12;
                                   }));
                               })
                               .UseContentRoot(Directory.GetCurrentDirectory())
                               .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                               .UseUrls(url);
                    
                // Add services to the container.
                builder.Configuration.AddServiceFabricConfiguration();

                builder.Logging.ClearProviders()
                               .AddConsole()
                               .AddDebug();

                builder.Services.AddLogging<Ingress>()
                                .AddJsonOptions()
                                .AddIntentsDb()
                                .AddMessageBroker();

                var app = builder.Build();
                    
                // Configure the HTTP request pipeline.
                app.MapEndpoints();

                return app;

            }))
    };
}
```
