### ISSUE TITLE
Backup and Restore from one cluster to other

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [microsoft/service-fabric#322]
Hi Team, 

We implemented the Backup and Restore mechanism for our Stateful services which stored backup in VM and also Azure Blob storage. 
Can we use the Azure Blob storage file to restore it to any other cluster? 
Such that I can create multiple environments based on demand.

**Comment by raunakpandya** [comment]
Yes you can. The Backup Restore service inherently provides API to achieve this. https://docs.microsoft.com/azure/service-fabric/service-fabric-backup-restore-service-trigger-restore#data-restore-in-the-case-of-disaster-recovery


Have you checked this out - https://github.com/microsoft/Service-Fabric-AppDRTool
This tool effectively backs up the application state from one cluster and restores it periodically on another cluster constantly. Depending on your availability needs, you can use the same tool or the logic to restore to another cluster. Do keep in mind, the backups are only consistent within a partition and hence if you have state dependency across different partitions / services/ applications then that is something you would need to correct.

**Comment by raunakpandya** [comment]
Please let me know if you have any further questions and feel free to reactivate accordingly.
