### ISSUE TITLE
Certificate Revocation List Warning for new SF Cluster

### ISSUE THREAD

**Issue by tj10harr** [microsoft/service-fabric#328]
Recently deployed a standalone SF Cluster with Azure hosted VMs and receiving the following error:  

Unhealthy event: SourceId='System.FabricNode', Property='CertificateRevocationList_FabricGateway', HealthState='Warning', ConsiderWarningAsError=false. Certificate revocation list:CRL offline encountered for certificates: {Cert thumbprint removed} Please ensure the reporting machine has access to 'CRL Distribution Point' at ALL levels in the certificate chain. 'CRL Distribution Point' is an extension in the certificate.

I have deployed many standalone SF on-premise and never encountered this issue and not sure if it is related to hosting this environment in Azure. I noticed when I go into SF Manager for this cluster the warning will pop up when I select the client cert (has the same thumbprint that it is giving an error about).

I see that other people have added disabled CRL checks this to their JSON. Can anyone provide advice on how to proceed on fixing this issue without disabling CRL?

**Comment by Simon-Syd** [comment]
Hello,
How did you fix your issue please ?
