### ISSUE TITLE
Service Fabric Application Restart

### ISSUE THREAD

**Issue by inkey** [microsoft/service-fabric#336]
Hi 

I have a service fabric app that reads from KeyVault on startup. When we change the KeyVault value we have to restart the nodes for it to read the new value. This causes the other applications on the same node to go down.

I am trying to write a PowerShell script to restart the service fabric application I have got the following script working on a 1 node cluster however it does not work on multiple node cluster.
```
Restart-ServiceFabricDeployedCodePackage -ApplicationName $appName -CommandCompletionMode Verify -ServiceName $ServiceName -TimeoutSec 8000
```

When I have a mutiple node cluster this does not work. I can't figure out why it will not work.

Am i doing something wrong?

**Comment by tuhland** [comment]
Not a direct answer to your question, but for these tasks we have built "Management API/Service" in our cluster . In your case, this API would call the service in question to read the new configuration from the key vault. Seems to be a better solution than brute forcing a restart. ;)
