### ISSUE TITLE
Docker Network stack issue in v6.5

### ISSUE THREAD

**Issue by solidcloudio** [microsoft/service-fabric#340]
The recent Service Fabric software update to v6.5.435.1 seems to have broken our DNS inside the docker containers..  All of our Java services running in docker can't resolve the DNS for SQL, Cosmos or Service Bus.

seeing errors like:
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host xxxx-server.database.windows.net, port 1433 has failed. Error: "xxxx-server.database.windows.net. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
       at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:191) ~[sqljdbc42-6.0.jar!/:na]
       at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:242) ~[sqljdbc42-6.0.jar!/:na]

com.mongodb.MongoSocketException: xxxxx.documents.azure.com: Temporary failure in name resolution
        at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongo-java-driver-3.2.2.jar!/:na]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.2.2.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.2.2.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.2.2.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128) ~[mongo-java-driver-3.2.2.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]

Reverting to v6.4.661.1 resolved the issue.

I saw a similar issue in the v6.3 update back in August 2018 https://blogs.msdn.microsoft.com/azureservicefabric/2018/08/22/microsoft-azure-service-fabric-6-3-refresh-release-cu1-notes/

**Comment by solidcloudio** [comment]
It seems the docker stack is configured incorrectly in this case.  The DNS server address on the right container is invalid.  This example shows the container inspections from one cluster node vs another...

![InvalidDNS](https://user-images.githubusercontent.com/11837859/59739681-78807400-921a-11e9-9b7f-f684309a7001.png)

**Comment by solidcloudio** [comment]
I also see this issue occurring in a SF cluster running v6.4.661.1 - So it doesnt seem isolated to v6.5.
It seems to have regressed...  I also saw this issue in August of last year, after time with support they stated:

> We were wrongly setting the DNS server chain on host network connected containers to only the Host IP address on Docker NAT network. On clusters where service_fabric bridge network is not present, the response from the DNS service running host appears to come from an IP (Host IP on cluster network) rather than the host IP on docker NAT network.

This happens due to missing NAT translation rules which get created by CNS plugin when bridge network is created. As the replies seem to be coming from an unexpected source (due to difference in IP), OS resolver drops the response, resulting into DNS resolution failures. To fix this, we now set the DNS server as 127.0.0.1 for host network connected containers. This will make the reply look from an expected source as DNS service is running on the host.

**Comment by solidcloudio** [comment]
This is a serious issue.  I can't control the Decker network stack configuration.  It's obviously a bug in service fabric.  Can I get some traction on this?  I'm leaving this cluster in a broken state so that Microsoft can look at it.  Otherwise, Id delete the cluster and the problem would probably go away.  It keeps regressing however, a system exhibiting this behavior may be invaluable in fixing this bug.

**Comment by dariopb** [comment]
The container's DNS service point to the node IP since that is where our DNS service runs (and it serves all the SF names + does the DNS forwarding).
Is the current cluster exhibiting the issue? Seems that our DNS service is not enabled on that cluster. DNS service has to be enabled for containers. There is a bug that we don't check nor enable the DNS service in this case (I'll open a bug on our side to track this down):

![image](https://user-images.githubusercontent.com/10108760/60850172-e4635600-a1a2-11e9-821f-502553330953.png)

Can we check that enabling the DNS service mitigates the issue on that cluster?

**Comment by solidcloudio** [comment]
It seems to be quite the opposite.  Microsoft had me remove the DNS Service from the cluster, and it seems to have resolved the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dariopb** [comment]
Oh, ok, so now your cluster: doesn't have the DNS service enables **and** inside the container the dns server is the NAT address?

**Comment by solidcloudio** [comment]
The container reports no DNS address when the DNS service disabled..

"Dns": [],
