### ISSUE TITLE
Standalone container node

### ISSUE THREAD

**Issue by teapejon** [microsoft/service-fabric#341]
I am not able to successful create a node with a single/ "standalone container" from a docker image. When I run service fabric locally with only the RavenDB image it works and runs great but one I add other services or applications the RavenDB container begins to fail.

Can I run a VM in the set with just RavenDB?

**Comment by craftyhouse** [comment]
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-containers-overview should help answer, but please let us know if you need more help.
