### ISSUE TITLE
Hire a Service Fabric product manager who gives a shit

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#342]
There are numerous issues raised here which haven't even been given a courtesy response.

That's bullshit. It's time for someone to get off their ass, or hire someone who will. This is SERVICE FABRIC, a core Azure technology, not some one off side product that nobody gives a shit about.

**Comment by solidcloudio** [comment]
Hear hear...  Agreed!  Not sure which is worse!?! a priority A support ticket, or a github issue...  Crickets either way pretty much..

**Comment by masnider** [comment]
Please provide links. The SF team does triage these issues, however most of the time is spent over on the old [issues list](https://github.com/Azure/service-fabric-issues/), and we're trying to crosstrain folks to look in both places :)

**Comment by masnider** [comment]
I'll add that abusive language isn't going to help your case. I'd avoid it.
