### ISSUE TITLE
Service Fabric fucking blows

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#343]
An experiment to see whether ANYONE on the SF team actually receives GitHub notifications.

**Comment by masnider** [comment]
@jackbond Please try to be more constructive. Of course we do.

**Comment by jackbond** [comment]
Oh, so you monitor them, but completely ignore them. Much better.

Is it acceptable that two core Microsoft offerings DevOps and Service Fabric are currently out of sync?

**Comment by masnider** [comment]
You are making toxic and unhelpful statements. Please refrain from doing so. Sarcasm and profanity will not help you get your issues resolved. 

I have replied in your [main question](https://github.com/microsoft/service-fabric/issues/333). If you would like to engage in constructive discussion, go there. If you want to continue to make mean and unhelpful assumptions and remarks, go ahead, but then we can just close down this whole thread as well.
