### ISSUE TITLE
service-fabric on Fedora

### ISSUE THREAD

**Issue by michelesolytic** [microsoft/service-fabric#359]
I am following the linux installation tutorial for service fabric at this link: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux

Unfortunately I see that Fedora is not supported at the moment. Fedora is quite popular among developers, and is pretty similar to RHEL (which you already seem to support). I tried to bluntly install the RHEL packages on Fedora 29, but I get some dependency problems (as expected)

As an alternative, I understand that there should exist a docker container named service-fabric-onebox which should work as long as I have docker, but I can't find it anywhere.

For reference, here's the error I currently get by forcing the RHEL package to install on Fedora 29:
```
[michele@michele-macbook servicefabric]$ sudo dnf install servicefabric_6.1.189.1.rpm 
Last metadata expiration check: 0:16:00 ago on Fri 12 Jul 2019 16:50:29 CEST.
Error: 
 Problem: conflicting requests
  - nothing provides libicuuc.so.50()(64bit) needed by servicefabric-6.1.189.1-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
Compiling seems like it takes a lot of time according to the documentation. Is there a quick way to get around this?

**Comment by maburlik** [comment]
As you may have noticed the installation conflict you were hitting was related to the base lib dependencies expected on the machine for the code to function, which would require changes to the dependency reeling process at the runtime drop & cmake levels.

Despite Fedora nor RHEL being on our current engineering roadmap it is possible to make this work by rebuilding the product with Fedora-based libs as dependencies, and we encourage the community to build a fork of the repo, run experiments, and contribute back.
