### ISSUE TITLE
Create a Virtual Kubelet provider 

### ISSUE THREAD

**Issue by rbitia** [Microsoft/service-fabric#36]
https://github.com/Virtual-Kubelet/Virtual-Kubelet
https://github.com/virtual-kubelet/virtual-kubelet/issues/30

**Comment by rbitia** [comment]
Service Fabric can model a create, delete etc for containers and it all can be managed by Kubernetes. We get the infrastructure capabilities of SF while getting the orchestrator capabilities of K8

**Comment by vturecek** [comment]
@rbitia - nice, would love to get into this some more to see what makes sense. @masnider FYI

**Comment by masnider** [comment]
Closing this issue as a VKP was built for Service Fabric Mesh, where it matches the correct activation pattern. Mesh is the correct environment to target the VK pattern enables scaling from a server-full to a server-less environment (similar to AKS->ACI). A provider from Kubernetes to Service Fabric proper wouldn't be the same common virtual kubelet pattern.  https://github.com/virtual-kubelet/virtual-kubelet#service-fabric-mesh-provider
