### ISSUE TITLE
Service Fabric Stateless Services Slow

### ISSUE THREAD

**Issue by stoepa** [microsoft/service-fabric#368]
This is more of a question than a issue. So please point me to the correct forum as I can't seem to find any.

We have a 5 node service fabric cluster which is currently running in Azure. The backing VMs in the cluster are normal D2V2 machines.

We have about 7 services currently, of which 3 are quest executables and 4 are Asp.Net stateless services.

My question is the following, does these services go cold after a time period. I know in IIS there is a setting where the app can be preloaded and it will always be hot, but this does not seem to be the case for Service Fabric services.

I get that the first time a service endpoint is hit, it might take some time to startup and subsequent requests would be served much faster, but with out services it seems that this is happening every couple of seconds. 

When we hit a endpoint with a very small payload and execution process the first call is slow, and subsequent requests are a bit faster, but in a couple of seconds it becomes slow again. I guess this is due to the load balancer sending our request to another node in the meantime. 

I need all services hot the whole time. After they have been placed they should be running without going in to a sleeping kind of moode.

It this due to our machines we use or is there a configuration that I am missing. 

Your input would be appreciated.

**Comment by stoepa** [comment]
Hi guys any feedback on this question above?

**Comment by aL3891** [comment]
Afaik, there is no app pool equivalent concept for service fabric, nor is there any built in service warming. When the replica is activated (when you deploy the service ) service fabric starts asp.net and kestrel, from there it pays no more mind to the service until it shuts down the replica, as part of a fail over or upgrade or something. 

Something else in the app code might become cold though, especially if this happens after just a few seconds

**Comment by stoepa** [comment]
@aL3891 thanks for the reply. I did some more investigation and it turns out the guest executable had a large memory leak and this caused the issue. After some time the GC would realize the memory assignment is incorrect and clear it, therefore the intermittent behavior.

I will close this issue.
