### ISSUE TITLE
Standalone Service Fabric Node Removal

### ISSUE THREAD

**Issue by tj10harr** [microsoft/service-fabric#370]
I am encountering an issue where two of our VMs vmdk files were deleted causing us to lose 2 nodes in our SF Cluster. I need to push an upgrade in the config file to remove the  ReverseProxy settings, but with these two nodes being down I am unable to. I am trying to remove the Nodes however if I try to remove both or one at a time I encounter the following error "Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: The difference between the maximum and minimum total node counts under each FD needs to be smaller than 2. Current maximum 8; minimum 6. "

How can I increase this count to be larger than 2?

**Comment by maburlik** [comment]
Can you share the node list from your config? Are you still hitting this with the latest version of SF?

**Comment by craftyhouse** [comment]
Please let us know if you need further assistance here.
