### ISSUE TITLE
downscaling a service fabric cluster fails

### ISSUE THREAD

**Issue by FreyJim** [microsoft/service-fabric#374]
I tried to downscale a service fabric cluster from 5 notes down to 3 notes. I also changed the reliability level from Silver to Bronze. 

I use ARM templates to execute this operation and I get this error: 

`
##[error]8:56:18 AM - Resource Microsoft.ServiceFabric/clusters 'CLUSTERNAME' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ClusterUpgradeFailed",
        "message": "Cluster upgrade failed. Reason Code: 'Unknown', Upgrade Progress: '{\"errors\":[{\"operation\":\"ProcessClusterUpgrade\",\"transient\":false,\"errorDetails\":{\"ClassName\":\"System.IO.FileNotFoundException\",\"Message\":\"The file 'WindowsFabricStore\\\\ClusterManifest.30.xml' was not found in the Image Store\",\"Data\":null,\"InnerException\":{\"ClassName\":\"System.Runtime.InteropServices.COMException\",\"Message\":\"Exception from HRESULT: 0x80071C00\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at System.Fabric.Interop.NativeClient.IFabricClusterManagementClient10.EndUpgradeFabric(IFabricAsyncOperationContext context)\\r\\n   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)\\r\\n   at System.Fabric.Interop.AsyncCallOutAdapter2'1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nEndUpgradeFabric\\nSystem.Fabric, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\\nSystem.Fabric.Interop.NativeClient+IFabricClusterManagementClient10\\nVoid EndUpgradeFabric(IFabricAsyncOperationContext)\",\"HResult\":-2147017728,\"Source\":\"System.Fabric\",\"WatsonBuckets\":null},\"HelpURL\":null,\"StackTraceString\":\"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.Common.FabricClientRetryHelper.<ExecuteFabricActionWithRetryAsync>d__9.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.FabricClientWrapper.<StartUpgradeFabricAsync>d__33.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.FabricClientWrapper.<UpgradeFabricAsync>d__32.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.ClusterCommandProcessor.<UpgradeClusterAsync>d__18.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.ClusterCommandProcessor.<ProcessClusterUpgradeAsync>d__17.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Fabric.UpgradeService.ClusterCommandProcessor.<ClusterTask>d__15.MoveNext()\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":\"8\\nThrow\\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\\nSystem.Runtime.ExceptionServices.ExceptionDispatchInfo\\nVoid Throw()\",\"HResult\":-2147024894,\"Source\":\"mscorlib\",\"WatsonBuckets\":null,\"FileNotFound_FileName\":null,\"FileNotFound_FusionLog\":null}}]}'.",
        "details": []
      }
    ]
  }
}'
`

What is the issue for this error? 

In the Azure portal is just shown an information "Cluster provisioning failed." but in the activity logs is nothing logged which give some additional information.

**Comment by FreyJim** [comment]
I found some information in the scale set: 
"Message: VHD Containers currently being used by any Virtual Machine Scale Set VM instances may not be removed. To remove a VHD Container, all Virtual Machine Scale Set VM instances using it must first be deleted" 

Okay thats a small hint. But how can I find the related machines ?

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
