### ISSUE TITLE
How to delete content from WindowsFabricStore

### ISSUE THREAD

**Issue by nyghtrocker** [microsoft/service-fabric#377]
Hi, I'm getting low disk space error (There is not enough space on the disk. (Exception from HRESULT: 0x80070070).)when I'm publish in service fabric. In service fabric explore Image Store I can see that  WindowsFabricStore taking lot of space as in attache picture 
<img width="491" alt="fbimageStore" src="https://user-images.githubusercontent.com/16857108/63696154-645c8280-c81a-11e9-9dbe-b42609e22f2f.png">

How can I delete content from  WindowsFabricStore

**Comment by maburlik** [comment]
You can unregister old application versions and old code package versions:
https://docs.microsoft.com/en-us/powershell/module/servicefabric/unregister-servicefabricapplicationtype?view=azureservicefabricps
https://docs.microsoft.com/en-us/powershell/module/servicefabric/unregister-servicefabricclusterpackage?view=azureservicefabricps

**Comment by maburlik** [comment]
Also
https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricapplicationpackage?view=azureservicefabricps
https://docs.microsoft.com/en-us/powershell/module/servicefabric/remove-servicefabricclusterpackage?view=azureservicefabricps
