### ISSUE TITLE
Fabric-Service deployment fails on AzureStack

### ISSUE THREAD

**Issue by pmanvoj** [microsoft/service-fabric#378]
Fabric installation fails on azure stack 
-  there are 3 instances installed using ARM template with the names 
SFDeployment0, SFDeployment1,SFDeployment2

SFDeployment1 & SFDeployment2 are finished with success after 5 minutes while SFDeployment0 fails with the following error after ~11 minutes

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VmScaleSetInstanceGoalSeekingError\",\r\n \"message\": \"Error occurred in processing of VMscale set 'sfnvmss0', Error 'VMExtensionProvisioningError: VM has reported a failure when processing extension 'DeployServiceFabricCluster'. Error message: DSC Configuration 'InstallServiceFabricConfiguration' completed with error(s). Following are the first few: PowerShell DSC resource xServiceFabricSecureClusterDeployment failed to execute Set-TargetResource functionality with error message: Cluster validation failed with error: System.Management.Automation.CommandNotFoundException: The term 'Connect-ServiceFabricCluster' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\\r\\n at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\\r\\n at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\\r\\n at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\\r\\n at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame).\\n Please check the detailed DSC logs and Service fabric deployment traces at: 'F:\\\\SFSetup\\\\ServiceFabric\\\\DeploymentTraces' on the VM: 'SFN0000000'. The SendConfigurationApply function did not succeed.'.\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by maburlik** [comment]
This indicates that the SF runtime was not installed due to deployment logic in Azure Stack. I suggest you follow up with them through their channels since they own this deployment wrapper.
