### ISSUE TITLE
EventStore on standalone cluster

### ISSUE THREAD

**Issue by sxp-sme** [microsoft/service-fabric#379]
Hello!

I've upgraded our standalone dev cluster (5 nodes) to version 6.5.658.9590.
After that I also did an upgrade to the configuration and activate the event store service with the followin configuration:

`"AddonFeatures": [
	"EventStoreService"
],`

There was no warning or error, when I test the configuration, so I started the upgrade and the configuration upgrade succeeded but the event store service is broken.
The service itself is marked as broken in the webbased service fabric explorer and in the event log of one of the nodes I've found the following error message:

> RunAsync failed due to an unhandled exception causing the host process to crash: EventStore.Service.Exceptions.ConnectionParsingException: Config is Missing Operational Store Connection information

I researched possible causes of errors and read the available documentation (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-eventstore)
However, I could not find any reason for the error or any further documentation.
The documentation only says that the event store is not supported in version 6.4 for standalone clusters and describes how to enable the service for a local cluster.

So my questions are:
- Is a local cluster different from a standalone cluster?
- Am I missing any additional configuration values or options to configure the missing connection information?
- Is event store service still unsupported for standalone clusters in v6.5? If so, is there any way to remove the broken service?
I tried to upgrade the configuration again, but it did not work for the same reasons like in issue #260. The only way seems to be to change the cluster manifest described by user ibabou in the linked issue (https://github.com/microsoft/service-fabric/issues/260#issuecomment-458747550). Are there any risks do such a upgrade to the cluster manifest?

Any information and helpful answer is really welcome.

**Comment by ibabou** [comment]
@sxp-sme EventStore is not officially supported for Standalone setup. Local one-box clusters is different, it is just a one-box setup which we usually use for development (one machine representing a cluster with multiple nodes).
The error above is because there is not diagnostics storage defined for this cluster, EventStore relies on external table storage to store aggregated events, and so its apis can serve the events by periodically fetching it.

**Comment by Jaans** [comment]
@ibabou So, what about the scenario where we have a standalone setup, running in Azure (because reasons). Would we be able to configure it with Azure Blob/Table storage to get the functionality?

Also, our SF Explorer gives a message that we should enable EventStore - is there a config somewhere where we can turn this off?

**Comment by ibabou** [comment]
For the first ask, it should probably work in this case. Regarding SFX, it's the same web interface bounded with runtime, I believe in this case it doesn't differentiate if it is localbox, standalone, standalone on azure, paas, sfrp, etc.

**Comment by sxp-sme** [comment]
Thanks a lot for all responses!

> EventStore is not officially supported for Standalone setup
If it is not officially supported is there anyway any chance to get it working on a standalone cluster? Maybe by using some special data storage in the Azure cloud?

Are there any information about when this feature (EventStore) will be available for standalone clusters? I think it is a very important feature to monitor services and get necessary information about any service for example to handle error scenarios.

Thanks for any response in advance!

**Comment by VikasPullagura-MSFT** [comment]
@ibabou I have same query from CX on [Microsoft Q&A](https://docs.microsoft.com/answers/questions/1546/eventstoreservice.html), can you please share the timelines on availability of EventStone Service on SF7.0.

_EventStoreService on SF 7.0 still does not work on standalone cluster. Are there any plans to enable it on stand alone cluster?_

**Comment by MicahMcKittrick-MSFT** [comment]
@masnider @athinanthny @peterpogorski any idea on this one?

**Comment by peterpogorski** [comment]
@VikasPullagura-MSFT there are currently no plans in the near future to enable EventStore service on a standalone cluster. We are currently investigating the requirements to bring it to Standalone and hope to have it in a future release but I cannot provide any ETAs at this point.

**Comment by Jaans** [comment]
Am I missing something? Why would you not have something like this available on a production-capable platform like standalone clusters?

Looking at Azure Service Fabric, it has a working event service (not sure what it is backed by), which is still a VM ScaleSet with extensions, blob/table/queue storage, etc. underneath.

We run our own standalone cluster in Azure on self managed scale-set VMs, surely we should be able to have the same capability for event store? Moreover, the OneBox DEV cluster already has an event store service capability. Maybe it would help explain why a standalone cluster is not able have this too?

To my "outsiders" view, it appears that the implementation/capability already exists, but that standalone customers are being cripled/discriminated against to push sales to PaaS Azure Service Fabric?

I'm sure it's more complicated than my perception - but we (and others in this thread) sure would appreciate some feature parity or at least some disclaimers on documentation that standalone clusters have limited functionality.

IMO, of course.

**Comment by pisees** [comment]
Hi, just checking if there is an update for EventStore on standalone Service Fabric.

**Comment by strabu** [comment]
Yes, you feel like a 2nd class citizen if you have to run Service Fabric on premises.
And patient ones are wasting their time:

VERBOSE: System.Fabric.FabricException: System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: EventStoreService cannot be enabled on non-development multi-node standalone clusters.
 ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C65
