### ISSUE TITLE
How to build a development service fabric environment on CentOS 7 ?

### ISSUE THREAD

**Issue by iracding** [microsoft/service-fabric#392]
How to build a development of  service fabric environment on CentOS 7 ? I tried it but it failed. Can someone help me write a guidebook, just like Ubuntu ?  etc , https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-linux .

**Comment by peterpogorski** [comment]
Hi @iracding, at this time we do not have any official support for CentOS 7. We appreciate feedback and will take it into consideration for future releases. 

#please-close

**Comment by athinanthny** [comment]
#please-close
