### ISSUE TITLE
Deployment crazyness.

### ISSUE THREAD

**Issue by AlexisColes** [microsoft/service-fabric#398]
I am not really sure how to explain this.

Sometime when we update a service that is already running in service fabric it will stop the service on one node and then start it up again (maybe on the same node, maybe on another).  Which is all very expected and at this point you would have thought SF had done all the work it needed to do.  But sometimes (maybe 1 in 2) it decides to do this again!  It stops the service it has just started up and starts it again (maybe on the same node, maybe on another).  

We really struggling to work out why it is doing this and how to stop it.  Any advice would be much appreciated.

```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="RedisEntityDispatcherCasinoPkg"
                 Version="${FileHash}"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <StatelessServiceType ServiceTypeName="RedisEntityDispatcherCasinoType" UseImplicitHost="true">
      <LoadMetrics>
        <LoadMetric Name="CPU" DefaultLoad="100" />
      </LoadMetrics>
      <PlacementConstraints>#{RedisEntityDispatcherCasino-PlacementConstraints}</PlacementConstraints>
    </StatelessServiceType>
  </ServiceTypes>

  <CodePackage Name="Code" Version="#{RedisEntityDispatcherCasino-Version}">
    <SetupEntryPoint>
      <ExeHost>
        <Program>SpreadexServiceManager/Spreadex.ServiceManager.exe</Program>
        <Arguments>-consulonly</Arguments>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </SetupEntryPoint>
    <EntryPoint>
      <ExeHost>
        <Program>Spreadex.Redis.EntityDispatcher.exe</Program>
      </ExeHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="SX_ENDPOINT" Value="Casino"/>
    </EnvironmentVariables>
  </CodePackage>

</ServiceManifest>
```

**Comment by wasabii** [comment]
So, this, seems sort of minor and explainable to me. It was probably evacuating an update domain for an upgrade, determined that the shortest path was to move stuff to another specific node. But that maybe triggered some other condition (like memory usage), and so it decided it would be better served somewhere else.

**Comment by AlexisColes** [comment]
Thanks for the feed back.

For most of our services this isn't really an issue, but we do have some that provide updates and content to our sites, are expensive to start up and we can only run one instance.  If these services are shut down and started up once we get about 10-15 seconds of laggy/hanging service which although isn't ideal has been a price worth paying for in hours deployments.  However when one of these services gets shut down and started twice it causes issues on the site for over a minute.

In your example why would it then decide to stop it and start it on the same node again though?

eg.
stop service A on node 1
start service A on node 2
stop service A on node 2
start service A on node 2

we don't set any memory metrics for our services, so I don't think this would be having any effect.

|            Name            | Node Capacity | Node Load | Node Remaining Capacity | Is Capacity Violation | Node Buffered Capacity | Node Remaining Buffered Capacity | Current Node Load | Node Capacity Remaining | Buffered Node Capacity Remaining | Planned Node Load Removal |
|:--------------------------:|:-------------:|:---------:|:-----------------------:|:---------------------:|:----------------------:|:--------------------------------:|:-----------------:|:-----------------------:|:--------------------------------:|:-------------------------:|
| servicefabric:/_MemoryInMB |     26213     |     0     |          26213          |         false         |          26213         |               26213              |         0         |          26213          |               26213              |             0             |

In the latest example of this happening node 2 was running at about 15% actual memory usage.

We do use the cpu metric to try to spread the services sensibly though.  But the metrics for the target nodes were all < 50% so it shouldn't feel the need to juggle things around too much.

Do you know of any settings that we could look at to prevent this from happening?

**Comment by JustinKaffenberger** [comment]
@AlexisColes I'm not an expert by any means, but I do believe you can setup a MovementCost with each service, to give Service Fabric some hints when deciding whether or not to move services.

**Comment by maburlik** [comment]
Setting movement cost as mentioned by @JustinKaffenberger should reduce the rate of service placement changes which should improve overall service quality. These services will still be moved during static config or code upgrades so you may want to manually trigger upgrades during a self-designated maintenance period.
