### ISSUE TITLE
Service Fabric template missing in 2019 16.3.4

### ISSUE THREAD

**Issue by danegsta** [microsoft/service-fabric#401]
I have 2019 16.3.4 and I do not see the service fabric template when trying to create a new project. I do not have the gramtlyq.e04 folder. I ran the update configuration but still can not see the template. I have removed and added the service fabric tools, I have even done the whole VS repair. I also have VS 2017 and I can see the the service fabric template there.

_Originally posted by @vikasm-mittal in https://github.com/microsoft/service-fabric/issues/365#issuecomment-542315441_

**Comment by vikasm-mittal** [comment]
It is fixed now, VS installer was not able to update the web.config file in this folder C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config (for others check the installer log for any errors).
After running the installer as administrator it has installed all the cloud related templates including service fabric. I will update the other issue as well. Thanks

**Comment by danegsta** [comment]
Good to hear it's fixed!
