### ISSUE TITLE
SF Management using python and a certificate

### ISSUE THREAD

**Issue by pixelicous** [microsoft/service-fabric#407]
Hi,

Is there any place to find documentation and examples on working with service fabric and python?

I have checked both client/management sdk pages at:
https://docs.microsoft.com/en-us/python/api/azure-servicefabric/?view=azure-python

I was wondering if there are places to find documentation and quick examples on working with service fabric and the python sdk, Azure resources usual official documentation on the site is for cli/powershell mostly, any python code examples were found only in github. I have seen examples for resource group and compute resources but not for service fabric.. It would be nice to see examples and some information on the options of connecting to the cluster, getting information, fetching applications, uploading new application types, creating new instances etc

At the moment I am having trouble to understand whether it is possible to work with the client using a certificate and not authenticating using the credentials object with user/pass/tenant combo as follows:
> 
> credentials = ServicePrincipalCredentials(
>     client_id = spn_client_id,
>     secret = spn_secret,
>     tenant = tenant_id
> )
> 
> sf_client = ServiceFabricManagementClient(credentials, subscription_id)
> sf_api_client = ServiceFabricClientAPIs(credentials, subscription_id)

I also tried using the API directly and I get no results, both the python sdk or the API directly do not provide any output value, when using "application_types" for example.
https://docs.microsoft.com/en-us/rest/api/servicefabric/application/applicationtypes

https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/azure.mgmt.servicefabric.operations.applicationtypesoperations?view=azure-python

**Comment by amenarde** [comment]
To use a certificate, you should have it exported as a .PEM file, then you can create a cert authentication credentials class like is done here: https://github.com/microsoft/service-fabric-cli/blob/628b5c1044e2cab1b60147097d24f4020eaaa80e/src/sfctl/auth.py#L13 which you can pass to the SDK, like ClientCertAuthentication(r"C:\path\to\your\unencrypted.pem", None, True)

**Comment by pixelicous** [comment]
@amenarde great thanks
