### ISSUE TITLE
Failed to start the local cluster manager

### ISSUE THREAD

**Issue by randheerucsc** [microsoft/service-fabric#408]
I used to have Service Fabric properly working previously, however, right now I cannot start the cluster and we get an immediate error.  I tried with uninstall (removed everything even from registry) and install new service fabric via API installer. Still no luck.

![image](https://user-images.githubusercontent.com/54991130/67190620-e4175f80-f40d-11e9-8b74-f10b705a96ef.png)

Trying to start the Service mannually also failed . Seems this is the problem. There is not much information on event viewer also.

![image](https://user-images.githubusercontent.com/54991130/67191321-0cec2480-f40f-11e9-8002-818dbf85bfed.png)

![image](https://user-images.githubusercontent.com/54991130/67190827-4d976e00-f40e-11e9-817f-fb40d02e9e51.png)
![image](https://user-images.githubusercontent.com/54991130/67191014-8f281900-f40e-11e9-9e07-d26dc8ab50c3.png)
![image](https://user-images.githubusercontent.com/54991130/67191056-9ea76200-f40e-11e9-9bf6-d09791c14de9.png)

**Comment by maburlik** [comment]
Looks like your runtime installation has been corrupted. Check if you are able to find "Microsoft Service Fabric" under installed programs. Try to reinstall using the WebPI or direct installer link found in our release blog post.

**Comment by maburlik** [comment]
I've addressed some of these issues in the 7.0 runtime installer so please create another issue if you are still blocked. The blog post for the new release should be published within the near future.
