### ISSUE TITLE
Missing libicudata.so.55

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/service-fabric#409]
I'm attempting to run servicefabric on Linux, but the `.deb` package [here](https://apt-mo.trafficmanager.net/repos/servicefabric/pool/main/s/servicefabric/servicefabric_6.5.476.1.deb) appears to be packaged with the incorrect version of `libicudata.so`.

Running `LD_DEBUG=files FabricHost` produces the [linked output](https://gist.github.com/JamieMagee/b01b109a14d5125b88e40b88ad7fa4e5), with the key part being

```
45722:	file=libicudata.so.55 [0];  needed by /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libboost_regex.so.1.61.0 [0]
FabricHost: error while loading shared libraries: libicudata.so.55: cannot open shared object file: No such file or directory
```

Running `find`, I can see that the package includes `libicudata.so.52`

```
$ find /opt/microsoft/servicefabric -name '*libicudata.so*' -exec ls -lah {} \;
-rw-rw-r-- 1 jamie jamie 23M Oct 22 12:09 /opt/microsoft/servicefabric/bin/Fabric/Fabric.Code/libicudata.so.52
```

**Comment by worldhello126** [comment]
I have a offline sync with the JamieMagee. he run the package on U18.04 with U16.04 deb file. that's why he see this.
