### ISSUE TITLE
Fabric 6.5.676 Not Deployed to West Europe?

### ISSUE THREAD

**Issue by jpwarner67** [microsoft/service-fabric#410]
Fabric 6.5.676 was deployed to North Europe a few days ago. Not available in West Europe? 

We have paired regions North and West Europe and aren't able to deploy updated clusters until West Europe has 6.5.676. Will this version be getting deployed to West Europe (it has been 10 days already :))

**Comment by jpwarner67** [comment]
Closing from no response and asking the question on another support vector ...

**Comment by Jaans** [comment]
@jpwarner67 May I ask which "support vector" you used? ;-)
