### ISSUE TITLE
Cluster only uses 125 nodes

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#413]
I have a Service Fabric cluster composed of three scalesets(availability zones rocks.) I just scaled all three scalesets to 50 nodes each, but in the SF Explorer, it's showing only 125 nodes. If I look at each scaleset, I clearly see 50 nodes in each. Any reason SF wouldn't use 25 of the available nodes? Thanks.

**Comment by maburlik** [comment]
To get the right people looking at this such that you can get it resolved in a timely manner you may want to create a support ticket through the portal.

**Comment by jackbond** [comment]
I'm doing this as part of scalability testing, and I've just scaled my cluster up to 50 nodes in each scaleset, and this time I'm seeing 135 nodes. There's definitely an issue here. I've just submitted a support request. It's gonna cost me at least $60/hr to keep this environment up, so hopefully I'll hear back soon. :)
