### ISSUE TITLE
Move release_notes on old GitHub for Service Fabric to this one.

### ISSUE THREAD

**Issue by pisees** [microsoft/service-fabric#419]
Given the new repo, I think it may make sense to move release_notes: https://github.com/Azure/service-fabric/tree/master/release_notes, to new Service Fabric GitHub: https://github.com/Microsoft/service-fabric

**Comment by athinanthny** [comment]
Release notes have been moved here https://github.com/microsoft/service-fabric/tree/master/release_notes
