### ISSUE TITLE
gRpc Sample app or documentation?

### ISSUE THREAD

**Issue by ToFab** [microsoft/service-fabric#422]
I have a sf cluster that uses .net framework 4.6.x and Service.Fabric.Wcf for internal communication. The only thing the prevents me from upgrading to .net core is that I cannot find any documentation or sample code on how to use gRpc instead of wcf with service fabric.

I am aware of the wcf did not make the cut to .net core and that is must be a major undertaking to come up with a replacement. I don't know how to formulate my question without sounding unreasonable, but does anyone have any info on when we can start to use gRpc with Service Fabric Reliable Services? And if that is already possible, then how do i do it?

**Comment by ToFab** [comment]
I have come to the conclusion that it is me that is being impatient. So I am closing this case again

**Comment by TaviTruman** [comment]
@ToFab there is a working sample of how to implement grpc in service fabric; I'll find the link and send it to you.

**Comment by TaviTruman** [comment]
@ToFab https://github.com/mholo65/service-fabric-grpc-playground/blob/master/ServiceFabric.Grpc.Client/Client.cs#L48

https://github.com/Haishi2016/ProgrammingServiceFabric/tree/master/Chapter-2/gRPCApplication
