### ISSUE TITLE
Service Fabric -Stateless ASP.Net Core - Support for ASP.Net Core 3.0 gRPC

### ISSUE THREAD

**Issue by sansindia85** [microsoft/service-fabric#425]
I had created a Service Fabric project called "Stateless ASP.Net Core" with ASP.Net Core 3.0 WebAPI. I replaced WebAPI code with ASP.Net Core 3.0 gRPC middlewear based on MSDN documentation.

MSDN Documentation link : https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-3.0&tabs=visual-studio

Is it technically possible to use ASP.Net Core 3.0 gRPC with Stateless ASP.Net Core? If yes, how to configure and use it?

**Comment by keikhara** [comment]
@sansindia85  Please report this to https://github.com/microsoft/service-fabric-aspnetcore/issues.

**Comment by sansindia85** [comment]
Moved to Kubernetes. I'm no longer looking into Service Fabric.

**Comment by chenzuo** [comment]
when will you complete the private deployment on linux on-premises!
