### ISSUE TITLE
Memory problems after moving to Linux cluster

### ISSUE THREAD

**Issue by radderz** [microsoft/service-fabric#427]
We have seen issues with service fabric since moving from a self hosted windows environment to an azure cluster running Linux a few months ago. We have invested a lot of time trying to narrow down the issues but have had no luck.

We often see the "Fabric" application run upwards of 9GB of memory and are having to restart our servers regularly to fight this problem.

![image](https://user-images.githubusercontent.com/1195471/70038775-b1bc6d00-161d-11ea-9269-801bfd1517a6.png)

On the our services themselves, they are constantly using large amounts of memory overtime and forcing a garbage collection doesn't help at all. Running these same services in our test windows cluster doesn't show any of these issues, the Linux version seems far from reliable when the servers keep running out of memory for no apparent reason. Changing the services to workstation garbage collection has helped reduce some of the cases of memory creep, but even then they still use 200MB-300MB vs 20MB-50MB on windows.

Is anyone able to explain if there is a known configuration change needed? The cluster is running the latest version of V6.x, and we are using a range of .NET Core 2.1, 2.2, 3.0, with all of them showing the same issues. We use a fair bit of remoting, and this seems to increase the memory creep quite quickly, either ingress or egress function calls over remoting.

We are using a mixture of Stateless and Stateful services, all showing similar symptoms.

**Comment by worldhello126** [comment]
If you are Microsoft Internal customer, please fire an ICM incident to ServiceFabric Group. and we will need to collect a core dump of the Fabric process, then we can see which one is the root cause.

and If you are external user, please also help to get a core dump for us. thanks

**Comment by pkcsf** [comment]
@radderz To investigate the issues further, could you open a support ticket from Azure portal using https://azure.microsoft.com/en-us/support/create-ticket/, and let us know the ticket number.
 
Please refer https://azure.microsoft.com/en-us/support/options/ for details on support options.

**Comment by radderz** [comment]
@pkcsf it seems like I'd have to go through our CSP just to create a ticket which seems silly when it is to do with the framework rather than something they can help me with. I assume there is no way to create a ticket outside of that?

**Comment by pkcsf** [comment]
@radderz  Please note that for investigating this issue, we need review the  core dump for the process and need your consent for reviewing the dump file, when you creating the ticket through CSS these will  be taken care, and that’s the one of the reason, why I suggested you to create a support ticket, and as far as I know , If you have azure subscription, it’s pretty much straight forward . 

Any way since you have some challenges in creating support ticket, are you comfortable sharing a core dump with Microsoft ? If yes, let us know where to grab it by dropping an email my MS ID, pkc@microsoft.com, hope this work for you.

**Comment by radderz** [comment]
@pkcsf yes we can do that, support tickets are usually straight forward but the CSP system is in the middle unfortunately. I'll flick you an email and we can go from there. Thanks!

**Comment by radderz** [comment]
The latest versions since 7.2 haven't had this problem, we have a problem when sending lots of messages between services, however we implemented a way to disable the log messages that were being sent over remoting, so that they are only flowing to our dashboard when we need them.
