### ISSUE TITLE
Service Fabric System service placement

### ISSUE THREAD

**Issue by mj-uk** [microsoft/service-fabric#428]
Hi there - is it expected behaviour that Service Fabric places the system services on our worker nodes?

We have a 5 "Primary" nodes with Is Seed Node set to true however Service Fabric is placing Naming Service (and others) replicas on my other worker nodes. Some of these are running in a DMZ which is then causing issues with deployments. 

Can I restrict the placement of these to certain nodes if this is expected?

**Comment by peterpogorski** [comment]
Hi there - are the worker nodes running a separate node type? Did you make any changes to the cluster configuration via Fabric settings?

**Comment by peterpogorski** [comment]
Please reopen if this issue persists.
