### ISSUE TITLE
Service Fabric breaks standalone cross-compilation of an ASP.NET Core app

### ISSUE THREAD

**Issue by vmendi** [Microsoft/service-fabric#43]
- On a Windows box, using Visual Studio, create a new solution.
- Select "Cloud" -> "Service Fabric Application" for the solution type.
- Select "Stateless ASP.NET Core" as the template.
- Edit Stateless1.csproj file to change the RuntimeIdentifier from "win7-x64" to "linux-x64".
- Edit ServiceManifest.xml to change the program entrypoint from "Stateless1.exe" to just "Stateless1"

Now, building and packaging/publishing the solution creates a standalone Linux build (all dependencies included). When publishing to the Ubuntu 16.04 cluster, we get an error:
```
Error event: SourceId='System.Hosting', Property='CodePackageActivation:Code:EntryPoint'. There was an error during CodePackage activation.The service host terminated with exit code:134
```

If we try to execute the service executable manually, we get this error:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted (core dumped)
```

If we open Stateless1.deps.json we see that the required version is actually 4.3.0 (not 4.2.0).

We suspect that there may be a problem with Service Fabric's build process (msbuild tasks) interfering with asp.net core cross-compilation to Linux.

**Comment by vturecek** [comment]
@amanbha have you seen this happen before?
