### ISSUE TITLE
Guidance around secret encryption key rotation

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/service-fabric#432]
The guidance located [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management-windows) describes how one creates a self-signed certificate, installs it to the VMs in the cluster and how secrets must be encrypted using the same certificate. However, the certificate I created with this approach has a one-year expiration. 

How does one roll secrets to use with a new certificate in a year's time? Would all secrets have to be re-generated and the secret values re-deployed with the new cert?

**Comment by dragav** [comment]
We recommend using the Service Fabric [Secret Store](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-store) for encrypted settings. 

If you want to continue using an encryption certificate, then yes, the procedure would entail re-encrypting the settings with the new certificate, provisioning the new certificate into the cluster (side by side with the older one), and upgrading/updating the application with the new settings and certificate.
