### ISSUE TITLE
Service Fabric 7.0 GA or NOT?

### ISSUE THREAD

**Issue by fbuser1** [microsoft/service-fabric#442]
![image](https://user-images.githubusercontent.com/36403476/73173029-115e6280-410d-11ea-80dc-18b39048843c.png)

Hey Service Fabric fans! I'm just curious when 7.0 release will be rollouted for Automatic Service Fabric upgrade mode? Even if I'm creating new sf cluster I've got not latest 6.5.676.9590 version 👎

**Comment by jjqquu** [comment]
Any ETA for 7.0 release?

**Comment by athinanthny** [comment]
We plan to resume automatic roll out of most recent version of 7.0 release this week. Please watch out for release annoucments here: https://techcommunity.microsoft.com/t5/azure-service-fabric/bg-p/Service-Fabric

**Comment by fbuser1** [comment]
> We plan to resume automatic roll out of most recent version of 7.0 release this week. Please watch out for release annoucments here: https://techcommunity.microsoft.com/t5/azure-service-fabric/bg-p/Service-Fabric

Any updates?

**Comment by athinanthny** [comment]
@fbuser1  we did resume roll-over and here is the blog on the latest 7.x release version https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-0-third-refresh-release/ba-p/1156508

**Comment by gkhanna79** [comment]
@fbuser1 Based upon the response from @athinanthny above, any concerns in closing this?

**Comment by jjqquu** [comment]
Thanks for the update. 

I feel a little bit confused about 2 things:
1) where and when can we get access to the source code release 7.0?  
2) why you put release notes in the obsoleted GitHub repository? 
https://github.com/Azure/service-fabric/tree/master/release_notes

**Comment by gkhanna79** [comment]
@jjqquu We are still working through the plans of open-sourcing 7.0 - there is no ETA yet.

Regarding the release notes, good catch. @athinanthny @masnider Can we please move the release notes to this repo from https://github.com/Azure/service-fabric - the latter already says that we have moved everything to this one :)

**Comment by jjqquu** [comment]
Txs @gkhanna79 
Just  curious why you guys can't open  source it immediately after  V7.0 GA?

**Comment by OranguTech** [comment]
> @jjqquu We are still working through the plans of open-sourcing 7.0 - there is no ETA yet.
> 
> Regarding the release notes, good catch. @athinanthny @masnider Can we please move the release notes to this repo from https://github.com/Azure/service-fabric - the latter already says that we have moved everything to this one :)

It's a little worrying to me that this had to be "caught", and still not fixed. See also #419

**Comment by athinanthny** [comment]
@OranguTech All Release notes have been moved to https://github.com/microsoft/service-fabric/tree/master/release_notes
