### ISSUE TITLE
Service Fabric Third Refresh release -NET SDK Link broken

### ISSUE THREAD

**Issue by tbertenshaw** [microsoft/service-fabric#444]
On
https://github.com/Azure/service-fabric/blob/master/release_notes/Service-Fabric-70CU3-releasenotes.md
The link for the .NET SDK below gives a 404
https://download.microsoft.com/download/8/b/2/8b21dcf8-4909-4aaa-8dcb-64c0a37a2d9c/MicrosoftServiceFabricSDK.4.0.466.msi

**Comment by athinanthny** [comment]
@tbertenshaw  Looking into it. Will update release notes by EOD tomorrow.

**Comment by athinanthny** [comment]
@tbertenshaw  Resolved download link in https://github.com/Azure/service-fabric/blob/master/release_notes/Service-Fabric-70CU3-releasenotes.md

**Comment by gkhanna79** [comment]
@tbertenshaw Based upon @athinanthny response, any concerns in closing the issue?

**Comment by tbertenshaw** [comment]
Can close now thanks. Latest download link works.
