### ISSUE TITLE
Service Fabric Unable To Find Certificate By Common Name

### ISSUE THREAD

**Issue by keggster101020** [microsoft/service-fabric#445]
Hi, 

I'm using an ARM template to deploy a service fabric cluster and VMSS that is backing that cluster.
On the VMSS I have the Key Vault extension installed so that I am able to pull the cluster certificate from a keyvault onto the VMSS machines. 

However, during the ARM rollout I'm getting the following error:

>{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension '<VMSSName>_ServiceFabricNode'. Error message: \\\"Cannot find certificate with 'FindBySubjectName' '<cn>' in store 'My'\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}

I have remoted into all of the VMSS machines and a certificate with subject cn=\<my subject name\> is installed in `local computer/personal/certificates`

-------
Checking the extension logs on the machine I can see that all but one machine has the log line in command execution logs for the service fabric node plugin:

>Found 1 certificates matching FindBySubjectName value 'my common name'

Despite that certificate being installed on the machine.

Any help would be appreciated. Thanks

**Comment by gkhanna79** [comment]
@linmeng08 Can you PTAL?

**Comment by keggster101020** [comment]
@gkhanna79 what do you mean by PTAL? 

I was able to alleviate this by deleting the SF cluster resource in the portal and re-deploying. But I kept the VMSS backing the cluster. 

Luckily this was a non production cluster so I didn't have any worries removing the cluster. But I'm worried if this happens again on a non-prod cluster I'll be in a stuck state.

**Comment by linmeng08** [comment]
@keggster101020 Can you share your subscription Id and resource group for the ones that you had this problem? Also +@romendmsft

**Comment by keggster101020** [comment]
@linmeng08 Sub id: 0241a5ae-8fa9-4f6c-984c-9696d4c812ad

Resource Group: SupportService-WestUS2
Deployment ID: 95E06F956811427798CA6652C3D14F370ServiceFabric.Resource

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.

We have solid TSG's for issues like this fwiw. https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/tree/master/Security#category

Latest api json here https://docs.microsoft.com/en-us/azure/templates/microsoft.servicefabric/2020-03-01/clusters
