### ISSUE TITLE
Deploy and Debug to local cluster with F5 fails without error: unsupported debug options

### ISSUE THREAD

**Issue by abatishchev** [microsoft/service-fabric#446]
My dev environment:

```
Microsoft Visual Studio Enterprise 2019
Version 16.4.5
VisualStudio.16.Release/16.4.5+29806.167
Microsoft .NET Framework
Version 4.8.03752

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio
```

SF version:

```
Microsoft Azure Service Fabric
6.5.676.9590

Microsoft Azure Service Fabric SDK
3.4.676.9590
```

Steps to reproduce:

1. Open under normal (non-admin) user
2. Create new project: Service Fabric Application (targeted .NET Framework 4.7.2 by default)
3. Add Stateless ASP.NET Service (targeted .NET Core 3.0 by default)
4. Wait installation to complete. press F5

Expected result: application is deployed to local cluster (in 1-node mode) and debugger is attached

Actual result: nothing happens, VS output reads the following:

```
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
```
Just in case the only NuGet package installed:
```
<PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.4.676" />
or
 <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="4.0.466" />
```

When I go to sfproj -> Properties -> Debugging I see this:

![image](https://user-images.githubusercontent.com/351644/75102119-628e3480-559b-11ea-9ff2-682aefdde86b.png)

Nowhere close as in [this SO post](https://stackoverflow.com/questions/43089847/service-fabric-use-refresh-mode-for-faster-debugging):

![image](https://i.stack.imgur.com/Mv8t1.png)

As as soon as I changed it to `Managed Only` it started to work properly.

Also can be same issue as [this report](https://developercommunity.visualstudio.com/content/problem/824688/service-fabric-debug-deployment-to-local-cluster-f.html) on Developer Community which apparently wasn't thoughtfully investigated.

**Comment by gkhanna79** [comment]
@amanbha Please check if this is SDK or VS integration issue and reroute as appropriate.

**Comment by amanbha** [comment]
@dbreshears and @anantshankar17 could you please help with this?

**Comment by dbreshears** [comment]
@abatishchev.    Service Fabric  requires running VS as Admin and you should see something like this below in the output window when F5 under normal user and and the cluster is not running.  If the SF local cluster is running, then you should get a prompt to restart VS under elevated permissions.  Can you create a new project and try running as VS elevated?

>Local Service Fabric Cluster is not running...
3>Please wait while we start the Local Service Fabric Cluster. This may take few minutes...
3>EnsureAdminPrivileges : Not running as administrator. You need to run Visual Studio with administrator privileges to 
3>start the local cluster.
3>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\DefaultLocalClusterSetup.psm1:70 char:9
3>+         EnsureAdminPrivileges "Not running as administrator. You need ...
3>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
3>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,EnsureAdminPrivileges
3> 
3>ScriptHalted
3>At C:\Program Files\Microsoft SDKs\Service Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:8 char:9
3>+         throw
3>+         ~~~~~
3>    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
3>    + FullyQualifiedErrorId : ScriptHalted
3> 

What version of the Microsoft.VisualStudio.Azure.Fabric.MSBuild is in packages.config of the SF Application project?    Latest is 1.6.9

Can you share the contents of your web1.csproj?

When you mention setting to  "managed only",  can you share exactly where  you are setting this?

Your properties dialog looks outdated. Can you share a screen shot of the "Create new Service Fabric Service" dialog to rule out a SxS issue we had  in https://developercommunity.visualstudio.com/content/problem/660096/service-fabric-project-not-loading.html.    You would also know if you have the extension folder as mentioned in that post.

My properties dialog looks like the following in 16.4.5

![image](https://user-images.githubusercontent.com/3432571/75177604-5f09c300-56eb-11ea-83b6-9ef9b3aeb998.png)

**Comment by abatishchev** [comment]
Spoke offline, please let me know how to proceed.

**Comment by dbreshears** [comment]
Spoke with @abatishchev.  The problem is no longer reproducing unfortunately and one can theorize that this strange behavior (no output and prompt when running under non-admin) could have been due to MEF cache corruption.     If it reproduces again, please re-activate
