### ISSUE TITLE
BackupRestoreService, does it accept policies with pre-encrypted credentials?

### ISSUE THREAD

**Issue by JustinKaffenberger** [microsoft/service-fabric#450]
We've recently started utilizing the Backup/Restore feature in Service Fabric and noticed that service is configured with a `SecretEncryptionCertThumbprint`. Its obvious that this will encrypt any unencrypted credentials that are provided with backup policies. My question is, if I pre-encrypt the credentials with the same certificate that was specified in `SecretEncryptionCertThumbprint` using `Invoke-ServiceFabricEncryptText`, and then provide that encrypted string in the policy, will the BackupRestoreService recognize this and decrypt as necessary?

I ask because this would help us from a DevOps perspective, ensuring we aren't leaving credentials in plaintext at any point during the deployment process.

**Comment by khandelwalbrijesh** [comment]
@JustinKaffenberger , We don't have any solution for this problem for now. There is no input taken from user in storage description which tells BRS if the credentials are already encrypted by the user or not. 
We encrypt only on the basis if SecretEncryptionCertThumbprint is provided or not. So, if you would encrypt the credentials and also input SecretEncryptionCertThumbprint to BRS then, double encryption will occur and policy will be useless.
