### ISSUE TITLE
Where to find download links of SF 7.0 Third Refresh release?

### ISSUE THREAD

**Issue by ckvckv** [microsoft/service-fabric#451]
WHere to find download links of SF 7.0 Third Refresh release?
As 4th refresh release is released the URL we use to download the package points to the 4th refresh release. 
https://go.microsoft.com/fwlink/?linkid=839354

But in 4th refresh release there is a breaking change which says that customers have to upgrade to 3rd refresh release before moving to the 4th refresh release in some cases. But where is the link for downloading 3rd refresh release runtime?
We have on-premise clusters and the clusters are upgraded offline.

**Comment by athinanthny** [comment]
Here is the blogpost for 7.0 third refresh release. https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-0-third-refresh-release/ba-p/1156508

Links are always available in release notes published with each release.

**Comment by ckvckv** [comment]
THanks for the info. Since it is in the right side of the table I missed to check it by scrolling to the right. Here after no confusion.
