### ISSUE TITLE
Incremental actor backup settings not working

### ISSUE THREAD

**Issue by santo2** [microsoft/service-fabric#456]
Hi, 

**Context**
We have a cluster of 5 nodes, and have around 6-7 actor services. 
for the services I want to address in this issue, we have 10 partitions.

We have a backup policy in place with an incremental backup for each 6 hours, this was first set to 15 minutes, but a Microsoft Engineer suggested us to put it longer. (we thought an incremental backup wouldn't be this big?)

**The issue:**
Instead of getting an incremental backup each interval, we always get a full backup, so the incremental backup is not working. This results into a high network traffic each interval.

This is our policy
```
 {
            "AutoRestoreOnDataLoss": true,
            "Name": "sfbackuppolicy",
            "MaxIncrementalBackups": 20,
            "Schedule": {
                "ScheduleKind": "FrequencyBased",
                "Interval": "PT6H"
            },
            "Storage": {
                "StorageKind": "AzureBlobStore",
                "ConnectionString": "****",
                "ContainerName": "servicefabricbackups",
                "FriendlyName": ""
            },
            "RetentionPolicy": {
                "RetentionPolicyType": "Basic",
                "RetentionDuration": "P10D",
                "MinimumNumberOfBackups": 0
            }
        }
```
Performance of the machines is fine, machines are not running out of cpu or memoy.

the support engineer mentioned this exception to us, which he found in the logs, but we still don't know what to do with this?
```
"(5d63c01d-2ddf-4e53-9496-fd79eef67c8f:132258873624181157) EndBackupLocal: error=FABRIC_E_INVALID_BACKUP_SETTING"
"AsyncCalloutAdapter-42758470: end delegate threw an exception
              System.Fabric.FabricException: Invalid backup setting. E.g. incremental backup option is not set upfront ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C36
```
I can't seem to find anything about what this means? No documentation, no other experiences.

Where can we find more logging about what is going wrong?

What can I change, do, test to see what is wrong?

**Comment by athinanthny** [comment]
@khandelwalbrijesh  Please can you review about incremental backup issue and provide guidance.

**Comment by santo2** [comment]
support has been changed of severity and they are helping us in the right direction, but we aren't there yet. 

Their last reply was:
Could you help to double check EnableIncrementalBackup value if possible, It would be recommended to set EnableIncrementalBackup  as true in LocalEseStoreSetting  object to enable the incremental backup. 

I searched for this but didn't immediately find the way that I can set this

**Comment by santo2** [comment]
this settings seems to be the one missing:
EnableIncrementalBackup can be set in Settings.xml (service level) under 

“<ActorName>LocalStoreConfig”. For example, the following is how it should look.

```
<Section Name="ReminderCounterActorServiceLocalStoreConfig">
  <Parameter Name="EnableIncrementalBackup" Value="true" />
</Section>
```

When it works I'll make sure to close the post. Could this be added to the documentation pages of the BackupRestore API?

**Comment by santo2** [comment]
the above settings helped.
