### ISSUE TITLE
SecretsCertificate X509FindType="FindBySubjectName" is strictly case sensetive: error FABRIC_E_CERTIFICATE_NOT_FOUND

### ISSUE THREAD

**Issue by abatishchev** [microsoft/service-fabric#459]
I'm having a .NET Core 3.1 service with Kestrel and SSL certificate running under Network Service. In order SF to ACL the cert to the account, I'm having the following sections in the application's manifest:

```xml
  <Parameters>
    <Parameter Name="MyService_SSL_Certificate_SubjectName" DefaultValue="" />
  </Parameters>
  ...
  <Principals>
    <Users>
      <User Name="NetworkServiceUser" AccountType="NetworkService" />
    </Users>
  </Principals>
  <Policies>
    <SecurityAccessPolicies>
      <SecurityAccessPolicy ResourceRef="SSLCert" PrincipalRef="NetworkServiceUser" GrantRights="Full" ResourceType="Certificate" />
    </SecurityAccessPolicies>
  </Policies>
  <Certificates>
    <SecretsCertificate X509FindType="FindBySubjectName" X509FindValue="[MyService_SSL_Certificate_SubjectName]" Name="SSLCert" />
  </Certificates>
```

Then I deploy my application using ARM. But I've got a typo (a copy&replace mistake) and passed parameter with the subject name in incorrect case:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "appPackageUrl": {
      "value": "bin\\MyService.Application.sfpkg"
    },
    "applicationTypeVersion": {
      "value": "1.0.0.0"
    },
    "MyService_SSL_Certificate_SubjectName": {
      "value": "MYSERVICE.example.com"
    }
  }
}
```

Now application fails to start with no traces in Event Log -> Applications.

However, in Microsoft-ServiceFabric\Admin I'm seeing this error:

>Failed to get private key file. x509FindValue: MYSERVICE.example.com, x509StoreName: My, findType: FindBySubjectName, Error FABRIC_E_CERTIFICATE_NOT_FOUND

While the actual certificate's subject name is just `CN=myservice.example.com`. Why it's apaprently strictly case sensitive? PKI is usually not.

**Comment by dragav** [comment]
Validation is not case sensitive; finding is.

**Comment by abatishchev** [comment]
Can both be case insensitive? Or at least consistent

**Comment by dragav** [comment]
A ‘common name’ (which is short for distinguished subject common name) is very much case sensitive. When a certificate is evaluated for an SSL policy, a server certificate’s Subject Alternative Name (SAN) which is a DNS name will be evaluated case-insensitively. A CN may be evaluated case-insensitively depending on the flags passed to the chain policy verification function.

SF does not support finding certs by SAN yet; it only supports by CN, and the comparison must be case sensitive, because there are no guarantees the CN represents a DNS name.

**Comment by abatishchev** [comment]
@athinanthny, @dragav please see if we should rather close the issue, thanks!

**Comment by dragav** [comment]
Closing out, thanks @abatishchev. This has been addressed/explained here: https://docs.microsoft.com/en-us/azure/service-fabric/cluster-security-certificates
