### ISSUE TITLE
IAsyncEnumerable and C#8.0

### ISSUE THREAD

**Issue by juepiezhongren** [Microsoft/service-fabric#46]
IAsyncEnumerable is not compatible with the current propositionfor C#8.0，will it be changed inthe future？ Considering it may be the most important imple for IAsyncEnumerable，we want compability！

**Comment by vturecek** [comment]
+1 for compatibility. We can change it in the future as language support in C# for IAsyncEnumerable surfaces. Until then, the best option has been to define our own interface. Happy to explore other options as well.

**Comment by samedder** [comment]
@vturecek do you want to follow this up with an enhancement in the future?
