### ISSUE TITLE
Error deploying service fabric application from visual studio

### ISSUE THREAD

**Issue by alex-carbonium** [microsoft/service-fabric#47]
If you use parameters for CpuCores in the ServicePackageResourceGovernancePolicy:
<ServicePackageResourceGovernancePolicy CpuCores="[Docker_CpuCores]" />

It is impossible to deploy project from visual studio. If you hardcode amount of cores it works. Also it works if you deploy from powershell.

**Comment by alex-carbonium** [comment]
The error is also not very informative:
Error in XML document (xxx, yyy)

**Comment by anmolah** [comment]
@alex-carbonium does it work when using parameters and deploying using Powershell?

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
