### ISSUE TITLE
Modify configuration setting for Security/SlowApiThreshold 

### ISSUE THREAD

**Issue by chiokejjones** [Microsoft/service-fabric#48]
We have a couple global on-premise clusters where at times all or some of the nodes display this warning:

```
Unhealthy event: SourceId='System.FabricNode', Property='SecurityApi_CertGetCertificateChain', HealthState='Warning', ConsiderWarningAsError=false.
Security API:call duration = 14.995, configuration Setting Security/SlowApiThreshold = 10.000
```

Is there any way to modify this configuration setting?  Would you be able to provide any clues as to what it's looking for when this warning is triggered?

**Comment by leikong** [comment]
This indicates that the machine cannot access CRL (certificate revocation list) distribution endpoint of some CA signed certificate you are using, such endpoint is usually a http endpoint.

If you do not care about X509 certificate revocation checking, then you can either disable CRL checking completely or using longer warning threshold.

If you want to keep CRL checking, then you should figure out why the machine cannot access CRL distribution endpoint. CRL distribution point is an extension in your certificate.

**Comment by chiokejjones** [comment]
Thanks @leikong 

I'm able to download the CRL list from both the issuing and root CAs without issue.  The random warnings probably indicate an issue with network latency.  Is there a way to extend the warning threshold?

**Comment by leikong** [comment]
Did you try it form the machine that reported the issue? Also, did you check all CRLs used by ALL your certificates.

If you can share the traces, I can tell you which certificate chain was causing the issue.

You can  set this in "fabricSettings" JSON element by adding a new element, the following increases the warning threshold from default 10 seconds to 30 seconds
{
        "name": "Security",
        "parameters": [
          {
            "name": "SlowApiThreshold ",
            "value": "30"
          }
        ]
      }

**Comment by leikong** [comment]
If you want to share your trace, you can search "collect logs for support purposes" on the following page, and please share the trace around the warning reporting time.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-for-windows-server#get-support-for-the-service-fabric-for-windows-server-package

**Comment by chiokejjones** [comment]
@leikong Thanks again for the information.  Which log file should I share?  Is it one of the *.dtr.zip files?

**Comment by leikong** [comment]
@Rakshita Tandon<mailto:ratando@microsoft.com>
I believe it is the .dtr.zip files, can you confirm to the customer, thanks.

**Comment by chiokejjones** [comment]
`Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
ValidationException: Section 'Security' and Parameter 'SlowApiThreshold ' is not allowed.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath .\C ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa   ...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterConfigurationUpgrade`

Does this setting only apply to Azure deployments?  I'm working with on-premise clusters.

**Comment by chiokejjones** [comment]
[a8d57c351fa62a4f1c95d8e89456be03_fabric_traces_6.1.456.9494_131660633404611103_10_00636572536231583133_0000000000.dtr.zip](https://github.com/Microsoft/service-fabric/files/1835171/a8d57c351fa62a4f1c95d8e89456be03_fabric_traces_6.1.456.9494_131660633404611103_10_00636572536231583133_0000000000.dtr.zip)

I've attached the fabric trace from a node that consistently displays the slowapithreshold warning.

**Comment by leikong** [comment]
this file does not have the warning report trace, can you share more files before the report time?
thanks.

**Comment by chiokejjones** [comment]
[fabric_traces.zip](https://github.com/Microsoft/service-fabric/files/1835225/fabric_traces.zip)

No problem.  This zip contains multiple traces.  Let me know if it's still missing the warning report trace.

**Comment by leikong** [comment]
@Rishi Sinha (rsinha@microsoft.com)<mailto:rsinha@microsoft.com>@Rakshita Tandon<mailto:ratando@microsoft.com>
Is there a workaround for this restriction?

**Comment by leikong** [comment]
It looks like CRL downloading for certificate 4a87da4e08b643ada1486eea748fa9c6eabceb99 was slow, have you verified CRL downloading on the warning reporting machine B1P1VSF1NOD0001 ?

2018-3-21 18:37:11.378	Transport.SecurityContextSsl	4044	2760	incoming cert: thumbprint = 4a87da4e08b643ada1486eea748fa9c6eabceb99, subject='O=Kroll Ontrack, CN=ClientServiceFabricCluster1KOI', issuer='DC=local, DC=edp, DC=ccp, CN=ccp-B1P1VSH1CAI0001-CA', issuerCertThumbprint=09746e4a5436db3bc804c185c88304cd2ec9c1c4, NotBefore=2018-01-17 16:17:47.000, NotAfter=2058-01-07 16:17:47.000

**Comment by leikong** [comment]
It looks like there is an extra space at the end of 'SlowApiThreshold ', probably my copy-paste error in the example above.

**Comment by chiokejjones** [comment]
@leikong Thanks for your help on this.  The CRLs are accessible with <2s response times from the target node.  I ended up updating the cluster configuration with new the 'slowapithreshold' parameter and the warnings have gone away.  I'll stick with this as a workaround for the two problem environments.  Thanks again.

**Comment by leikong** [comment]
The "slow" security API also downloads Windows disallowed CTL, is it possible that your machine cannot download Windows disallowed CTL? Do they have access to public internet?

**Comment by chiokejjones** [comment]
No, our servers do not have public internet access.  We'll have to explore either disabling this check or creating a proxy to download the CTLs.

Yes, there are only two issuers in the certificate chain.

**Comment by leikong** [comment]
If you want to disable CTL downloading for service fabric, you can add the following to fabricSettings:
{
  "name": "Security",
  "parameters": [
  {
    "name": "CrlCheckingFlag",
    "value": "4"
  }
  ]
}
{
  "name": "Federation",
  "parameters": [
  {
    "name": "X509CertChainFlags",
    "value": "4"
  }
  ]
}
