### ISSUE TITLE
FabricCommon.dll not found when starting local cluster offline

### ISSUE THREAD

**Issue by ysabih** [microsoft/service-fabric#482]
I've installed SF runtime 7.0.466.9590 and SDK 4.0.466 in my Windows 10 machine connected to enterprise VPN and we connect to the internet using a proxy, when I try to start the local cluster I get the error “Unable to load DLL 'FabricCommon.dll': The specified module could not be found”. The weird thing is that this happens only when I'm offline.
I installed the same runtime and sdk on my personal laptop (Windows 10) and it works normally both online and offline.

**Comment by maburlik** [comment]
In an admin console try running
> where FabricCommon.dll

and if you find multiple entries, it's likely one of these is conflicting with your SF installation and is being loaded from a foreign location. Remove the foreign drop if it is not coming from a subdirectory of "%programfiles%\Microsoft Service Fabric". Feel free to create another thread if you are still hitting issues.
