### ISSUE TITLE
What happens during application deployment?

### ISSUE THREAD

**Issue by Pete1138** [Microsoft/service-fabric#49]
I asked this question on the Azure Service Fabric forum originally ( https://social.msdn.microsoft.com/Forums/en-US/9ef80876-a070-4e0d-a0f7-821401d62d94/what-happens-during-application-deployment?forum=AzureServiceFabric&prof=required ), and I was asked to post it here - apologies if it is not relevant.

I would like to know some more detail about the deployment process, basically so that I can hack together a faster solution for development/QA purposes. I have already done this for updating services on my local machine with a simple script that kills the process and replaces the binaries in the cluster before it restarts (obviously this is not safe in terms of maintaining quorum etc). As I typically work on 1 service at a time, I can build->deploy->attach to process in a few seconds, whereas deploying in visual studio (even using Refresh Application mode) takes several minutes.

I was going to extend this to application upgrades (and fresh app deployments) but I'm not sure what role the different processes (FabricApplicationGateway,FabricDCA, FabricGateway,FabricHost etc) have and how to have the cluster pick up a new version in the fastest way possible (e.g. restarting nodes is quite slow, killing any of the Fabric*.exe processes kills the cluster).

Thanks!

**Comment by MikkelHegn** [comment]
@Pete1138  To give a little background on how we dealt with this in the VS tooling. What you described above is more or less how we do "Refresh Application Mode" in Visual Studio. It's the fastest way to replace the binaries (we actually symlink the bin folder in the service to the build output folder to support updating static files in web scenarios). Theres a bit more explanation here: https://github.com/Azure/service-fabric-issues/issues/660

For this feature we decided to make all other operations against services and applications (updating descriptions, parameters etc.) to be full deployments as it's the safest path.
For app upgrades, the fastest way to run an upgrade i by using the UnMonitoredAuto upgrade option.

Don't know if you can hack the ImageStore (which is where app definitions and binaries lie) @oanapl would know more, but you are basically trying to mess with core parts of the reliably subsystem (versioning and rolling upgrades) of the platform.

**Comment by Pete1138** [comment]
Thanks @MikkelHegn. I'm going to do a bit more experimentation and see what happens.
