### ISSUE TITLE
Deploying Service Fabric Timeout issue. 

### ISSUE THREAD

**Issue by Simo-51** [microsoft/service-fabric#493]
I am trying to create a standalone service fabric on 4 VMs (for MS Dynamics365)
but unfortunately I got the below errors when executing the deployment script.
firewall is off on all VMs and i couldn't find any issue on windows eventlog 
Any help will be really nice.

PS C:\MSASF> .\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.json -AcceptEULA

Trace folder already exists. Traces will be written to existing trace folder: C:\MSASF\DeploymentTraces
Creating Service Fabric Cluster...
If it's taking too long, please check in Task Manager details and see if Fabric.exe for each node is running. If not, please look at: 1. traces in Deploym
entTraces directory and 2. traces in FabricLogRoot configured in ClusterConfig.json.
Trace folder already exists. Traces will be written to existing trace folder: C:\MSASF\DeploymentTraces
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.
Creating Service Fabric Cluster...
Processing and validating cluster config.
Configuring nodes.
Default installation directory chosen based on system drive of machine '192.168.8.134'.
Copying installer to all machines.
Configuring machine '192.168.8.134'.
Configuring machine '192.168.8.132'.
Configuring machine '192.168.8.133'.
Configuring machine '192.168.8.131'.
Machine 192.168.8.131 configured.
Machine 192.168.8.132 configured.
Machine 192.168.8.134 configured.
Machine 192.168.8.133 configured.
Running Fabric service installation.
Successfully started FabricInstallerSvc on machine 192.168.8.131
Successfully started FabricInstallerSvc on machine 192.168.8.134
Successfully started FabricInstallerSvc on machine 192.168.8.132
Successfully started FabricInstallerSvc on machine 192.168.8.133
Successfully started FabricHostSvc on machine 192.168.8.132
Successfully started FabricHostSvc on machine 192.168.8.134
Successfully started FabricHostSvc on machine 192.168.8.133
Timed out waiting for Installer Service to complete for machine 192.168.8.131. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeploye
r -> Fabric
CreateCluster Error: System.AggregateException: One or more errors occurred. ---> System.ServiceProcess.TimeoutException: Timed out waiting for Installer 
Service to complete for machine 192.168.8.131. Investigation order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController
 installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass19_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody,
 Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWit
hState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.RunFabricServices(MachineHealthContainer machineHealthContainer, FabricPackageTy
pe fabricPackageType, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<CreateClusterAsyncInternal>d__1.MoveNext()
---> (Inner Exception #0) System.ServiceProcess.TimeoutException: Timed out waiting for Installer Service to complete for machine 192.168.8.131. Investiga
tion order: FabricInstallerService -> FabricSetup -> FabricDeployer -> Fabric
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndValidateInstallerServiceCompletion(String machineName, ServiceController
 installerSvc, TimeSpan timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.StartAndWaitForInstallerService(String machineName, Nullable`1 timeout)
   at Microsoft.ServiceFabric.DeploymentManager.DeploymentManagerInternal.<>c__DisplayClass19_0.<RunFabricServices>b__0(String m)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

Trace folder already exists. Traces will be written to existing trace folder: C:\MSASF\DeploymentTraces
Cleaning up faulted installation.
Removing configuration from machine 192.168.8.133
Removing configuration from machine 192.168.8.132
Removing configuration from machine 192.168.8.134
Removing configuration from machine 192.168.8.131
Configuration removed from machine 192.168.8.134
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:52 AM - MRVM - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you m
ean to use the 's' structured trace option?
3/15/2020 9:59:53 AM - MRVM - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:04:34 AM - MRVM - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:06:57 AM - MRVM - Error - Config for Security.DisableFirewallRuleForDomainProfile changed but this entry can not be dynamically updated
3/15/2020 10:06:57 AM - MRVM - Error - Configuration can not be updated dynamically for Security/DisableFirewallRuleForDomainProfile
3/15/2020 10:06:57 AM - MRVM - Error - Exiting the process as configuration can not be updated dynamically.
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:09 AM - MRVM - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:07:10 AM - MRVM - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:11:39 AM - MRVM - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - MRVM - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:27:55 AM - MRVM - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:32:35 AM - MRVM - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:45:57 AM - MRVM - Error - Config for Security.DisableFirewallRuleForDomainProfile changed but this entry can not be dynamically updated
3/15/2020 10:45:57 AM - MRVM - Error - Configuration can not be updated dynamically for Security/DisableFirewallRuleForDomainProfile
3/15/2020 10:45:57 AM - MRVM - Error - Exiting the process as configuration can not be updated dynamically.
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:10 AM - MRVM - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:46:11 AM - MRVM - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:50:41 AM - MRVM - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you 
mean to use the 's' structured trace option?
3/15/2020 10:57:09 AM - MRVM - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 11:01:50 AM - MRVM - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
Error occurred. Event logs from all the nodes are copied to C:\Windows\temp\ServiceFabricEventLogs on machine 192.168.8.134. Please investigate, fix the i
ssue and redeploy your cluster.
Configuration removed from machine 192.168.8.132
3/15/2020 9:59:52 AM - SQL01 - Error - Config for Security.DisableFirewallRuleForDomainProfile changed but this entry can not be dynamically updated
3/15/2020 9:59:52 AM - SQL01 - Error - Configuration can not be updated dynamically for Security/DisableFirewallRuleForDomainProfile
3/15/2020 9:59:52 AM - SQL01 - Error - Exiting the process as configuration can not be updated dynamically.
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:04 AM - SQL01 - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:00:05 AM - SQL01 - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:04:34 AM - SQL01 - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:06:58 AM - SQL01 - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:11:39 AM - SQL01 - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:53 AM - SQL01 - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:27:54 AM - SQL01 - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:32:35 AM - SQL01 - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:45:59 AM - SQL01 - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:46:00 AM - SQL01 - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 10:50:41 AM - SQL01 - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
3/15/2020 10:57:09 AM - SQL01 - Error - Config for Security.DisableFirewallRuleForDomainProfile changed but this entry can not be dynamically updated
3/15/2020 10:57:09 AM - SQL01 - Error - Configuration can not be updated dynamically for Security/DisableFirewallRuleForDomainProfile
3/15/2020 10:57:09 AM - SQL01 - Error - Exiting the process as configuration can not be updated dynamically.
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(162,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(163,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(164,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(167,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(168,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:20 AM - SQL01 - Error - tconfig.ini(169,1) : Error : Dynamic manifest event tagged with 'd' already exists in the static manifest. Did you
 mean to use the 's' structured trace option?
3/15/2020 10:57:21 AM - SQL01 - Error - Kernel crash upload is configured but failed to get kernel crash dump folder.
3/15/2020 11:01:50 AM - SQL01 - Error - Failed to close ContainerActivator. Error FABRIC_E_INVALID_OPERATION
Error occurred. Event logs from all the nodes are copied to C:\Windows\temp\ServiceFabricEventLogs on machine 192.168.8.132. Please investigate, fix the i
ssue and redeploy your cluster.

**Comment by maburlik** [comment]
Another option to investigate such stuck conditions when using -NoCleanupOnFailure flag is to look at the machine's event logs. Sometimes the warning/error type logs will help to determine the cause of the issue. Feel free to open another thread if you are still encountering issues.
