### ISSUE TITLE
Service Fabric runtime is not reclaiming unused memory from Actor Service Instance

### ISSUE THREAD

**Issue by kishorebarik26** [microsoft/service-fabric#495]
I am running this service fabric application in On-Premises Service fabric cluster and used non persistent actors for execution only, initially actor instance's used memory is just few MB.
One request creates one actor in any one partition, and for processing of one request Memory increases 200MB-250MB during execution of actor as it works with multiple files, and after execution is finished I have deleted the actors.

## Expected Behavior
As I am passing `new ActorGarbageCollectionSettings(10, 2)` Service Fabric Runtime should claim the used memory after IdealTimeout which is sepecified in above code and instance memory size should shrink again to few MB as there is no active actors.

## Current Behavior
Used memory is not claimed sooner by runtime it takes long time (5min-50min) to release memory, but I can see there is no in-active actors by querying the partitions, when multiple actors are created 
actor instance size is keeps increasing and in just couple of day, it's generate Memory Out of exception. Sometime VM also crashed automatically.

## Steps to Reproduce

1. During actor service registration I have passed `ActorGarbageCollectionSettings = new ActorGarbageCollectionSettings(10, 2)`
2. In actor class I used attribute `[StatePersistence(StatePersistence.None)]`
3. After execution is finished, I have deleted it
```
Task.Run(() =>
                        {
                            actorObject.ExecuteGrainAsync(requestId, jsonModel).ContinueWith(async (t) =>
                            {
                                await GrainFactory.DeleteActor(actorObject.GetActorId(), "Workflow", CancellationToken.None);
                            }); 
                        });
```
4.

## Context (Environment)
1.  It's starts by slowing down the entire processing of actors.
2.  Actor generate OutOfMemoryException during execution.
3.  After few hours VM is crashed because of low memory in VM.

#### Service Fabric Runtime and SDK Version :
7.0.457.9590 and 4.0.457.9590
#### Operating System :
Windows Server 2019

#### Cluster Size :
Dev-Cluster with 5 VMs of 8 GB RAM 
## Possible Workaround
Till now, VM restart is the only solutions for me.

**Comment by craftyhouse** [comment]
sorry for late response, but is this still occurring? Latest version is now 7.2.445.9590 as of this comment and would like to know if you still see it. thanks!
