### ISSUE TITLE
Certificate rotation in on premise environment Service fabric D365

### ISSUE THREAD

**Issue by Sanjay4646** [microsoft/service-fabric#496]
I am working on certificate rotation in on premise environment for D365.  After updating the new thumbprint values in clusterconfig.json file and executed the script for updating the SF, one of my orchestrator node is facing below error,

Following are commands used for upgrading my SF,

Connect-ServiceFabricCluster

Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath ClusterConfig.json

Update-ServiceFabricClusterUpgrade -UpgradeReplicaSetCheckTimeoutSec 30

Get-ServiceFabricClusterUpgrade

I am getting the below error in one node after executing this commands,

ERROR 
'System.Hosting' reported Error for property 'FabricDownload:7.0.466.9590:3'. There was an error during download. Failed to download 'WindowsFabricStore\ClusterManifest.3.xml' from ImageStore. Error 'FABRIC_E_SERVER_AUTHENTICATION_FAILED'. Check if the file or folder is present in ImageStore by using 'Get-ServiceFabricImageStoreContent -RemoteRelativePath WindowsFabricStore\ClusterManifest.3.xml'.

I am also unable to reboot the error node in SF, 
![SF Status](https://user-images.githubusercontent.com/61734942/75765801-15158280-5d66-11ea-99e3-7ecf28254d4f.png)

![Invalidaddress](https://user-images.githubusercontent.com/61734942/75765540-b0f2be80-5d65-11ea-8740-3a83d6d3f069.png)

**Comment by abarger-bss** [comment]
We were able to reproduce this error in Fabric 7.0.464. We successfully added new thumbprints for the cluster and client certificates. When we attempted another upgrade to add thumbprints for the server certificate, the upgrade failed on the final node with this error. We used the same thumbprint for cluster and server certificate. These are self-signed certs.

In troubleshooting, we RDP'd into the failing node and ran the suggested command, Get-ServiceFabricImageStoreContent. This function returned data, indicating we were able to download the new manifest content,

**Comment by JustinKaffenberger** [comment]
To continue with @abarger-bss 's comment, we eliminated the possibility that the node was somehow corrupt by creating a fresh node, adding it to the cluster, then removing the old one. After attempting to add a secondary server certificate, the upgrade once again fails on the final node.

**Comment by craftyhouse** [comment]
Older, but if possible, can you comment if this was resolved? We've updated our guidance to file issues with our support teams for production issues vs here. https://github.com/microsoft/service-fabric/blob/master/CONTRIBUTING.md#production-issues
