### ISSUE TITLE
InternalDNS no longer working since upgrade to service fabric 7

### ISSUE THREAD

**Issue by brechtvhb** [microsoft/service-fabric#499]
This week my cluster got upgraded to service fabric 7.
Since then the internal dns records are no longer resolving inside my docker containers.

This is the base image i am using.
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.10 AS base

Can easiliy be reproduced by doing a call to the internal dns with a httpclient.
or by doing sudo docker exec -it imageid ping api.application.

How can I fix this?

**Comment by craftyhouse** [comment]
Closing, but please re-open if you need more triage.
