### ISSUE TITLE
Unable to resolve host wanuget.corp.microsoft.com

### ISSUE THREAD

**Issue by drnic** [Microsoft/service-fabric#50]
This line references a URL https://github.com/Microsoft/service-fabric/blob/f258f7579af9643dac6b1c75c93db9a3bcd28fdd/src/prod/tools/linux/init.sh#L9

But I cannot resolve this URL:
```
$ curl http://wanuget.corp.microsoft.com/ManualMirror/api/v2/package/
curl: (6) Could not resolve host: wanuget.corp.microsoft.com
```

During my running of `./build.sh -release -j8` it failed with:

```
Start build at Wed Mar 21 02:33:06 UTC 2018.
Distribution: DEBIAN
Checking WinFab.Linux.Libs.2.2.7:not found. Prepare to download.
Connecting to http://wanuget.corp.microsoft.com/ManualMirror/api/v2/package/..
HTTP 000; Nuget repo may not be reachable.
Download failed. Aborting.
InstallPkgs has failed. Stopping build.
```

**Comment by anmolah** [comment]
@bpm-ms can you please see why it is going down the init path for @drnic.

**Comment by bpm-ms** [comment]
You need to run ./runbuild.sh instead of build.sh. build.sh is run inside the container, which has the packages prepopulated that the script is looking for. Definitely a bit confusing. I opened an issue about a check to verify that a script that should only be run inside the container is indeed run inside

**Comment by drnic** [comment]
The `runbuild.sh` is a docker-based build system. I tried that but got errors - will raise separate issue for it.

I was looking to build SF directly against my Ubuntu Trusty environment.

My build script so far is:

```
set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

# Detect # of CPUs so make jobs can be parallelized
CPUS=$(grep -c ^processor /proc/cpuinfo)
 # Available variables
# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
export HOME=/var/vcap

curl -L https://sfossdeps.blob.core.windows.net/binaries/v0.1.tgz -o /tmp/v0.1.tgz
mkdir -p /external && tar -xvf /tmp/v0.1.tgz -C /
rm /tmp/v0.1.tgz

 # libunwind-dev on 16.04LTS
apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    openssh-server \
    build-essential \
    libtool \
    cmake \
    libunwind8-dev \
    uuid-dev \
    libxml2-dev \
    libssl-dev \
    libssh2-1-dev \
    lttng-tools \
    lttng-modules-dkms \
    liblttng-ust-dev \
    locales \
    libcgroup-dev \
    libib-util \
    libcurl3 \
    git \
    libtool \
    autoconf \
    automake \
    libglib2.0-0 \
    libglib2.0-dev \
    bison \
    flex \
    libpopt-dev \
    libncurses5-dev \
    libncursesw5-dev \
    swig \
    libedit-dev \
    chrpath

# Install the .NET runtime dependency.  Required for running the product.

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
apt-get install -y apt-transport-https apt-utils
apt-get update
apt-get install -y dotnet-runtime-2.0.0
apt-get remove -y apt-transport-https apt-utils

locale-gen en_US.UTF-8

exportLANG=en_US.UTF-8
exportLANGUAGE=en_US:en
exportLC_ALL=en_US.UTF-8

cd service-fabric/src/
./build.sh -release -j$CPUS
```

Most of this comes from the `Dockerfile`, modified for ubuntu trusty.

Is there more to it (e.g. I didn't use `-all` flag) to get this building outside docker container?

**Comment by bpm-ms** [comment]
Ah, cool! If you get this working it would be an awesome contribution back since we don't currently support building outside the container. 

The missing link is the preloaded "external" folder. If you look in the Dockerfile, it downloads a tgz of a few prebuilt stuff we're still working on getting open sourced (technical issues with building them on Linux). You need to download that tgz and extract to root of repo folder

**Comment by bpm-ms** [comment]
These lines: 
https://github.com/Microsoft/service-fabric/blob/master/Dockerfile#L6;L8 

These lines extract the files that the above init.sh script looks for into the appropriate place.

**Comment by bpm-ms** [comment]
I'm sorry, I just saw that you do indeed have those lines in your script.  However the correct extraction location is the root of the git repository, not the root of your Ubuntu machine.  Sorry that isn't very clear.  We want to phase out this "external" folder as soon as possible

**Comment by drnic** [comment]
Thanks. That fixed that issue.

I also added:

```
export CMAKE_C_COMPILER=/usr/bin/gcc
export CMAKE_CXX_COMPILER=/usr/bin/gcc
```

I'll create new issues for anything else that pops up.
