### ISSUE TITLE
Standalone Cluster Monitoring 

### ISSUE THREAD

**Issue by poutler** [microsoft/service-fabric#500]
After working on setting up a new cluster on premises, I've come across documentation that notes the EventStore does not work for standalone clusters. 

Is it even possible to log cluster events for standalone clusters? I have seen some documentation around sending ETW to sinks like ELK, but nothing about getting the ETW logs in the first place. Is this the only method of logging cluster events and metrics?

**Comment by craftyhouse** [comment]
We have some walkthroughs on setting up apps to ELK for example here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-java-elk 


Cluster log settings reference here
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-manifest#log-settings

Please re-open if you need anything further on this.
