### ISSUE TITLE
6.5.676.9590 - SSL cert not binding to explorer port

### ISSUE THREAD

**Issue by stuartag** [microsoft/service-fabric#544]
I'm setting up a standalone cluster on Windows with a gMSA account for windows authentication. The cluster setup completes and I can see the certificate binding for the reverse proxy but no matter what I try, I cannot get the Service Fabric Explorer to switch correctly to SSL. If I specify just the reverse proxy certificate, then explorer works on HTTP and the reverse proxy is HTTPS.

If I specify a server certificate (as advised here https://github.com/MicrosoftDocs/azure-docs/issues/7550#issuecomment-454221435), the explorer web server becomes SSL and I can see in the node settings `<Parameter Name="HttpGatewayProtocol" Value="https" />` however I cannot connect to Service Fabric Explorer and `netsh http show sslcert` shows that no certificate has been bound to the port. I can manually bind the certificate via netsh and then it works fine, but I want to know if I'm doing anything wrong. I've tried setting ClusterCertificate instead which also seems to set the HttpGatewayProtocol to https but not bind the certificate. I've also tried ServerCertificate without setting the ReverseProxyCertificate and rebuilt the cluster from scratch many times.

I have given both NETWORK SERVICE and the gMSA account full access to the certificate.

Below is my security section in the cluster config

```"Security": {
      "WindowsIdentities": {
        "ClustergMSAIdentity": "mydomain\\SFTestCluster1",
        "ClusterSPN": "http/SFTestCluster1.mydomain.local",
        "ClientIdentities": [
          {
            "IsAdmin": true,
            "Identity": "SFTestCluster1Administrators"
          },
          {
            "IsAdmin": false,
            "Identity": "SFTestCluster1Users"
          }
        ]
      },
      "ClusterCredentialType": "Windows",
      "ServerCredentialType": "Windows",
      "CertificateInformation": {
        "ReverseProxyCertificateCommonNames": {
          "CommonNames": [
            {
              "CertificateCommonName": "sftestcluster1.mydomain.local"
            }
          ],
          "X509StoreName": "My"
        },
        "ServerCertificateCommonNames": {
          "CommonNames": [
            {
              "CertificateCommonName": "sftestcluster1.mydomain.local"
            }
          ],
          "X509StoreName": "My"
        }
      }
    }
```

**Comment by craftyhouse** [comment]
@stuartag Do you still need assistance on this?
