### ISSUE TITLE
ARM deployment of Service Fabric service gets stuck deploying when service also defined in DefaultServices section in ApplicationManifest.xml

### ISSUE THREAD

**Issue by MedAnd** [microsoft/service-fabric#547]
ARM deployment of Service Fabric service gets stuck deploying when service also defined in DefaultServices section in ApplicationManifest.xml:

![image](https://user-images.githubusercontent.com/13365135/65844701-9a8da480-e37a-11e9-91b3-cb4098a610d4.png)

Consider adding validation / feedback to ARM to cover this scenario. As many Service Fabric deployments will be using ApplicationManifest.xml originally, this finding would also be good clarify / add to the documentation?

> Any service being deployed via ARM json definition must be removed from the DefaultServices section of the corresponding ApplicationManifest.xml file.

https://github.com/MicrosoftDocs/azure-docs/issues/39485

**Comment by craftyhouse** [comment]
Docs were updated, closing.
