### ISSUE TITLE
sfxstandalone - Access Denied issue

### ISSUE THREAD

**Issue by wi5nia** [microsoft/service-fabric#559]
Hi,

We are using AAD auth for our cluster. When you don't have access and go to the SF Explorer via web you get a nice error message.

But when you try to login using the sfxstandalone (18.9.2701) app you just get a blank white screen

![image (1)](https://user-images.githubusercontent.com/12593852/62926819-951dd000-bdb5-11e9-9c8b-35ef8e72e088.png)

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
