### ISSUE TITLE
Is there a way to update a config of standalone SF cluster fully if certificate is expired?

### ISSUE THREAD

**Issue by strymm** [microsoft/service-fabric#562]
We have a standalone service fabric cluster running on several internal machines (NOT in Azure Cloud) and use a certificate to secure it.

Usually we used following way to update a certificate (if it's not expired yet):

1. Create new self-signed certificate using CertSetup.ps1 from service fabric SDK
2. Install it on all nodes.
3. `Get-ServiceFabricClusterConfiguration > C:\SfInstall\ClusterConfig.current.json`
4. Edit ClusterConfig.current.json to replace old thumbprint to new one
5. `Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath C:\SfInstall\ClusterConfig.current.json`

It worked fine and updated certificate fully (I mean here the cluster worked fine and commands `Get-ServiceFabricClusterConfiguration` and `Get-ServiceFabricClusterManifest` showed the new thumbprint after that)

But some time ago our certificate expired and we had to follow the instruction
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/3754d5c2d4bfe6094bff000cb7ffd4f80897be31/Security/Fix%20Expired%20Cluster%20Certificate%20Manual%20Steps.md
to update certificate and get the cluster worked.

It allowed to get the cluster worked but commands `Get-ServiceFabricClusterConfiguration` and `Get-ServiceFabricClusterManifest` still showed old thumbprint (seems it's due to note 2 from point 10 in the instruction above).

We managed to update a cluster manifest following steps:

1. Run `Get-ServiceFabricRegisteredClusterConfigVersion` to detect current version of the cluster manifest
2. `Get-ServiceFabricClusterManifest > C:\SfInstall\ClusterManifestV7.xml`
3. Edit ClusterManifestV7.xml to replace old thumbprint to new one
4. `Copy-ServiceFabricClusterPackage -ImageStoreConnectionString "fabric:ImageStore" -Config -ClusterManifestPath "C:\SfInstall\ClusterManifestV7.xml"`
5. `Register-ServiceFabricClusterPackage -Config -ClusterManifestPath "ClusterManifestV7.xml"`
6. `Start-ServiceFabricClusterUpgrade -Monitored -FailureAction Rollback -Config -ClusterManifestVersion 7`

After that `Get-ServiceFabricClusterManifest` became to show new thumbprint
![Get-ServiceFabricClusterManifest](https://user-images.githubusercontent.com/53749800/62453869-eefe1480-b77b-11e9-8c5d-c2899f1fd52a.png)

but `Get-ServiceFabricClusterConfiguration` still shows old one
![Get-ServiceFabricClusterConfiguration](https://user-images.githubusercontent.com/53749800/62454062-4603e980-b77c-11e9-8604-378783683c2e.png)

and isn't possible to update cluster config in usual way using steps

3. `Get-ServiceFabricClusterConfiguration > C:\SfInstall\ClusterConfig.current.json`
4. Edit ClusterConfig.current.json to replace old thumbprint to new one
5. `Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath C:\SfInstall\ClusterConfig.current.json`

due to error
![Start-ServiceFabricClusterConfigurationUpgrade](https://user-images.githubusercontent.com/53749800/62454092-56b45f80-b77c-11e9-95db-ae0fedc9ffe6.png)

So, my questions are
1. What is the difference between upgrade of cluster config using `Start-ServiceFabricClusterUpgrade` with flag `-Config` and `Start-ServiceFabricClusterConfigurationUpgrade`? Why first approach works but second one gets failed in case of updating expired certificate?
2. Is there a way (or workaround) to update a config of standalone SF cluster fully in order to `Get-ServiceFabricClusterConfiguration` to show new thumbprint and become possible to update cluster config in usual way using `Start-ServiceFabricClusterConfigurationUpgrade`?

**Comment by craftyhouse** [comment]
@dragav Do you know if we addressed this?

**Comment by dragav** [comment]
@craftyhouse I think Antonio made some fixes in this area for 72; we can follow up internally to see if there is anything else left unaddressed.

**Comment by craftyhouse** [comment]
@strymm please see latest release which should help in the future on this.

**Comment by amenarde** [comment]
@strymm If you are still seeing the issues, can you provide,

- the security section that comes from get-servicefabricclustermanifest
- the security section that comes from Get-ServiceFabricClusterConfiguration
- The security section of the json configuration you tried to push which was blocked when you ran Start-ServiceFabricClusterConfigurationUpgrade
