### ISSUE TITLE
Clear State from Reliable Queue

### ISSUE THREAD

**Issue by Pete1138** [microsoft/service-fabric#563]
Is it possible to clear the contents of a Reliable Queue in a deployed application (i.e. non-programmatically)?

I have tried using Start-ServiceFabricDataLoss and Start-ServiceFabricRepairTask (with RemoveData), but neither removed items.

I have also tried stopping the "Service Fabric Host" service on each node and deleting the replicatorshared.log file (before re-starting the services). This works on some environments but not on others. Does Service Fabric re-create the replicator log from some other transaction logs?

**Comment by zuhairp** [comment]
@masnider's suggestion is correct. Besides deleting the service instance, there isn't any other SF exposed way to clear the contents of reliable collections externally
