### ISSUE TITLE
	'FabricDCA' reported Warning for property 'DataCollectionAgent.DiskSpaceAvailable'.

### ISSUE THREAD

**Issue by brechtvhb** [microsoft/service-fabric#568]
I am running a Linux cluster but I'm having the warning above.

I tried to fix this issue by adding the following properties to my ARM template

          {
            "name": "KtlLogger",
            "parameters": [
              {
                "name": "SharedLogSizeInMB",
                "value": "4096"
              }
            ]
          },
          {
            "name": "Diagnostics",
            "parameters": [
              {
                "name": "MaxDiskQuotaInMB",
                "value": "4096"
              }
            ]
          }

I also tried to increase the size of my OS disk to 256Gb instead of 128Gb but that doesn't help either.

          "storageProfile": {
            "imageReference": {
              "publisher": "[parameters('vmImagePublisher')]",
              "offer": "[parameters('vmImageOffer')]",
              "sku": "[parameters('vmImageSku')]",
              "version": "[parameters('vmImageVersion')]"
            },
            "osDisk": {
              "caching": "ReadOnly",
              "createOption": "FromImage",
              "diskSizeGB": "[parameters('vmOsDiskSizeInGb')]",
              "managedDisk": {
                "storageAccountType": "[parameters('storageAccountType')]"
              }
            }
          }

Any other suggestions?

**Comment by maburlik** [comment]
Take a look at the data/log root location specified for your cluster i.e. /mnt/sfroot and see if anything in particular stands out that may be consuming an excess of space.

The df command will tell you how much disk space is available per drive:
> df

One common reason to run out of disk space on the machines would be related to congested docker container cache which can be cleaned by pruning unused images:
```
docker system prune -a
```
