### ISSUE TITLE
VS2017 publish gets stuck on Copy-ServiceFabricApplication

### ISSUE THREAD

**Issue by riznard-rf** [microsoft/service-fabric#571]
Hi,

I'm getting an issue when trying to publish to Azure Service Fabric from VS2017, where the Publish process gets stuck at Copy-ServiceFabricApplication command. I've tried removing the local cluster, but am getting an error; despite the message saying that detailed logs are available in DevClusterSetup.txt, the file doesn't contain any error details. However, I've managed to shut down the local cluster service, but it didn't help.

I've been able to successfully do publishing from VS2017 up until yesterday, and haven't made any changes to my local environment in the meantime. Also the Azure Service Fabric had the last upgrade on 4/7, so no changes there either. My machine has the latest Service Fabric and Service Fabric SDK installed.

Can someone please assist with this one?

Thanks,
Daniel

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
