### ISSUE TITLE
add node failure use script AddNode.ps1

### ISSUE THREAD

**Issue by chenzuo** [microsoft/service-fabric#581]
2019/06/05-12:26:50.367,Info,10012,Testability.FabricClientRetryHelper,Enter ExecuteFabricActionWithRetryAsync() with function
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,AsyncCalloutAdapter-63835064: begin
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<IFabricAsyncOperationContext>-11454272 is initialized. CurrentReferenceCount=1
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<IFabricAsyncOperationContext>-11454272.TryAdd: SUCCESS. CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetFabricUpgradeProgress,AsyncCalloutAdapter-63835064: callback
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,AsyncCalloutAdapter-63835064: end
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<IFabricAsyncOperationContext>-11454272 is already initialized. CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<IFabricAsyncOperationContext>-11454272.TryAdd: SUCCESS. CurrentReferenceCount=3
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<SharedNativeObject<IFabricAsyncOperationContext>-11454272>.Release: CurrentReferenceCount=3
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<SharedNativeObject<IFabricAsyncOperationContext>-11454272>.Release: CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,7104,SystemFabric.ClusterManager.GetFabricUpgradeProgress,SharedNativeObject<SharedNativeObject<IFabricAsyncOperationContext>-11454272>.Release: CurrentReferenceCount=1
2019/06/05-12:26:50.367,Info,10012,Testability.FabricClientRetryHelper,Enter ExecuteFabricActionWithRetryAsync() with function
2019/06/05-12:26:50.367,Verbose,7084,SystemFabric.ClusterManager.GetClusterManifest,AsyncCalloutAdapter-15688314: begin
2019/06/05-12:26:50.367,Verbose,7084,SystemFabric.ClusterManager.GetClusterManifest,SharedNativeObject<IFabricAsyncOperationContext>-52307948 is initialized. CurrentReferenceCount=1
2019/06/05-12:26:50.367,Verbose,7084,SystemFabric.ClusterManager.GetClusterManifest,SharedNativeObject<IFabricAsyncOperationContext>-52307948.TryAdd: SUCCESS. CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,7084,SystemFabric.ClusterManager.GetClusterManifest,SharedNativeObject<SharedNativeObject<IFabricAsyncOperationContext>-52307948>.Release: CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetClusterManifest,AsyncCalloutAdapter-15688314: callback
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetClusterManifest,SharedNativeObject<IFabricAsyncOperationContext>-52307948 is already initialized. CurrentReferenceCount=1
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetClusterManifest,SharedNativeObject<IFabricAsyncOperationContext>-52307948.TryAdd: SUCCESS. CurrentReferenceCount=2
2019/06/05-12:26:50.367,Verbose,5056,SystemFabric.ClusterManager.GetClusterManifest,AsyncCalloutAdapter-15688314: end
2019/06/05-12:26:50.414,Info,5056,SystemFabricDeployer.SFDeployer,Running Best Practices Analyzer...
2019/06/05-12:26:50.414,Verbose,5056,SystemFabricDeployer.SFDeployer,Validating executing user is an Administrator.
2019/06/05-12:26:50.414,Verbose,5056,SystemFabricDeployer.SFDeployer,Validating CAB file is valid at D:\ServiceFabric\DeploymentRuntimePackages\MicrosoftAzureServiceFabric.6.4.664.9590.cab.
2019/06/05-12:26:51.539,Verbose,5056,SystemFabricDeployer.SFDeployer,Validating machines are reachable and have opened required ports.
2019/06/05-12:26:51.554,Verbose,5056,SystemFabricDeployer.SFDeployer,Using IPv4 address for 192.168.0.102
2019/06/05-12:26:51.554,Verbose,5056,SystemFabricDeployer.SFDeployer,Verifying remote procedure ### call access against cluster machines.
2019/06/05-12:26:51.585,Warning,5056,FabricDeployer.FabricDeployer,System.UnauthorizedAccessException: 尝试执行未经授权的操作。
	   在 Microsoft.Win32.RegistryKey.Win32ErrorStatic(Int32 errorCode, String str)
	   在 Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(RegistryHive hKey, String machineName, RegistryView view)
	   在 System.Fabric.FabricDeployer.Utility.GetHklm(String machineName)
	   在 System.Fabric.FabricDeployer.Utility.GetTempPathInner(String machineName)
	   在 System.Fabric.FabricDeployer.Utility.GetTempPath(String machineName)
2019/06/05-12:26:51.585,Error,5056,SystemFabricDeployer.SFDeployer,Machine 192.168.0.102 failed CheckRPCAccess. HRESULT=192.168.0.102
2019/06/05-12:26:51.585,Error,5056,SystemFabricDeployer.SFDeployer,Best Practices Analyzer determined environment has an issue. Please see additional BPA log output in DeploymentTraces folder.
2019/06/05-12:26:51.585,Error,5056,SystemFabricDeployer.SFDeployer,Add Node cancelled due to validation error(s) found by Best Practices Analyzer. Inspect details in DeploymentTraces log folder local to executing location.

**Comment by maburlik** [comment]
Please try the latest 7.1 and see if you still hitting the issue. A fix had been made in this area in a 7.0 CU.
