### ISSUE TITLE
Install the Microsoft Azure Service Fabric SDK fails

### ISSUE THREAD

**Issue by trigifu** [microsoft/service-fabric#612]
Installing this
https://www.microsoft.com/web/handlers/webpi.ashx?command=getinstallerredirect&appid=MicrosoftAzure-ServiceFabric-CoreSDK
Fails with popup about 
Microsoft Azure Service Fabric Runtime - 6.4.644
This product did not install successfully.

Here is the log from View Log here
DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webpifeed51
DownloadManager Information: 0 : https://aka.ms/webpifeed51 responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Location: https://webpifeed.blob.core.windows.net/webpifeed/5.1/WebProductList.xml
Server: Kestrel
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Wed, 20 Mar 2019 16:00:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 20 Mar 2019 16:00:14 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/5.1/WebProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: aeb7f46f-d01e-000f-0536-dfd59f000000
x-ms-version: 2009-09-19
Date: Wed, 20 Mar 2019 16:00:14 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\1460077924.xml.temp
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Resource Provider
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Terawe
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webapplicationlist
DownloadManager Information: 0 : https://aka.ms/webapplicationlist responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Location: https://webgallery.microsoft.com/feed/webapplicationlist.xml
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Wed, 20 Mar 2019 16:00:15 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 20 Mar 2019 16:00:15 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

DownloadManager Information: 0 : https://webgallery.microsoft.com/feed/webapplicationlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
ETag: "0246ae9cad7d41:0"
Date: Wed, 20 Mar 2019 16:00:15 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\-966730450.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webapplicationlist' after preprocessing, location on disk: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-966730450.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: aeb7f965-d01e-000f-1636-dfd59f000000
x-ms-version: 2009-09-19
Date: Wed, 20 Mar 2019 16:00:16 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\2000756975.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml' after preprocessing, location on disk: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\preprocessor\2000756975.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: aeb7f98a-d01e-000f-3936-dfd59f000000
x-ms-version: 2009-09-19
Date: Wed, 20 Mar 2019 16:00:16 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\609314840.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml' after preprocessing, location on disk: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\preprocessor\609314840.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: aeb7f9c3-d01e-000f-6d36-dfd59f000000
x-ms-version: 2009-09-19
Date: Wed, 20 Mar 2019 16:00:16 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\140237651.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml' after preprocessing, location on disk: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\preprocessor\140237651.xml'
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webpifeed51' after preprocessing, location on disk: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\preprocessor\1460077924.xml'
DownloadManager Information: 0 : Getting ratings file from http://go.microsoft.com/?linkid=9752395
DownloadManager Information: 0 : Contextual entry products: MicrosoftAzure-ServiceFabric-CoreSDK
DownloadManager Information: 0 : Adding product Microsoft Azure Service Fabric SDK - 3.3.644 (MicrosoftAzure-ServiceFabric-CoreSDK) to cart
DownloadManager Information: 0 : Contextual navigation to product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : http://go.microsoft.com/?linkid=9752395 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Location: http://www.microsoft.com/web/handlers/WebPI.ashx?command=getatomfeedwithavgratingquery
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Wed, 20 Mar 2019 16:00:17 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 20 Mar 2019 16:00:17 GMT
Connection: keep-alive

DownloadManager Information: 0 : Number of bytes downloaded over the internet: '0'
DownloadManager Information: 0 : Number of bytes after possible decompression: '0'
DownloadManager Warning: 0 : Error getting last-modified header, error code: 12150
DownloadManager Warning: 0 : HttpQueryInfoWithRetry for HTTP_QUERY_LAST_MODIFIED failed.
DownloadManager Error: 0 : Error loading rating files: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Microsoft.Web.PlatformInstaller.ProductServiceImpl.GetAppRatings()
DownloadManager Information: 0 : Adding product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricSDK_3_3_CU4
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricRuntime_6_4_CU4
DownloadManager Information: 0 : Setting current install to 1
DownloadManager Information: 0 : Starting install sequence
DownloadManager Information: 0 : Downloading file 'https://download.microsoft.com/download/D/8/3/D834F3B5-ECAA-413D-AFEA-8C57E8510164/MicrosoftServiceFabric.6.4.644.9590.exe' to: C:\Users\efolz\AppData\Local\Temp\tmp359C.tmp
DownloadManager Information: 0 : Content-disposition header: attachment
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '232451488'
DownloadManager Information: 0 : Number of bytes after possible decompression: '232451488'
DownloadManager Information: 0 : Moving downloaded file 'C:\Users\efolz\AppData\Local\Temp\tmp359C.tmp' to: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU4\242DB4489429FD06EA9CFD4CE6337D78E3134A03\MicrosoftServiceFabric.6.4.644.9590.exe
DownloadManager Information: 0 : Downloading file 'https://download.microsoft.com/download/D/8/3/D834F3B5-ECAA-413D-AFEA-8C57E8510164/MicrosoftServiceFabricSDK.3.3.644.msi' to: C:\Users\efolz\AppData\Local\Temp\tmp4146.tmp
DownloadManager Information: 0 : Content-disposition header: attachment
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c wmic product where name="Microsoft Azure Service Fabric" call uninstall'. Process Id: 3456
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '61915136'
DownloadManager Information: 0 : Number of bytes after possible decompression: '61915136'
DownloadManager Information: 0 : Moving downloaded file 'C:\Users\efolz\AppData\Local\Temp\tmp4146.tmp' to: C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_3_3_CU4\79780A6EC69CE12CE431A9D6D02D3B43A24310CC\MicrosoftServiceFabricSDK.3.3.644.msi
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is '0'
DownloadManager Information: 0 : Ignoring exit code '0' for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop KtlLogger'. Process Id: 8792
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is '1060'
DownloadManager Information: 0 : Ignoring exit code '1060' for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop LeasLayr'. Process Id: 14448
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is '1060'
DownloadManager Information: 0 : Ignoring exit code '1060' for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'. Commandline is: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU4\242DB4489429FD06EA9CFD4CE6337D78E3134A03\MicrosoftServiceFabric.6.4.644.9590.exe /AcceptEULA'. Process Id: 9264
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is '1'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is Failure
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric Runtime - 6.4.644 done install completed
DownloadManager Information: 0 : Increasing current install to 2
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.644'. Skipping install
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.644'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.644 had a dependency fail. Increasing install product to 3
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.644 had a dependency fail. Increasing install product to 4
DownloadManager Information: 0 : Product: ServiceFabricRuntime_6_4_CU4, Install Status: InstallCompleted-Failure, Install Time: 00:02:35.3700612
DownloadManager Information: 0 : Product: ServiceFabricSDK_3_3_CU4, Install Status: DependencyFailed-None, Install Time: 00:00:00
DownloadManager Information: 0 : Product: MicrosoftAzure-ServiceFabric-CoreSDK, Install Status: DependencyFailed-None, Install Time: 00:00:00

It seems the offending line is:
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.644'. Commandline is: 'C:\Users\efolz\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU4\242DB4489429FD06EA9CFD4CE6337D78E3134A03\MicrosoftServiceFabric.6.4.644.9590.exe /AcceptEULA'. Process Id: 9264
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.644' is '1'

**So I started up power shell and tried to run the same command with this result:**
PS C:\users\efolz\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_CU4\242DB4489429FD06EA9CFD4CE6337D78E3134A03> .\MicrosoftServiceFabric.6.4.644.9590.exe /accepteula
3/20/2019 3:43:53 PM,Info,Start installation... Logs created at C:\WINDOWS\TEMP\InstallFabricRuntime.log
3/20/2019 3:43:53 PM,Info,3/20/2019 11:43:53 AM running: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser
3/20/2019 3:43:53 PM,Error,Object reference not set to an instance of an object.

**Comment by maburlik** [comment]
Improvements have been made to the runtime installer in the last few major releases. Please try the latest 7.1 version and if you are still encountering issues create a new thread.
