### ISSUE TITLE
Microsoft/service-fabric but Azure/service-fabric-cli

### ISSUE THREAD

**Issue by drnic** [Microsoft/service-fabric#65]
![service-fabric-explorer](https://user-images.githubusercontent.com/108/37844064-de5f9932-2e83-11e8-954d-03b9e96958e1.png)

Hurray!

I've put some pre-built `.deb` on an s3 bucket of mine if anyone else wants to use them:

```
wget https://s3.amazonaws.com/service-fabric-bits/out/build.prod/FabricDrop/deb/servicefabric_6.2.141.1.deb
wget https://s3.amazonaws.com/service-fabric-bits/out/build.prod/FabricDrop/deb/servicefabric_sdkcommon_1.2.0.deb
```

Will this repo move to the github.com/Azure org or will the CLI move to this org?

* https://github.com/Microsoft/service-fabric
* https://github.com/Azure/service-fabric-cli

**Comment by anmolah** [comment]
The service-fabric repos in the Azure org will transition into the Microsoft org. 

@drnic thanks for trying the build/test pipeline out and all the good feedback.

**Comment by drnic** [comment]
I probably shouldn't have started with "ok lets try to deploy this my way on a different Ubuntu version" before first deploying it your way :)

Oh, and I should have read the instructions on "use a huge vm for initial build and have patience" :)
