### ISSUE TITLE
Cannot Install Because PowerShell Repeatedly Stops Working

### ISSUE THREAD

**Issue by brianstringfellow** [microsoft/service-fabric#675]
Followed the installation steps and ensured prerequisites are in place. Run the PowerShell command 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser'. The old SF SDK and cluster have been uninstalled.

Used the Core SDK WebPI link. Always fails.

Unable to get Powershell ExecutionPolicy. ExitCode: -1073741819

![image](https://user-images.githubusercontent.com/22823524/47936946-8ad0bc00-de9c-11e8-87c3-747acb066d34.png)

**Comment by brianstringfellow** [comment]
Nearly another year has passed and the Web Platform Installer 5.1 still fails. Again, clean machine with Windows 10 Enterprise (18363.836).

![image](https://user-images.githubusercontent.com/22823524/84679464-2eda7000-aee6-11ea-8482-323617e6ab15.png)

**Comment by maburlik** [comment]
This appears to be the same issue as
https://github.com/microsoft/service-fabric/issues/756

If you can ensure the powershell execution policy is set prior to running the installer, you can skip this step using the parameter /SkipPSExecutionPolicy.
