### ISSUE TITLE
Connecting to my SF via Visual Studio

### ISSUE THREAD

**Issue by drnic** [microsoft/service-fabric#68]
I'm following the instructions at https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-quickstart-dotnet but am trying to Publish to my own SF dev cluster. I've tried `:19000` and `:19080` ports, e.g `10.11.12.13:19080` but the dialog box gives me an X error.

<img width="477" alt="failing-to-connect" src="https://user-images.githubusercontent.com/108/37932856-e71e8ca2-318c-11e8-988b-7e69424fdcaf.PNG">

Any tips on how to get Visual Studio to connect?

I've had success deploying to a party cluster (except for https://github.com/Azure-Samples/service-fabric-dotnet-quickstart/issues/5)

**Comment by Eneuman** [comment]
Try this:
1) If you are using a self signed certificate, make sure you have added it to your personal certificate store as well as your machine certificate store.
2) Verify that you have added the thumbprint for the certificate as a "Client Certificate" with "Admin" rights in the "Security" blade of your Azure SF Cluster.
3) Make sure that you have added the certificate settings to the Cloud.xml publish profile file.

**Comment by drnic** [comment]
I didn’t think the OSS SF dev cluster includes a self signed cert. Using the sfctl cli and the browser I have been accsssing via http:// protocol. If http:// works, should Visual Studio accept that? Or must I figured out how to setup my own self signed cert in my dev cluster first?

		
		

		Get Outlook for iOS
	




On Tue, Mar 27, 2018 at 8:52 PM +1000, "Per Bornsjö" <notifications@github.com> wrote:












Try this:

If you are using a self signed certificate, make sure you have added it to your personal certificate store as well as your machine certificate store.
Verify that you have added the thumbprint for the certificate as a "Client Certificate" with "Admin" rights in the "Security" blade of your Azure SF Cluster.
Make sure that you have added the certificate settings to the Cloud.xml publish profile file.

**Comment by Eneuman** [comment]
By OSS Dev Cluster, do you mean a Azure One Node Dev Cluster or a dev cluster on your local computer?

**Comment by Eneuman** [comment]
I'm sorry but my SF Linux knowledge is limited.
In the image above you have selected the Cloud.xml profile, have you tried the 1-Node one?
The 1-node profile comes with default settings to connect to a local cluster.

**Comment by MikkelHegn** [comment]
VS publishes to the tcp mgmt endpoint, which by default is 19000. If you’re using certs to secure the endpoint, you’ll have to add the cert information in the publish profile xml file you’re choosing in the Target Profile dropdown.

**Comment by drnic** [comment]
Is the OSS SF in this project offering the `:19000` TCP port used by Visual Studio? Will VS -> :19000 work without certs? (as per the https://github.com/Microsoft/service-fabric/blob/master/docs/install_packages_and_deploy_cluster.md#set-up-a-local-cluster instructions?)

**Comment by MikkelHegn** [comment]
Yes - the 19000 and 19080 are endpoints hosted in the cluster and they support Cert based auth, no auth, Azure AD authentication (and Windows auth on the Windows version of SF).

**Comment by drnic** [comment]
Ok thanks.
Any suggestions for debugging my original issue? VS is giving me the unhappy X when I point it at my publicip:19000

**Comment by MikkelHegn** [comment]
I remember having seen VS getting it wrong. You can check connectivity by running the Connect-ServiceFabricCluster PowerShell command. (No need to do parameters if the target it localhost. Otherwise do -Endpoint ip:19000.
