### ISSUE TITLE
Service Fabric Configuration Upgrade

### ISSUE THREAD

**Issue by JanMcke** [microsoft/service-fabric#693]
In order to test certain scenarios, I am trying to remove a node from our lab Service Fabric cluster using the following article: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-windows-server-add-remove-nodes

I start from [Config0.txt](https://github.com/Azure/service-fabric-issues/files/2440920/Config0.txt)
add the NodesToBeRemoved section, delete the node in the Nodes List.

This gives me [Config1.txt](https://github.com/Azure/service-fabric-issues/files/2440925/Config1.txt)
However when I try to start the ServiceFabricClusterupgrade it gives me the following error:
![image](https://user-images.githubusercontent.com/43542279/46393961-b6b72100-c6e7-11e8-82c3-73d7905aeeca.png)
Strange, we are not using a certificate for this laboratory environment.

I check the config and remove the CertificateInformation node, which besides an unknown id to me, doesn't contain anything.
This gives me [Config2.txt](https://github.com/Azure/service-fabric-issues/files/2440927/Config2.txt)
Trying this gives me the following error
![image](https://user-images.githubusercontent.com/43542279/46394079-38a74a00-c6e8-11e8-87b7-c040e513c197.png)
Weird, I am not adding nodes, only removing them.

Ok, so I am thinking: Maybe the article didn't really mean physically removing the node section from the config. Only to add the 'NodesToBeRemoved' section
This gives me [Config3.txt](https://github.com/Azure/service-fabric-issues/files/2440929/Config3.txt)
Sure enough, that wasn't the problem because the error quite clearly tells me to remove it from the Nodes list
![image](https://user-images.githubusercontent.com/43542279/46394210-bf5c2700-c6e8-11e8-90d7-51ff474b4743.png)

But that gives me the 'Nodes cannot be added and removed in the same upgrade' error.
My question thus, what am I doing wrong, or what is going that Service Fabric is thinking that I am adding and removing a node whilst the config only removes nodes?

**Comment by maburlik** [comment]
This had been fixed as of 7.0 CU4.
