### ISSUE TITLE
Unable to disable Certificate Revocation List look-up in on-premise cluster

### ISSUE THREAD

**Issue by framgeld** [Microsoft/service-fabric#70]
Hi,

We are getting the following issue in our Service Fabric cluster after deploying to our pre-production cluster that has no internet connectivity:

>Unhealthy event: SourceId='System.FabricNode', Property='SecurityApi_CertGetCertificateChain', HealthState='Warning', ConsiderWarningAsError=false.
Security API:call duration = 19.695, configuration Setting Security/SlowApiThreshold = 10.000   

>>Unhealthy event: SourceId='System.FabricNode', Property='CertificateRevocationList_FabricGateway', HealthState='Warning', ConsiderWarningAsError=false. Certificate revocation list:CRL offline encountered for certificates: {cert thumbprint removed}. Please ensure the reporting machine has access to 'CRL Distribution Point' at ALL levels in the certificate chain. 'CRL Distribution Point' is an extension in the certificate. 

The documentation for Service Fabric states that the CRL checking can be disabled:

>https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-fabric-settings

Below is the snippet of configuration from our **ClusterConfig.X509.json**, using the settings stipulated in the Service Fabric documentation:

```
"fabricSettings": [
    {
        "name": "Setup",
        "parameters": [
            {
                "name": "FabricDataRoot",
                "value": "C:\\ProgramData\\SF"
            },
            {
                "name": "FabricLogRoot",
                "value": "C:\\ProgramData\\SF\\Log"
            }
        ]
    },
    {
        "name": "Security",
        "parameters": [
            {
                "name": "CrlCheckingFlag",
                "value": "0"
            },
            {
                "name": "IgnoreCrlOfflineError",
                "value": true
            }
        ]
    }
]
```

Is there something else we need to do, in addition to the above?

Thanks.

**Comment by framgeld** [comment]
We have still not been able to rectify this issue. Does anybody have any ideas on how to disable the CRL checking please?

**Comment by samedder** [comment]
@leikong this looks like it's related to a question you're looking at, can you give guidance?

**Comment by leikong** [comment]
does this cluster have internet access?

**Comment by leikong** [comment]
If the cluster is not allowed to have outgoing traffic on port 80 at all, then Windows CTL downloading will also fail, in which case, you need to set the flag value to 0x80000004 in both "Security" and "Federation" section.

**Comment by framgeld** [comment]
@leikong This worked perfectly! Thank you very much for the information.
