### ISSUE TITLE
When will .NET Core 2.0 services be available on Linux?

### ISSUE THREAD

**Issue by oacsed** [Microsoft/service-fabric#71]
Our business needs .NET Core 2.0 stateless/stateful services to run on Linux thanks to a true .Net Core portable code.

This is currently not supported :

> In this release, .NET Core 2.0 services are only supported on Service Fabric for Windows. Full cross-platform support for .NET Core 2.0 services on Windows and Linux is coming soon.
See [the 6.1 release blog post](https://blogs.msdn.microsoft.com/azureservicefabric/2018/01/26/service-fabric-6-1-release/).

Any ETA would be greatly appreciated.

**Comment by raunakpandya** [comment]
This is going to be available very soon.. In our next release which should be just a week or 10 days out. BTW, the support for Linux is already there, just that its in preview right now with the existing SDK. https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-create-your-first-linux-application-with-csharp

**Comment by oacsed** [comment]
Great! Thanks for your reply.
