### ISSUE TITLE
Why is only a subset of X509FindType supported?

### ISSUE THREAD

**Issue by stijnherreman** [microsoft/service-fabric#717]
In ApplicationManifest.xml I can specify a certificate:

```xml
  <Certificates>
    <SecretsCertificate Name="ResourceServerCertificate" X509FindType="FindByThumbprint" X509FindValue="[ResourceServerCertificate_thumbprint]"/>
  </Certificates>
```

Why are only `FindByThumbprint`, `FindBySubjectName` and `FindByExtension` supported instead of all 15 types available in `System.Security.Cryptography.X509Certificates.X509FindType`?

**Comment by zendu** [comment]
@dragav I don't see any documentation about auto roll over. Will new certificate be bound to port as soon as it is installed in certificate store? Or a restart/upgrade is necessary?
