### ISSUE TITLE
Standalone Linux Cluster on Azure

### ISSUE THREAD

**Issue by Pothulapati** [microsoft/service-fabric#726]
These Azure docs [one](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-anywhere#create-service-fabric-standalone-clusters-on-premises-or-with-any-cloud-provider) and [two](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-deploy-anywhere#supported-operating-systems-for-standalone-clusters) state that you can't create a standalone Linux Cluster on Azure or other cloud provider. Just like there are scripts for windows, Aren't there scripts through which a linux SF cluster can be made without using the Azure Service Fabric Service.

Asking because, I want to run a Linux SF cluster using the low priority Virtual Machine Scale sets, Not only that there would be many other use cases like running on other providers,etc. There should definitely be a way!

Thanks :smile:

**Comment by craftyhouse** [comment]
https://github.com/microsoft/service-fabric/issues/149#issuecomment-669587037 is still the best answer we can provide right now.
