### ISSUE TITLE
IdleSecondary replica warning: System.UnauthorizedAccessException (-2147024891) Access is denied. 

### ISSUE THREAD

**Issue by w-star** [microsoft/service-fabric#733]
On our standalone cluster (6.2.283) we're often noticing issues with some IdleSecondary replicas showing UnauthorizedAccessException warnings. If not removed, those replicas start draining memory from nodes. If IdleSecondary doesn't show a warning, it's generally ok and doesn't seem to be causing memory usage spikes. 

The IdleSecondary replicas appear usually during application upgrades and don't go away despite there being 3 healthy replicas after upgrade completes. 

There doesn't seem to be much correlation between size of service replica and possibility of it having an IdleSecondary after upgrade. 

![image](https://user-images.githubusercontent.com/25615005/42844257-4ad0660a-8a0a-11e8-9afa-01fca3c48aee.png)

What could cause these warnings? Why would the replicas with warnings drain memory? 

I understand an IdleSecondary is a standby replica, for when upgrades take longer than expected. Is there a way to instruct cluster to remove those replicas after upgrade completes? 

--
Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on tf-sf-dev-n10. API call: IStatefulServiceReplica.Open(); Error = System.UnauthorizedAccessException (-2147024891) Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))    at Microsoft.ServiceFabric.Replicator.RecoveryManager.d__31.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Replicator.LoggingReplicator.d__140.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Replicator.DynamicStateManager.d__118.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Replicator.TransactionalReplicator.d__79.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Replicator.StatefulServiceReplica.d__21.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Data.ReliableStateManagerImpl.d__49.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.d__17.MoveNext() For more information see: http://aka.ms/sfhealth

**Comment by ashishnegi** [comment]
@w-star If you still see this issue, please share a performance monitor report with file system for the Idle secondary process. That will help us easily find cause of `unauthorizedaccessexception`. Otherwise, please share a dump of the process.

We have fixed memory leak in service object re creation code path, which seems to be getting triggered in your case as recovery is failing with unauthotizedacceess exception. The fix is available in 7.2 CU5 or later release.
Can you try that ?

**Comment by ashishnegi** [comment]
Hi.. we have not heard back from you.
If you are still seeing same issue with latest SF release, please comment back for reopening or create a new issue.
