### ISSUE TITLE
cluster on a multi-linux VM

### ISSUE THREAD

**Issue by lin-jianjun** [Microsoft/service-fabric#75]
How do you deploy the service fabric cluster on a multi-linux VM？

**Comment by samedder** [comment]
The only way to do this currently is through an Azure deployment. There's [documentation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-create-vnet-and-linux-cluster) on how to do this currently, and in the future we will support this scenario in other environments.
