### ISSUE TITLE
MicrosoftServiceFabric.6.2.283.9494.exe installation error - PowerShell has stopped working

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [microsoft/service-fabric#756]
I tried to install the azure service fabric SDK with the web installer (MicrosoftAzure-ServiceFabric-CoreSDK.exe), as explained in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-quickstart-dotnet.

After I got errors here, I tried the intermediate step, starting with the installation of just the service fabric runtime (MicrosoftServiceFabric.6.2.283.9494.exe).

But I always get following error:
"Error,Unable to get Powershell ExecutionPolicy. ExitCode: -1073741819"
Before this, an powershell error pops up "windows powershell has stopped working".
When debugging this error, I just get some message that access to adress xy is denied, which does not provide any useful google results.
![capture](https://user-images.githubusercontent.com/11556950/41147445-baffb41c-6b06-11e8-884d-234dddbb0cab.PNG)

Everything is run as admin. On "GetExecutionPolicy -List", everything is set to "Unrestricted".

When I run "Powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser" by myself, I also get the same behavior, The powershell "has stopped working".
But when I open powershell directly and type "Get-ExecutionPolicy -Scope CurrentUser", it IS WORKING without a problem.

This is a first time azure service fabric SDK installation. I work on windows 10 with visual studio enterprise 2017 installed. I have admin rights on my computer.

I appreciate any help.

**Comment by maburlik** [comment]
If you can ensure the powershell execution policy is set prior to running the installer, you can skip this step using the parameter /SkipPSExecutionPolicy.
