### ISSUE TITLE
Getting Started with Service Fabric and Wcf

### ISSUE THREAD

**Issue by mauriciomagni** [microsoft/service-fabric#765]
I am trying to get Service Fabric and Wcf working.
I am learning and was following the sample shown in [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-wcf).
I have basically copied the information shown in that page and completed the details, but I cannot have the application running. The method CreateServiceInstanceListeners() is being call time and time again when it returns a ServiceInstanceListener. If I return and empty array, the application starts and works.
I am using VS2017 and Service Fabric 3.0.472. 
I am sorry if this is a really silly post, but I have not been able to go beyond this point.
Any help will be greatly appreciated.

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
