### ISSUE TITLE
Linux - sfctl compose - allow private container registry password

### ISSUE THREAD

**Issue by loekd** [Microsoft/service-fabric#78]
I need to run Linux containers using images stored in a private registry. Also, I want to deploy them automatically, after every version upgrade. 
For this, I need to be allowed to pass credentials to sfctl compose. There are two documented ways to provide the registry password:

- interactive - I can't use this, because a daemon is deploying
- encrypted - I can't use this, because I can't encrypt settings data on Linux (?) (only found [PowerShell cmd ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management#encrypt-application-secrets)to encrypt)

**Repro:**

- Create docker-compose.yaml
- Push images to private registry
- Create deployment pipeline, not using VSTS but Jenkins on Linux.
- Run script:
  `sfctl compose create --deployment-name MyApp --file-path /var/lib/jenkins/workspace/ServiceFabricJob/docker-compose-asf.yml`

**Issue:**

The behavior now is to access the registry without credentials, which fails.

**Comment by samedder** [comment]
We'll create an issue in the [sfctl](https://github.com/Azure/service-fabric-cli) repository.
