### ISSUE TITLE
Services won't run: Exit code 4294770688 

### ISSUE THREAD

**Issue by Pete1138** [Microsoft/service-fabric#79]
I have a number of services that will not run when the application is deployed from Visual Studio (these were previously working, but I've done a full clean on my local repository). In my solution I have .net core projects (targetting v4.6.2) and regular .net projects (targetting v4.6.2). The core projects are starting.

The only error I get from the event logs is "ServiceHostProcess: FabricServiceSetupEntryPoint.bat started at ‎2018‎-‎04‎-‎03T14:46:04.157092200Z with Process Id 5300 for ApplicationId 505fc20e-5faf-40e3-9e9b-6eccbd29b8f2 terminated unexpectedly with exit code 4294770688 on node id bf865279ba277deb864a976fbf4c200e". 

The service fabric explorer shows "There was an error during CodePackage activation.The service host terminated with exit code:4294770688". Googling this shows this is a generic Powershell code.

I can't break into any of the services in Visual Studio because they do not start (I don't get any application logs for this reason either).

**Comment by vturecek** [comment]
Check the "Deployments" tab under the application in SFX. The deployed service packages themselves can report health events, and sometimes those are more descriptive.

Other thing you can try, if it's a local deployment or you have access to the node VM, is the Windows Event Viewer. A code package activation failure means the process crashed immediately, and a lot of the time there's simply no output for Service Fabric to relay back to you. But .NET usually will write something to the Windows Event log.

**Comment by Pete1138** [comment]
In the deployments tab I am getting "The ServiceType was disabled on the node" for the broken services.
I have tried resetting my cluster. I am also getting a "exit code 2147942402" (File Not Found?) in my Windows Event Logs. I guess I'll have to re-install Service Fabric?

**Comment by samedder** [comment]
Have you tried posting on [StackOverflow](https://stackoverflow.com/questions/tagged/azure-service-fabric)? It sounds like there's an issue with how your code package is launching.
