### ISSUE TITLE
Timed out waiting for Installer Service to complete

### ISSUE THREAD

**Issue by yderi** [microsoft/service-fabric#791]
When creating a new standalone Service Fabric with X509 certificates (self signed), 
we get an error. With 3 servers only one complete setup, other cannot complete (you can see below it is due to Installer Service cannot complete on other two machines).
Full log from console attached
[ServiceFabric_create_error.txt](https://github.com/Azure/service-fabric-issues/files/1924711/ServiceFabric_create_error.txt)

What we see:
`
Timed out waiting for Installer Service to complete for machine win-cl2. Investigation order: FabricInstallerService ->
FabricSetup -> FabricDeployer -> Fabric
`

We can see that both services are installed and in running state by services console.

Other clue might be:
`
TimeoutException: Timed out waiting for Installer Service to complete for machine win2
`

Other clue:
`Error - Configuration can not be updated dynamically for Hosting/FirewallPolicyEnabled`

Other clue:
`4/18/2018 5:57:30 PM - WIN-CL3 - Error - Exception occured while creating an object of type FabricDCA.FileShareEtwCsvUpl
oader (assembly FileShareUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer FileShareWinFabEtw. Exception information: System.Reflection.TargetInvocationException: Exception has been thrown by
 the target of an invocation. ---> System.IO.IOException: Unable to create destination directory \\win-cl1\DiagnosticsStore\fabriclogs-42456018-d3a9-4017-ae70-b594abd26e9f\node3. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))`

Here is the JSON config:
[X509-3node-test3.json.txt](https://github.com/Azure/service-fabric-issues/files/1924730/X509-3node-test3.json.txt)
Configuration passed a test script procedure.

Certificate are generated and exported to all three servers (Windows Server 2016 ver1607, windows itself not yet activated)

Network share ("\\\\win-cl1\\DiagnosticsStore") accessible from all three servers (shared to Everyone with Full access).

Does any one know how to fix it? What may cause a problem?

**Comment by maburlik** [comment]
Please create another issue if you hit this again. There have been reworking changes related to diagnostic storage since 2018.
