### ISSUE TITLE
Cluster configuration upgrade of type StandAloneBaselineUpgradeState is already in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by MathijsHofkens** [microsoft/service-fabric#792]
I'm trying to upgrade the configuration of my cluster. But i'm getting the following error:

```
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
FabricException: Cluster configuration upgrade of type StandAloneBaselineUpgradeState is already in progress and cannot be interrupted.
```

If I execute Get-ServiceFabricClusterConfigurationUpgradeStatus:
```
           UpgradeState ProgressStatus ConfigVersion Details
           ------------ -------------- ------------- -------
RollingForwardCompleted              0 1.0.0
```

What to do? Logs aren't telling me much...

**Comment by venushiligireddy** [comment]
> I'm having the exact same problem. I want to run a cluster upgrade but got the message above when trying to start it. I ran `Get-ServiceFabricClusterUpgrade` and got the following:
> 
> ![image](https://user-images.githubusercontent.com/36278411/38958027-e8ce0754-4310-11e8-9360-b120651ab743.png)
> 
> I know what I need to do to fix this UnhealthyEvaluation (ironically, that's why I'm trying to run the configuration upgrade), but I can't get past this. Is there a way to get this to either rollback or complete even with the unhealthy evaluation?
> 
> This is a production cluster and we're stuck.

Can you guide me how to change service fabric app health state to green, I'm facing issues in local, sometimes its continuously refreshing for 3-4 hours, but green status is not coming, showing warnings or errors. ?
