### ISSUE TITLE
Is ASF development on laptop just unstable?

### ISSUE THREAD

**Issue by sathiathirumal** [microsoft/service-fabric#798]
I wonder if the constant sleeping and network switches is not handled well by the local cluster setup.
1) DNSService has well known problems with network interface switches
2) The local cluster becomes "unstable" after a few deploys and laptop going into sleep mode

e.g.
2>Started executing script 'GetApplicationExistence'.
2>Finished executing script 'GetApplicationExistence'.
2>Time elapsed: 00:00:16.1816665
2>Unable to determine whether the application is installed on the cluster or not

Once you get to this bad state, stopping a local cluster works usually. But (re) starting it fails 100%. A machine reboot is required to clear this up, which is an absolute pain as u can imagine.

![image](https://user-images.githubusercontent.com/9466367/37883406-fbf90762-305e-11e8-9957-ea1858843536.png)

![image](https://user-images.githubusercontent.com/9466367/37883416-0ba0a3b4-305f-11e8-89d3-a18ad245690d.png)

**Comment by craftyhouse** [comment]
Please re-open if you are still facing similar issues on the latest sdks. I haven't personally seen anything like the above.
