### ISSUE TITLE
Certificate, created in azure portal for basic security, might be issued for wrong URL

### ISSUE THREAD

**Issue by BitBender1** [microsoft/service-fabric#803]
recently, the azure portals UI to create a service fabric cluster was improved. it now offers to create a service fabric cluster with basic security. this creates a cluster with a self-signed-certificate without the user needing to know how this works.

the steps i talk about are nicely documented here:
[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-portal](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-creation-via-portal)

the part of the portal-UI creating the certificate looks like this in the document above:
![image](https://user-images.githubusercontent.com/33854375/37560877-7eb4517c-2a40-11e8-9f49-f72c972c84e8.png)

after creating the cluster, that certificate is offered for download because its needed to access the cluster.

i experimented with self signed certificates and service fabric cluster many months ago, i believe to remember the certificate had to be issued for the exact URL of the cluster to have the clusters management UI work.

my problem now is, if i import that auto-generated certificate into my local certificate store, even if i put it into the root-certificates-section, i get errors and warnings when trying to access the clusters management portal because of trust-issues.

the certificate microsoft azure portal creates during cluster-setup looks like this:
![image](https://user-images.githubusercontent.com/33854375/37560783-2369ce74-2a3f-11e8-8974-d0981a7c1280.png)

while the clusters URL which i will change later ;) is like this:
![image](https://user-images.githubusercontent.com/33854375/37560814-a245c090-2a3f-11e8-8ba8-1e9edd274b8a.png)

is it possible that the URL in the self signed certificate should indeed include the cluster-name, but it doesnt? in my experiments a few months ago i made a certificate myself, using the full URL of the cluster, and that worked perfectly fine.

i believe the azure portal might create the certificate with a wrong URL

further consequence - even if i import that certificate locally, it seems the browser can not locate it when the clusters management-portal wants to query for it to ensure i am allowed to access the management-portal. so its not only a trust issue that i could just ignore in the browser, i get locked out from the management portal this way.

please have a look at the creation of that certificate or tell me if i do or understand something wrong there :)

thank you!

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
