### ISSUE TITLE
'New-AzureRmServiceFabricCluster' occurs error unlike 'az sf cluster create'

### ISSUE THREAD

**Issue by wminos** [microsoft/service-fabric#809]
I had tried both shell script examples.
* az cli example: https://docs.microsoft.com/en-us/azure/service-fabric/scripts/cli-create-cluster
* powershell example: https://docs.microsoft.com/en-us/azure/service-fabric/scripts/service-fabric-powershell-create-secure-cluster-cert

Of course, I didn't use same resource name at page.

'az sf cluster create' makes user access policy in vault,
but 'New-AzureRmServiceFabricCluster' don't create user access policy in vault.

user policy was made after 'az sf cluster create' like below, but powershell command don't.
<img width="200" alt="37150643-cd9ad496-2315-11e8-99be-879797d4a420" src="https://user-images.githubusercontent.com/36513305/37200712-f5c7d456-23c8-11e8-9ae1-7d802a182c30.png">

I had reported this issue on azure-docs page, originally.
https://github.com/MicrosoftDocs/azure-docs/issues/5253

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
