### ISSUE TITLE
Cluster provisioning failed after adding a secondary certificate

### ISSUE THREAD

**Issue by Dan-cws** [microsoft/service-fabric#818]
I deployed a single node Service Fabric cluster by the portal. After I modified the downloaded template following this instructions https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure, but the result is "Cluster provisioning failed". 
The main error is the following.

```
"code": "ClusterUpgradeFailed",
"message": "Cluster upgrade failed. Reason Code: 'HealthCheck'
"description": "Exception occured while creating an object of type FabricDCA.AzureBlobEtwCsvUploader (assembly AzureFileUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureBlobServiceFabricEtw. 
Exception occured while creating an object of type FabricDCA.AzureTableQueryableEventUploader (assembly AzureTableUploader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35) for creating consumer AzureTableServiceFabric EtwQueryable."
```

Then I deleted the cluster and redeployed with the secondary certificate and it worked fine, but when I tried to swap the certificates by the portal I got again a "Cluster provisioning failed" without no reason apparently. Following the event details, the request is accepted but neither successed nor failed.

**Comment by craftyhouse** [comment]
TSG's here should help resolve if you are still facing issues. For anything production though please file support case.
https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/tree/master/Security#certificate-expired
