### ISSUE TITLE
Unable to create/start local cluster on Windows 7 machine

### ISSUE THREAD

**Issue by ajeetcoolkarni** [microsoft/service-fabric#819]
We have windows 7 with VS 2015 Update 3 and **Service Fabric Runtime 6.1.456.9494** installed along with **Service Fabric SDK 3.0.456**. There are no errors while installing either the runtime or sdk, but still while setting up local cluster it fails with following errors, and this is happening in all the machines we are using.

**2>WARNING: Service Fabric Cluster is taking longer than expected to connect.
2>
2>Waiting for Naming Service to be ready. This may take a few minutes...
2>Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check 
2>if there is connectivity/firewall/DNS issue.
2>At C:\Program Files\Microsoft SDKs\Service 
2>Fabric\Tools\Scripts\ClusterSetupUtilities.psm1:620 char:12
2>+     [void](Connect-ServiceFabricCluster @connParams)
2>+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2>    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricClus 
2>   ter], FabricException
2>    + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFa 
2>   bric.Powershell.ConnectCluster**

**Faulting application name: Fabric.exe, version: 6.1.456.9494, time stamp: 0x5a66710e
Faulting module name: FabricCommon.dll_unloaded, version: 0.0.0.0, time stamp: 0x5a666cec
Exception code: 0xc0000005
Fault offset: 0x000007febd3e6d31
Faulting process id: 0x2854
Faulting application start time: 0x01d3a64824f31fdc
Faulting application path: C:\SfDevCluster\Data\_Node_0\Fabric\Fabric.Code\Fabric.exe
Faulting module path: FabricCommon.dll
Report Id: 62dd8dbf-123b-11e8-bbb0-00505699504f**

I don't see anything useful in Trace logs either.
[CrashDump.zip](https://github.com/Azure/service-fabric-issues/files/1727397/CrashDump.zip)
[TraceLogs.zip](https://github.com/Azure/service-fabric-issues/files/1727400/TraceLogs.zip)

I tried resintalling **microsoft visual c++ 2012 redistributable package (x64)** , tried running cleanupfabric , cleanupcluster but still the issue persists. 
Also unisntalled and reinstalled service fabric runtime and sdk multiple times, still issue persists.

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
