### ISSUE TITLE
The largest number of actor service on one service fabric cluster with three nodes

### ISSUE THREAD

**Issue by Damon227** [Microsoft/service-fabric#82]
Hi,
I have a service fabric cluster with three nodes, and it already exist two applications, then I publish the third application, it is not wroking.

If I publish the application of 'KC.Fengniaowu.Talos.ServerType' or publish the application of 'KC.Fengniaowu.Eos.ServerType' only, it is working.

The actor service TargetReplicaSetSize is 3.

![12](https://user-images.githubusercontent.com/20295242/38498750-0280879c-3c38-11e8-80c0-fc228958b6f2.png)

![13](https://user-images.githubusercontent.com/20295242/38498777-15ab6b16-3c38-11e8-982a-ec337f15aa04.jpg)

**Comment by amanbha** [comment]
@Damon227 Actor services is partitioned and can have one or emore partitions, partitions have one or more replicas. The number of replicas that can be put on a node depends on cpu, memory, disk of the machine.
