### ISSUE TITLE
Service Fabric project nuget packages are not getting restored in VSTS

### ISSUE THREAD

**Issue by ralav** [microsoft/service-fabric#826]
On latest Service Fabric SDK / .NET Core SDK / VS2017 community edition, we have 1 package reference Microsoft.VisualStudio.Azure.Fabric.MSBuild for service fabric project. I have checkin the solution and triggered build in VSTS it is failing to restore packages for .sfproj

> 2018-02-08T04:51:51.4074522Z C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe "D:\a\_temp\NuGetScratch\azh3fxfq.a3u.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="D:\a\_temp\NuGetScratch\mcjmon3n.xty.nugetrestore.targets" /p:RestoreTaskAssemblyFile="D:\a\_tool\NuGet\4.5.1\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\3\s\xyz" /p:RestoreConfigFile="D:\a\3\Nuget\tempNuGet_23.config" /p:SolutionDir="D:\a\3\s\xyz"
> 2018-02-08T04:51:51.4075226Z D:\a\3\s\xyz\xyz\xyz.sfproj(59,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.
> 2018-02-08T04:51:51.4075606Z D:\a\3\s\xyz\xyz\xyz.sfproj : warning NU1503: Skipping restore for project 'D:\a\3\s\xyz\xyz\xyz.sfproj'. The project file may be invalid or missing targets required for restore. [D:\a\_temp\NuGetScratch\azh3fxfq.a3u.nugetinputs.targets]
> 2018-02-08T04:51:51.4075817Z 
> 2018-02-08T04:51:51.4075948Z All packages listed in packages.config are already installed.

> 2018-02-08T04:52:39.3020087Z ##[error]xyz\xyz\xyz.sfproj(59,5): Error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.
> 2018-02-08T04:52:39.3020738Z Project "D:\a\3\s\xyz\xyz.sln" (1) is building "D:\a\3\s\xyz\xyz\xyz.sfproj" (4) on node 1 (Clean target(s)).
> 2018-02-08T04:52:39.3022703Z D:\a\3\s\xyz\xyz\xyz.sfproj(59,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.
> 2018-02-08T04:52:39.3023682Z Done Building Project "D:\a\3\s\xyz\xyz\xyz.sfproj" (Clean target(s)) -- FAILED.
> 2018-02-08T04:52:39.3024211Z Done Building Project "D:\a\3\s\xyz\xyz.sln" (Clean target(s)) -- FAILED.
> 2018-02-08T04:52:39.3566326Z 
> 2018-02-08T04:52:39.3567113Z Build FAILED.
> 2018-02-08T04:52:39.3614454Z 
> 2018-02-08T04:52:39.3628772Z "D:\a\3\s\xyz\xyz.sln" (Clean target) (1) ->
> 2018-02-08T04:52:39.3628987Z "D:\a\3\s\xyz\xyz\xyz.sfproj" (Clean target) (4) ->
> 2018-02-08T04:52:39.3629188Z (ValidateMSBuildFiles target) -> 
> 2018-02-08T04:52:39.3629452Z   D:\a\3\s\xyz\xyz\xyz.sfproj(59,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.
> 2018-02-08T04:52:39.3629651Z 
> 2018-02-08T04:52:39.3630272Z     0 Warning(s)
> 2018-02-08T04:52:39.3630552Z     1 Error(s)
> 2018-02-08T04:52:39.3633535Z 
> 2018-02-08T04:52:39.3633896Z Time Elapsed 00:00:21.14
> 2018-02-08T04:52:39.7984353Z ##[error]Process 'msbuild.exe' exited with code '1'.

To expel this issue, i have checkin the packages folder manually as a work around.

**Comment by brianvanderlugt** [comment]
In spite of what this thread indicates, there are conditions in which `InitialTargets=";ValidateMSBuildFiles"` seems to be required. Or I just haven't been able to put the right solution together.

While building locally worked fine, my ADO build kept failing. I've got a solution of projects that has a mix of PackageReference and my sfproj's that have packages.config. I tried the various fixes, save for deleting the whole validation logic altogether, and they all failed for one reason or another. For some reason, including the InitialTargets condition causes my first nuget restore to do a packages.config restore and restore to both the global nuget cache and the solution level nuget cache the build tasks depend on via relative reference. Not sure why and giving up trying to figure out a better solution.

Leaving this here in case it saves someone else the headache of not trying because "it shouldn't be required".

**Comment by MartinDemberger** [comment]
I had the same problem with the restored package after I updated from 1.7.2 to 1.7.3.

In run on the devops pipeline with
```xml
  <Import Project="..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.7.3\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.7.3\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
```

but localy the package wasn't found. So I implemented the following workaround

```xml
  <PropertyGroup>
    <!-- This version number must be the same as in packages.config -->
    <ServiceFabricPackageVersion>1.7.3</ServiceFabricPackageVersion>
    <ServiceFabricPackageRootFolder>..\packages</ServiceFabricPackageRootFolder>
    <ServiceFabricPackageRootFolder Condition="!Exists('$(ServiceFabricPackageRootFolder)')">$(APPDATA)\BuildConfig\packages</ServiceFabricPackageRootFolder>
    <!-- Nothing found: back to start. -->
    <ServiceFabricPackageRootFolder Condition="!Exists('$(ServiceFabricPackageRootFolder)')">..\packages</ServiceFabricPackageRootFolder>
  </PropertyGroup>
  <Import Project="$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.props" Condition="Exists('$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.7.3\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" />
```

And at the end of the sfproj file I changed to:
```xml
  <Import Project="$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets" Condition="Exists('$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" />
  <Target Name="ValidateMSBuildFiles" BeforeTargets="PrepareForBuild">
    <Error Condition="!Exists('$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.props')" Text="Unable to find the '$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
    <Error Condition="!Exists('$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets')" Text="Unable to find the '$(ServiceFabricPackageRootFolder)\Microsoft.VisualStudio.Azure.Fabric.MSBuild.$(ServiceFabricPackageVersion)\build\Microsoft.VisualStudio.Azure.Fabric.Application.targets' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package." />
  </Target>
```

Now it's running local and in the pipeline.

**Comment by thales-man** [comment]
the whole is not fit for purpose and hasn't been for years. the whole toolchain is questionable, nuget has over 2k issues logged against it. most of the devs nad been moved elsewhere. they seem to work on the principal, let's buy a phone company, ah, no we're bored now, let's dump it. let's build a voice system and embed in some speakers that seems like a good idea... ah, no we're bored now, let's give 20 bucks and f*** 'em off. let's build a dual screen android phone (but not call it a phone), because we've never failed at that before... you know we're not much cop at android... i wonder....

**Comment by ralav** [comment]
Inderministic targets and should be available over built-in support for Dotnet build tool extension.

**Comment by woeterman94** [comment]
I followed [MartinDemberger](https://github.com/MartinDemberger)'s steps. 
And in my yaml I needed to add:

```
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          solution: $(SlnPath)
          restoreDirectory: '$(System.DefaultWorkingDirectory)/packages/'
```
          
          
 restoreDirectory refering the the packages folder
