### ISSUE TITLE
Container template

### ISSUE THREAD

**Issue by clausndk** [microsoft/service-fabric#827]
Hello Service Fabric users

I'm looking to support containers in our clusters, but I'm having difficulties understanding what is required, and how to setup my cluster for production use.

Having looked at the tutorial for creating a containerized application:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-time-interval-before-container-is-force-terminated

.. there are some recommendations, regarding termination of containers, as well as configuring the runtime to prune unused images:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers#configure-the-runtime-to-remove-unused-container-images

Both sections refer to a "Hosting" section, but I have yet to understand where "Hosting" is to be placed?
I'm also unable to find any templates utilizing this kind of setup, so what are other people's solution to this, and/or recommendations regarding cluster templates?

We currently have a cluster in production, but without VM image support for containers, but I've activated the 2016-Datacenter-with-Containers vmImageSku for a new setup.

Any feedback is much appreciated!

**Comment by craftyhouse** [comment]
Looks like this was created after this issue https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-containers which should help. Please let us know if you need more assistance.
