### ISSUE TITLE
DNS service not starting on Linux cluster created from portal

### ISSUE THREAD

**Issue by vjrantal** [microsoft/service-fabric#831]
I am trying to get the DNS configuration as described in https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose#servicednsname-computation

Here is what my docker-compose.yml looks like:

```
$ cat docker-compose.yml 
version: "3"

services:
  python.server.app:
    ports:
      - 80:8080
    image: <...>.azurecr.io/python-server-app
```

I am doing the deployment like:

```
$ sfctl compose create --deployment-name NewDeploymentName --file-path docker-compose.yml --user <...> --has-pass
```
The deployment seemingly succeeds, but in the Service Fabric Explorer, I can see that the application manifest ends up having following content:

```
...
 <DefaultServices>
  <Service Name="python.server.app" ServiceDnsName="" ServicePackageActivationMode="ExclusiveProcess">
   <StatelessService ServiceTypeName="python.server.appType">
    <SingletonPartition/>
   </StatelessService>
  </Service>
...
```

Key part in above is that the `ServiceDnsName` attribute is empty.

I am running a Linux cluster with Service Fabric version 6.0.133.1. The `sfctl` is installed is:

```
$ pip freeze | grep sfctl
sfctl==3.0.0
```

**Comment by craftyhouse** [comment]
Closing due to age, but please re-open if facing similar issue. I have recently deployed some linux clusters via portal with dns services okay so looks resolved. We also now do some checks for proper vm sizes.
