### ISSUE TITLE
SF Cluster Troubleshooting - Naming Service down

### ISSUE THREAD

**Issue by nareshkhatri81** [microsoft/service-fabric#840]
Hi Team,

when trying to connect to cluster its saying not able to contact naming service and then displaying connecting information.
Below ip address and name of node i have marked with * for security reason.

PS C:\Windows\system32> Connect-ServiceFabricCluster
WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
True

ConnectionEndpoint   :
FabricClientSettings : {
                       ClientFriendlyName                   : PowerShell-1b89ff35-f5f6-43d1-8cdb-3555587bd8a6
                       PartitionLocationCacheLimit          : 100000
                       PartitionLocationCacheBucketCount    : 1024
                       ServiceChangePollInterval            : 00:02:00
                       ConnectionInitializationTimeout      : 00:00:02
                       KeepAliveInterval                    : 00:00:20
                       ConnectionIdleTimeout                : 00:00:00
                       HealthOperationTimeout               : 00:02:00
                       HealthReportSendInterval             : 00:00:00
                       HealthReportRetrySendInterval        : 00:00:30
                       NotificationGatewayConnectionTimeout : 00:00:30
                       NotificationCacheUpdateTimeout       : 00:00:30
                       AuthTokenBufferSize                  : 4096
                       }
GatewayInformation   : {
                       NodeAddress                          : *********:19000
                       NodeId                               : ec164054d539e07b93a4d66d91991fd4
                       NodeInstanceId                       : 131598930182215759
                       NodeName                             : ********
                       }

after that when i try to see service fabric health. i am getting timeout.
PS C:\Windows\system32> Get-ServiceFabricClusterHealth
Get-ServiceFabricClusterHealth : Operation timed out.
At line:1 char:1
+ Get-ServiceFabricClusterHealth
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabr
   icClusterHealth], TimeoutException
    + FullyQualifiedErrorId : GetClusterHealthErrorId,Microsoft.ServiceFabric.Powershell.GetClusterHealth

SF Explorer is opening but its saying gateway timeout.

These processes are running on node in cluster.

PS C:\Windows\system32> Get-Process fab*

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    452      65    50304      56916   1,182.33   8888   0 Fabric
    143    3140   710448      98528       8.95  12572   0 FabricApplicationGateway
    534      40    72360      86440     145.88   1116   0 FabricDCA
    377      45    52108      70580       2.41  14064   0 FabricFAS
    189     113    14948      25192      13.58  12724   0 FabricGateway
    419      20     8396      19244       0.97   1788   0 FabricHost
    382      45    71508      91624       2.41  14816   0 FabricUOS

Let me know how to troubleshoot this issue in cluster.

Thanks,
Naresh Khatri

**Comment by craftyhouse** [comment]
Closing due to age, but please re-open if facing similar issue. Thanks
