### ISSUE TITLE
Question - Service Fabric Powershell modules onpremise

### ISSUE THREAD

**Issue by nareshkhatri81** [microsoft/service-fabric#843]
Hi Team,

Does service fabric power-shell modules requires SF runtime to be present ?
is there way to install SF powershell moduels from powershell gallery for onpremise ?

we are having build server from where we are trying to deploy to cluster using powershell.

As per documentation to install SF Powershell module, we need to install SDK.
we tried to install SDK but its required SF run time to be present.
on build server, we don't want to install SF runtime.

we are using below command to connect to cluster which fails with error.
Not able to find naming service, trying to contact FMS.
failed to contact FMS.

$endpoint = http://ipaddressofnode:19000
Connect-ServiceFabricCluster -ConnectionEndpoint $endpoint

https://docs.microsoft.com/en-us/azure/service-fabric/scripts/service-fabric-powershell-deploy-application

with sfctl command
https://docs.microsoft.com/en-us/azure/service-fabric/samples-cli

 we are able to connect to cluster from build server and able to do deployment.
can we use powershell commands as mentioned in above link ? we want to deploy it from machine which doesnt have runtime present.

we are having cluster on onpremise.

do we need to run SF powershell command remotely to one of node in cluster to do the deployment?

Thanks,
Naresh Khatri

**Comment by craftyhouse** [comment]
Please let us know if you have this issue using the latest powershell modules (you shouldn't)
