### ISSUE TITLE
ConfigOverrides are not being applied in Azure Cluster

### ISSUE THREAD

**Issue by ivanhernandez** [microsoft/service-fabric#851]
A stateless, singleton service being deployed into Azure with ConfigOverrides, is taking default values declared in application manifest parameters list. Values in application parameters file are not being take into consideration.

When deploying the same application into local 1 node cluster, using the same application parameters file (local1node publish profile makes use of the same parameters file), it works ok (application instance running at local cluster reads overriden values instead of default ones).

 * Azure cluster is at version 6.1.445.9494. It is a 2016 datacenter. _The application works on .Net Fw 4.6.2_
 * Local cluster is at version 6.0.232.9494.
* Application is including Microsoft.ServiceFabric nuget 6.0.232 _(upgrading to 6.1.232-preview does not fix the problem)_
* Microsoft Azure Service Fabric SDK locally installed is 2.8.232

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
