### ISSUE TITLE
Service Fabric - services running inside Containers not able to talk with Naming service - FabricClient.dll not found.

### ISSUE THREAD

**Issue by nareshkhatri81** [microsoft/service-fabric#852]
Hello Team,

while trying to consume naming service by using Service Fabric SDK getting below error.

Sample Code

 ServicePartitionResolver resolver = ServicePartitionResolver.GetDefault();
CancellationToken cancellationToken;
            
            ResolvedServicePartition partition =
                await resolver.ResolveAsync(new Uri("fabric:/app/service"), new ServicePartitionKey(),cancellationToken);
        
Error
{"IsError":true,"ErrorMessages":["Unable to load DLL 'FabricClient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)","   at System.Fabric.Interop.NativeClientInternal.GetFabricClientDefaultSettings()\r\n   at System.Fabric.FabricClientSettings.LoadFromConfigHelper()\r\n   at System.Fabric.Interop.Utility.<>c__DisplayClass27_0.<WrapNativeSyncInvoke>b__0()\r\n   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)\r\n   at System.Fabric.Interop.Utility.RunInMTA(Action action)\r\n   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.<>c.<GetDefault>b__20_0()\r\n   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.GetClient()\r\n   at Microsoft.ServiceFabric.Services.Client.ServicePartitionResolver.<ResolveHelperAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApi.Controllers.Controller.<HelloWorldUsingNamingServiceRestAPI>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"],"SuccessMessages":[],"LocaleCode":"en-US","BaseReturnCode":1000}

I have below nuget packages. None of those contains FabricClient.dll.
i can see that FabricClient.dll. is part of service fabric runtime at all nodes in cluster where SF is installed.

it seems there is tight coupling between SDK and SF runtime.
Inside containers, we don't have runtime. Host has runtime installed.

<packages>
  <package id="Microsoft.ServiceFabric" version="6.0.211" targetFramework="net451" />
  <package id="Microsoft.ServiceFabric.Data" version="2.8.211" targetFramework="net451" />
  <package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="2.8.211" targetFramework="net451" />
  <package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="2.8.211" targetFramework="net451" />
  <package id="Microsoft.ServiceFabric.Services" version="2.8.211" targetFramework="net451" />
  <package id="Microsoft.ServiceFabric.Services.Remoting" version="2.8.211" targetFramework="net451" />
</packages>

Thanks,
Naresh Khatri

**Comment by craftyhouse** [comment]
please let us know if you still have this issue with supported versions. thanks!
