### ISSUE TITLE
Internal Error for ImageStore on Mac

### ISSUE THREAD

**Issue by nickward13** [microsoft/service-fabric#854]
I'm trying to follow the tutorial at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started-mac.  I have the sfonebox container up and running and can succesfully connect to the SF Explorer via the browser.  

I get an error when I try and upload my java app using the following command: 
sfctl application upload --path sf-java-app --show-progress

The error contains the following text (excerpt):
requests.exceptions.HTTPError: 500 Server Error: Internal Error for url: http://localhost:19080/ImageStore/sf-java-app/ApplicationManifest.xml?api-version=3.0-preview

I believe I've followed all the steps (multiple times) and can't seem to get past this error.  Any help would be greatly appreciated.

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.
