### ISSUE TITLE
Visual Studio 2017 Performance Profiler with 1 Node Local Dev Cluster (.net Core)

### ISSUE THREAD

**Issue by Eneuman** [microsoft/service-fabric#855]
Has anyone been able to get the VS performance profiler running against a stateless .Net Core 2.0 Project?
Is it possible? If not, is there a timeframe when this will be fixed?

**Comment by craftyhouse** [comment]
Please re-open if you are still facing this issue, but closing at this time.

**Comment by jabhalla** [comment]
I'm trying to run Profiler with an SF app for memory leaks in VS 2022. Does SF support VS Profiler or this is still not supported?
