### ISSUE TITLE
FileNotFoundException: ServiceFabricServiceModel.xsd ?!?!

### ISSUE THREAD

**Issue by uvznab** [microsoft/service-fabric#866]
Been working over a week trying to deploy a standalone Service Fabric secured cluster on premise for our development/staging environment. I've been following ALL the official guides and experimental blogs. Been tackling one roadblock after the other. This last one left me completely lost and would greatly appreciate assistance.

TestConfiguration.ps1 passes with flying colors.
All 17 requirements for the environment set up have been implemented and tested (ports, services, remote access, accounts, etc).
during the creation of the cluster, right after configuring all the nodes, I get a System.IO.FileNotFoundException: ServiceFabricServiceModel.xsd error and from there, a cascade rollback with no further detail.
All logs seem to be as mysterious with no exact explanation as to where was this file attempted to be found (it's there where it should be with the rest of the cluster setup!), at what stage is this thrown, why is this needed, etc.

Any suggestions where to look or what to test?

For reference, here's the exact powershell output:

> PS C:\Users\Administrator\Downloads\AzureServiceFabric\> .\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\Dev.ClusterConfig.Windows.Multimachine.json -FabricRuntimePackagePath .\MicrosoftAzureServiceFabric.6.0.219.9494.cab -AcceptEULA
Creating Service Fabric Cluster...
If it's taking too long, please check in Task Manager details and see if Fabric.exe for each node is running. If not, please look at: 1. traces in DeploymentTraces directory and 2. traces in FabricLogRoot configured in ClusterConfig.json.
Trace folder already exists. Traces will be written to existing trace folder: C:\Users\Administrator\Downloads\AzureServiceFabric\DeploymentTraces
Running Best Practices Analyzer...
Best Practices Analyzer completed successfully.
Creating Service Fabric Cluster...
Processing and validating cluster config.
Configuring nodes.
Default installation directory chosen based on system drive of machine 'Node01'.
Copying installer to all machines.
Configuring machine 'Node01'.
Configuring machine 'Node03'.
Configuring machine 'Node02'.
Configuring machine 'Node04'.
System.IO.FileNotFoundException: ServiceFabricServiceModel.xsd
   at System.Fabric.Common.SchemaLocation.GetWindowsFabricSchemaLocation()
   at System.Fabric.FabricDeployer.DeploymentParameters.Initialize()
   at System.Fabric.FabricDeployer.DeploymentOperation.ExecuteOperation(DeploymentParameters parameters, Boolean disableFileTrace)
   at System.Fabric.FabricDeployer.ConfigurationDeployer.NewNodeConfigurationInner(String clusterManifestPath, String infrastructureManifestPath, String jsonClusterConfigPath, String fabricDataRoot, String fabricLogRoot, String fabricHostCredentialUser, SecureString fabricHostCredentialPassword, Boolean runFabricHostServiceAsManual, Boolean removeExistingConfiguration, FabricPackageType fabricPackageType, String fabricPackageRoot, String machineName, String bootstrapPackagePath)

**Comment by maburlik** [comment]
We have added extra fallback steps in cleanup to purge old versions from GAC as part of uninstall.
