### ISSUE TITLE
SFRP in inconsistent state after certificate swap

### ISSUE THREAD

**Issue by mkosieradzki** [microsoft/service-fabric#884]
During certificate rollover, if some (not sure which ones) of the conditions are met (not sure which ones):
1. the new certificate has a different CN than original
2. swap occurs on primary certificate first
3. new certificate has later issuance date but old certificate has later expiration date
4. service fabric endpoint address is not updated to the new CN
5. original certificate is self signed, new certificate is issued by a proper CA

upgrade fails leaving SFRP resource for cluster in an inconsistent state. The main symptom of this state is:
```
Error event: SourceId='UpgradeService.Primary', Property='SFRPPoll'.
Exception encountered: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
```

No further ARM upgrade operation can succeed due to UpgradeServiceDown.

Workaround:
using upgrade service downgrade cluster to a different version and upgrade it back

Because reproduction is highly time consuming it is difficult to say which points: 1,2,3,4,5 are enough for this issue to occur.

/cc: @ChackDan 

UPDATE: after restoring back to original certificates UpdateService sometimes stabilizes and allows another upgrade (without changing the cluster version)

**Comment by craftyhouse** [comment]
Closing due to age and change in guidance for support 
https://github.com/microsoft/service-fabric/blob/0ed99b8b37b91f46d2481c5a784179c1a6c7e7df/CONTRIBUTING.md#production-issues
