### ISSUE TITLE
Cluster Certificate swap - Stuck in Updating state

### ISSUE THREAD

**Issue by funrockstefan** [microsoft/service-fabric#897]
We have a cluster stuck in limbo after swapping out the primary cluster certificate to a newer certificate
We did these operations (adding secondary and swapping) using ARM in one go,
as described here: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure#add-a-secondary-certificate-and-swap-it-to-be-the-primary-using-resource-manager-powershell
The New-AzureRmResourceGroupDeployment execution timed out after > 2 hours.
Although the certificate swap seems to have been successful on all nodes, the Azure Portal reports a failed deployment due to the timeout, and
the Cluster is still in 'Updating' mode after over 24 hours later (Cluster is updating user certificate.)
Which means that we are kind of stuck here.

Also, the fabric:/System/UpgradeService is reporting an unhealthy evaluation:
Unhealthy event: SourceId='UpgradeService.Primary', Property='SFRPPoll', HealthState='Warning', ConsiderWarningAsError=false.
Exception encountered: System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

Any advice is appreciated...

**Comment by esond** [comment]
@michelnyx 

If it's of any help to you (and anyone else who finds this), I had the same issue. I was informed by support that:

> Service Fabric itself needs a bare minimum of 14GB SSD to even be able to operate. A minimum of D1_V2 is recommended for test environment and D2_V2 for production.

So, I guess we can't cheap out on the VMs, heh.

**Comment by craftyhouse** [comment]
please re-open if you need further support on this. We have new guidance for production support. 
https://github.com/microsoft/service-fabric/blob/0ed99b8b37b91f46d2481c5a784179c1a6c7e7df/CONTRIBUTING.md#production-issues
