### ISSUE TITLE
Allow singleton stateless services to have multiple instances per node bypassing placement constraint 

### ISSUE THREAD

**Issue by guibirow** [microsoft/service-fabric#902]
I've posted this as an Idea in UserVoice, but I think this is a bug, so I will post it here as well.
[https://feedback.azure.com/forums/293901-service-fabric/suggestions/19664074-allow-singleton-services-to-have-multiple-instance](url)

Currently, service fabric does not allow you to have multiple instances of the same service in the same node to avoid data loss. But for stateless services it is not the case, as we do not have data to loose neither replication, the orchestrator should know that if my stateless service has more instances than the node count, it should be smart enough to split these instances around the nodes without warning about it.

`
Unhealthy event: SourceId='System.PLB', Property='ServiceReplicaUnplacedHealth_Secondary_ba654c6a-3e83-4560-9ea1-9fadbe7b115d', HealthState='Warning', ConsiderWarningAsError=false. The Load Balancer was unable to find a placement for one or more of the Service's Replicas: Secondary replica could not be placed due to the following constraints and properties: TargetReplicaSetSize: 9 Placement Constraint: N/A Parent Service: N/A Constraint Elimination Sequence: Existing Secondary Replicas eliminated 3 possible node(s) for placement -- 0/3 node(s) remain. `

**Comment by moldyseaswimmer** [comment]
If you included a UI feature in SFX to do something like below that would be suitable but allow us to specify the number of times New-ServiceFabricService is called

Connect-ServiceFabricCluster localhost:19000
New-ServiceFabricService -ApplicationName 'fabric:/rnd2' -ServiceName 'fabric:/rnd2/Stateless3' -ServiceTypeName 'Stateless2Type' -Stateless -PartitionSchemeSingleton -InstanceCount 1


Remove-ServiceFabricService -ServiceName fabric:/rnd2/Stateless3

**Comment by vshan** [comment]
This functionality is now available through the https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-resource-manager-advanced-placement-rules-placement-policies#placement-of-multiple-stateless-instances-of-a-partition-on-single-node AllowMultipleStatelessInstancesOnNode placement policy.
