### ISSUE TITLE
On-prem hardware recommendation, clarify documentation

### ISSUE THREAD

**Issue by gcampbell-epiq** [microsoft/service-fabric#911]
In reference to this article:
[https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation)

It's surprising to me that the hardware recommendation is 16GB RAM. What is this based on? This seems appropriate in a scenario where reliable collections and stateful services are used, but does not seem appropriate in a scenario where they are not used. For example in my situation, we are only interested in very small stateless owin self hosted services. 

Can you provide more detail around how to determine the appropriate hardware?

**Comment by craftyhouse** [comment]
Not sure this existed at the time of this post so referencing.

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-capacity-planning

Suggest in general to use perf counters to help your data model as the applications can vary so much it's hard to just provide generic answers.
