### ISSUE TITLE
Feature request: reliable collection explorer

### ISSUE THREAD

**Issue by SeanFeldman** [microsoft/service-fabric#915]
Currently, there's no way to view (or modify) reliable collection items.
Considering that a lot of data could potentially be stored in SFRC to replace a data store, this becomes a question of "if this is my data store, why can't I see the data".

Is this something that is planned and if so, what's the functionality it will support?

**Comment by zuhairp** [comment]
We have released a Backup Explorer that will allow you to view a Reliable Collections backup offline: https://github.com/microsoft/service-fabric-backup-explorer 

We will be soon releasing a read-only viewer tool for viewing live data in Reliable Collections.

**Comment by athinanthny** [comment]
@SeanFeldman Please review backup explorer info shared in former commend and let us know it meets needs or your requirements. If yes, please close the issue and watch our release announcements for updates on RC viewer tool updates

**Comment by craftyhouse** [comment]
Tool released as noted above and demoed in community call 48.
