### ISSUE TITLE
Service Fabric Runtime 6.2 installation on Windows 10 might fail

### ISSUE THREAD

**Issue by MikkelHegn** [microsoft/service-fabric#92]
Installing Service Fabric Runtime 6.2 on Windows 10 might fail because of a conflict deleting ese.dll. If the installation fails, you can find a setup log in the %LOCALAPPDATA%\Temp\InstallFabricRuntime.log, which will give you detailed information about the error.

To successfully install the runtime, restart your machine and re-run the installer.

**Comment by maburlik** [comment]
This is fixed in internal builds and is planned to included in the next major release.

**Comment by maburlik** [comment]
To clarify the mitigation from above, a reboot is not necessary: stop com.docker.service, install the new version of Service Fabric, then restart the docker service.

**Comment by maburlik** [comment]
This is fixed via an automitigation code path in the installer as of 7.0 CU4:
https://techcommunity.microsoft.com/t5/azure-service-fabric/azure-service-fabric-7-0-fourth-refresh-release/ba-p/1205414
