### ISSUE TITLE
StandAlone Cluster Config upgrade

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [microsoft/service-fabric#926]
Hi ,

Is there a way to upgrade only config without code .Basically i am trying to upgrade using Azure SDk. I need equivalent method which we use in Powershell **ServiceFabricClusterConfigurationUpgrade**  . in Azure SDK.

**Comment by maburlik** [comment]
How are you trying to run this? Please share the details regarding what you've tried so far.

**Comment by AbhishekAdusumilli** [comment]
@maburlik : I have tried using ProvisionFabricAsync  method by passing packagePath as null .

**Comment by maburlik** [comment]
Using newer thread for this item:
https://github.com/microsoft/service-fabric/issues/952
