### ISSUE TITLE
Microsoft Azure Service fabric runtime - 6.4.617 did not install

### ISSUE THREAD

**Issue by mishvivek** [microsoft/service-fabric#928]
I tried several times installing and every time gives us error
Can you plz share me the fix

DownloadManager Information: 0 : Loading product xml from: https://go.microsoft.com/?linkid=9842185
DownloadManager Information: 0 : https://go.microsoft.com/?linkid=9842185 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Location: https://webpifeed.blob.core.windows.net/webpifeed/WebProductList.xml
Server: Kestrel
Request-Context: appId=cid-v1:26ef1154-5995-4d24-ad78-ef0b04f11587
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Mon, 04 May 2020 20:02:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 04 May 2020 20:02:14 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/WebProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Content-Length: 0
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 8c3c22f1-e01e-0043-0b4e-221280000000
x-ms-version: 2009-09-19
Date: Mon, 04 May 2020 20:02:14 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\1343597488.xml.temp
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID 5nine
DownloadManager Warning: 0 : Could not resolve keyword ID Security
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Portal
DownloadManager Warning: 0 : Could not resolve keyword ID Backup
DownloadManager Warning: 0 : Could not resolve keyword ID Resource Provider
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID VMWare
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Usage
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Hybrid Cloud
DownloadManager Warning: 0 : Could not resolve keyword ID Windows Azure Pack
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Assert
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Cloud Cruiser
DownloadManager Warning: 0 : Could not resolve keyword ID Billing
DownloadManager Warning: 0 : Could not resolve keyword ID Showback
DownloadManager Warning: 0 : Could not resolve keyword ID Terawe
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Loading product xml from: https://aka.ms/webapplicationlist
DownloadManager Information: 0 : https://aka.ms/webapplicationlist responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Location: https://webgallery.microsoft.com/feed/webapplicationlist.xml
Server: Kestrel
Request-Context: appId=cid-v1:9b037ab9-fa5a-4c09-81bd-41ffa859f01e
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Mon, 04 May 2020 20:02:17 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 04 May 2020 20:02:17 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

DownloadManager Information: 0 : https://webgallery.microsoft.com/feed/webapplicationlist.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 Not Modified
ETag: "0ab6bbeeb1bd61:0"
Date: Mon, 04 May 2020 20:02:18 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\-966730450.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://aka.ms/webapplicationlist' after preprocessing, location on disk: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\preprocessor\-966730450.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Content-Length: 0
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 8c3c2aab-e01e-0043-374e-221280000000
x-ms-version: 2009-09-19
Date: Mon, 04 May 2020 20:02:19 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\2000756975.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/MediaProductList.xml' after preprocessing, location on disk: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\preprocessor\2000756975.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Content-Length: 0
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 8c3c2b29-e01e-0043-274e-221280000000
x-ms-version: 2009-09-19
Date: Mon, 04 May 2020 20:02:19 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\609314840.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/ToolsProductList.xml' after preprocessing, location on disk: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\preprocessor\609314840.xml'
DownloadManager Information: 0 : Loading product xml from: https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml
DownloadManager Information: 0 : https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml responded with 304
DownloadManager Information: 0 : Response headers:
HTTP/1.1 304 The condition specified using HTTP conditional header(s) is not met.
Content-Length: 0
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 8c3c2ba5-e01e-0043-194e-221280000000
x-ms-version: 2009-09-19
Date: Mon, 04 May 2020 20:02:19 GMT

DownloadManager Information: 0 : Remote file has not changed, using local cached file: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\140237651.xml.temp
DownloadManager Information: 0 : Filtering by current OS
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://webpifeed.blob.core.windows.net/webpifeed/EnterpriseProductList.xml' after preprocessing, location on disk: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\preprocessor\140237651.xml'
DownloadManager Information: 0 : Sucessfully loaded the feed 'https://go.microsoft.com/?linkid=9842185' after preprocessing, location on disk: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\preprocessor\1343597488.xml'
DownloadManager Information: 0 : Getting ratings file from http://go.microsoft.com/?linkid=9752395
DownloadManager Information: 0 : http://go.microsoft.com/?linkid=9752395 responded with 302
DownloadManager Information: 0 : Response headers:
HTTP/1.1 302 Moved Temporarily
Location: http://www.microsoft.com/web/handlers/WebPI.ashx?command=getatomfeedwithavgratingquery
Server: Kestrel
Request-Context: appId=cid-v1:b47e5e27-bf85-45ba-a97c-0377ce0e5779
X-Response-Cache-Status: True
X-Powered-By: ASP.NET
Content-Length: 0
Expires: Mon, 04 May 2020 20:02:20 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 04 May 2020 20:02:20 GMT
Connection: keep-alive

DownloadManager Information: 0 : Contextual entry products: MicrosoftAzure-ServiceFabric-CoreSDK
DownloadManager Information: 0 : Adding product Microsoft Azure Service Fabric SDK - 3.3.617 (MicrosoftAzure-ServiceFabric-CoreSDK) to cart
DownloadManager Information: 0 : Contextual navigation to product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '0'
DownloadManager Information: 0 : Number of bytes after possible decompression: '0'
DownloadManager Warning: 0 : Error getting last-modified header, error code: 12150
DownloadManager Warning: 0 : HttpQueryInfoWithRetry for HTTP_QUERY_LAST_MODIFIED failed.
DownloadManager Error: 0 : Error loading rating files: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Microsoft.Web.PlatformInstaller.ProductServiceImpl.GetAppRatings()
DownloadManager Error: 0 : WebClient download error. Uri: http://www.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png, Error: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.Web.PlatformInstaller.UI.DownloadServiceImplementation.DownloadFile(Uri uri, String filePath)
DownloadManager Error: 0 : WebClient download error. Uri: http://www.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png, Error: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.Web.PlatformInstaller.UI.DownloadServiceImplementation.DownloadFile(Uri uri, String filePath)
DownloadManager Information: 0 : http://www.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://developer.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-EdgeConnect-Origin-MEX-Latency: 39
Date: Mon, 04 May 2020 20:02:28 GMT
Connection: keep-alive
TLS_version: UNKNOWN
X-RTag: RT

DownloadManager Information: 0 : http://www.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://developer.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-EdgeConnect-Origin-MEX-Latency: 36
Date: Mon, 04 May 2020 20:02:28 GMT
Connection: keep-alive
TLS_version: UNKNOWN
X-RTag: RT

DownloadManager Information: 0 : https://developer.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://developer.microsoft.com/en-us/web
Date: Mon, 04 May 2020 20:02:28 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains

DownloadManager Information: 0 : https://developer.microsoft.com/web/media/gallery/apps-screenshots/webplatformsplashscreen.png responded with 301
DownloadManager Information: 0 : Response headers:
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://developer.microsoft.com/en-us/web
Date: Mon, 04 May 2020 20:02:28 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains

DownloadManager Information: 0 : Adding product 'MicrosoftAzure-ServiceFabric-CoreSDK'
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricSDK_3_3_RTO
DownloadManager Information: 0 : Adding dependency product 'ServiceFabricRuntime_6_4_RTO
DownloadManager Information: 0 : Adding dependency product 'VC11Redist_x64
DownloadManager Information: 0 : Content-Encoding header: 'gzip'
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '15816'
DownloadManager Information: 0 : Number of bytes after possible decompression: '80883'
DownloadManager Information: 0 : Content-Encoding header: 'gzip'
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '15815'
DownloadManager Information: 0 : Number of bytes after possible decompression: '80883'
DownloadManager Information: 0 : Setting current install to 1
DownloadManager Information: 0 : Starting install sequence
DownloadManager Information: 0 : Downloading file 'http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU1/vcredist_x64.exe' to: C:\Users\vivmishr1\AppData\Local\Temp\tmpC0B6.tmp
DownloadManager Information: 0 : Number of bytes downloaded over the internet: '7194488'
DownloadManager Information: 0 : Number of bytes after possible decompression: '7194488'
DownloadManager Information: 0 : File 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\VC11Redist_x64\ABE47E4996CF0409A794C1844F1FA8404032EDB2\vcredist_x64.exe' already exists, deleting old copy of the file
DownloadManager Information: 0 : Moving downloaded file 'C:\Users\vivmishr1\AppData\Local\Temp\tmpC0B6.tmp' to: C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\VC11Redist_x64\ABE47E4996CF0409A794C1844F1FA8404032EDB2\vcredist_x64.exe
DownloadManager Information: 0 : Using cached file at C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_RTO\79EDC918E599D35F729FC8822DBC3582CBB15E8A\MicrosoftServiceFabric.6.4.617.9590.exe instead of downloading from https://download.microsoft.com/download/D/D/D/DDD408E4-6802-47FB-B0A1-ECF657BEB35F/MicrosoftServiceFabric.6.4.617.9590.exe
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'. Commandline is: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\VC11Redist_x64\ABE47E4996CF0409A794C1844F1FA8404032EDB2\vcredist_x64.exe /q /norestart'. Process Id: 9660
DownloadManager Information: 0 : Install exit code for product 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)' is '0'
DownloadManager Information: 0 : Install return code for product 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)' is Success
DownloadManager Information: 0 : Product Microsoft Visual C++ 2012 SP1 Redistributable Package (x64) done install completed
DownloadManager Information: 0 : Increasing current install to 2
DownloadManager Information: 0 : Launching the file with Windows: http://azure.microsoft.com/
DownloadManager Information: 0 : Using cached file at C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricSDK_3_3_RTO\9FC51F4ECF712819D89787116B58C036FCDFC529\MicrosoftServiceFabricSDK.3.3.617.msi instead of downloading from https://download.microsoft.com/download/D/D/D/DDD408E4-6802-47FB-B0A1-ECF657BEB35F/MicrosoftServiceFabricSDK.3.3.617.msi
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c wmic product where name="Microsoft Azure Service Fabric" call uninstall'. Process Id: 13428
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.617' is '1'
DownloadManager Information: 0 : Ignoring exit code '1' for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop KtlLogger'. Process Id: 10180
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.617' is '1'
DownloadManager Information: 0 : Ignoring exit code '1' for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop LeasLayr'. Process Id: 1620
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.617' is '1'
DownloadManager Information: 0 : Ignoring exit code '1' for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 6.4.617'. Commandline is: 'C:\Users\vivmishr1\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_6_4_RTO\79EDC918E599D35F729FC8822DBC3582CBB15E8A\MicrosoftServiceFabric.6.4.617.9590.exe /AcceptEULA'. Process Id: 13880
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 6.4.617' is '1'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric Runtime - 6.4.617' is Failure
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric Runtime - 6.4.617 done install completed
DownloadManager Information: 0 : Increasing current install to 3
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.617'. Skipping install
DownloadManager Warning: 0 : Dependency failed for product 'Microsoft Azure Service Fabric SDK - 3.3.617'. Skipping install
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.617 had a dependency fail. Increasing install product to 4
DownloadManager Information: 0 : Product Microsoft Azure Service Fabric SDK - 3.3.617 had a dependency fail. Increasing install product to 5
DownloadManager Information: 0 : Product: VC11Redist_x64, Install Status: InstallCompleted-Success, Install Time: 00:00:04.2349745
DownloadManager Information: 0 : Product: ServiceFabricRuntime_6_4_RTO, Install Status: InstallCompleted-Failure, Install Time: 00:00:13.2645900
DownloadManager Information: 0 : Product: ServiceFabricSDK_3_3_RTO, Install Status: DependencyFailed-None, Install Time: 00:00:00
DownloadManager Information: 0 : Product: MicrosoftAzure-ServiceFabric-CoreSDK, Install Status: DependencyFailed-None, Install Time: 00:00:00
[InstallFabricRuntime.log](https://github.com/microsoft/service-fabric/files/4577203/InstallFabricRuntime.log)

**Comment by maburlik** [comment]
Is powershell.exe not under path?
5/4/2020 8:02:52 PM,Info,5/5/2020 1:32:52 AM running: powershell.exe -NoProfile Get-ExecutionPolicy -Scope CurrentUser
5/4/2020 8:02:52 PM,Error,The system cannot find the file specified

Please also try a newer version of the SDK since this version is no longer within support:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-versions#supported-versions
