### ISSUE TITLE
Docker Image for Service Fabric Onebox is out of date

### ISSUE THREAD

**Issue by tedvanderveen** [microsoft/service-fabric#930]
Hi! We are using SF 7.1 on Ubuntu 18.04. We want to be able to use the Service Fabric Onebox container for local testing and development on Mac and Linux developer workstations.
Problem is that the images published at https://hub.docker.com/_/microsoft-service-fabric-onebox are out of date as the latest image version is running SF version 6.5.435.1 on Ubuntu 16.04.
Please provide guidance on how to proceed.

**Comment by tedvanderveen** [comment]
@sridmad is this something you can support me with please?
How can I create/publish a OneBox image to Azure Container Registry that runs on Ubuntu 18.04 with the latest SF version (7.1.410.1)

**Comment by craftyhouse** [comment]
These have been updated
