### ISSUE TITLE
Console.CancelKeyPress subscription prevents from graceful shutdown

### ISSUE THREAD

**Issue by TheAzureGuy** [microsoft/service-fabric#936]
Hello!

I'm seeing abnormal behavior in SF services whenever a event handler for Console.CancelKeyPress is registered. One of reasons why one will need this even handler is to be able to handle shutdowns gracefully and flush EventFlow pipeline as discussed here: https://github.com/Azure/diagnostics-eventflow/issues/96

In summary, as soon as I subscribe to Console.CancelKeyPress, the SF service won't be able to exit gracefully within the allotted amount of time. This results in a longer than expected restart cycle and noisy warnings in the SF Explorer, similar to the following:

`There was an error during CodePackage activation.The process/container terminated with exit code:7148`

It also results in higher-than-expected shutdown times. Basically, each instance take a minute for SF to time out before the service process will be forcibly restarted. 

This behavior persists even after setting .Cancel = true on the event args as suggested here:
https://dotnet.github.io/orleans-docs/Documentation/Deployment-and-Operations/SiloShutdown.html

Environment:
- OS: Windows 10
- SF: 7.1.409.9590
- .NET: 4.6.1

Here is a super simple repro app:

Service's entry point:

```
public class Program
{
        public static void Main(string[] args)
        {
            Console.CancelKeyPress += (s, e) =>
            {
                e.Cancel = true; // DOES NOT MATTER
            };
            ServiceRuntime.RegisterServiceAsync("MyServiceType", context =>
            {
                return new TestService(context);
            }, cancellationToken: CancellationToken.None).GetAwaiter().GetResult();
            Thread.Sleep(Timeout.Infinite);
        }
}
```

Service's implementation:

```
public class TestService : StatelessService
{
    public TestService(
        StatelessServiceContext context
        ) : base(context)
    {
    }

    protected override async Task RunAsync(CancellationToken cancellationToken)
    {
        await Task.Delay(-1, cancellationToken); // DOES NOT MATTER AS WELL
    }
}
```

Repro step:

1. Deploy the above service
2. Go to SFX and restart the Code package for the service
3. Patiently wait for 1 minute while starring at the SFX
4. Be surprised with a timeout error similar to the following:

![image](https://user-images.githubusercontent.com/1142171/81366883-93f9a500-90a0-11ea-887f-0c6eef346c7b.png)

5. Comment out Console.CancelKeyPress handler
6. Repeat steps 1-2
7. Notice that service restarts immediately and there is no timeout

I'm asking the PG folks to investigate and suggest a solution. Thank you!

**Comment by karolz-ms** [comment]
@TheAzureGuy, Service Fabric uses Ctrl-C/SIGINT signal to indicate to the service host program that it should terminate. If you do not have a handler for the signal, the application that receives it is immediately terminated. That is the default behavior of the .NET runtime.

If you do handle the signal, it gives you the opportunity to clean up resources, but *it is now your job to ensure that, after resources are cleaned up, the service host process exits*. In your example the handler does nothing, and the startup thread sleeps indefinitely. The program effectively ignores the SIGINT signal. This violates the contract with Service Fabric.

Take a look [at the example in EventFlow documentation](https://github.com/azure/diagnostics-eventflow#service-fabric-support) to see how you can use `ManualResetEvent` in the event handler to wake up the startup thread and cause it (and the whole service host process) to exit.

Hope this helps!

**Comment by TheAzureGuy** [comment]
@karolz-ms, thank you for your prompt response. Very much appreciated.

Unfortunately, the code sample referenced in the EventFlow documentation exhibits very similar issue. That's why I initially posted a question on this issue [here](https://github.com/Azure/diagnostics-eventflow/issues/96) and asked if the sample code included therein was actually tested. I have indeed started going down the same path, and implemented my code as per ManualResetEvent example. It did not work as expected.

My repro code was _intentionally_ simplified to make it easy to render the problem in question. 

Below is the reworked repro app that is subject to exactly the same behavior.

```
    public class Program
    {
        public static void Main(string[] args)
        {
            using (ManualResetEvent terminationEvent = new ManualResetEvent(initialState: false))
            {
                Console.CancelKeyPress += (sender, eventArgs) => Shutdown(null, terminationEvent);

                ServiceRuntime.RegisterServiceAsync("MyServiceType", context =>
                {
                    return new TestService(context);
                }, cancellationToken: CancellationToken.None).GetAwaiter().GetResult();

                terminationEvent.WaitOne();
            }
        }

        private static void Shutdown(IDisposable disposable, ManualResetEvent terminationEvent)
        {
            try
            {
                disposable?.Dispose();
            }
            finally
            {
                terminationEvent.Set();
            }
        }
    }
```
Stopping the above code in SFX results in the same warning as before, however, the original warning is then followed by this new warning:

`'System.Hosting' reported Warning for property 'CodePackageDeactivation:Code:M'.
Graceful deactivation of CodePackage=Code has encountered timeout.  ProcessId=20060, IsSetupEntryPoint=false, InstanceId=132334305033873716, DeactivationTimeout=59.999.`

**Comment by karolz-ms** [comment]
@TheAzureGuy sorry, I cannot reproduce the problem you are experiencing.

I tried exactly the code that you have posted above, a Service Fabric application with a single, stateless, .NET 4.7.1 framework, 5-node local Service Fabric cluster, same version of Service Fabric runtime. Everything works as expected. I tried restarting the code package and scaling the service up and down, publishing the app as well as running it from Visual Studio debugger. No errors encountered. 🤔  

FWIIW, this code has not only been "tested", it is used as we speak by some of Microsoft largest customers, with 10s of thousands of service instances running in production.

**Comment by TheAzureGuy** [comment]
@karolz-ms that's very strange. I'm able to reproduce it consistently. And of course, I did try doing a complete local cluster reset. It is a 1-node cluster by the way.

Have you tried with .NET 4.6.1 to match my setup, or you think it is insignificant given the problem space?

Are you getting the informational confirmation popup box in the SFX UI stating that "Code package restart started" immediately after restarting your service?

**Comment by karolz-ms** [comment]
@TheAzureGuy strange indeed.

I think it is unlikely the issue is .NET 4.6 vs 4.7. We spent a lot of time developing on and testing 4.6 back in the day.

Yes, I do get all the expected pop-ups upon code package restart & service scale up/down.

Can you do me a favor and try the following
- 5-node cluster
- another computer, if possible

**Comment by TheAzureGuy** [comment]
Update: trying on a real 5-node cluster appears to have derived the expected results. Services restart quickly. However, despite the restart is happening as expected and no timeout are observed, I'm still seeing the same warning from time to time (same text as included in my initial message - see above). I don't feel it is significant though, so I will be closing this issue as "ROOT CAUSE UNKNOWN, RESOLVED BY ITSELF".

One of the reasons why it might be misbehaving on a local dev machine is (potentially) due to using the VS debugger while troubleshooting service restart issues. All local deployments were accomplished via F5, tried both "Refresh Application" and "Remove Application" modes.

**Comment by karolz-ms** [comment]
Thanks for letting us know!

As for troubleshooting error 7148, [this might get you started in the right direction](https://stackoverflow.com/questions/45724648/azure-service-fabric-activation-error-7148)
