### ISSUE TITLE
Failed to install the deb due to uninstalled dependencies

### ISSUE THREAD

**Issue by bingosummer** [microsoft/service-fabric#94]
After building service fabric successfully in ubuntu 16.04, I tried to [install the deb](https://github.com/Microsoft/service-fabric/blob/master/docs/install_packages_and_deploy_cluster.md#install-and-set-up-the-service-fabric-debians-for-local-cluster-setup), but got the error:
```
$ sudo dpkg -i out/build.prod/FabricDrop/deb/servicefabric_6.2.141.1.deb && sudo apt-get install -fy
(Reading database ... 55479 files and directories currently installed.)
Preparing to unpack .../servicefabric_6.2.141.1.deb ...
In PreInst - upgrade 6.2.141.1
Service Fabric license has already been accepted
Stopping service fabric service
Failed to stop servicefabric.service: Unit servicefabric.service not loaded.
Disable service fabric service
Failed to execute operation: No such file or directory
Unpacking servicefabric (6.2.141.1) over (6.2.141.1) ...
In PostRm - upgrade 6.2.141.1
upgrade
6.2.141.1
dpkg: dependency problems prevent configuration of servicefabric:
 servicefabric depends on lttng-tools; however:
  Package lttng-tools is not installed.
 servicefabric depends on lttng-modules-dkms; however:
  Package lttng-modules-dkms is not installed.
 servicefabric depends on liblttng-ust0; however:
  Package liblttng-ust0 is not installed.
 servicefabric depends on rssh; however:
  Package rssh is not installed.
 servicefabric depends on sshpass; however:
  Package sshpass is not installed.
 servicefabric depends on members; however:
  Package members is not installed.
 servicefabric depends on libib-util; however:
  Package libib-util is not installed.
 servicefabric depends on libssh2-1; however:
  Package libssh2-1 is not installed.
 servicefabric depends on nodejs; however:
  Package nodejs is not installed.
 servicefabric depends on nodejs-legacy; however:
  Package nodejs-legacy is not installed.
 servicefabric depends on npm; however:
  Package npm is not installed.
 servicefabric depends on atop; how
dpkg: error processing package servicefabric (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 servicefabric
```
How to fix the issue? Thanks.

**Comment by bpm-ms** [comment]
@bingosummer can you try running `sudo apt-get install -fy`?  Looks like the same thing I ran into when I looked at this PR https://github.com/Microsoft/service-fabric/pull/26#discussion_r175196941 .  
I think my suggestion at the time to make it `sudo dpkg -i out/build.prod/FabricDrop/deb/servicefabric_6.2.141.1.deb && sudo apt-get install -fy` might not actually work because `&&` will only run the second command if there's a non-zero exit code on the first command.  So I think if you run the second command after the fact, you might be able to get it to install.

I think this line needs to be changed to `sudo dpkg -i out/build.prod/FabricDrop/deb/servicefabric_6.2.141.1.deb & sudo apt-get install -fy`.  @bingosummer can you try that and see if it works?

**Comment by bingosummer** [comment]
Thanks for your suggestions, @bpm-ms .
I've run these two commands separately instead of using `&`. Using `&` makes my commands stuck for a long time.

I agree with you that "it is confusing that it seems like it failed, so maybe we should make it clear this is what it should look like". And maybe it's not a good idea to wrap them together with `&&` or `&`.

To prevent from upgrading `6.2.141.1` to `6.2.184.1`, I also run `echo "servicefabric hold" | sudo dpkg --set-selections`. It seems that the service fabric version in ubuntu 16.04 distro is ahead of the version which is built from source codes. Correct? It makes sense for me not to upgrade the version.

So, my commands to install the debs are:
```
sudo dpkg -i out/build.prod/FabricDrop/deb/servicefabric_6.2.141.1.deb
echo "servicefabric hold" | sudo dpkg --set-selections
sudo apt-get install -fy
```

Now they are installed.
```
$ sudo dpkg --list | grep fabric
hi  servicefabric                       6.2.141.1                                  amd64        Service Fabric
hi  servicefabricsdkcommon              1.2.0                                      amd64        Service Fabric SDK Common
```

**Comment by maburlik** [comment]
The lttng-tools was conflicting with a package installed as part of the dotnet runtime and this issue was addressed in a previous release.
