### ISSUE TITLE
Locally Service Fabric Cluster Never Works

### ISSUE THREAD

**Issue by NorthHighlandNicole** [microsoft/service-fabric#947]
Attempt to run my service fabric application on my machine just never seems to work. Currently I'm getting " The operation failed because the requested partition does not exist."

Other times I get "Unable to determine whether the application is installed on the cluster or not" and there are more.

But it's not EVER as simple as the documentation reports, saying that once I created my new SF solution/project I can hit "run". It fails. At best multiple reboots of my machine does the trick.

This is simply NOT an acceptable way to debug when doing development work. Please, please someone tell you me have a solution.

I have tried uninstalling the SDK multiple times & reinstalling. Nothing seems to be the key.

**Comment by craftyhouse** [comment]
We have made some strides in getting the VS 2019 experience, samples, and some core updates to SF since this post that should help provide a smoother experience. Please let us know specifics so we can track/help further if needed. Feel free to re-open or post new.
