### ISSUE TITLE
Unable to assign ClusterConfoiguration using  ConfigurationUpgradeDescription method

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [microsoft/service-fabric#952]
I am trying to update cluster configuration settings using **UpgradeConfigurationAsync (System.Fabric.Description.ConfigurationUpgradeDescription description);** but ConfigurationUpgradeDescription  is not accepting configuration settings

**Comment by maburlik** [comment]
See response here:
https://github.com/microsoft/service-fabric-issues/issues/1681

**Comment by maburlik** [comment]
You can use reflection to set this value:
http://dotnetfollower.com/wordpress/2012/12/c-how-to-set-or-get-value-of-a-private-or-internal-property-through-the-reflection/

            ConfigurationUpgradeDescription description = new ConfigurationUpgradeDescription();
            description.SetPropertyValue("ClusterConfiguration", jsonstring);


FabricClientRetryHelper.ExecuteFabricActionWithRetry(
                () => client.ClusterManager.UpgradeConfigurationAsync(description).GetAwaiter().GetResult(),
               FabricClientRetryErrors.ProvisionFabricErrors.Value);
