### ISSUE TITLE
fabric:/System/InfraustructureService is not healthy on Service Fabric Cluster

### ISSUE THREAD

**Issue by SinghVarun** [microsoft/service-fabric#959]
SF cluster infrastructure service is in unhealthy state for quite sometime now. We are seeing below error. 
> System.InfrastructureService' reported Warning for property 'CoordinatorStatus'.
> Failed to create infrastructure coordinator: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Fabric.InfrastructureService.ManagementException: Unable to get tenant policy agent endpoint from registry; verify that tenant settings match InfrastructureService configuration

We have already compared the durability settings between VMSS and SF cluster setting as mentioned [here](https://stackoverflow.com/questions/48553125/fabric-system-infraustructureservice-is-not-healthy-on-service-fabric-cluster) and this doesnt appear to be an issue. 
Primary nodes have silver durability where as other nodes types have bronze durability tier.
Reliability tier is Silver.

**Comment by maburlik** [comment]
For context this is specific for Azure SF clusters, and I have seen this come up as a result of CRP/VMAgent behavior. Incident 196691804 is currently tracking the investigation on the VMAgent side.

**Comment by craftyhouse** [comment]
Incident filed and triaged. Posting new guidance for reference https://github.com/microsoft/service-fabric/blob/0ed99b8b37b91f46d2481c5a784179c1a6c7e7df/CONTRIBUTING.md#production-issues
