### ISSUE TITLE
[Question] Is ITransaction.CommitAsync necessary after a read operation?

### ISSUE THREAD

**Issue by FDUdannychen** [microsoft/service-fabric#964]
For example, after invoking IReliableDictionary.TryGetValueAsync, should I still call ITransaction.CommitAsync even there is no changes? What's the best practice here?

**Comment by masnider** [comment]
Not strictly required but best practice is to always call commit or abort.

**Comment by juho-hanhimaki** [comment]
This is news to me. Is there any performance hit for committing (or aborting) read transactions?

Is there a difference between disposing (via `using (var tx = StateManager.CreateTransaction())`) and explicitly calling Abort or CommitAsync?

**Comment by mfmadsen** [comment]
@preethasubbarayalu maybe you can elaborate based on the question from @juho-hanhimaki ? Thanks!

**Comment by preethasubbarayalu** [comment]
If the transaction is disposed without commit, it i considered abort. There is no difference here. The delay in the replica close can happen if transactions are not disposed. As long as the transaction is disposed, it is good. There should be no performance impact if abort or commit is called explicitly.

**Comment by mfmadsen** [comment]
So, @preethasubbarayalu if we ensure that we dispose our transactions via using (var tx = StateManager.CreateTransaction()) we do not need to explicitly abort (or commit) the transaction in the case that the transaction is a pure read-only transaction? Or should we always call either abort or commit while also disposing the transaction?
Sorry to keep asking here, but I don’t feel it’s entirely clear what best practice is here. Currently we just dispose our read transactions without doing explicit commit or abort as our understanding was that this the same as calling Abort. But maybe we are wrong?
