### ISSUE TITLE
DiagnosticsStore folder on one of the nodes too big

### ISSUE THREAD

**Issue by v1nt06** [microsoft/service-fabric#965]
Hello,

I have standalone SF cluster with 10 nodes (including 3 seed nodes) working on Service Fabric v.6.5.676.9590.

Several months ago I ran into a problem:
I deploying our application to this cluster every few months. After deployment in several weeks occurs the problem with disk space on one of the nodes. I discovered that DiagnosticsStore folder is too big, specifically this folder: DiagnosticsStore\fabriclogs-43466ece-0e6c-41af-8c87-33632debcfbc\VEC4PAAW_W2K12_NODE_NC4\Fabric. In this folder appears 5 files (4Mb each) every 5 minutes or about 5Gb per day. In contrast to this, on other nodes, I have only 1 or 2 files (100Kb - 1.5Mb) every 5 minutes:
![mRemoteNG_Bl8DIe2vtf](https://user-images.githubusercontent.com/2842503/84779070-967ae300-afec-11ea-9702-454e743cbae0.png)

Besides, the problem disappears by itself a few weeks later. Also, our SF-application works fine and I can't found the cause of the problem because I don't know how to analyze these *.dtr files. 

One of zipped *.dtr files:
[f962dc86d5d1af93b32db0e6ba8d879d_fabric_traces_6.5.676.9590_132344105321281492_26236_00637276824596925059_2147483647.dtr.zip](https://github.com/microsoft/service-fabric/files/4786817/f962dc86d5d1af93b32db0e6ba8d879d_fabric_traces_6.5.676.9590_132344105321281492_26236_00637276824596925059_2147483647.dtr.zip)

Can you help with resolving that issue?

**Comment by maburlik** [comment]
I can tell this node is processing many FM queries which could be related to service resolutions. It's expected that system services that are being actively utilized would be logging at a faster rate than other nodes.


2020-6-13 22:00:01.503 | FM.Query | 5560 | 10308 | [9ac86b82-4208-4ebc-b299-7d6461c2e62e:0] Query completed with error S_OK.
-- | -- | -- | -- | --
2020-6-13 22:00:01.504 | FM.Query | 5560 | 10308 | [d8f1aa59-56e0-441e-a2cd-199a3aca0a28:0] Processing Query
2020-6-13 22:00:01.504 | FM.Query | 5560 | 10308 | [d8f1aa59-56e0-441e-a2cd-199a3aca0a28:0] Query completed with error S_OK.
2020-6-13 22:00:01.506 | FM.Query | 5560 | 4496 | [cc770f8f-902d-46ad-ba14-50e2eeb3515b:0] Processing Query
2020-6-13 22:00:01.506 | FM.Query | 5560 | 4496 | cc770f8f-902d-46ad-ba14-50e2eeb3515b:0: Cache nodes: continuation token=, count=10
2020-6-13 22:00:01.506 | FM.Query | 5560 | 4496 | [cc770f8f-902d-46ad-ba14-50e2eeb3515b:0] Query completed with error S_OK.
2020-6-13 22:00:01.509 | FM.Query | 5560 | 10164 | [bfe568f0-27e4-4076-ad69-620cf007ae4f:0] Processing Query
2020-6-13 22:00:01.509 | FM.Query | 5560 | 10164 | [bfe568f0-27e4-4076-ad69-620cf007ae4f:0] Query completed with error S_OK.
2020-6-13 22:00:01.510 | FM.Query | 5560 | 10164 | [1dcdbb89-a42f-4619-868c-3684ce553a3a:0] Processing Query
2020-6-13 22:00:01.510 | FM.Query | 5560 | 10164 | [1dcdbb89-a42f-4619-868c-3684ce553a3a:0] Query completed with error S_OK.
2020-6-13 22:00:01.511 | FM.Query | 5560 | 10164 | [72a28208-a39c-488d-ac41-083477ac8a45:0] Processing Query
2020-6-13 22:00:01.512 | FM.Query | 5560 | 10164 | [72a28208-a39c-488d-ac41-083477ac8a45:0] Query completed with error S_OK.
2020-6-13 22:00:01.513 | FM.Query | 5560 | 4496 | [d74b30bf-ff74-46b2-af16-a016089d067a:0] Processing Query
2020-6-13 22:00:01.513 | FM.Query | 5560 | 4496 | [d74b30bf-ff74-46b2-af16-a016089d067a:0] Query completed with error S_OK.
2020-6-13 22:00:01.514 | FM.Query | 5560 | 10164 | [18b8fc75-e1dc-4144-8e72-3981be6f4f2b:0] Processing Query
2020-6-13 22:00:01.514 | FM.Query | 5560 | 10164 | [18b8fc75-e1dc-4144-8e72-3981be6f4f2b:0] Query completed with error S_OK.
2020-6-13 22:00:01.515 | FM.Query | 5560 | 4496 | [f5f3d93e-dc77-43bf-8e8a-fef572d80c03:0] Processing Query
2020-6-13 22:00:01.516 | FM.Query | 5560 | 4496 | [f5f3d93e-dc77-43bf-8e8a-fef572d80c03:0] Query completed with error S_OK.
2020-6-13 22:00:01.588 | FM.Query | 5560 | 10308 | [c672a968-e444-44c7-8f16-9b761d4cab0d:0] Processing Query
2020-6-13 22:00:01.588 | FM.Query | 5560 | 10308 | c672a968-e444-44c7-8f16-9b761d4cab0d:0: Cache nodes: continuation token=, count=10
2020-6-13 22:00:01.588 | FM.Query | 5560 | 10308 | [c672a968-e444-44c7-8f16-9b761d4cab0d:0] Query completed with error S_OK.
2020-6-13 22:00:01.591 | FM.Query | 5560 | 6596 | [d027d444-5d52-4a93-8b41-1a47ba871e82:0] Processing Query
2020-6-13 22:00:01.591 | FM.Query | 5560 | 6596 | [d027d444-5d52-4a93-8b41-1a47ba871e82:0] Query completed with error S_OK.

**Comment by v1nt06** [comment]
Hello @maburlik ,

So, if this expected behavior for Failover Manager then It is ok that we have log messages like this? (example from table above):

[d8f1aa59-56e0-441e-a2cd-199a3aca0a28:0] Query **completed with error** S_OK.

**Comment by maburlik** [comment]
Query completed with error S_OK really means the error code for success, which is what we expect.

**Comment by maburlik** [comment]
The diagnostics management process FabricDCA regularly monitors, organizes, and trims log data based on size quotas. If you are concerned with the amount of space used for logging data you can update your Diagnostics quota in the cluster configuration:
https://github.com/microsoft/service-fabric/issues?page=1&q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc
Diagnostics : DiskFullSafetySpaceInMB, MaxDiskQuotaInMB

**Comment by v1nt06** [comment]
Thank you for explanation. I'll close this issue.
