### ISSUE TITLE
How can I migrate the apps from one cluster to the other ?

### ISSUE THREAD

**Issue by sall84993356** [microsoft/service-fabric#966]
I have a three nodes sf cluster, now the issue is these three servers doesn't perform well , I created an one node sf in another server . So ,how can I migrate all the apps from these three nodes cluster to the one node SF Server?

**Comment by craftyhouse** [comment]
@sall84993356 do you still need guidance on this? These docs may help. Redeploying to the new target is probably the simplest approach, but you can look in to backup/restore methods as described below.

If on azure:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-azurecluster
if standalone:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-backuprestoreservice-quickstart-standalonecluster
