### ISSUE TITLE
Microsoft.VisualStudio.Azure.Fabric.MSBuild changelog

### ISSUE THREAD

**Issue by dmytro-gokun** [microsoft/service-fabric#976]
Does that exist anywhere? What's new in 1.7.0 compared to 1.6.9?

**Comment by dmytro-gokun** [comment]
Anyone?

**Comment by IvanAlekseev** [comment]
Looks like they started to include "[What's new](https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Fabric.MSBuild/1.7.1)" section on nuget.org from 1.7.1

**Comment by craftyhouse** [comment]
Resolved per comment above, thank you!
