### ISSUE TITLE
Liveness probe - breaks port redirection on node

### ISSUE THREAD

**Issue by vdvarlamov** [microsoft/service-fabric#977]
I have standalone cluster 7.1.417.9590 on Windows Server 2019 and containerized application.
I add Liveness probe in ApplicationManifest - https://docs.microsoft.com/en-us/azure/service-fabric/probes-codepackage
`      <CodePackagePolicy CodePackageRef="Code">`
        `<Probes>`
          `<Probe Type="Liveness" FailureThreshold="3" SuccessThreshold="2" InitialDelaySeconds="10" PeriodSeconds="5" TimeoutSeconds="5">`
            `<HttpGet Path="/healthcheck" Port="2532" Scheme="http"/>`
          `</Probe>`
        `</Probes>`
      `</CodePackagePolicy>`
Application successfully upgrade, but http endpoint becomes unavailable. I tested this on several applications.

**Comment by gkhanna79** [comment]
@vdvarlamov Can you please clarify which endpoint becomes unusable? Will it be possible for you to share a repro with @tugup  to triage?

**Comment by vdvarlamov** [comment]
More details here: https://docs.microsoft.com/en-us/answers/questions/43537/liveness-probe-breaks-port-redirection-on-node.html

**Comment by gkhanna79** [comment]
Thanks @vdvarlamov. @tugup will take a look to understand this and revert with findings.

**Comment by tugup** [comment]
@vdvarlamov it seems the port that you are specifying the probe is not the port the container exposes? 
Test-NetConnection -ComputerName <NodeIP> -port 2532
means that 2352 is the host port, not the contaomer port which is port mapped to a container port.

**Comment by vdvarlamov** [comment]
@tugup Port 2352 - Is the port of the container and the host, they are the same.
<Endpoint Name="Endpoint'" UriScheme="http"  Protocol="http" Port=2532 PathSuffix="healthcheck/"/>
<PortBinding ContainerPort=2532 EndpointRef="Endpoint'" />

**Comment by tugup** [comment]
@vdvarlamov I know the issue now. I looked at your manifest file:

      <ContainerHostPolicies CodePackageRef="Code">
        <PortBinding ContainerPort="80" EndpointRef="Guest_Container1TypeEndpoint" />
      </ContainerHostPolicies>
      <CodePackagePolicy CodePackageRef="Code">
        <Probes>
          <Probe Type="Liveness" FailureThreshold="3" SuccessThreshold="2" InitialDelaySeconds="10" PeriodSeconds="5" TimeoutSeconds="5">
            <HttpGet Path="/" Port="80" Scheme="http" />
          </Probe>
        </Probes>
      </CodePackagePolicy>

We have a bug in 7.1 that us going to be fixed in up coming release. The issue is the port are not getting passed correctly to the container runtime if there is a port mapping with the same port number in Livenesss probe. for ex: in your case this 80.

To unblock you now, can you do either one of the following?
 1. Can you remove the <PortBinding ContainerPort="80" EndpointRef="Guest_Container1TypeEndpoint" />
 2. Expose 2 ports from container, where one of the port is dedicated for probe?
 3. Use Exec probe for now?

**Comment by vdvarlamov** [comment]
Fixed in version 7.1.458.9590.
