### ISSUE TITLE
DataContract schema validation

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#986]
Has the SF runtime recently changed to perform DataContract schema validation? I used to be able to add properties to my classes, and deploy without difficulty, but recently I started getting serialization exceptions complaining about BackingField conflicts. If it has changed, is there a way to disable it?

**Comment by zuhairp** [comment]
Hi @jackbond 
SF runtime does not do any schema validation itself, we defer that to DataContract. There have not been any recent changes with how SF interacts with DataContract.

**Comment by craftyhouse** [comment]
Closing as this looks answered. Please let us know if if you need further assistance by re-opening or filing a new issue.
