### ISSUE TITLE
Cluster configuration upgrade of type StandAloneBaselineUpgradeState is already in progress and cannot be interrupted

### ISSUE THREAD

**Issue by MonDeveloper** [microsoft/service-fabric#987]
A few days ago our cluster had **succesfully** and **automatically** upgraded to **7.1.417.9590**

Today we tried to add a cluster configuration, we tested the new config and every check was passed, unfortunately when we started the Upgrade we receive the following exception:

```
Start-ServiceFabricClusterConfigurationUpgrade : System.Runtime.InteropServices.COMException (-2147017627)
FabricException: Cluster configuration upgrade of type StandAloneSimpleClusterUpgradeState is already in progress and
cannot be interrupted.
At line:1 char:1
+ Start-ServiceFabricClusterConfigurationUpgrade -ClusterConfigPath clu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Start-ServiceFa
   ...gurationUpgrade], FabricException
    + FullyQualifiedErrorId : StartClusterConfigurationUpgradeErrorId,Microsoft.ServiceFabric.Powershell.StartClusterC
   onfigurationUpgrade
```

Looking around (Logs, Explorer, UpgradeStatus Api) everything seems to be ok, even the cluster upgrade to 7.* had been completed succesfully, but we cannot run further upgrade now.

Seems to related to: #792

**Comment by gkhanna79** [comment]
@TassaduqBasu @maburlik PTAL.

**Comment by maburlik** [comment]
We've made changes for the upcoming 7.2 release regarding FabricUOS state management to improve this experience and avoid cases like this. Try analyze the delta between the previous & latest cluster configuration and see if the reverse upgrade makes any difference. Did you add/remove nodes?

If this doesn't resolve your issue we may need the fabric trace logs from the FabricLogRoot (as set in your cluster configuration) to identify next steps.

**Comment by maburlik** [comment]
@jkochhar

**Comment by maburlik** [comment]
What I expect has happened in your case is the state machine failed silently and FabricUOS needs to rerun the cycle to pick up or complete the pending upgrade. The way to do this is to restart or move the primary replica:

`Move-ServiceFabricPrimaryReplica -PartitionId 00000000-0000-0000-0000-000000006000 -ServiceName fabric:/System/UpgradeOrchestrationService`

You can run the command below before and after to make sure the primary had transitioned to another node:

`Get-ServiceFabricReplica -PartitionId 00000000-0000-0000-0000-000000006000`

**Comment by MonDeveloper** [comment]
Unfortunately we have had to revert our cluster to 6.latest because we noticed some other breacking changes we can not face at this time.
We have planned the cluster update in the early September.
Anyway now I know what I can do in case the same problem will appear again.
